var mysql_wn_data_noun_feeling = {
"withdrawal":[["noun.feeling","verb.emotion:withdraw","noun.act","noun.act","noun.act","verb.possession:withdraw","noun.act"],["withdrawal","detachment","indifference","withdrawal2","drug withdrawal","termination","withdrawal6","separation1","withdrawal3","removal","withdrawal5","removal"]],
"fulfillment":[["noun.feeling","verb.consumption:fulfill","verb.consumption:fulfil"],["fulfillment","fulfilment","satisfaction"]],
"frustration":[["noun.feeling","verb.social:frustrate","noun.person:defeatist"],["frustration","defeat","disappointment"]],
"disappointment":[["noun.feeling","verb.emotion:disappoint","verb.emotion:let down"],["disappointment","letdown","dissatisfaction"]],
"leaning":[["noun.feeling","verb.stative:tend1"],["leaning","propensity","tendency","inclination"]],
"confusion":[["noun.feeling","verb.emotion:confuse","verb.emotion:discombobulate","verb.cognition:discombobulate","noun.state"],["confusion","discombobulation","embarrassment","confusion1","disorder"]],
"apprehension":[["noun.feeling","verb.emotion:apprehend","adj.all:uneasy^apprehensive","adj.all:afraid^apprehensive","adj.all:alarming^dread","verb.emotion:dread","noun.cognition","verb.emotion:apprehend","verb.cognition:misgive"],["apprehension","apprehensiveness","dread","fearfulness","apprehension1","misgiving2","expectation"]],
"care":[["noun.feeling","verb.emotion:care2","verb.emotion:care12","noun.state:predicament","noun.act","verb.social:care13","verb.social:attend12","verb.body:aid","verb.social:tend","verb.emotion","noun.feeling:care","noun.feeling:caring1","verb.social:care13","verb.social","noun.act:care1"],["care","care1","attention1","aid1","tending","work","care2","^care for8","^sympathize with","frames:22","care13","give care","help"]],
"inclination":[["noun.feeling","verb.stative:incline1","verb.cognition:incline3","noun.shape","verb.motion:incline","noun.cognition:geometry","noun.shape","verb.motion:incline","noun.cognition:astronomy"],["inclination","disinclination","!liking","inclination1","angle of inclination","angle","inclination2","inclination of an orbit","angle"]],
"attrition":[["noun.feeling","adj.all:penitent^contrite"],["attrition","contrition","contriteness","sorrow1"]],
"aggravation":[["noun.feeling","verb.emotion:aggravate","verb.emotion:exasperate1","verb.emotion:exasperate"],["aggravation","exasperation","annoyance"]],
"attachment":[["noun.feeling","verb.social:attach3"],["attachment","fond regard","affection"]],
"warpath":[["noun.feeling"],["warpath","belligerence"]],
"annoyance":[["noun.feeling"],["annoyance","chafe","vexation","anger"]],
"harassment":[["noun.feeling","verb.emotion:torment1"],["harassment","torment3","annoyance"]],
"cruelty":[["noun.feeling","adj.all:merciless","adj.all:inhumane^pitiless","adj.all:merciless^ruthless","noun.attribute","adj.all:inhumane^cruel1","adj.all:unkind^harsh"],["cruelty","mercilessness","pitilessness","ruthlessness","heartlessness","cruelty1","cruelness","harshness4","malevolence"]],
"wrath":[["noun.feeling"],["wrath","fury"]],
"pleasure":[["noun.feeling","verb.emotion:please","adj.all:pleasant","noun.Tops:feeling"],["pleasure","pain","!pleasance"]],
"disapproval":[["noun.feeling","verb.cognition:disapprove"],["disapproval","approval","!dislike"]],
"aggression":[["noun.feeling","noun.act","noun.act","verb.competition:aggress"],["aggression","aggressiveness","hostility","aggression1","behavior","aggression2","combat","war"]],
"emulation":[["noun.feeling","verb.stative:emulate","verb.competition:emulate"],["emulation","ambition"]],
"agape":[["noun.feeling","noun.feeling","noun.cognition:Christian theology"],["agape","agape love","love","agape1","love"]],
"devotion":[["noun.feeling","adj.all:dedicated^devoted2","noun.act","verb.communication:devote","noun.act","verb.communication:devote"],["devotion","devotedness","love","devotion2","veneration","cultism","worship","devotion1","commitment"]],
"enjoyment":[["noun.feeling","verb.emotion:enjoy1","verb.emotion:enjoy","verb.consumption:enjoy"],["enjoyment","pleasure"]],
"satisfaction":[["noun.feeling","noun.possession","noun.group:law"],["satisfaction","dissatisfaction","!contentment","satisfaction1","payment"]],
"contempt":[["noun.feeling","adj.all:disrespectful^contemptuous","verb.emotion:disdain","verb.emotion:scorn"],["contempt","disdain","scorn","despite","dislike"]],
"fetish":[["noun.feeling"],["fetish","sexual desire"]],
"consolation":[["noun.feeling","verb.emotion:console","verb.emotion:solace","verb.emotion:solace"],["consolation","solace","solacement","comfort"]],
"easiness":[["noun.feeling","adj.all:easy2","verb.social:relax2","verb.body:relax1"],["easiness","relaxation","tranquillity"]],
"benevolence":[["noun.feeling"],["benevolence","malevolence","!love"]],
"forgiveness":[["noun.feeling"],["forgiveness","mercy"]],
"titillation":[["noun.feeling"],["titillation","excitement"]],
"stupefaction":[["noun.feeling","verb.cognition:stupefy"],["stupefaction","astonishment"]],
"weight":[["noun.feeling","adj.all:heavy2^weighty","noun.attribute","adj.all:important^weighty","adj.all:persuasive^weighty","adj.all:important^weighty","noun.quantity","verb.cognition:weight","noun.cognition:statistics"],["weight","oppression","weight1","weightiness1","importance","weight2","weighting","coefficient"]],
"mawkishness":[["noun.feeling","adj.all:emotional^mawkish"],["mawkishness","bathos","sentimentality"]],
"moodiness":[["noun.feeling","adj.all:ill-natured^moody"],["moodiness","ill humor"]],
"cheerfulness":[["noun.feeling","adj.all:optimistic^cheerful","adj.all:cheerful^blithe"],["cheerfulness","cheerlessness","!blitheness","happiness"]],
"exuberance":[["noun.feeling","adj.all:spirited^exuberant","verb.communication:exuberate"],["exuberance","enthusiasm","joy"]],
"apathy":[["noun.feeling","adj.all:uninterested^apathetic","adj.all:spiritless^apathetic","noun.Tops:feeling"],["apathy"]],
"sulkiness":[["noun.feeling","adj.all:ill-natured^sulky","adj.all:ill-natured^huffish"],["sulkiness","huffishness","resentment"]],
"impatience":[["noun.feeling","adj.all:eager^impatient"],["impatience","restlessness"]],
"levity":[["noun.feeling","!noun.Tops:feeling"],["levity","gravity"]],
"friendliness":[["noun.feeling","adj.all:amicable^friendly"],["friendliness","unfriendliness","!liking"]],
"amicability":[["noun.feeling"],["amicability","amicableness","friendliness"]],
"mellowness":[["noun.feeling","adj.all:soft2^mellow","\\adj.all:relaxed^mellow","\\adj.all:intoxicated^mellow"],["mellowness","\\compassion"]],
"closeness":[["noun.feeling","adj.all:close2"],["closeness","intimacy","belonging"]],
"unfriendliness":[["noun.feeling","adj.all:hostile1^unfriendly1"],["unfriendliness","friendliness","!dislike"]],
"misanthropy":[["noun.feeling","adj.all:ill-natured^misanthropic","adj.all:ill-natured^misanthropical","noun.person:misanthropist"],["misanthropy","hate"]],
"pensiveness":[["noun.feeling","adj.all:thoughtful^pensive"],["pensiveness","brooding","melancholy"]],
"carefreeness":[["noun.feeling","adj.all:irresponsible^carefree","adj.all:unconcerned^insouciant","adj.all:cheerful^lighthearted","adj.all:cheerful^lightsome"],["carefreeness","insouciance","lightheartedness","lightsomeness","cheerfulness"]],
"compatibility":[["noun.feeling"],["compatibility","sympathy"]],
"protectiveness":[["noun.feeling","adj.all:tender3^protective"],["protectiveness","affection"]],
"pleasantness":[["noun.feeling","adj.all:nice^pleasant"],["pleasantness","unpleasantness","!pleasure"]],
"unpleasantness":[["noun.feeling","adj.all:unpleasant"],["unpleasantness","pleasantness","!pain"]],
"mercifulness":[["noun.feeling","adj.all:merciful"],["mercifulness","mercy","compassion"]],
"compassion":[["noun.feeling","verb.emotion:compassionate","adj.all:compassionate"],["compassion","compassionateness","sympathy"]],
"murderousness":[["noun.feeling","adj.all:bloody^murderous"],["murderousness","hate"]],
"beneficence":[["noun.feeling","adj.all:beneficent"],["beneficence","maleficence","!benevolence"]],
"malevolence":[["noun.feeling","adj.all:malicious^malevolent"],["malevolence","benevolence","!malignity","hate"]],
"maleficence":[["noun.feeling","adj.all:maleficent"],["maleficence","beneficence","!malevolence"]],
"fearlessness":[["noun.feeling","adj.all:bold^fearless","noun.Tops:feeling"],["fearlessness","fear","!bravery"]],
"coolness":[["noun.feeling","adj.all:fashionable^cool","adj.all:composed^imperturbable","adj.all:composed^imperturbable"],["coolness","imperturbability","imperturbableness","calmness"]],
"timidity":[["noun.feeling","adj.all:timid","adj.all:cowardly^timid","adj.all:timid","adj.all:timid^timorous"],["timidity","timidness","timorousness","fear"]],
"loyalty":[["noun.feeling"],["loyalty","love"]],
"humility":[["noun.feeling","noun.Tops:feeling"],["humility","pride","!humbleness"]],
"meekness":[["noun.feeling","adj.all:humble^meek","adj.all:docile^meek"],["meekness","submission","humility"]],
"wildness":[["noun.feeling","adj.all:passionate^wild","noun.attribute","adj.all:wild2"],["wildness","abandon","passion","wildness1","unruliness"]],
"buoyancy":[["noun.feeling","adj.all:cheerful^buoyant","adj.all:cheerful^perky"],["buoyancy","perkiness","cheerfulness"]],
"faintness":[["noun.feeling","adj.all:ill1^faint","noun.Tops:feeling"],["faintness"]],
"heaviness":[["noun.feeling","adj.all:heavy2"],["heaviness","sadness"]],
"weakness":[["noun.feeling","noun.state","adj.all:down^weak"],["weakness","preference","weakness1","strength1","misfortune"]],
"preference":[["noun.feeling","verb.emotion:prefer"],["preference","penchant","predilection","taste2","liking"]],
"optimism":[["noun.feeling","adj.all:positive1^optimistic","adj.all:optimistic","noun.person:optimist"],["optimism","pessimism","!hope"]],
"pessimism":[["noun.feeling","adj.all:pessimistic","noun.person:pessimist"],["pessimism","optimism","!despair"]],
"velleity":[["noun.feeling"],["velleity","wish"]],
"enthusiasm":[["noun.feeling","adj.all:enthusiastic","noun.Tops:feeling"],["enthusiasm"]],
"concern":[["noun.feeling","verb.stative","noun.feeling:concern1","noun.cognition:concern1","noun.cognition:interest","noun.act:occupation4"],["concern","unconcern","!sympathy","concern1","interest1","occupy4","worry","frames:10"]],
"self-consciousness":[["noun.feeling","adj.all:uncomfortable1^self-conscious","adj.all:uncomfortable1^uneasy","adj.all:uncomfortable1"],["self-consciousness","uneasiness1","uncomfortableness","embarrassment"]],
"sensibility":[["noun.feeling"],["sensibility","sensitivity"]],
"daze":[["noun.feeling","verb.perception:daze","verb.body:shock","verb.emotion:shock","verb.emotion:shock2"],["daze","shock1","stupor","stupefaction"]],
"temptation":[["noun.feeling","verb.communication:tempt1"],["temptation","desire"]],
"jealousy":[["noun.feeling"],["jealousy","green-eyed monster","envy"]],
"insight":[["noun.feeling","adj.pert:perceptive","adj.all:perceptive","adj.all:perceptive","noun.cognition","verb.cognition:brainstorm"],["insight","perceptiveness","perceptivity","sensibility","insight1","brainstorm","brainwave","understanding1"]],
"antipathy":[["noun.feeling","adj.all:hostile1^antipathetic","adj.all:disinclined^antipathetic","adj.all:hostile1^antipathetical"],["antipathy","aversion","distaste","dislike"]],
"infatuation":[["noun.feeling","verb.emotion:infatuate"],["infatuation","passion"]],
"joy":[["noun.feeling","adj.all:joyous","verb.emotion:joy1","verb.emotion:joy","adj.all:joyous","adj.all:joyous^joyful","adj.all:joyful"],["joy","sorrow","!joyousness","joyfulness","emotion"]],
"grief":[["noun.feeling","adj.all:sorrowful^brokenhearted"],["grief","heartache","heartbreak","brokenheartedness","sorrow"]],
"expectation":[["noun.feeling","verb.cognition:expect","verb.body:expect","noun.Tops:feeling"],["expectation"]],
"nationalism":[["noun.feeling","noun.person:nationalist1","noun.cognition","noun.person:nationalist1"],["nationalism","ambition","nationalism1","internationalism","doctrine"]],
"rhapsody":[["noun.feeling","verb.communication:rhapsodize","noun.communication"],["rhapsody","joy","rhapsody1","music","music"]],
"resignation":[["noun.feeling","verb.cognition:resign"],["resignation","surrender","despair"]],
"confidence":[["noun.feeling","adj.all:close2^confidential","noun.state","adj.all:private^confidential","verb.possession:confide","adj.all:trusty","verb.possession:trust","noun.state","adj.all:confident"],["confidence","diffidence","!security","confidence3","trust","friendship","confidence2","hopefulness"]],
"approbation":[["noun.feeling","verb.communication:approbate","verb.cognition:approbate","verb.cognition:approve"],["approbation","approval"]],
"encouragement":[["noun.feeling","verb.emotion:encourage"],["encouragement","hope"]],
"exultation":[["noun.feeling","verb.emotion:exult","adj.all:joyous^jubilant","adj.all:elated^jubilant","verb.communication:jubilate","adj.all:joyous^jubilant","adj.all:elated^jubilant","verb.communication:jubilate","verb.communication:jubilate"],["exultation","jubilance","jubilancy","jubilation","joy"]],
"foreboding":[["noun.feeling","verb.communication:forebode"],["foreboding","premonition","presentiment","boding","apprehension"]],
"sinking":[["noun.feeling"],["sinking","sinking feeling","anxiety"]],
"undertow":[["noun.feeling"],["undertow","inclination"]],
"emotion":[["noun.feeling","adj.pert:emotional","adj.all:emotional2","verb.emotion:emote","noun.Tops:feeling"],["emotion"]],
"passion":[["noun.feeling","adj.all:passionate","noun.Tops:feeling","noun.state"],["passion","passionateness","Passion2","Passion of Christ","agony"]],
"ardor":[["noun.feeling","noun.feeling","adj.all:enthusiastic^zealous"],["ardor","ardour","love","ardor1","ardour1","elan","zeal1","eagerness"]],
"zeal":[["noun.feeling","adj.all:enthusiastic^zealous"],["zeal2","fervor"]],
"sentiment":[["noun.feeling","adj.all:tender3^sentimental","adj.all:emotional^sentimental","noun.Tops:feeling"],["sentiment"]],
"sentimentality":[["noun.feeling","adj.all:tender3^sentimental"],["sentimentality","sentiment"]],
"razbliuto":[["noun.feeling","noun.location:Russia"],["razbliuto","sentiment"]],
"oedipus complex":[["noun.feeling"],["Oedipus complex","Oedipal complex","complex"]],
"electra complex":[["noun.feeling"],["Electra complex","complex"]],
"inferiority complex":[["noun.feeling"],["inferiority complex","complex"]],
"ambivalence":[["noun.feeling","adj.all:uncertain2^ambivalent","noun.Tops:feeling"],["ambivalence","ambivalency"]],
"emotionlessness":[["noun.feeling","adj.all:cold2^emotionless","adj.all:unemotional^impassive","adj.all:unemotional^impassive","adj.all:uncommunicative^impassive","adj.all:unemotional^phlegmatic","adj.all:unemotional^phlegmatical","adj.all:unemotional^stolid"],["emotionlessness","impassivity","impassiveness","phlegm","indifference1","stolidity","unemotionality","apathy"]],
"american dream":[["noun.feeling"],["American Dream","ambition"]],
"bloodlust":[["noun.feeling"],["bloodlust","desire"]],
"craving":[["noun.feeling","verb.consumption:crave"],["craving","desire"]],
"appetite":[["noun.feeling","adj.all:desirous^appetent","adj.all:desirous^appetent"],["appetite","appetency","appetence","craving"]],
"sweet tooth":[["noun.feeling"],["sweet tooth","appetite"]],
"longing":[["noun.feeling","verb.emotion:long2","verb.emotion:yearn1","verb.emotion:yearn","adj.all:desirous^hungry"],["longing","yearning","hungriness","desire"]],
"hankering":[["noun.feeling","verb.emotion:hanker","verb.emotion:yen"],["hankering","yen","longing"]],
"pining":[["noun.feeling","verb.emotion:pine"],["pining","longing"]],
"wishfulness":[["noun.feeling","adj.all:wishful"],["wishfulness","longing"]],
"wistfulness":[["noun.feeling","adj.all:sad^wistful1"],["wistfulness","longing"]],
"nostalgia":[["noun.feeling"],["nostalgia","longing"]],
"lovesickness":[["noun.feeling","adj.all:unhappy^lovesick"],["lovesickness","pining"]],
"homesickness":[["noun.feeling"],["homesickness","nostalgia"]],
"sexual desire":[["noun.feeling","adj.all:sexy^erotic","adj.all:passionate^concupiscent"],["sexual desire","eros","concupiscence","physical attraction","desire"]],
"aphrodisia":[["noun.feeling"],["aphrodisia","anaphrodisia","!sexual desire"]],
"anaphrodisia":[["noun.feeling"],["anaphrodisia","aphrodisia","!sexual desire"]],
"sensuality":[["noun.feeling","adj.all:physical^sensual","adj.all:physical^sensual","adj.all:hot2^sensual","noun.person:sensualist"],["sensuality","sensualness","sensualism","sexual desire"]],
"amorousness":[["noun.feeling","adj.all:loving^amorous2","adj.all:sexy4","adj.all:sexy","adj.all:loving^amative","noun.feeling","adj.all:loving^amorous1","adj.all:loving^enamored"],["amorousness2","eroticism","erotism","sexiness","amativeness","sexual desire","amorousness1","enamoredness","love"]],
"libido":[["noun.feeling","adj.all:sexy^libidinous","adj.pert:libidinal","noun.act:psychoanalysis"],["libido","sexual desire"]],
"lecherousness":[["noun.feeling","adj.all:sexy^lecherous","adj.all:passionate^lusty","verb.consumption:lust","adj.all:sexy^lustful2","adj.all:sexy^lustful1","adj.all:passionate^lustful"],["lecherousness","lust","lustfulness","sexual desire"]],
"nymphomania":[["noun.feeling","adj.all:neurotic^nymphomaniacal"],["nymphomania","sexual desire"]],
"satyriasis":[["noun.feeling"],["satyriasis","sexual desire"]],
"the hots":[["noun.feeling"],["the hots","sexual desire"]],
"prurience":[["noun.feeling","adj.all:sexy^prurient","adj.all:sexy^prurient","adj.all:sexy^lascivious","adj.all:physical^carnal"],["prurience","pruriency","lasciviousness","carnality","lubricity","amorousness2"]],
"caprice":[["noun.feeling","adj.all:arbitrary^capricious"],["caprice","impulse1","whim","desire"]],
"entrancement":[["noun.feeling","verb.emotion:entrance","verb.body:entrance","verb.emotion:ravish"],["entrancement","ravishment","delight"]],
"amusement":[["noun.feeling","verb.communication:amuse"],["amusement","delight"]],
"schadenfreude":[["noun.feeling","noun.location:Germany"],["Schadenfreude","delight"]],
"joie de vivre":[["noun.feeling"],["joie de vivre","enjoyment"]],
"gusto":[["noun.feeling","verb.emotion:relish","adj.all:spirited^zesty","adj.all:spirited^zestful"],["gusto","relish2","zest","zestfulness","enjoyment","enthusiasm"]],
"cold comfort":[["noun.feeling"],["cold comfort","consolation"]],
"silver lining":[["noun.feeling"],["silver lining","bright side","consolation"]],
"sexual pleasure":[["noun.feeling"],["sexual pleasure","pleasure"]],
"algolagnia":[["noun.feeling","adj.pert:algolagnic"],["algolagnia","algophilia","sexual pleasure"]],
"sadism":[["noun.feeling","adj.all:sadistic","noun.person:sadist"],["sadism","sexual pleasure"]],
"sadomasochism":[["noun.feeling","adj.pert:sadomasochistic","noun.person:sadomasochist"],["sadomasochism","sadism","masochism"]],
"masochism":[["noun.feeling","adj.all:masochistic","noun.person:masochist"],["masochism","sexual pleasure"]],
"guilt pang":[["noun.feeling"],["guilt pang","pang"]],
"mental anguish":[["noun.feeling"],["mental anguish","pain"]],
"throes":[["noun.feeling"],["throes","suffering1"]],
"chafing":[["noun.feeling","noun.state:tenderness"],["chafing"]],
"intertrigo":[["noun.feeling"],["intertrigo","chafing"]],
"self-torture":[["noun.feeling"],["self-torture","self-torment","suffering2"]],
"tsoris":[["noun.feeling","noun.communication:Yiddish"],["tsoris","suffering2"]],
"liking":[["noun.feeling","!noun.Tops:feeling"],["liking","dislike"]],
"fondness":[["noun.feeling","adj.all:inclined2^fond","verb.emotion:fancy"],["fondness1","fancy","partiality","liking"]],
"captivation":[["noun.feeling","verb.emotion:captivate","verb.emotion:enchant1","verb.emotion:enthrall","verb.emotion:fascinate1"],["captivation","enchantment","enthrallment","fascination","liking"]],
"acquired taste":[["noun.feeling"],["acquired taste","preference"]],
"mysophilia":[["noun.feeling"],["mysophilia","liking"]],
"anglophilia":[["noun.feeling","adj.pert:anglophilic"],["Anglophilia","Anglophobia","!admiration1"]],
"hero worship":[["noun.feeling"],["hero worship","admiration1"]],
"philhellenism":[["noun.feeling","noun.person:philhellenist"],["philhellenism","admiration1"]],
"philogyny":[["noun.feeling"],["philogyny","misogyny","!admiration1"]],
"disinclination":[["noun.feeling"],["disinclination","inclination","!dislike"]],
"anglophobia":[["noun.feeling","adj.pert:anglophobic"],["Anglophobia","Anglophilia","!dislike"]],
"abhorrence":[["noun.feeling","adj.all:offensive1^abhorrent","verb.emotion:abhor","verb.emotion:abominate","verb.emotion:detest","verb.emotion:execrate","verb.emotion:loathe","adj.all:hateful^odious"],["abhorrence","abomination","detestation","execration","loathing","odium","hate","disgust"]],
"creepy-crawlies":[["noun.feeling"],["creepy-crawlies","dislike"]],
"scunner":[["noun.feeling","noun.location:Scotland"],["scunner","dislike"]],
"repugnance":[["noun.feeling","adj.all:offensive1^repugnant"],["repugnance","repulsion","revulsion","horror","disgust"]],
"technophobia":[["noun.feeling"],["technophobia","dislike"]],
"gratitude":[["noun.feeling","!noun.Tops:feeling"],["gratitude","ingratitude"]],
"gratefulness":[["noun.feeling","adj.all:grateful","adj.all:thankful","adj.all:grateful^appreciative"],["gratefulness","thankfulness","appreciativeness","gratitude"]],
"ingratitude":[["noun.feeling","adj.all:ungrateful","noun.Tops:feeling"],["ingratitude","gratitude","!ungratefulness"]],
"solicitude":[["noun.feeling","adj.all:concerned^solicitous","adj.all:attentive^solicitous"],["solicitude","solicitousness","concern"]],
"softheartedness":[["noun.feeling","adj.all:softhearted","adj.all:tender3"],["softheartedness","tenderness","concern"]],
"unconcern":[["noun.feeling","!noun.Tops:feeling"],["unconcern","concern"]],
"indifference":[["noun.feeling","adj.all:impartial^indifferent2","adj.all:unimportant^indifferent","adj.all:unconcerned^indifferent","adj.all:impartial^indifferent"],["indifference","unconcern"]],
"heartlessness":[["noun.feeling","adj.all:heartless2","adj.all:coldhearted","adj.all:uncompassionate^hardhearted","adj.all:hardhearted"],["heartlessness","coldheartedness","hardheartedness","unconcern"]],
"self-disgust":[["noun.feeling"],["self-disgust","self-hatred","shame"]],
"shamefacedness":[["noun.feeling","adj.all:ashamed^shamefaced2","adj.all:ashamed^shamefaced1","adj.all:modest1^shamefaced","adj.all:ashamed^sheepish"],["shamefacedness","sheepishness","embarrassment"]],
"chagrin":[["noun.feeling","verb.emotion:chagrin1","verb.emotion:humiliate","verb.emotion:mortify1"],["chagrin","humiliation","mortification","embarrassment"]],
"abashment":[["noun.feeling","verb.emotion:abash","adj.all:timid^bashful"],["abashment","bashfulness","embarrassment"]],
"discomfiture":[["noun.feeling","verb.emotion:discomfit","verb.emotion:discompose","verb.emotion:disconcert2","verb.emotion:disconcert1","verb.emotion:disconcert2","verb.emotion:disconcert1"],["discomfiture","discomposure","disconcertion","disconcertment","embarrassment","anxiety"]],
"self-esteem":[["noun.feeling"],["self-esteem","self-pride","pride"]],
"amour propre":[["noun.feeling","adj.all:proud^vain"],["amour propre","conceit","self-love","vanity","pride"]],
"self-depreciation":[["noun.feeling"],["self-depreciation","humility"]],
"astonishment":[["noun.feeling","verb.cognition:astonish","verb.cognition:amaze","noun.Tops:feeling"],["astonishment","amazement"]],
"buck fever":[["noun.feeling"],["buck fever","fever"]],
"gold fever":[["noun.feeling"],["gold fever","fever"]],
"gaiety":[["noun.feeling"],["gaiety","merriment","happiness"]],
"earnestness":[["noun.feeling","adj.all:sincere^earnest","adj.all:serious^sincere"],["earnestness","seriousness","sincerity","gravity"]],
"oversensitiveness":[["noun.feeling","adj.all:sensitive2^oversensitive"],["oversensitiveness","sensitivity"]],
"feelings":[["noun.feeling","verb.emotion:feel","verb.cognition:feel1"],["feelings","sensitivity"]],
"sensuousness":[["noun.feeling","adj.all:aesthetic^sensuous"],["sensuousness","sensibility"]],
"unrest":[["noun.feeling"],["unrest","agitation"]],
"stewing":[["noun.feeling"],["stewing","agitation"]],
"placidity":[["noun.feeling","adj.all:good-natured^placid","adj.all:calm^placid"],["placidity","placidness","calmness"]],
"dudgeon":[["noun.feeling"],["dudgeon","high dudgeon","indignation"]],
"lividity":[["noun.feeling","adj.all:angry^livid"],["lividity","fury"]],
"infuriation":[["noun.feeling","verb.emotion:infuriate","verb.emotion:enrage"],["infuriation","enragement","anger"]],
"umbrage":[["noun.feeling","adj.all:angry^umbrageous","verb.emotion:offend1"],["umbrage","offense","offence","anger"]],
"indignation":[["noun.feeling","verb.emotion:outrage1"],["indignation","outrage","anger"]],
"huffiness":[["noun.feeling","adj.all:sensitive2^huffy","adj.all:angry^huffy"],["huffiness","anger"]],
"bad temper":[["noun.feeling"],["bad temper","ill temper","anger"]],
"frisson":[["noun.feeling","adj.all:alarming^shivery","verb.motion:shiver","adj.all:alarming^shuddery","verb.emotion:thrill1","verb.emotion:thrill2","verb.perception:tingle"],["frisson","shiver","chill2","quiver","shudder","thrill2","tingle","fear"]],
"swivet":[["noun.feeling"],["swivet","panic"]],
"scare":[["noun.feeling","adj.all:alarming^scary","verb.emotion:scare"],["scare","panic attack","fear"]],
"stage fright":[["noun.feeling"],["stage fright","fear"]],
"trepidation":[["noun.feeling"],["trepidation","apprehension"]],
"presage":[["noun.feeling"],["presage","foreboding"]],
"cold feet":[["noun.feeling"],["cold feet","timidity"]],
"shyness":[["noun.feeling"],["shyness","timidity"]],
"diffidence":[["noun.feeling","adj.all:reserved1^diffident"],["diffidence","confidence","!self-doubt","self-distrust","timidity"]],
"hesitance":[["noun.feeling","adj.all:indecisive1^hesitant","adj.all:indecisive1^hesitant"],["hesitance","hesitancy","diffidence"]],
"unassertiveness":[["noun.feeling","adj.all:unassertive"],["unassertiveness","diffidence"]],
"intimidation":[["noun.feeling","verb.emotion:intimidate","noun.feeling"],["intimidation","fearfulness","intimidation1","discouragement2"]],
"anxiousness":[["noun.feeling","adj.all:troubled^anxious","verb.emotion:disquiet"],["anxiousness","disquiet","anxiety"]],
"edginess":[["noun.feeling","adj.all:tense3^edgy","adj.all:uneasy"],["edginess","uneasiness2","inquietude","disquietude","anxiety"]],
"willies":[["noun.feeling"],["willies","edginess"]],
"jitteriness":[["noun.feeling","adj.all:tense3^jittery","adj.all:tense3^jumpy","adj.all:troubled^nervous","adj.all:excited^nervous","adj.all:tense3^restive"],["jitteriness","jumpiness","nervousness","restiveness","anxiety"]],
"angst":[["noun.feeling"],["angst","anxiety"]],
"bonheur":[["noun.feeling","noun.location:France"],["bonheur","happiness"]],
"gladness":[["noun.feeling","adj.all:grateful^glad","adj.all:cheerful^glad","adj.all:glad","adj.all:glad^gladsome"],["gladness","gladfulness","gladsomeness","happiness"]],
"triumph":[["noun.feeling","adj.all:elated^triumphal","verb.emotion:triumph"],["triumph","exultation"]],
"exhilaration":[["noun.feeling","verb.emotion:exhilarate","verb.emotion:excite2"],["exhilaration","excitement","joy"]],
"intoxication":[["noun.feeling","verb.emotion:intoxicate"],["intoxication","excitement"]],
"euphoria":[["noun.feeling","adj.all:euphoric"],["euphoria","dysphoria","!euphory","elation"]],
"hilarity":[["noun.feeling","adj.all:humorous^hilarious","adj.all:joyous^mirthful","adj.all:humorous^mirthful","adj.all:joyous^gleeful"],["hilarity","mirth","mirthfulness","glee","gleefulness","merriment"]],
"rejoicing":[["noun.feeling","verb.emotion:rejoice2","verb.emotion:rejoice"],["rejoicing","happiness"]],
"jocundity":[["noun.feeling","adj.all:joyous^jocund","adj.all:humorous^jocular"],["jocundity","jocularity","merriment"]],
"belonging":[["noun.feeling"],["belonging","happiness"]],
"comfortableness":[["noun.feeling","adj.all:comfortable1"],["comfortableness","belonging"]],
"togetherness":[["noun.feeling","adj.all:unneurotic^together"],["togetherness","closeness"]],
"contentment":[["noun.feeling","verb.consumption:content"],["contentment","discontentment","!happiness"]],
"complacency":[["noun.feeling","adj.all:contented^complacent","adj.all:contented^complacent","adj.all:contented^self-complacent"],["complacency","complacence","self-complacency","self-satisfaction","satisfaction"]],
"smugness":[["noun.feeling","adj.all:contented^smug"],["smugness","complacency"]],
"dolefulness":[["noun.feeling","adj.all:sad^doleful"],["dolefulness","sadness"]],
"gloom":[["noun.feeling","adj.all:cheerless^somber","adj.all:cheerless^sombre","noun.state","adj.all:dark1^gloomy","adj.all:colorless2^somber","adj.all:colorless2^sombre","noun.state"],["gloom","gloominess","somberness","sombreness","melancholy","apprehension","gloom1","somberness","sombreness","semidarkness","gloom2","gloominess2","glumness","atmosphere1"]],
"heavyheartedness":[["noun.feeling","adj.all:sad^heavyhearted"],["heavyheartedness","melancholy"]],
"world-weariness":[["noun.feeling","adj.all:tired^world-weary"],["world-weariness","Weltschmerz","melancholy"]],
"woe":[["noun.feeling","adj.all:sorrowful^woeful"],["woe","woefulness","mournfulness"]],
"forlornness":[["noun.feeling","adj.all:dejected^lonely","verb.cognition:desolate"],["forlornness","loneliness","desolation2","sadness"]],
"weepiness":[["noun.feeling","adj.all:tearful^weepy","adj.all:sorrowful^tearful","adj.all:tearful"],["weepiness","tearfulness","sadness"]],
"sorrow":[["noun.feeling","verb.emotion:sorrow","noun.feeling","verb.emotion:sorrow","verb.communication:regret2","verb.emotion:regret1","verb.emotion:regret","verb.emotion:rue","adj.all:penitent^rueful"],["sorrow","joy","!sadness","sorrow1","regret","rue","ruefulness","sadness"]],
"broken heart":[["noun.feeling"],["broken heart","sorrow"]],
"mournfulness":[["noun.feeling","adj.all:sorrowful^mournful1","adj.all:sad^mournful","adj.all:sorrowful","adj.all:penitent^ruthful"],["mournfulness","sorrowfulness","ruthfulness","sorrow"]],
"plaintiveness":[["noun.feeling","adj.all:sorrowful^plaintive"],["plaintiveness","mournfulness"]],
"dolor":[["noun.feeling","adj.all:sorrowful^dolourous","adj.all:sorrowful^dolorous","noun.communication:poetry2"],["dolor","dolour","grief"]],
"compunction":[["noun.feeling"],["compunction","remorse","self-reproach","sorrow1"]],
"survivor guilt":[["noun.feeling","noun.state:posttraumatic stress disorder"],["survivor guilt","guilt"]],
"repentance":[["noun.feeling","adj.all:repentant","verb.emotion:repent","adj.all:penitent^penitential","adj.all:punitive^penitentiary","adj.all:penitent"],["repentance","penitence","penance","compunction"]],
"cheerlessness":[["noun.feeling","adj.all:cheerless","adj.all:uncheerful4"],["cheerlessness","cheerfulness","!uncheerfulness","sadness"]],
"joylessness":[["noun.feeling","adj.all:joyless"],["joylessness","cheerlessness"]],
"downheartedness":[["noun.feeling","adj.all:dejected^downhearted","adj.all:dejected^low-spirited","adj.all:humble^low","adj.all:dejected^low","adj.all:spiritless^dispirited","adj.all:dejected^dispirited"],["downheartedness","dejectedness","low-spiritedness","lowness","dispiritedness","sadness"]],
"self-pity":[["noun.feeling"],["self-pity","sorrow"]],
"despondency":[["noun.feeling","adj.all:hopeless^despondent","verb.emotion:despond","adj.all:hopeless^despondent","verb.emotion:despond","adj.all:sorrowful^heartsick","adj.all:hopeless^heartsick","adj.all:disconsolate4"],["despondency","despondence","heartsickness","disconsolateness","depression"]],
"discontentment":[["noun.feeling","verb.emotion:discontent","adj.all:discontent","verb.emotion:discontent","adj.all:discontented"],["discontentment","contentment","!discontent","discontentedness","longing"]],
"disgruntlement":[["noun.feeling","verb.emotion:disgruntle"],["disgruntlement","discontentment"]],
"dysphoria":[["noun.feeling","adj.all:dysphoric"],["dysphoria","euphoria","!discontentment","depression"]],
"dissatisfaction":[["noun.feeling","verb.emotion:dissatisfy"],["dissatisfaction","satisfaction","!discontentment"]],
"boredom":[["noun.feeling","adj.all:uninteresting^tedious"],["boredom","ennui","tedium","dissatisfaction"]],
"blahs":[["noun.feeling","noun.communication:colloquialism"],["blahs","boredom"]],
"displeasure":[["noun.feeling","verb.emotion:displease"],["displeasure","dissatisfaction","annoyance"]],
"sanguinity":[["noun.feeling","adj.all:optimistic^sanguine","adj.all:optimistic^sanguine"],["sanguinity","sanguineness","optimism"]],
"hopelessness":[["noun.feeling","adj.all:unskilled^hopeless3","adj.all:hopeless"],["hopelessness","hopefulness","!despair"]],
"defeatism":[["noun.feeling","noun.person:defeatist"],["defeatism","resignation"]],
"cynicism":[["noun.feeling"],["cynicism","pessimism"]],
"filial love":[["noun.feeling"],["filial love","love"]],
"puppy love":[["noun.feeling","verb.emotion:infatuate"],["puppy love","calf love","crush","infatuation2","love"]],
"affection":[["noun.feeling","adj.all:loving^affectionate","adj.all:loving^fond2","adj.all:loving^tender","adj.all:warm2^hearty","adj.all:warm2","adj.all:warmhearted","noun.Tops:feeling"],["affection","affectionateness","fondness","tenderness1","heart4","warmness","warmheartedness","philia"]],
"soft spot":[["noun.feeling"],["soft spot","affection"]],
"heartstrings":[["noun.feeling"],["heartstrings","love","compassion"]],
"lovingness":[["noun.feeling","adj.all:loving","adj.all:compassionate^caring","verb.emotion:care2"],["lovingness","caring1","love"]],
"warmheartedness":[["noun.feeling","adj.all:warmhearted"],["warmheartedness1","warmth","lovingness"]],
"misogamy":[["noun.feeling","noun.person:misogamist"],["misogamy","hate"]],
"misogyny":[["noun.feeling","adj.all:distrustful^misogynic","adj.all:ill-natured^misogynous","!noun.person:misogynist"],["misogyny","philogyny","misogynism","hate"]],
"mysoandry":[["noun.feeling"],["mysoandry","hate"]],
"misology":[["noun.feeling"],["misology","hate"]],
"misoneism":[["noun.feeling"],["misoneism","hate"]],
"misocainea":[["noun.feeling"],["misocainea","misoneism"]],
"misopedia":[["noun.feeling"],["misopedia","hate"]],
"despisal":[["noun.feeling","verb.emotion:despise","verb.emotion:despise"],["despisal","despising","hate"]],
"animosity":[["noun.feeling"],["animosity","animus","bad blood","hostility"]],
"class feeling":[["noun.feeling"],["class feeling","hostility"]],
"belligerence":[["noun.feeling","adj.all:hostile1^belligerent","adj.all:hostile1^belligerent"],["belligerence","belligerency","hostility"]],
"resentment":[["noun.feeling","verb.emotion:resent","adj.all:hostile1^bitter","verb.emotion:gall","adj.all:resentful^rancorous"],["resentment","bitterness","gall","rancor","rancour","hostility"]],
"heartburning":[["noun.feeling"],["heartburning","resentment"]],
"covetousness":[["noun.feeling"],["covetousness1","envy"]],
"penis envy":[["noun.feeling","noun.act:psychoanalysis"],["penis envy","envy"]],
"malice":[["noun.feeling","adj.all:malicious","adj.all:malicious","verb.emotion:spite","adj.all:malicious^spiteful","adj.all:malicious^venomous"],["malice","maliciousness","spite","spitefulness","venom","malevolence"]],
"vindictiveness":[["noun.feeling","adj.all:unforgiving^vindictive","adj.all:malicious^vindictive","adj.all:unforgiving^vengeful"],["vindictiveness","vengefulness","malevolence"]],
"good humor":[["noun.feeling","adj.all:good-natured^amiable","adj.all:friendly1^amiable"],["good humor","ill humor","!good humour","good temper","amiability","temper"]],
"jollity":[["noun.feeling","adj.all:joyous^jolly","adj.all:joyous^jolly","adj.all:joyous^jovial"],["jollity","jolliness","joviality","good humor","merriment"]],
"ill humor":[["noun.feeling"],["ill humor","good humor","!ill humour","distemper","temper"]],
"moroseness":[["noun.feeling","adj.all:ill-natured^morose","adj.all:ill-natured^glum","adj.all:dejected^glum","adj.all:cloudy^sullen"],["moroseness","glumness","sullenness","moodiness"]],
"irascibility":[["noun.feeling","adj.all:ill-natured^irascible","adj.all:angry^irascible","adj.all:ill-natured^splenetic"],["irascibility","short temper","spleen","quick temper","bad temper"]],
"irritability":[["noun.feeling","adj.all:ill-natured^irritable","adj.all:complaining^fretful","adj.all:ill-natured^fussy","adj.all:ill-natured^peevish","adj.all:ill-natured^petulant"],["irritability","crossness","fretfulness","fussiness","peevishness","petulance","choler2","ill humor"]],
"testiness":[["noun.feeling","adj.all:ill-natured^testy","adj.all:sensitive2^touchy","adj.all:ill-natured^tetchy"],["testiness","touchiness1","tetchiness","irritability"]],
"kindheartedness":[["noun.feeling","adj.all:kind^kindhearted"],["kindheartedness","kind-heartedness","sympathy"]],
"commiseration":[["noun.feeling","verb.emotion:commiserate","adj.all:unfortunate^piteous","verb.emotion:pity","adj.all:unfortunate^pathetic"],["commiseration","pity","ruth","pathos","sympathy"]],
"empathy":[["noun.feeling","adj.all:sympathetic^empathetic","verb.cognition:empathize","verb.cognition:empathise"],["empathy","sympathy"]],
"eagerness":[["noun.feeling","adj.all:eager","adj.all:enthusiastic^avid","adj.all:enthusiastic^avid"],["eagerness","avidity1","avidness","keenness","enthusiasm"]],
"technophilia":[["noun.feeling"],["technophilia","enthusiasm"]]
}