var mysql_wn_data_noun_Tops = {
"food":[["noun.Tops","adj.all:wholesome^nutrient","verb.consumption:nutrify"],["food","nutrient","substance1"]],
"thing":[["noun.Tops","noun.cognition"],["thing","physical entity","thing1","aim1"]],
"relation":[["noun.Tops","noun.state:relationship","noun.relation:relationship1","noun.relation:relationship","verb.stative:relate1","verb.cognition:relate","noun.communication","verb.communication:relate","verb.communication:tell1","verb.communication:recount"],["relation","abstraction","relation1","telling1","recounting","narration"]],
"motivation":[["noun.Tops","adj.pert:motivational","verb.creation:motivate","adj.all:causative^motive2","verb.creation:motivate"],["motivation","motive","need","psychological feature"]],
"abstraction":[["noun.Tops","verb.cognition:abstract","noun.cognition","verb.cognition:abstract","verb.communication:generalize1","verb.communication:generalise1"],["abstraction","abstract entity","entity","abstraction2","generalization3","generalisation3","theorization"]],
"possession":[["noun.Tops","noun.act"],["possession","relation","possession1","control","sport"]],
"cell":[["noun.Tops","adj.pert:cellular","adj.all:cellular","noun.cognition:biology","noun.artifact","adj.pert:cellular","noun.artifact","adj.pert:cellular","noun.artifact","adj.pert:cellular","adj.all:cellular"],["cell","living thing","organism","cell1","jail cell","prison cell","room","cellblock","cell2","cubicle2","room","monastery","convent","cell3","compartment1"]],
"location":[["noun.Tops","verb.stative:locate","verb.possession:locate1","verb.possession:locate","verb.change:locate"],["location","object","space"]],
"matter":[["noun.Tops","noun.cognition","noun.cognition"],["matter","physical entity","matter1","affair","thing2","concern","matter2","trouble"]],
"person":[["noun.Tops","noun.attribute:personhood","verb.cognition:personify","verb.change:individualize","adj.all:mortal","noun.group:people"],["person","individual","someone","somebody","mortal","soul","organism","causal agent"]],
"feeling":[["noun.Tops","verb.emotion:feel","noun.cognition","verb.perception:feel"],["feeling","state","feeling1","somesthesia1"]],
"life":[["noun.Tops","noun.time","noun.person:lifer","noun.time"],["life","living thing","life2","time period","life1","time period"]],
"whole":[["noun.Tops","adj.all:undiversified^whole","verb.contact:unify","verb.change:unify","verb.contact:unitize","verb.change:unitize"],["whole","unit","object"]],
"communication":[["noun.Tops","adj.all:communicative^communicational","verb.possession:communicate10","verb.communication:communicate8","verb.communication:communicate7","verb.communication:communicate2","verb.communication:communicate1","verb.communication:communicate"],["communication","abstraction"]],
"phenomenon":[["noun.Tops"],["phenomenon","process"]],
"organism":[["noun.Tops","adj.pert:organismic","adj.all:organic2","adj.all:organic","verb.stative:be1"],["organism","being","living thing"]],
"benthos":[["noun.Tops","adj.pert:benthonic"],["benthos","organism"]],
"native":[["noun.Tops","noun.Tops:organism","noun.person","noun.Tops:person"],["native","native1"]],
"parent":[["noun.Tops"],["parent","organism"]],
"event":[["noun.Tops"],["event","psychological feature"]],
"substance":[["noun.Tops","adj.all:substantial","noun.relation:part","noun.Tops"],["substance","matter","substance1","matter"]],
"congener":[["noun.Tops"],["congener","whole"]],
"entity":[["noun.Tops"],["entity"]],
"physical entity":[["noun.Tops"],["physical entity","entity"]],
"living thing":[["noun.Tops"],["living thing","animate thing","whole"]],
"heterotroph":[["noun.Tops"],["heterotroph","organism"]],
"biont":[["noun.Tops"],["biont","living thing"]],
"causal agent":[["noun.Tops","adj.all:causative^causal","verb.creation:cause","verb.communication:cause"],["causal agent","cause","causal agency","physical entity"]],
"animal":[["noun.Tops","verb.creation:animalize","verb.creation:animalise","adj.all:inhumane^beastly","adj.all:inhumane^bestial","verb.creation:create","noun.animal:kingdom Animalia"],["animal","animate being","beast","brute","creature","fauna","organism"]],
"natural object":[["noun.Tops"],["natural object","artifact","whole"]],
"nutrient":[["noun.Tops"],["nutrient1","substance1"]],
"artifact":[["noun.Tops","adj.pert:artifactual","adj.pert:artefactual"],["artifact","natural object","artefact","whole"]],
"psychological feature":[["noun.Tops"],["psychological feature","abstraction"]],
"cognition":[["noun.Tops","adj.all:mental^noetic"],["cognition","knowledge","noesis","psychological feature"]],
"attribute":[["noun.Tops"],["attribute","abstraction"]],
"absolute space":[["noun.Tops"],["absolute space","space"]],
"phase space":[["noun.Tops","noun.cognition:physics"],["phase space","space"]],
"social relation":[["noun.Tops"],["social relation","relation"]]
}