var mysql_wn_data_verb_weather = {
"shoot":[["verb.weather","verb.communication","verb.competition","noun.act:sport","verb.contact","noun.person:shooter2","noun.artifact:shooter","verb.motion","verb.creation:cast2","verb.contact"],["shoot","emit","shoot5","utter2","shoot6","score","shoot1","hit3","frames:2","shoot3","shoot10","weave"]],
"flare":[["verb.weather","noun.process:flare","verb.change:burn","verb.weather","noun.process:flare"],["flare","flame up","blaze up","burn up","flare1","flame1","flame up","^shine"]],
"shower":[["verb.weather","noun.phenomenon:shower","noun.event:shower","verb.consumption"],["shower","shower down","rain","shower12","provide"]],
"sprinkle":[["verb.weather","noun.phenomenon:sprinkle","noun.phenomenon:sprinkling"],["sprinkle","spit","spatter","patter","pitter-patter","rain"]],
"overcast":[["verb.weather","noun.state:overcast1","noun.state:overcast","noun.object:cloud","noun.process:clouding","^verb.change:darken1","verb.contact","noun.artifact:overcast","noun.artifact:overcasting"],["overcast","clear up","cloud","cloud over","^cloud up","overcast1","sew"]],
"blow":[["verb.weather","noun.phenomenon:blow","verb.change","verb.contact","verb.motion","noun.act:blow2","verb.motion","noun.artifact:blower2","noun.artifact:blower","verb.motion","noun.phenomenon:blow","noun.artifact:blower2","noun.artifact:blower","verb.perception"],["blow","frames:1","3","blow7","burst","frames:1","blow8","lay","blow12","spurt1","blow9","direct1","blow3","move1","frames:8","blow5","sound"]],
"storm":[["verb.weather","noun.phenomenon:storm","verb.weather","noun.phenomenon:storm"],["storm","blow","storm1","rain"]],
"ray":[["verb.weather","noun.phenomenon:ray","noun.animal"],["ray","emit","ray1","spine","fin"]],
"flicker":[["verb.weather","noun.event:flicker"],["flicker","flick","shine"]],
"spat":[["verb.weather","verb.contact","noun.animal:spat"],["spat","fall","spat1","attach","frames:1"]],
"char":[["verb.weather","noun.substance:char","noun.substance:coal","noun.object:coal"],["char","coal","burn2"]],
"gutter":[["verb.weather","noun.artifact","verb.contact:gut"],["gutter","burn1","gutter1","hand tool"]],
"mirror":[["verb.weather","noun.cognition:mirror","noun.artifact:mirror","verb.perception:reflect"],["mirror","frames:11"]],
"sheet":[["verb.weather","noun.artifact","verb.motion:tack","noun.act:seafaring","noun.artifact","noun.Tops:artifact"],["sheet","pour","sheet2","tack2","mainsheet","weather sheet","shroud1","line","ship","sheet3","flat solid"]],
"sluice":[["verb.weather","noun.artifact:sluice","verb.motion","noun.artifact:sluice"],["sluice","sluice down","pour","frames:1","sluice1","transport"]],
"blaze":[["verb.weather","noun.process:blaze","^verb.change:burn"],["blaze","blaze up"]],
"sparkle":[["verb.weather","noun.attribute:sparkle","noun.event:sparkle","noun.possession:sparkler","noun.event:sparkling","adj.all:bright^scintillant","noun.attribute:scintillation","adj.all:bright^coruscant","noun.event:coruscation"],["sparkle","scintillate3","coruscate","shine1"]],
"rain":[["verb.weather","noun.substance:rain","noun.phenomenon:rain"],["rain","rain down","precipitate","frames:3"]],
"shadow":[["verb.weather","noun.location:shadow","noun.state:shadow1","noun.state:shade","verb.change:darken1","noun.state","adj.all:shaded1^shadowy2","verb.weather:shadow"],["shadow","shade","shade off","frames:11","10","shadow1","shade"]],
"hail":[["verb.weather","noun.phenomenon:hail","verb.communication"],["hail","precipitate","hail1","call5"]],
"thunder":[["verb.weather","noun.event:thunder1"],["thunder","boom","storm"]],
"twinkle":[["verb.weather","noun.event:twinkle","noun.object:twinkler","adj.all:bright^scintillant","noun.attribute:scintillation1","noun.object:scintilla","noun.object:celestial body"],["twinkle","winkle","scintillate","shine"]],
"shimmer":[["verb.weather","noun.event:shimmer"],["shimmer","shine"]],
"swamp":[["verb.weather","noun.object:swamp","verb.change:flood"],["swamp","drench","frames:1"]],
"snow":[["verb.weather","noun.substance:snow","noun.phenomenon:snow"],["snow","precipitate"]],
"breeze":[["verb.weather","noun.phenomenon:breeze"],["breeze","blow","frames:1","3"]],
"bluster":[["verb.weather","noun.phenomenon:bluster"],["bluster","blow"]],
"haze":[["verb.weather","noun.phenomenon:haze"],["haze","overcast"]],
"drizzle":[["verb.weather","noun.phenomenon:drizzle","noun.phenomenon:mizzle"],["drizzle","mizzle","rain"]],
"sleet":[["verb.weather","noun.phenomenon:sleet"],["sleet","precipitate"]],
"squall":[["verb.weather","noun.phenomenon:squall","verb.communication"],["squall","blow","squall1","waul","wawl","howl2","frames:1"]],
"blight":[["verb.weather","noun.state:blight1","noun.state:blight","noun.group:plague","noun.state:plague1","noun.state:plague","verb.change:afflict"],["blight","plague","frames:10"]],
"precipitate":[["verb.weather","noun.quantity:precipitation","noun.phenomenon:precipitation","verb.change:condense1","verb.motion","noun.event:precipitation"],["precipitate","come down","fall","*frames:1","precipitate1","fall","frames:22"]],
"steam":[["verb.weather","verb.motion"],["steam","emit","frames:1","steam1","rise"]],
"reek":[["verb.weather"],["reek","emit"]],
"emit":[["verb.weather","noun.act:emission","noun.artifact:emitter"],["emit","absorb","give out","give off","frames:8"]],
"black out":[["verb.weather","verb.change","noun.event:blackout","noun.state:blackout"],["black out","extinguish","frames:8","black out1","blacken out","darken"]],
"radiate":[["verb.weather","adj.all:bright^radiant","noun.phenomenon:radiation","noun.attribute:radiancy","noun.attribute:radiance","verb.change","adj.all:bright^radiant","noun.object:radiator"],["radiate","emit","frames:1","radiate2","emerge2","frames:4"]],
"erupt":[["verb.weather","adj.all:combustible^ignitible","adj.all:combustible^ignitable","noun.act:ignition","adj.all:combustible","adj.all:combustible^combustive","verb.change:change state","verb.change","noun.event:eruption3","noun.event:irruption","noun.event:flare-up1","verb.change","verb.body:ail1","verb.change","verb.stative:begin","verb.change","verb.change","noun.event:eruption2"],["erupt","ignite1","catch fire","take fire","combust","conflagrate","erupt2","irrupt3","flare up","flare1","break open","burst out","intensify","frames:1","erupt3","recrudesce","break out","frames:1","erupt1","break out4","erupt6","erupt4","$appear","frames:1","erupt4","come out3","break through1","push through","appear"]],
"absorb":[["verb.weather","adj.all:absorptive","adj.all:absorbent","adj.all:absorbable","noun.process:absorption2","verb.cognition","noun.cognition:absorption","noun.cognition:engrossment1","noun.cognition:engrossment","noun.attribute:engrossment","noun.act:occupation4","noun.act:occupation","verb.emotion:interest","verb.contact","verb.contact","adj.all:absorptive","adj.all:absorbent","noun.process:absorption","noun.substance:absorbate","noun.substance:absorbent","noun.substance:absorber","noun.cognition:chemistry"],["absorb","emit","take in","frames:8","absorb3","engross","engage","occupy","frames:9","absorb10","receive","frames:9","absorb1","sorb"]],
"set in":[["verb.weather"],["set in","blow"]],
"douse":[["verb.weather"],["douse","put out","extinguish"]],
"liquefy":[["verb.weather","adj.all:liquid^liquefiable","noun.process:liquefaction","verb.change:change state","verb.change","adj.all:liquid^liquefiable","noun.process:liquefaction","adj.all:liquid^liquifiable","noun.substance:liquid","noun.state:liquid","noun.artifact:liquidizer","noun.artifact:liquidizer","noun.cognition:physics"],["liquefy","liquefy1","liquify1","liquidize","liquidise","change1","frames:8"]],
"snuff out":[["verb.weather","noun.act:extinction1","noun.artifact:extinguisher","noun.act:extinguishing","noun.act:quenching"],["snuff out","blow out","extinguish","ignite","quench","frames:8"]],
"deflagrate":[["verb.weather","noun.process:deflagration"],["deflagrate","burn2","frames:8"]],
"reflect":[["verb.weather","adj.all:reflective","noun.object:shiner","noun.attribute:shine","verb.perception","verb.communication:indicate3","verb.perception","noun.cognition:optics"],["reflect","shine1","emit","reflect1","reflect2","show"]],
"flame":[["verb.weather","noun.process:flame","noun.process:flaming","verb.change:burn"],["flame"]],
"outshine":[["verb.weather"],["outshine","shine"]],
"suck":[["verb.weather","noun.act:suck","noun.act:suction"],["suck","suck in","absorb"]],
"rekindle":[["verb.weather"],["rekindle","kindle"]],
"fume":[["verb.weather","noun.phenomenon:fume","noun.process:smoke","noun.phenomenon:smoke","noun.process:smoking"],["fume","smoke","emit"]],
"waft":[["verb.weather"],["waft","blow","frames:1"]],
"pour":[["verb.weather","noun.phenomenon:pelter","verb.motion","verb.motion","verb.consumption:pour down"],["pour","pelt","stream","rain cats and dogs","rain buckets","rain","pour2","run1","pour3","^run1",">move1","frames:8"]],
"shine":[["verb.weather","noun.attribute:shine","noun.phenomenon:beam"],["shine","beam3"]],
"opalesce":[["verb.weather","adj.all:bright^opalescent","noun.attribute:opalescence"],["opalesce","reflect"]],
"ice up":[["verb.weather","*verb.change:change"],["ice up","frost over","ice over","freeze10","frames:1"]],
"ignite":[["verb.weather","adj.all:combustible^ignitible","adj.all:combustible^ignitable","noun.process:ignition","noun.act:ignition","noun.substance:igniter","noun.artifact:igniter","noun.substance:ignitor","noun.artifact:ignitor","noun.artifact:light1","noun.substance:lighter","noun.artifact:lighter","verb.change:burn"],["ignite","extinguish","light",">burn2","frames:8"]],
"set ablaze":[["verb.weather"],["set ablaze","set aflame","set on fire1","set afire","ignite","*burn2","frames:8"]],
"reignite":[["verb.weather"],["reignite","ignite"]],
"kindle":[["verb.weather","noun.act:inflammation1","verb.weather","noun.substance:kindling","noun.act:kindling","noun.act:inflammation1"],["kindle","enkindle","conflagrate1","inflame","ignite","frames:8","kindle1","inflame1","flare up"]],
"flare up":[["verb.weather"],["flare up","ignite"]],
"luminesce":[["verb.weather","adj.all:light6^luminescent","noun.phenomenon:luminescence","noun.attribute:luminescence"],["luminesce","shine1"]],
"overcloud":[["verb.weather","verb.change:darken"],["overcloud","cloud over","cloud up","frames:1"]],
"clear up":[["verb.weather"],["clear up","overcast","clear","light up","brighten","frames:3"]],
"run dry":[["verb.weather","verb.change:dry"],["run dry","dry out1"]],
"fog up":[["verb.weather"],["fog up","overcast","frames:3"]]
}