var mysql_wn_data_verb_body = {
"soup":[["verb.body","noun.act:medicine"],["soup","dope","frames:8"]],
"mousse":[["verb.body","noun.artifact:mousse"],["mousse","gel","groom"]],
"lamb":[["verb.body","noun.food:lamb","noun.animal:lamb","noun.person","noun.person"],["lamb","deliver1","lamb1","victim1","Lamb2","Charles Lamb","Elia","essayist"]],
"exercise":[["verb.body","noun.act:exercise","noun.artifact:exerciser","noun.act:exercising","noun.act:workout","$verb.motion:move","verb.body","noun.act:exercise","noun.artifact:exerciser","noun.act:workout",">verb.social:work1","noun.act","verb.cognition:exercise","verb.creation:practice","verb.cognition:practice","verb.cognition:drill1","verb.cognition:drill"],["exercise","work out","work out1","*frames:2","exercise1","work","work out1","exercise","frames:9","exercise2","practice2","drill","practice session","recitation","training"]],
"entrance":[["verb.body","noun.feeling:entrancement","noun.person:spellbinder"],["entrance","spellbind","hypnotize","frames:9"]],
"blink":[["verb.body","noun.act:blink","noun.act:blinking","noun.act:wink","noun.person:winker","noun.act:winking","noun.act:nictitation","noun.act:nictation"],["blink","wink","nictitate","nictate","act involuntarily"]],
"blush":[["verb.body","noun.act:blush","noun.plant:blusher","noun.artifact:blusher","noun.attribute:crimson","noun.state:flush","noun.act:flush","verb.change:discolor","verb.change"],["blush","crimson","flush","redden","blush1","redden","frames:1"]],
"vomit":[["verb.body","noun.act:vomit","noun.artifact:vomit","noun.substance:vomit","noun.person:vomiter","noun.act:vomiting","noun.group:sick","noun.act:disgorgement","noun.act:retch","noun.substance:puke","noun.act:puking","noun.person:spewer","noun.act:regurgitation"],["vomit","keep down","vomit up","frames:8purge4","cast","sick","cat","be sick1","disgorge","regorge","retch","frames:8puke","barf","spew","spue","chuck","upchuck","honk","regurgitate","frames:8throw up","frames:8eliminate"]],
"tonsure":[["verb.body","noun.act:tonsure","noun.body:tonsure"],["tonsure","shave"]],
"shampoo":[["verb.body","noun.act:shampoo","noun.artifact:shampoo"],["shampoo","wash","frames:2","8"]],
"salve":[["verb.body","noun.act:salve","noun.artifact:salve","noun.act:medicine"],["salve","medicate"]],
"habit":[["verb.body","noun.artifact:habit","noun.artifact"],["habit","dress1","habit1","riding habit","attire"]],
"torture":[["verb.body","noun.act:torture","noun.state:torture","noun.person:torturer","noun.act:torturing","noun.state:excruciation","noun.act:excruciation","noun.state:torment","noun.person:tormenter"],["torture","excruciate","torment","injure"]],
"doctor":[["verb.body","noun.person:doctor","noun.act:medicine","noun.person","adj.pert:doctorial","adj.pert:doctoral"],["doctor","treat","frames:9","doctor1","Dr.1","scholar"]],
"bat":[["verb.body","verb.contact","noun.artifact:bat3","noun.artifact:bat","noun.person:batter","noun.act:batting","noun.act:baseball","verb.contact","noun.act:baseball","verb.contact","noun.act:baseball"],["bat","flutter","wink","bat1","hit","bat2","bat1","$hit","bat3","bat1","$hit"]],
"manicure":[["verb.body","noun.act:manicure","noun.person:manicurist","verb.body","noun.act:manicure","noun.person:manicurist","verb.contact:cut"],["manicure","groom","manicure1"]],
"pedicure":[["verb.body","noun.act:pedicure"],["pedicure","groom"]],
"douche":[["verb.body","noun.act:douche","noun.artifact:douche"],["douche","cleanse","frames:2"]],
"snore":[["verb.body","noun.act:snore","noun.event:snore","noun.person:snorer","noun.act:snoring"],["snore","saw wood","saw logs","sleep","*breathe"]],
"snuffle":[["verb.body","noun.act:snuffle","noun.person:snuffler","noun.act:snivel1","noun.person:sniveller"],["snuffle","snivel","inhale"]],
"wheeze":[["verb.body","noun.act:wheeze"],["wheeze","breathe"]],
"yawn":[["verb.body","noun.act:yawn","noun.person:yawner","noun.act:yawning"],["yawn","breathe"]],
"fart":[["verb.body","noun.act:fart","noun.act:farting"],["fart","break wind","act involuntarily"]],
"nap":[["verb.body","noun.act:nap","noun.act:catnap"],["nap","catnap","catch a wink","sleep"]],
"wince":[["verb.body","noun.communication:wince"],["wince","grimace"]],
"sob":[["verb.body","noun.act:sob","noun.act:sobbing"],["sob","cry"]],
"stare":[["verb.body","noun.act:stare","noun.person:starer","verb.perception:look"],["stare"]],
"wake":[["verb.body","noun.cognition:waking","verb.communication"],["wake","sleep","wake2","alert","frames:9"]],
"comfort":[["verb.body","noun.state:comfort","noun.artifact:comforter1","noun.artifact:comforter","noun.act:easement","noun.act:easing","noun.state"],["comfort","ease","relieve","frames:9","comfort2","gratification"]],
"cub":[["verb.body","noun.animal:cub","noun.person"],["cub","give birth","cub1","greenhorn","rookie","novice"]],
"spawn":[["verb.body","noun.animal:spawner","verb.contact:lay2"],["spawn"]],
"kitten":[["verb.body","noun.animal:kitten"],["kitten","deliver1"]],
"foal":[["verb.body","noun.animal:foal"],["foal","deliver1"]],
"hock":[["verb.body"],["hock","disable"]],
"autoclave":[["verb.body","noun.artifact:autoclave"],["autoclave","sterilize1"]],
"bandage":[["verb.body","noun.artifact:bandage","noun.act:medicine"],["bandage","dress2"]],
"beam":[["verb.body","noun.artifact","verb.communication"],["beam","smile","beam2","side","beam1","express1","frames:8"]],
"bonnet":[["verb.body","noun.artifact:bonnet"],["bonnet","hat"]],
"calk":[["verb.body","verb.contact","noun.artifact:calk","verb.possession:provide","noun.act:animal husbandry"],["calk","wound","calk1"]],
"chloroform":[["verb.body","noun.artifact:chloroform"],["chloroform","anesthetize"]],
"corset":[["verb.body","noun.artifact:corset"],["corset","dress1"]],
"detox":[["verb.body","noun.act:detoxification1"],["detox","detoxify","treat"]],
"floss":[["verb.body","noun.artifact:floss1"],["floss","cleanse","frames:2"]],
"frock":[["verb.body","noun.artifact:frock"],["frock","dress1"]],
"gown":[["verb.body","noun.artifact:gown2","noun.artifact:gown1","noun.artifact:gown","noun.artifact","verb.body:gown","verb.body:robe","noun.artifact","verb.body:gown"],["gown","dress1","gown1","robe1","outerwear","gown2","surgical gown","scrubs","garment"]],
"pomade":[["verb.body","noun.artifact:pomade"],["pomade","groom"]],
"poultice":[["verb.body","noun.artifact:poultice","noun.artifact:plaster2","noun.act:plastering","noun.act:medicine"],["poultice","plaster","dress2"]],
"powder":[["verb.body","noun.artifact:powder1","noun.person:powderer"],["powder","make up"]],
"razor":[["verb.body","noun.artifact:razor"],["razor","shave"]],
"remedy":[["verb.body","noun.artifact:remedy","noun.act:medicine"],["remedy","relieve2","treat"]],
"rouge":[["verb.body","noun.artifact:rouge"],["rouge","make up"]],
"shed":[["verb.body","noun.process:shedding","noun.animal:molter","noun.process:molting","noun.process:molt","noun.animal:moulter","noun.process:moulting","noun.process:moult","noun.object:slough","noun.process:sloughing","verb.contact:shed1","verb.contact","verb.change:remove"],["shed","molt","exuviate","moult","slough","shed1","cast1","cast off","shake off","throw7","throw off","throw away","drop1","frames:8"]],
"shirt":[["verb.body","noun.artifact:shirt"],["shirt","dress1"]],
"shoe":[["verb.body","noun.artifact:shoe","noun.artifact","noun.act:card game"],["shoe","dress1","shoe3","case"]],
"soap":[["verb.body","noun.artifact:soap","noun.object:lather1","noun.object:lather","noun.artifact"],["soap","lather","wash","*cleanse","frames:8","soap1","scoop2","max","liquid ecstasy","grievous bodily harm","goop","Georgia home boy","easy lay","gamma hydroxybutyrate"]],
"splint":[["verb.body","noun.artifact:splint","noun.act:medicine"],["splint","treat"]],
"tire":[["verb.body","noun.feeling:fatigue","noun.animal:jade","verb.body","noun.state:wear","noun.animal:jade","noun.state:fatigue"],["tire","pall","weary1","fatigue1","jade","deteriorate","tire1","refresh","wear upon","tire out","wear3","weary","jade1","wear out","outwear","wear down","fag out","fag","fatigue","tire",">indispose","frames:9"]],
"vest":[["verb.body","noun.artifact:vesture","noun.artifact:vestment","noun.artifact:robe1","noun.artifact:robe","verb.possession","verb.possession"],["vest","robe","dress1","vest3","vest2","$change hands","vest2","give"]],
"highlight":[["verb.body","noun.artifact:highlighter1"],["highlight","make up"]],
"marcel":[["verb.body"],["marcel","wave","frames:2"]],
"scab":[["verb.body","noun.body:scab"],["scab","heal"]],
"drivel":[["verb.body","noun.body:drivel","noun.person:driveller1","noun.body:drool","noun.person:drooler","verb.emotion:drool over","noun.person:slobberer","noun.body:slobber","verb.emotion:slobber over","noun.body:dribble","noun.person:dribbler"],["drivel","drool","^slabber","slaver","slobber","^dribble","salivate"]],
"fleer":[["verb.body","noun.communication:fleer"],["fleer","smirk","frames:2"]],
"sneer":[["verb.body","noun.communication:sneer1","noun.communication:sneer","noun.person:sneerer","verb.body","noun.communication:sneer1","noun.communication:sneer","noun.person:sneerer","$verb.communication:express1"],["sneer","smile","frames:2","sneer1","sneer","frames:2"]],
"grimace":[["verb.body","noun.communication:grimace","verb.communication:communicate"],["grimace","make a face","pull a face"]],
"pout":[["verb.body","noun.communication:pout","noun.person:pouter"],["pout","mop","mow","grimace"]],
"frown":[["verb.body","noun.communication:frown","noun.act:glower"],["frown","glower","lour","lower","grimace","frames:2"]],
"laugh":[["verb.body","adj.all:humorous^laughable","noun.communication:laugh1","noun.communication:laugh2","noun.communication:laugh","noun.person:laugher","verb.communication:laugh off","^verb.communication:laugh away","^verb.communication:laugh at","verb.emotion:express emotion"],["laugh","cry","^express joy","express mirth","frames:2"]],
"smirk":[["verb.body","noun.person:smirker","noun.communication:smirk","noun.person:simperer"],["smirk","simper","smile","frames:2"]],
"giggle":[["verb.body","noun.person:giggler","noun.communication:giggle","noun.person:titterer","noun.communication:titter"],["giggle","titter","laugh"]],
"guffaw":[["verb.body","noun.communication:guffaw"],["guffaw","laugh loudly1","laugh","frames:2"]],
"snicker":[["verb.body","noun.communication:snicker","noun.communication:snigger"],["snicker","snigger","laugh","frames:2"]],
"sigh":[["verb.body","noun.event:sigh","noun.communication:sigh","noun.communication:suspiration","verb.communication","noun.event:sigh","noun.communication:sigh"],["sigh","suspire4","breathe","sigh1","utter2","frames:8"]],
"shrug":[["verb.body","noun.communication:shrug","verb.communication:shrug off","^verb.communication:gesture"],["shrug"]],
"bray":[["verb.body","noun.event:bray"],["bray","laugh","frames:2"]],
"trample":[["verb.body","noun.event:trample","noun.person:trampler1"],["trample","injure","frames:10"]],
"atrophy":[["verb.body","noun.state:atrophy","noun.event:atrophy","verb.change:shrink2"],["atrophy","frames:1","2"]],
"faint":[["verb.body","noun.event:faint","noun.event:swoon"],["faint","conk","swoon","pass out","zonk out1"]],
"perm":[["verb.body","noun.body:perm"],["perm","wave"]],
"vesture":[["verb.body","noun.artifact:vesture"],["vesture","clothe"]],
"barber":[["verb.body","noun.person:barber","noun.person"],["barber","groom","Barber1","Samuel Barber","composer"]],
"clown":[["verb.body","noun.person:clown","noun.communication:clowning","noun.act:clowning","noun.act:antic","noun.person"],["clown","clown around","antic","jest","clown1","buffoon1","fool"]],
"groom":[["verb.body","noun.act:grooming","verb.change:embellish","noun.person","noun.group:wedding"],["groom","neaten","frames:2","groom2","bridegroom1","participant"]],
"crick":[["verb.body","noun.state:crick","verb.contact:twist"],["crick"]],
"sweat":[["verb.body","noun.body:sweat","noun.person:sweater","noun.process:sweating","noun.process:sudation","noun.process:perspiration","noun.body:perspiration"],["sweat","sweat off","^sudate","perspire","excrete"]],
"farrow":[["verb.body","noun.process:farrow","noun.process:farrowing","noun.animal:pig"],["farrow","pig","give birth"]],
"frazzle":[["verb.body","noun.state:frazzle"],["frazzle","exhaust"]],
"fester":[["verb.body","noun.process:festering","noun.state:fester","noun.process:maturation2","adj.pert:suppurative","noun.process:suppuration","noun.body:suppuration"],["fester","maturate","suppurate","discharge"]],
"canker":[["verb.body","noun.state:canker","verb.body","noun.state:canker"],["canker","infect1","canker1","sicken"]],
"sunburn":[["verb.body","noun.state:sunburn","noun.state:sunburn1","noun.state:burn2","verb.change:discolor"],["sunburn","burn"]],
"sneeze":[["verb.body","noun.person:sneezer","noun.state:sneezing","noun.state:sneeze"],["sneeze","exhale","*act involuntarily"]],
"cough":[["verb.body","noun.state:cough","noun.state:coughing","^verb.possession:cough up"],["cough","cough out","^cough up","^expectorate","frames:2"]],
"hiccup":[["verb.body","noun.state:hiccup","noun.state:hiccough"],["hiccup","hiccough","breathe"]],
"twitch":[["verb.body","noun.state:twitch","noun.state:twitching","noun.act:jerk","noun.act:jerking","verb.contact"],["twitch","jerk","move involuntarily","frames:2","twitch2","pull","frames:1","2","4"]],
"hypertrophy":[["verb.body","noun.state:hypertrophy","verb.change:grow"],["hypertrophy"]],
"undress":[["verb.body","noun.state:undress","noun.act:strip","noun.person:stripper","noun.person:peeler","verb.change:take off"],["undress","dress1","discase","uncase","unclothe","strip1","strip down","disrobe1","peel2","frames:8","9"]],
"talc":[["verb.body","noun.substance:talc"],["talc","powder"]],
"respire":[["verb.body","adj.pert:respiratory","noun.act:respiration1","noun.act:respiration","$verb.perception:undergo4","verb.body","adj.pert:respiratory"],["respire1","respire","respire2","respire","$breathe"]],
"hyperventilate":[["verb.body","noun.act:hyperventilation","verb.body","noun.act:hyperventilation"],["hyperventilate","breathe","hyperventilate1","hyperventilate","$treat"]],
"burp":[["verb.body","noun.act:burp","noun.object:bubble","noun.act:belch","noun.act:eructation"],["burp","bubble","belch","eruct","emit"]],
"exhale":[["verb.body","noun.substance:exhalation","noun.act:exhalation","adj.pert:expiratory","noun.act:expiration","verb.body","noun.substance:exhalation","noun.substance:emanation","noun.act:emanation"],["exhale","inhale","expire","breathe out","breathe","frames:2","exhale1","give forth","emanate","emit","frames:11"]],
"expectorate":[["verb.body","noun.process:expectoration","noun.act:expectoration","noun.person:expectorator","verb.change"],["expectorate","cough up","cough out","spit up","spit out1","discharge","expectorate3","clear out3","drive out3","remove"]],
"palpebrate":[["verb.body","noun.body:palpebra","noun.act:palpebration"],["palpebrate","blink"]],
"desquamate":[["verb.body","noun.phenomenon:desquamation"],["desquamate","peel off","slough"]],
"fibrillate":[["verb.body","noun.state:fibrillation"],["fibrillate","twitch"]],
"move involuntarily":[["verb.body","verb.motion:move"],["move involuntarily","move reflexively","frames:2"]],
"act involuntarily":[["verb.body"],["act involuntarily","act reflexively","act"]],
"fall over backwards":[["verb.body"],["fall over backwards","bend over backwards","act"]],
"vulgarize":[["verb.body","adj.all:unrefined1^vulgar"],["vulgarize","vulgarise","act"]],
"swagger":[["verb.body","noun.person:swaggerer","noun.person:blusterer"],["swagger","bluster","swash","act"]],
"sentimentalise":[["verb.body","noun.act:sentimentalisation","noun.act:sentimentalization"],["sentimentalise","sentimentalize","sentimentize","sentimentise","act"]],
"bungle":[["verb.body","noun.act:bungle","noun.person:bungler"],["bungle","behave"]],
"shiver":[["verb.body","noun.act:shiver","noun.state:shivering","noun.act:shudder"],["shiver","shudder","move involuntarily","frames:1"]],
"be active":[["verb.body","noun.state:motion","noun.act:move","noun.person:mover1"],["be active","rest","move6"]],
"snooze":[["verb.body","noun.act:snooze","noun.act:drowse","noun.act:doze"],["snooze","drowse1","doze","doze off","^nap"]],
"oversleep":[["verb.body"],["oversleep","sleep"]],
"sleep late":[["verb.body"],["sleep late","sleep in","sleep"]],
"estivate":[["verb.body","noun.state:estivation","noun.state:aestivation"],["estivate","hibernate","aestivate","hibernate","sleep"]],
"drowse":[["verb.body","noun.act:drowse"],["drowse","drowse off","^rest"]],
"zonk out":[["verb.body","verb.body","noun.cognition:blackout","verb.change:change state"],["zonk out","fall asleep","zonk out1","pass out1","black out"]],
"fall asleep":[["verb.body"],["fall asleep","wake up","dope off","flake out","drift off","nod off","drop off","doze off","drowse off"]],
"bed down":[["verb.body"],["bed down","bunk down","go to bed","frames:2"]],
"doss":[["verb.body","noun.person:dosser"],["doss","doss down","crash","bed down","frames:2"]],
"go to bed":[["verb.body"],["go to bed","get up","turn in","turn out","bed","crawl in","kip down","hit the hay","hit the sack","sack out","go to sleep1","retire"]],
"get up":[["verb.body","noun.act:rise","noun.person:riser","verb.body","verb.motion:raise"],["get up","go to bed","turn out","turn in","arise","uprise","rise8","get up1","frames:10"]],
"wake up":[["verb.body","noun.cognition:arousal","noun.act:awakening","noun.person:waker","noun.act:wakening","*verb.change:change state"],["wake up","fall asleep","awake","arouse5","awaken1","wake1","come alive","waken","sleep"]],
"reawaken":[["verb.body"],["reawaken","awaken","frames:9"]],
"cause to sleep":[["verb.body",">verb.change:change1"],["cause to sleep","awaken","sleep","frames:9"]],
"stay up":[["verb.body"],["stay up","sit up","wake"]],
"hypnotize":[["verb.body","noun.person:hypnotizer","noun.state:hypnosis","noun.person:hypnotiser","noun.state:hypnosis","noun.person:mesmer","noun.person:mesmer"],["hypnotize","hypnotise","mesmerize","mesmerise","sedate","frames:9"]],
"anesthetize":[["verb.body","noun.artifact:anesthetic","adj.pert:anaesthetic","noun.artifact:anaesthetic","noun.artifact:anesthetic","noun.artifact:anaesthetic"],["anesthetize","bring to","anaesthetize","anesthetise","anaesthetise","put under","put out","drug","frames:8","9"]],
"etherize":[["verb.body","noun.artifact:ether"],["etherize","etherise","anesthetize","frames:9"]],
"cocainize":[["verb.body","noun.artifact:cocain","noun.artifact:cocain"],["cocainize","cocainise","anesthetize","frames:9"]],
"bring to":[["verb.body"],["bring to","anesthetize","bring back","bring round","bring around","awaken","frames:9"]],
"sedate":[["verb.body","adj.all:depressant^sedative","noun.act:sedation","noun.attribute:calm","noun.artifact:tranquilizer","noun.artifact:tranquillizer","noun.artifact:tranquilliser"],["sedate","stimulate","calm","tranquilize","tranquillize","tranquillise","affect"]],
"de-energize":[["verb.body","verb.change:weaken1"],["de-energize","energize","de-energise","energise"]],
"cathect":[["verb.body"],["cathect","energize"]],
"perk up":[["verb.body","noun.artifact:pickup3"],["perk up","perk","percolate","pick up","gain vigor","recuperate"]],
"animate":[["verb.body","noun.act:recreation1","noun.object:quickener","noun.act:vivification","noun.act:revivification"],["animate","recreate2","reanimate","revive","renovate","repair3","quicken","vivify","revivify","stimulate","frames:9"]],
"freshen":[["verb.body","noun.act:refreshment","verb.change:change"],["freshen2","refresh2","refreshen","freshen up2","frames:1"]],
"vege out":[["verb.body","adj.pert:vegetative1","noun.act:vegetation"],["vege out","vegetate","relax"]],
"sit back":[["verb.body"],["sit back","take it easy","relax"]],
"limber up":[["verb.body","noun.act:warm-up"],["limber up","warm up","loosen up3","exercise"]],
"exsert":[["verb.body","adj.all:extensible","adj.all:long1^extendible","noun.body:extensor","verb.communication:gesture"],["exsert","stretch out1","put out1","extend1","hold out","stretch forth"]],
"hyperextend":[["verb.body","noun.act:hyperextension"],["hyperextend","extend1"]],
"invigorate":[["verb.body","noun.attribute:invigoration","noun.act:invigoration","noun.object:invigorator"],["invigorate","reinvigorate","stimulate"]],
"grin":[["verb.body","noun.person:grinner","noun.communication:grinning","noun.communication:grin"],["grin","smile"]],
"bellylaugh":[["verb.body"],["bellylaugh","laugh"]],
"drop like flies":[["verb.body"],["drop like flies","collapse","frames:1"]],
"fall over":[["verb.body"],["fall over","go over","collapse"]],
"chuckle":[["verb.body","noun.communication:chuckle","noun.communication:chortle"],["chuckle","chortle","laugh softly","laugh"]],
"cachinnate":[["verb.body","noun.communication:cachinnation"],["cachinnate","laugh"]],
"glower":[["verb.body","noun.act:glower","noun.act:glare"],["glower1","glare","stare","frames:2"]],
"scowl":[["verb.body","noun.communication:scowl"],["scowl","frown"]],
"clear the throat":[["verb.body"],["clear the throat","hawk1","cough"]],
"foment":[["verb.body","noun.act:fomentation1"],["foment","bathe"]],
"cleanse":[["verb.body","noun.artifact:cleanser","noun.act:cleansing","noun.act:cleaning","verb.change","verb.possession:rid"],["cleanse","clean","groom","frames:2","8","cleanse5","frames:9"]],
"epilate":[["verb.body","adj.all:hairless^depilatory","noun.artifact:depilator","noun.act:depilation","verb.change:remove"],["epilate","depilate"]],
"gauffer":[["verb.body"],["gauffer","goffer","wave"]],
"doll up":[["verb.body"],["doll up","do up","pretty up","glam up","groom"]],
"overdress":[["verb.body","noun.artifact:attire","noun.artifact:getup","noun.artifact:rigout","verb.body"],["overdress","underdress","frames:2dress up","dress","^dress down","frames:2fig out","fig up","deck up","gussy up","fancy up","trick up","deck out","trick out","prink","attire","get up2","rig out","tog up","tog out","dress up6","$dress up4","$dress","overdress1","underdress1","overclothe","dress1"]],
"dress down":[["verb.body"],["dress down","dress up","underdress","overdress","dress"]],
"prink":[["verb.body"],["prink1","dress"]],
"sweat off":[["verb.body"],["sweat off","reduce"]],
"bundle up":[["verb.body"],["bundle up","dress"]],
"try on":[["verb.body","noun.act:try-on"],["try on","try","wear1"]],
"underdress":[["verb.body"],["underdress1","overdress1","dress1"]],
"slip on":[["verb.body","noun.artifact:slip-on"],["slip on","slip off","put on"]],
"slip off":[["verb.body"],["slip off","slip on","take off3"]],
"cross-dress":[["verb.body","noun.person:cross-dresser"],["cross-dress","dress"]],
"dandify":[["verb.body","noun.person:dandy"],["dandify","dress"]],
"cross-fertilize":[["verb.body","noun.event:cross-fertilization","noun.event:cross-fertilisation","verb.body","noun.event:cross-fertilization","noun.event:cross-fertilisation","verb.change:change state"],["cross-fertilize","cross-fertilise","cross-fertilize1",">fertilize","cross-fertilize1","cross-fertilise1"]],
"pollinate":[["verb.body","noun.plant:pollen","noun.event:pollination","noun.animal:pollinator","noun.event:pollenation","noun.event:cross-pollination"],["pollinate","pollenate","cross-pollinate","fertilize","frames:8"]],
"conceive":[["verb.body","adj.all:fertile^conceptive","noun.act:conception1","verb.contact:mate","*verb.change:change state"],["conceive","frames:2"]],
"beget":[["verb.body","noun.person:begetter","noun.person:father","noun.person:mother","noun.animal:sire","noun.person:sire","adj.all:fruitful^generative","noun.group:generation","noun.event:generation","noun.act:generation","verb.creation:create"],["beget","get8","engender","father","mother","sire","generate","bring forth"]],
"ejaculate":[["verb.body","noun.process:ejaculation","noun.body:ejaculate","noun.person:ejaculator1"],["ejaculate","discharge"]],
"pullulate":[["verb.body","verb.change","noun.process:pullulation"],["pullulate","breed","pullulate1","increase"]],
"lie in":[["verb.body"],["lie in","birth"]],
"whelp":[["verb.body","noun.animal:whelp","noun.animal:pup"],["whelp","pup","give birth"]],
"have a bun in the oven":[["verb.body","noun.time:gestation","noun.state:gestation","adj.all:pregnant^expectant","noun.feeling:expectation"],["have a bun in the oven","bear","carry","gestate","expect","bear1","$conceive","*bear1"]],
"carry to term":[["verb.body"],["carry to term","miscarry","expect","*frames:2"]],
"miscarry":[["verb.body","noun.act:miscarriage"],["miscarry","carry to term","abort","frames:2"]],
"defeminize":[["verb.body"],["defeminize","defeminise","alter"]],
"caponize":[["verb.body","noun.animal:capon","noun.animal:capon"],["caponize","caponise","castrate"]],
"geld":[["verb.body","noun.animal:gelding"],["geld","cut","castrate","frames:8"]],
"vasectomize":[["verb.body","noun.act:vasectomy"],["vasectomize","vasectomise","sterilize"]],
"sterilize":[["verb.body","noun.act:sterilization","noun.act:sterilisation","noun.act:fixing1","verb.body","noun.act:sterilization1","noun.artifact:sterilizer","noun.act:sterilisation1","noun.artifact:steriliser"],["sterilize","sterilise","desex","unsex","desexualize","desexualise","fix","operate on","sterilize1","sterilise1","disinfect"]],
"face-lift":[["verb.body","noun.act:face lifting"],["face-lift","lift","operate"]],
"trephine":[["verb.body","noun.act:trephination","noun.artifact:trephine"],["trephine","operate on","frames:8"]],
"menstruate":[["verb.body","noun.process:menstruation","noun.process:flow1"],["menstruate","flow","ovulate","*bleed"]],
"ovulate":[["verb.body","noun.body:ovum","noun.body:ovule1","noun.process:ovulation"],["ovulate","discharge"]],
"antisepticize":[["verb.body"],["antisepticize","disinfect","frames:8","9","10"]],
"soothe":[["verb.body"],["soothe","irritate","relieve","frames:8","9","11"]],
"be well":[["verb.body","verb.stative:be3"],["be well","suffer","frames:2"]],
"wail":[["verb.body","noun.communication:wail","noun.communication:whimper"],["wail","whimper","mewl","pule","cry"]],
"superfetate":[["verb.body","noun.event:superfetation"],["superfetate","conceive","frames:1"]],
"distill":[["verb.body","verb.change","noun.substance:distillate","noun.process:distillment","noun.substance:distillation","noun.process:distillation","noun.artifact:distillery","noun.cognition:chemistry","verb.change","noun.substance:distillate","noun.substance:distillation","noun.process:distillation","noun.artifact:distillery","adj.all:removable^extractible","noun.process:extraction","verb.creation:create","noun.cognition:chemistry"],["distill","distil","exude","distill1","distil1","distill2","$distill3","$change","distill2","extract","distil2"]],
"secrete":[["verb.body","noun.process:secretion","noun.body:secretor","noun.process:release","verb.perception","adj.all:uncommunicative^secretive"],["secrete","release","exude","frames:8","secrete2","hide"]],
"swelter":[["verb.body","verb.body"],["swelter","sweat","frames:2","swelter1","suffer3"]],
"injure":[["verb.body","noun.state:injury","noun.event:injury","noun.act:injury2","noun.event:wound","noun.act:wound","noun.act:wounding"],["injure","wound","hurt1","frames:9","8","10"]],
"disagree with":[["verb.body"],["disagree with","hurt1"]],
"urinate":[["verb.body"],["urinate1","urinate","$excrete"]],
"stale":[["verb.body"],["stale","urinate"]],
"excrete":[["verb.body","adj.pert:excretory","noun.process:excretion","noun.process:excreting","noun.act:passing5"],["excrete","egest","eliminate","pass","discharge"]],
"constipate":[["verb.body","noun.state:constipation"],["constipate","bind","indispose"]],
"obstipate":[["verb.body","noun.state:obstipation"],["obstipate","constipate"]],
"overtire":[["verb.body"],["overtire","overweary","overfatigue","tire1","frames:9"]],
"spew":[["verb.body","noun.state:eructation"],["spew2","spew out","eruct4","eject","frames:8"]],
"keep down":[["verb.body"],["keep down","vomit"]],
"gnash":[["verb.body","verb.contact:grind"],["gnash"]],
"ail":[["verb.body","noun.state:ailment"],["ail","suffer"]],
"irrigate":[["verb.body","noun.act:irrigation1"],["irrigate","treat"]],
"digitalize":[["verb.body","noun.act:digitalization","noun.substance:digitalis","noun.act:medicine"],["digitalize","administer"]],
"bring around":[["verb.body","adj.all:curable","adj.all:healthful^curative","noun.artifact:cure","noun.person:healer","noun.act:medicine"],["bring around1","cure","heal1","treat","*help","frames:9"]],
"operate on":[["verb.body","adj.all:operative4","noun.act:operation","noun.act:medicine"],["operate on","operate","treat","frames:9"]],
"venesect":[["verb.body","noun.act:venesection","noun.act:medicine"],["venesect","operate"]],
"medicate":[["verb.body","adj.all:healthful^medicative","noun.cognition:medicine","noun.artifact:medicine","noun.act:medicine","noun.artifact:medication","noun.act:medication","noun.act:medicine","noun.artifact:medicine","noun.cognition:medicine","noun.act:medicine","verb.body","adj.all:healthful^medicative","noun.artifact:medicine","noun.act:medication","verb.change:impregnate","noun.act:medicine"],["medicate","medicine","treat","medicate1"]],
"overdose":[["verb.body","o.d."],["overdose","drug"]],
"narcotize":[["verb.body","noun.artifact:narcotic"],["narcotize","narcotise","drug"]],
"infuse":[["verb.body","noun.act:infusion","noun.act:medicine","verb.change","noun.process:infusion"],["infuse","inject","infuse2","infuse","$steep"]],
"wan":[["verb.body"],["wan","sicken"]],
"catch cold":[["verb.body"],["catch cold","catch10"]],
"infect":[["verb.body","adj.all:unhealthful^infective","adj.all:septic^infective","noun.process:infection","noun.state:infection","noun.state:taint","verb.change:contaminate","verb.cognition","noun.communication:infection","verb.emotion:affect","verb.social"],["infect","disinfect","taint","infect1","frames:9","infect2","corrupt","frames:8","10","9"]],
"superinfect":[["verb.body","noun.state:superinfection"],["superinfect","infect","frames:8"]],
"disinfect":[["verb.body","adj.all:antiseptic^disinfectant","noun.act:disinfection","noun.artifact:disinfectant","verb.contact:clean"],["disinfect","infect","frames:9","8"]],
"traumatize":[["verb.body","noun.state:trauma2","noun.state:trauma1","noun.state:trauma2","noun.event:shock1","noun.feeling:shock1"],["traumatize","traumatise","shock","injure"]],
"maim":[["verb.body","noun.person:maimer"],["maim","injure","frames:9"]],
"subluxate":[["verb.body","noun.event:subluxation"],["subluxate","injure"]],
"devolve":[["verb.body","noun.state:deterioration","noun.process:deterioration","adj.all:chronic^degenerative","noun.state:degeneration","noun.process:degeneration","verb.change:worsen","verb.social","noun.act:devolvement","noun.act:devolution"],["devolve","deteriorate","recuperate","drop1","degenerate","frames:1","devolve2","delegate"]],
"recuperate":[["verb.body","adj.all:healthful^recuperative","noun.process:recuperation","noun.process:recovery","adj.all:ill1^convalescent","noun.person:convalescent","noun.process:convalescence","verb.change:improve","verb.body","adj.all:healthful^recuperative","noun.process:recuperation"],["recuperate","deteriorate","recover","convalesce","recuperate1","recuperate","$cure","frames:9"]],
"snap back":[["verb.body"],["snap back","recover"]],
"relapse":[["verb.body","noun.act:relapse","noun.act:relapsing","noun.act:lapse1","noun.act:recidivism","verb.change:revert"],["relapse","lapse","recidivate","regress","retrogress","fall back"]],
"languish":[["verb.body","noun.person:languisher","noun.event:fading"],["languish","fade","deteriorate"]],
"regrow":[["verb.body"],["regrow","grow"]],
"teethe":[["verb.body","noun.process:teething"],["teethe","grow"]],
"ankylose":[["verb.body","verb.change:grow2","noun.act:medicine","verb.body","verb.contact:join1","noun.act:medicine"],["ankylose","ancylose","ankylose1","ancylose1"]],
"pupate":[["verb.body","noun.animal:pupa"],["pupate","develop"]],
"work up":[["verb.body"],["work up","get up3","develop"]],
"suppurate":[["verb.body","noun.process:suppuration","noun.body:suppuration","noun.process:maturation2"],["suppurate1","mature4","suppurate","$draw"]],
"necrose":[["verb.body","noun.state:gangrene","noun.phenomenon:mortification","noun.state:sphacelus","noun.phenomenon:sphacelus"],["necrose","gangrene","mortify","sphacelate","rot"]],
"resuscitate":[["verb.body","noun.act:resuscitation","noun.artifact:resuscitator"],["resuscitate","revive1","revive2",">bring to","frames:9"]],
"resurrect":[["verb.body","noun.act:resurrection","verb.body","noun.event:rise3","$verb.motion:return"],["resurrect","raise","upraise","resuscitate","frames:9","resurrect1","rise","uprise5","resurrect","frames:1"]],
"skin over":[["verb.body"],["skin over","heal"]],
"heal":[["verb.body","noun.process:healing","verb.change:improve"],["heal","frames:1"]],
"poop out":[["verb.body"],["poop out","peter out","run down","run out","conk out","tire"]],
"splutter":[["verb.body"],["splutter","sputter","spit out","spit up"]],
"harm":[["verb.body","noun.act:harm","noun.event:harm1"],["harm","injure","frames:1","2","12","9"]],
"pale":[["verb.body","noun.attribute:pallor","verb.change:discolor"],["pale","blanch","blench"]],
"suntan":[["verb.body","noun.state:suntan"],["suntan","tan"]],
"metastasize":[["verb.body","noun.process:metastasis1","verb.contact:spread"],["metastasize","metastasise","frames:1"]],
"feel like a million":[["verb.body"],["feel like a million","feel like a million dollars","feel"]],
"piffle":[["verb.body","noun.communication:piffle"],["piffle","act"]],
"pack on":[["verb.body"],["pack on","gain"]],
"make as if":[["verb.body"],["make as if","act"]],
"refracture":[["verb.body"],["refracture","fracture1"]],
"froth":[["verb.body","verb.change","noun.object:froth","noun.object:spume","noun.object:suds","verb.creation:make"],["froth","exude","frames:1","froth1","spume","suds"]]
}