var mysql_wn_data_noun_event = {
"chicken":[["noun.event","noun.animal"],["chicken","contest","chicken1","Gallus gallus2","domestic fowl"]],
"concoction":[["noun.event","verb.contact:concoct"],["concoction","mix"]],
"plonk":[["noun.event","verb.contact:plonk"],["plonk","noise"]],
"eye opener":[["noun.event"],["eye opener","surprise"]],
"cross-fertilization":[["noun.event","verb.body:cross-fertilize1","verb.body:cross-fertilize","verb.body:cross-fertilise1","verb.body:cross-fertilise"],["cross-fertilization","self-fertilization","cross-fertilisation","fertilization"]],
"delivery":[["noun.event"],["delivery","birth"]],
"egress":[["noun.event","noun.cognition:astronomy"],["egress","ingress","emersion","immersion1","reappearance","eclipse"]],
"recovery":[["noun.event","verb.change:recover"],["recovery","improvement"]],
"appearance":[["noun.event","verb.change:appear","noun.act","adj.all:ostentatious^showy","noun.act","verb.social:appear3"],["appearance","disappearance","happening","appearance2","show1","pretense","appearance1","appearing","coming into court","attendance"]],
"emergence":[["noun.event","verb.change:emerge","verb.change:egress"],["emergence","egress1","issue","beginning"]],
"reappearance":[["noun.event","verb.change:reappear"],["reappearance","appearance"]],
"disappearance":[["noun.event","verb.perception:disappear","noun.event"],["disappearance","appearance","happening","disappearance1","happening"]],
"vanishing":[["noun.event","verb.change:vanish"],["vanishing","disappearance"]],
"receding":[["noun.event","verb.change:recede","verb.change:fade out"],["receding","fadeout","disappearance"]],
"passing":[["noun.event","verb.change:pass11","verb.motion:depart4","verb.motion:depart1","verb.motion:depart","verb.change:exit","verb.change:expire","verb.change:go","noun.communication:euphemism","noun.event","verb.motion:pass1","verb.motion:pass1"],["passing","loss2","departure","exit","expiration","going","release","death","passing1","passage","movement"]],
"error":[["noun.event","noun.cognition:computer science"],["error","computer error","happening"]],
"distortion":[["noun.event","verb.change:deform"],["distortion","deformation","damage"]],
"remission":[["noun.event","verb.change:remit2","verb.change:remit2","verb.change:subside"],["remission","remittal","subsidence2","suspension"]],
"roller":[["noun.event","verb.motion:roll10","noun.artifact","verb.motion:roll","noun.animal"],["roller","roll1","rolling wave","wave1","roller2","wheel","roller skate","roller1","coraciiform bird","family Coraciidae"]],
"plunk":[["noun.event","verb.perception:plunk"],["plunk","sound"]],
"knock":[["noun.event","verb.contact:knock4","verb.contact:bash","verb.contact:bang","verb.contact:smash8","verb.change:smash","verb.contact:smash","verb.contact:belt","verb.communication","noun.person:critic2","noun.person:critic1","noun.person:critic","noun.communication:criticism1","noun.communication:criticism","noun.cognition:criticism","verb.cognition:judge","verb.contact","noun.event:knock1","noun.person:knocker1","noun.event:knocking","verb.contact","noun.act:knock","noun.event:knock","verb.motion:knock over"],["knock","bash","bang1","smash1","belt","blow","knock2","criticize","praise","criticise","pick apart","*comment","frames:8","knock1","rap","knock4","^knock down","^knock out","^knock cold","^strike hard","strike","frames:8"]],
"convergence":[["noun.event","adj.all:convergent","verb.motion:converge","verb.stative:converge"],["convergence","happening"]],
"resolution":[["noun.event","noun.communication"],["resolution","remission","resolution2","preparation","harmony1","music"]],
"cross-pollination":[["noun.event","verb.body:cross-pollinate"],["cross-pollination","self-pollination","pollination"]],
"substitution":[["noun.event","verb.possession:substitute1","verb.possession:substitute","verb.change:replace","verb.possession:switch","verb.change:switch3","verb.change:switch"],["substitution","permutation","transposition1","replacement","switch","variation1"]],
"destruction":[["noun.event","verb.contact:destroy","verb.creation:demolish","verb.change:wipe out","verb.change:wipe out2","verb.change:wipe out3","verb.change:wipe out4","verb.creation:wipe out"],["destruction","demolition","wipeout","ending"]],
"razing":[["noun.event","verb.creation:raze"],["razing","wrecking","destruction"]],
"annihilation":[["noun.event","verb.change:annihilate"],["annihilation","disintegration1","destruction"]],
"reversal":[["noun.event","verb.change:reverse1","verb.motion:turn around","noun.act","verb.cognition:reverse","noun.group:law"],["reversal","turn around","turning","reversal6","affirmation","judgment"]],
"creation":[["noun.event","verb.creation:create13","verb.creation:create2"],["creation","conception","beginning"]],
"initiation":[["noun.event","verb.social:initiate1","verb.social:induct1","verb.social:induct","verb.social:install"],["initiation","induction","installation","ceremony"]],
"kickoff":[["noun.event","verb.social:kick off"],["kickoff","send-off","start-off","start"]],
"engagement":[["noun.event","verb.contact:engage","verb.change:engage","verb.contact:mesh1","verb.contact:mesh1"],["engagement","mesh","meshing","interlocking","contact"]],
"takeoff":[["noun.event","verb.motion:take off"],["takeoff","rise2"]],
"slide":[["noun.event","verb.motion:slide1","noun.cognition:geology","noun.artifact","verb.motion","noun.act:slide","noun.communication:slide","noun.artifact","verb.motion:slide1"],["slide","descent","slide1","lantern slide","foil2","slide2","move1","slide3","playground slide","sliding board","plaything","playground"]],
"easing":[["noun.event","verb.change:ease"],["easing","moderation","relief","change"]],
"burnup":[["noun.event","noun.location:Britain","noun.communication:slang"],["burnup","race"]],
"compression":[["noun.event","verb.contact:compress","verb.change:condense6","verb.change:condense5","verb.change:condense4","noun.act","verb.contact:compress1"],["compression","condensation","contraction2","shrinkage","compression1","decompression1","encoding"]],
"shrinking":[["noun.event","verb.change:shrink1","verb.change:shrink1","verb.change:shrink"],["shrinking","shrinkage","decrease"]],
"weakening":[["noun.event","verb.change:weaken"],["weakening","strengthening","transformation"]],
"augmentation":[["noun.event","verb.change:augment1","verb.change:augment"],["augmentation","increase"]],
"dispersion":[["noun.event","verb.motion:disperse","verb.motion:scatter1"],["dispersion","scattering","spread"]],
"strengthening":[["noun.event","verb.change:strengthen"],["strengthening","weakening","transformation"]],
"concentration":[["noun.event","verb.change:concentrate3","verb.change:concentrate1","verb.change:concentrate"],["concentration","increase"]],
"explosion":[["noun.event","verb.change:explode1","verb.change:detonate1","verb.change:blow up3","noun.event","verb.change:explode2","noun.event"],["explosion","detonation","blowup","discharge","explosion1","increase","explosion2","noise"]],
"avulsion":[["noun.event"],["avulsion","change"]],
"schism":[["noun.event","adj.pert:schismatic"],["schism","rupture"]],
"punctuation":[["noun.event"],["punctuation","interruption"]],
"deletion":[["noun.event","noun.cognition:genetics"],["deletion","mutation"]],
"bending":[["noun.event"],["bending","bend","movement"]],
"crucifixion":[["noun.event"],["Crucifixion","death"]],
"celebration":[["noun.event","verb.social:celebrate1","verb.social:celebrate","verb.social:jubilate","noun.act","verb.social:celebrate1","verb.social:solemnize1","verb.social:solemnize","verb.social:solemnise1","verb.social:solemnise"],["celebration","jubilation","affair","celebration1","solemnization","solemnisation","ritual1"]],
"high jump":[["noun.event"],["high jump","field event"]],
"lottery":[["noun.event"],["lottery","accident"]],
"sideshow":[["noun.event"],["sideshow","incident"]],
"cotillion":[["noun.event"],["cotillion","cotilion","ball"]],
"bell ringing":[["noun.event"],["bell ringing","ringing"]],
"outburst":[["noun.event","verb.change:flare up"],["outburst","burst","flare-up1","happening"]],
"waxing":[["noun.event","verb.change:wax1","verb.change:wax"],["waxing","waning","increase"]],
"deviation":[["noun.event","verb.stative:deviate","verb.stative:diverge1","verb.stative:depart","verb.cognition:differentiate2","verb.cognition:differentiate1","verb.change:differentiate","noun.attribute","verb.stative:deviate"],["deviation","divergence","departure1","difference","variation1","deviation1","erroneousness"]],
"shakedown":[["noun.event","noun.act","noun.communication:slang"],["shakedown","adjustment","shakedown1","search"]],
"field trial":[["noun.event"],["field trial","contest"]],
"marathon":[["noun.event","noun.person:marathoner","noun.act","noun.location:Greece"],["marathon","footrace","Marathon1","battle of Marathon","pitched battle"]],
"conservation":[["noun.event","noun.person:conservationist","verb.possession:conserve2"],["conservation","preservation","improvement"]],
"zizz":[["noun.event","noun.location:Britain"],["zizz","sound"]],
"pageant":[["noun.event"],["pageant","pageantry","ceremony"]],
"invasion":[["noun.event","verb.motion:invade","verb.stative:invade","verb.motion:encroach","noun.event","verb.contact:invade","noun.cognition:medicine"],["invasion","encroachment","intrusion","entrance","invasion1","spread"]],
"adjustment":[["noun.event","verb.change:adjust1","verb.stative:accommodate","verb.change:accommodate1","verb.change:accommodate","verb.change:fit1","verb.change:fit"],["adjustment","accommodation","fitting","improvement"]],
"ceremony":[["noun.event","adj.all:formal1^ceremonial","adj.all:formal1^ceremonial","verb.social:observe2"],["ceremony","ceremonial","ceremonial occasion","observance1","affair"]],
"military ceremony":[["noun.event","noun.group:military"],["military ceremony","ceremony"]],
"resurrection":[["noun.event","noun.communication:New Testament"],["Resurrection","Christ's Resurrection","Resurrection of Christ","miracle1"]],
"destabilization":[["noun.event","verb.change:destabilize","noun.artifact:ship","noun.artifact:aircraft"],["destabilization","change"]],
"tug-of-war":[["noun.event"],["tug-of-war","athletic contest"]],
"trial":[["noun.event","verb.emotion:try1","verb.emotion:tribulate","verb.communication:visit1","noun.event","noun.act:sport"],["trial","tribulation","visitation","affliction","trial1","contest"]],
"ordeal":[["noun.event"],["ordeal","experience"]],
"formality":[["noun.event","adj.all:official^formal"],["formality","formalities","ceremony"]],
"waterloo":[["noun.event"],["waterloo","defeat"]],
"wrack":[["noun.event","verb.contact:wrack"],["wrack","rack","destruction"]],
"death knell":[["noun.event"],["death knell","omen"]],
"discus":[["noun.event"],["discus","field event"]],
"ground floor":[["noun.event"],["ground floor","beginning"]],
"homestretch":[["noun.event","noun.communication:colloquialism"],["homestretch","end"]],
"javelin":[["noun.event"],["javelin","field event"]],
"makeup":[["noun.event","verb.social:make up","verb.social:make up","noun.Tops:event"],["makeup","make-up"]],
"opener":[["noun.event","verb.social:open1"],["opener","start"]],
"wild card":[["noun.event"],["wild card","factor"]],
"drama":[["noun.event","adj.all:impressive^dramatic","adj.all:dramatic","verb.communication:dramatize","verb.communication:dramatize1","verb.communication:dramatise1"],["drama","dramatic event","episode"]],
"smudge":[["noun.event"],["smudge","fire"]],
"vicissitude":[["noun.event"],["vicissitude","variation1"]],
"discrepancy":[["noun.event","adj.all:discordant^discrepant","adj.all:different^variant","verb.stative:vary"],["discrepancy","variance","variant","deviation"]],
"fatality":[["noun.event"],["fatality","human death","death"]],
"refinement":[["noun.event","verb.change:refine1","verb.change:elaborate"],["refinement","elaboration","improvement"]],
"noise":[["noun.event","verb.perception:noise"],["noise","sound"]],
"dedication":[["noun.event","verb.social:dedicate","verb.communication:dedicate","verb.cognition:dedicate"],["dedication","ceremony"]],
"resilience":[["noun.event","adj.all:elastic^resilient","verb.change:resile2","adj.all:elastic^resilient","verb.motion:resile"],["resilience","resiliency","recoil"]],
"attenuation":[["noun.event","verb.change:attenuate","verb.change:fade1","verb.body:fade"],["attenuation","fading","weakening"]],
"coincidence":[["noun.event"],["coincidence","happenstance","accident"]],
"diaspora":[["noun.event"],["Diaspora","dispersion"]],
"amplitude":[["noun.event","noun.cognition:physics"],["amplitude","shift"]],
"vision":[["noun.event"],["vision","experience"]],
"fundamental":[["noun.event"],["fundamental","factor"]],
"regurgitation":[["noun.event","verb.motion:regurgitate"],["regurgitation","backflow"]],
"corollary":[["noun.event"],["corollary","consequence"]],
"circumstance":[["noun.event","noun.state"],["circumstance","ceremony","circumstance1","condition"]],
"parameter":[["noun.event","noun.cognition"],["parameter","factor","parameter3","quantity1"]],
"predestination":[["noun.event","noun.person:predestinationist","verb.communication:predestine","verb.cognition:predestine"],["predestination","destiny"]],
"etiology":[["noun.event","adj.pert:etiologic","adj.pert:etiological","noun.person:etiologist","adj.pert:aetiologic","noun.person:aetiologist","adj.pert:aetiological"],["etiology","aetiology","cause"]],
"gravitation":[["noun.event","adj.pert:gravitational","verb.motion:gravitate"],["gravitation","levitation","change of location"]],
"ending":[["noun.event","verb.stative:end1","verb.creation:end13","verb.change:finish3","verb.stative:finish","verb.change:finish2"],["ending","beginning","conclusion","finish2","happening"]],
"conjunction":[["noun.event","noun.cognition:astronomy","noun.relation"],["conjunction","alignment","meeting","conjunction2","grammatical relation"]],
"anticlimax":[["noun.event","adj.all:anticlimactic"],["anticlimax","fall1"]],
"episode":[["noun.event"],["episode","happening"]],
"sequel":[["noun.event","adj.all:subsequent"],["sequel","subsequence","result"]],
"flashback":[["noun.event"],["flashback","recurrence"]],
"genesis":[["noun.event","verb.creation:generate","verb.body:generate"],["genesis","generation","beginning"]],
"word of god":[["noun.event"],["Word of God","manifestation"]],
"cliffhanger":[["noun.event"],["cliffhanger","contest"]],
"round robin":[["noun.event"],["round robin","tournament"]],
"blowback":[["noun.event"],["blowback","backfire1","explosion"]],
"salvo":[["noun.event"],["salvo","outburst"]],
"static":[["noun.event"],["static","atmospherics","atmospheric static","noise1"]],
"denouement":[["noun.event"],["denouement","result"]],
"manifestation":[["noun.event"],["manifestation","appearance"]],
"alpha":[["noun.event","adj.all:important^alpha"],["alpha","start"]],
"omega":[["noun.event"],["omega","Z","ending"]],
"coup de theatre":[["noun.event","noun.communication","noun.cognition:stagecraft"],["coup de theatre","surprise","coup de theatre1","production"]],
"accompaniment":[["noun.event","verb.stative:accompany","adj.all:subsequent^attendant","adj.all:synchronous^co-occurrent","verb.stative:cooccur"],["accompaniment","concomitant","attendant","co-occurrence","happening"]],
"implosion":[["noun.event","verb.change:implode"],["implosion","collapse"]],
"howl":[["noun.event","verb.communication:howl1","verb.communication","noun.communication:howl","noun.communication:howling","noun.communication:ululation","noun.communication:wail","noun.person:wailer","noun.act:wailing1","noun.communication:roar","noun.communication:roaring","verb.communication","noun.event:howl2","noun.animal:howler","noun.communication:yowl"],["howl","noise","howl2","ululate","wail","roar2","yawl","yaup","shout1","frames:1","howl3","wrawl","yammer1","yowl1","utter2","frames:1"]],
"collision":[["noun.event","verb.contact:collide","noun.event","verb.contact:collide","verb.contact:hit1","noun.cognition:physics"],["collision","accident1","collision1","hit1","contact"]],
"scandal":[["noun.event","adj.all:immoral^scandalous","verb.emotion:scandalize","verb.emotion:scandalise","adj.all:offensive1^outrageous","verb.emotion:outrage1"],["scandal","outrage","trouble"]],
"blip":[["noun.event"],["blip","shock1"]],
"milestone":[["noun.event"],["milestone","juncture"]],
"might-have-been":[["noun.event","noun.Tops:event"],["might-have-been"]],
"nonevent":[["noun.event","noun.Tops:event"],["nonevent"]],
"happening":[["noun.event","verb.change:happen","adj.all:current^occurrent","noun.Tops:event"],["happening","occurrence","occurrent","natural event"]],
"appalling":[["noun.event"],["appalling","experience"]],
"augury":[["noun.event","verb.change:inaugurate"],["augury","sign","foretoken","preindication","experience"]],
"war cloud":[["noun.event"],["war cloud","augury"]],
"omen":[["noun.event","adj.all:unpropitious^ominous","adj.all:alarming^ominous","verb.communication:omen","adj.all:significant^portentous","adj.all:prophetic^portentous","verb.communication:portend","verb.communication:presage","adj.all:prophetic^prognostic","verb.communication:prognosticate1","adj.all:significant^prodigious"],["omen","portent","presage","prognostic","prognostication","prodigy","augury"]],
"auspice":[["noun.event","verb.communication:auspicate","verb.change:auspicate"],["auspice","omen"]],
"good time":[["noun.event"],["good time","blast2","experience"]],
"near-death experience":[["noun.event"],["near-death experience","experience"]],
"out-of-body experience":[["noun.event"],["out-of-body experience","experience"]],
"social event":[["noun.event","noun.Tops:event"],["social event"]],
"miracle":[["noun.event","adj.all:supernatural^miraculous"],["miracle","happening"]],
"night terror":[["noun.event"],["night terror","drama"]],
"eventuality":[["noun.event","adj.all:possible^contingent"],["eventuality","contingency","contingence","happening"]],
"casus belli":[["noun.event"],["casus belli","beginning"]],
"endgame":[["noun.event","noun.event"],["endgame","end game","end","endgame1","end game1","end"]],
"fair deal":[["noun.event"],["fair deal","square deal","deal"]],
"raw deal":[["noun.event"],["raw deal","deal"]],
"split decision":[["noun.event"],["split decision","decision2"]],
"just deserts":[["noun.event","noun.communication:plural"],["just deserts","comeuppance","comeupance","poetic jstice","consequence"]],
"sequella":[["noun.event"],["sequella","consequence"]],
"wages":[["noun.event","verb.social:reward1","verb.possession:reward"],["wages","reward","payoff","consequence"]],
"foregone conclusion":[["noun.event"],["foregone conclusion","matter of course","ending"]],
"one-off":[["noun.event"],["one-off","happening"]],
"periodic event":[["noun.event"],["periodic event","recurrent event","happening"]],
"mutation":[["noun.event","adj.pert:mutational","verb.change:mutate","noun.cognition:genetics"],["mutation","genetic mutation","chromosomal mutation","change"]],
"sublimation":[["noun.event","verb.motion:sublimate","noun.cognition:psychology","noun.event","verb.change:sublimate5","noun.cognition:chemistry"],["sublimation1","change","sublimation2","transformation"]],
"peripeteia":[["noun.event"],["peripeteia","peripetia","peripety","surprise"]],
"stunner":[["noun.event"],["stunner","surprise"]],
"hardware error":[["noun.event","noun.cognition:computer science"],["hardware error","error"]],
"disk error":[["noun.event","noun.cognition:computer science"],["disk error","hardware error"]],
"software error":[["noun.event","noun.cognition:computer science"],["software error","programming error","error"]],
"semantic error":[["noun.event","noun.cognition:computer science"],["semantic error","run-time error","runtime error","software error"]],
"syntax error":[["noun.event","noun.cognition:computer science"],["syntax error","software error"]],
"algorithm error":[["noun.event","noun.cognition:computer science"],["algorithm error","error"]],
"accident":[["noun.event","adj.all:unintended^accidental","noun.event"],["accident","stroke2","fortuity","chance event","happening","accident1","mishap"]],
"near miss":[["noun.event"],["near miss","mishap"]],
"derailment":[["noun.event","verb.motion:derail1","verb.motion:derail"],["derailment","mishap"]],
"ground loop":[["noun.event"],["ground loop","mishap"]],
"bonfire":[["noun.event"],["bonfire","balefire","fire"]],
"brush fire":[["noun.event"],["brush fire","fire"]],
"campfire":[["noun.event"],["campfire","fire"]],
"conflagration":[["noun.event","adj.pert:infernal1"],["conflagration","inferno","fire"]],
"forest fire":[["noun.event"],["forest fire","fire"]],
"grassfire":[["noun.event"],["grassfire","prairie fire","fire"]],
"smoulder":[["noun.event","verb.change:smoulder"],["smoulder","smolder","fire"]],
"crown fire":[["noun.event"],["crown fire","forest fire"]],
"ground fire":[["noun.event"],["ground fire","forest fire"]],
"surface fire":[["noun.event"],["surface fire","forest fire"]],
"wildfire":[["noun.event"],["wildfire","conflagration"]],
"pity":[["noun.event","adj.all:unfortunate^piteous"],["pity","shame","misfortune"]],
"disembarrassment":[["noun.event","verb.possession:disembarrass"],["disembarrassment","embarrassment","easing"]],
"onslaught":[["noun.event"],["onslaught","trouble"]],
"teapot dome":[["noun.event"],["Teapot Dome","Teapot Dome scandal","scandal"]],
"watergate":[["noun.event"],["Watergate","Watergate scandal","scandal"]],
"idyll":[["noun.event","adj.all:pleasant^idyllic","adj.all:perfect^idyllic"],["idyll","episode"]],
"cause celebre":[["noun.event"],["cause celebre","incident"]],
"electrical discharge":[["noun.event"],["electrical discharge","discharge"]],
"nerve impulse":[["noun.event"],["nerve impulse","nervous impulse","neural impulse","impulse","electrical discharge"]],
"action potential":[["noun.event"],["action potential","nerve impulse"]],
"crustal movement":[["noun.event","noun.cognition:geology"],["crustal movement","tectonic movement","movement"]],
"change of location":[["noun.event","verb.motion:travel3","verb.motion:travel"],["change of location","travel","movement"]],
"fender-bender":[["noun.event"],["fender-bender","collision"]],
"hap":[["noun.event","verb.change:hap"],["hap","accident"]],
"mishap":[["noun.event"],["mishap","misadventure","mischance","misfortune"]],
"calamity":[["noun.event","adj.all:unfortunate^calamitous","adj.all:unfortunate^disastrous","adj.all:sad^tragical","adj.all:sad^tragic","adj.all:destructive^cataclysmic","adj.all:destructive^cataclysmal"],["calamity","catastrophe","disaster","tragedy","cataclysm","misfortune"]],
"act of god":[["noun.event"],["act of God","force majeure","vis major","inevitable accident","unavoidable casualty","calamity"]],
"apocalypse":[["noun.event","adj.pert:apocalyptic","adj.all:prophetic^apocalyptical"],["apocalypse","calamity"]],
"famine":[["noun.event"],["famine","calamity"]],
"the irish famine":[["noun.event"],["the Irish Famine","the Great Hunger","the Great Starvation","the Great Calamity","famine"]],
"kiss of death":[["noun.event"],["kiss of death","calamity"]],
"pileup":[["noun.event"],["pileup","collision"]],
"downfall":[["noun.event","verb.social:ruin"],["downfall1","ruin1","ruination1","failure"]],
"flame-out":[["noun.event","noun.artifact:jet engine"],["flame-out","power failure"]],
"blowout":[["noun.event","verb.change:blow out"],["blowout","malfunction"]],
"godspeed":[["noun.event"],["Godspeed","success"]],
"miscarriage":[["noun.event","verb.social:miscarry","verb.change:abort"],["miscarriage","abortion","failure"]],
"live birth":[["noun.event","noun.act:stillbirth"],["live birth","birth"]],
"blessed event":[["noun.event","noun.communication:colloquialism"],["blessed event","happy event","live birth"]],
"posthumous birth":[["noun.event","noun.event"],["posthumous birth","birth","posthumous birth1","birth"]],
"transmigration":[["noun.event","verb.stative:transmigrate"],["transmigration","reincarnation"]],
"cycle of rebirth":[["noun.event","noun.cognition:Hinduism"],["cycle of rebirth","reincarnation"]],
"moksa":[["noun.event","noun.cognition:Hinduism"],["moksa","cycle of rebirth"]],
"ingress":[["noun.event","noun.cognition:astronomy"],["ingress","egress","immersion1","emersion","disappearance","eclipse"]],
"second coming":[["noun.event","noun.cognition:Christian theology"],["Second Coming","Second Coming of Christ","Second Advent","Advent","Parousia","manifestation"]],
"theophany":[["noun.event"],["theophany","manifestation"]],
"crime wave":[["noun.event"],["crime wave","rise"]],
"adrenarche":[["noun.event"],["adrenarche","start"]],
"menarche":[["noun.event"],["menarche","start"]],
"thelarche":[["noun.event"],["thelarche","start"]],
"onset":[["noun.event"],["onset","oncoming","start"]],
"flying start":[["noun.event","noun.event"],["flying start","running start","start","flying start1","running start1","racing start"]],
"preliminary":[["noun.event","adj.all:exploratory^preliminary"],["preliminary","prelim","athletic contest"]],
"unknown quantity":[["noun.event"],["unknown quantity","factor"]],
"producer":[["noun.event","verb.creation:produce2","noun.person","verb.perception:produce"],["producer","cause","producer2","creator"]],
"racing start":[["noun.event"],["racing start","start"]],
"inevitable":[["noun.event"],["inevitable","destiny"]],
"karma":[["noun.event","noun.cognition:Hinduism","noun.cognition:Buddhism"],["karma","destiny"]],
"kismet":[["noun.event","noun.cognition:Islam"],["kismet","kismat","destiny"]],
"eradication":[["noun.event","verb.creation:eradicate","verb.change:obliterate3","verb.change:obliterate2","verb.change:obliterate"],["eradication","obliteration","destruction"]],
"debilitation":[["noun.event","verb.change:debilitate","verb.change:enervate","verb.change:enfeeble"],["debilitation","enervation","enfeeblement","exhaustion","weakening"]],
"dissipation":[["noun.event","verb.motion:dissipate1","verb.motion:dissipate"],["dissipation","dispersion"]],
"martyrdom":[["noun.event","noun.person:martyr1"],["martyrdom","death"]],
"megadeath":[["noun.event"],["megadeath","death"]],
"wrongful death":[["noun.event"],["wrongful death","death"]],
"doom":[["noun.event","verb.communication:doom4","verb.communication","noun.event:doom"],["doom","doomsday","day of reckoning","end of the world","destiny","doom4","assure3","frames:8"]],
"ravage":[["noun.event","verb.change:ravage1","verb.change:ravage","noun.communication:plural"],["ravage","depredation","destruction"]],
"evanescence":[["noun.event","adj.all:impermanent^evanescent","verb.change:evanesce"],["evanescence","disappearance"]],
"hardship":[["noun.event"],["hardship","misfortune"]],
"vagary":[["noun.event"],["vagary","change"]],
"allomerism":[["noun.event","adj.pert:allomerous","noun.cognition:chemistry"],["allomerism","variation1"]],
"battle damage":[["noun.event","noun.group:military"],["battle damage","combat casualty","damage1"]],
"operational damage":[["noun.event","noun.group:military"],["operational damage","operational casualty","damage1"]],
"blighty wound":[["noun.event"],["blighty wound","wound"]],
"flesh wound":[["noun.event"],["flesh wound","wound"]],
"personnel casualty":[["noun.event","noun.group:military"],["personnel casualty","loss","casualty1"]],
"cardiac cycle":[["noun.event"],["cardiac cycle","cycle1"]],
"carnot cycle":[["noun.event"],["Carnot cycle","Carnot's ideal cycle","cycle1"]],
"merry-go-round":[["noun.event"],["merry-go-round","cycle2"]],
"samsara":[["noun.event","noun.cognition:Hinduism","noun.cognition:Buddhism"],["samsara","cycle2"]],
"recurrence":[["noun.event","adj.all:continual^recurrent","verb.change:recur"],["recurrence","return1","repetition"]],
"atavism":[["noun.event","noun.person:atavist"],["atavism","reversion1","throwback","recurrence"]],
"ground swell":[["noun.event","noun.event"],["ground swell","heavy swell","swell","ground swell1","transition1"]],
"gravity wave":[["noun.event","noun.cognition:physics"],["gravity wave","gravitation wave","wave"]],
"sine wave":[["noun.event"],["sine wave","wave"]],
"jitter":[["noun.event"],["jitter","noise1"]],
"seiche":[["noun.event"],["seiche","wave"]],
"soliton":[["noun.event","noun.cognition:physics"],["soliton","soliton wave","solitary wave","traveling wave"]],
"standing wave":[["noun.event"],["standing wave","stationary wave","wave"]],
"traveling wave":[["noun.event"],["traveling wave","travelling wave","wave"]],
"sound wave":[["noun.event","noun.cognition:acoustics"],["sound wave","acoustic wave","wave"]],
"air wave":[["noun.event"],["air wave","sound wave"]],
"wave form":[["noun.event"],["wave form","waveform","wave shape","wave"]],
"shock wave":[["noun.event"],["shock wave","blast wave","wave"]],
"sonic boom":[["noun.event"],["sonic boom","shock wave"]],
"tidal wave":[["noun.event","noun.event","noun.event"],["tidal wave","wave1","tidal wave1","wave1","calamity","tidal wave2","manifestation"]],
"tsunami":[["noun.event"],["tsunami","calamity","wave1"]],
"periodic motion":[["noun.event"],["periodic motion","periodic movement","movement"]],
"harmonic motion":[["noun.event"],["harmonic motion","periodic motion"]],
"recoil":[["noun.event","verb.motion:recoil1","verb.motion:rebound","noun.event","verb.contact:recoil","verb.contact:kick8"],["recoil","repercussion","rebound","backlash","movement","recoil1","kick","movement"]],
"instroke":[["noun.event"],["instroke","throw"]],
"outstroke":[["noun.event"],["outstroke","throw"]],
"undulation":[["noun.event","verb.motion:undulate"],["undulation1","movement"]],
"whitecap":[["noun.event"],["whitecap","white horse","wave1"]],
"capsizing":[["noun.event","noun.act:navigation1"],["capsizing","shipwreck"]],
"dead heat":[["noun.event"],["dead heat","draw"]],
"photo finish":[["noun.event"],["photo finish","finish"]],
"second-place finish":[["noun.event"],["second-place finish","runner-up finish","finish"]],
"third-place finish":[["noun.event"],["third-place finish","finish"]],
"first-place finish":[["noun.event"],["first-place finish","win"]],
"christianization":[["noun.event","verb.change:Christianize","verb.change:Christianise"],["Christianization","Christianisation","conversion1"]],
"breath of fresh air":[["noun.event"],["breath of fresh air","easing"]],
"deformation":[["noun.event","adj.pert:deformational","verb.contact:deform2","verb.contact:deform1","verb.contact:deform","verb.change:deform2","verb.change:deform1","verb.change:deform"],["deformation1","alteration"]],
"quantum leap":[["noun.event"],["quantum leap","quantum jump1","jump1"]],
"quantum jump":[["noun.event","noun.cognition:physics"],["quantum jump","leap"]],
"population shift":[["noun.event"],["population shift","transformation"]],
"pyrolysis":[["noun.event","adj.pert:pyrolytic"],["pyrolysis","transformation"]],
"sea change":[["noun.event"],["sea change","transformation"]],
"tin pest":[["noun.event"],["tin pest","tin disease","tin plague","transformation"]],
"cave in":[["noun.event","verb.motion:cave in","verb.motion:subside2"],["cave in","subsidence1","collapse"]],
"fatal accident":[["noun.event"],["fatal accident","casualty2","fatality","accident1"]],
"collateral damage":[["noun.event","noun.communication:euphemism","noun.group:military"],["collateral damage","fatal accident"]],
"cessation":[["noun.event","verb.stative:cease"],["cessation","surcease","stop"]],
"settling":[["noun.event","verb.motion:settle4","verb.motion:subside2","verb.motion:subside2"],["settling","subsiding","subsidence","sinking"]],
"free fall":[["noun.event"],["free fall","drop"]],
"lightening":[["noun.event"],["lightening","descent"]],
"submergence":[["noun.event","verb.motion:submerge","verb.contact:submerge1","verb.change:submerge2","verb.motion:submerge","verb.contact:submerge1","verb.change:submerge2","verb.motion:submerse","verb.contact:submerse","verb.motion:submerge"],["submergence","submerging","submersion","immersion","sinking"]],
"foundering":[["noun.event","verb.motion:founder1","noun.artifact:ship"],["foundering","going under","sinking"]],
"gravitational collapse":[["noun.event"],["gravitational collapse","implosion"]],
"driftage":[["noun.event","verb.motion:drift4","noun.artifact:aircraft"],["driftage","deviation"]],
"malformation":[["noun.event","verb.cognition:miscreate"],["malformation","miscreation","failure"]],
"monstrosity":[["noun.event","adj.all:evil^monstrous"],["monstrosity","malformation"]],
"interruption":[["noun.event","verb.stative:break5"],["interruption","break","happening"]],
"defervescence":[["noun.event","adj.pert:defervescent","verb.change:defervesce"],["defervescence","suspension"]],
"solar eclipse":[["noun.event"],["solar eclipse","eclipse"]],
"lunar eclipse":[["noun.event"],["lunar eclipse","eclipse"]],
"annular eclipse":[["noun.event"],["annular eclipse","solar eclipse"]],
"total eclipse":[["noun.event"],["total eclipse","eclipse"]],
"partial eclipse":[["noun.event"],["partial eclipse","eclipse"]],
"liftoff":[["noun.event"],["liftoff","rise2"]],
"headway":[["noun.event","verb.motion:head2","verb.motion:head1","verb.motion:head"],["headway","head","progress"]],
"amphimixis":[["noun.event","noun.process:sexual reproduction"],["amphimixis","union"]],
"combining":[["noun.event","verb.stative:combine","verb.contact:combine3","verb.stative:combine","verb.possession:combine","verb.contact:combine3","verb.contact:combine1","verb.change:combine2","verb.change:combine"],["combining","combine","union"]],
"recombination":[["noun.event","verb.change:recombine1","verb.change:recombine","noun.cognition:genetics","noun.event","verb.change:recombine3","noun.cognition:physics"],["recombination","combining","recombination1","combining"]],
"rapid climb":[["noun.event","verb.motion:zoom3"],["rapid climb","rapid growth","zoom","rise2"]],
"upheaval":[["noun.event","verb.contact:upheave","verb.motion:uplift2","noun.cognition:geology"],["upheaval","uplift","upthrow","upthrust","rise2"]],
"uplifting":[["noun.event","verb.motion:uplift"],["uplifting","rise2"]],
"baa":[["noun.event","verb.communication:baa"],["baa","cry"]],
"banging":[["noun.event"],["banging","noise"]],
"beep":[["noun.event","verb.perception:beep","verb.communication:beep1","verb.perception:bleep","verb.communication","noun.event:beep","noun.artifact:beeper"],["beep","bleep","sound","beep1","call5"]],
"blare":[["noun.event","verb.perception:blare1","adj.all:cacophonic","adj.all:cacophonous","adj.all:noisy^clamorous","verb.perception:din"],["blare","blaring","cacophony","clamor","din","noise"]],
"bow-wow":[["noun.event"],["bow-wow","bark"]],
"caterwaul":[["noun.event","verb.communication:caterwaul"],["caterwaul","cry"]],
"cheep":[["noun.event","verb.communication:cheep","verb.communication:peep"],["cheep","peep","cry"]],
"chirp":[["noun.event","adj.pert:chirpy","verb.creation:chirp","verb.communication:chirp"],["chirp","sound"]],
"chirrup":[["noun.event","verb.communication:chirrup","verb.communication:twitter"],["chirrup","twitter","sound"]],
"clack":[["noun.event","verb.perception:clack","verb.communication:clack1","verb.contact:clap"],["clack","clap1","noise"]],
"click-clack":[["noun.event"],["click-clack","sound"]],
"clickety-clack":[["noun.event"],["clickety-clack","clickety-click","click-clack"]],
"clip-clop":[["noun.event"],["clip-clop","clippety-clop","clop","clopping","clunking","clumping","sound"]],
"cock-a-doodle-doo":[["noun.event"],["cock-a-doodle-doo","crow"]],
"creak":[["noun.event","adj.all:noisy^creaky","verb.perception:creak","verb.perception:creak"],["creak","creaking","noise"]],
"crepitation rale":[["noun.event","noun.state:symptom"],["crepitation rale","rattle"]],
"decrepitation":[["noun.event","verb.change:decrepitate1","verb.change:decrepitate"],["decrepitation","crackle"]],
"ding-dong":[["noun.event"],["ding-dong","noise"]],
"footfall":[["noun.event","verb.motion:step4","verb.motion:step"],["footfall","footstep","step","sound"]],
"growl":[["noun.event","verb.communication:growl","verb.communication:growl"],["growl","growling","cry"]],
"hubbub":[["noun.event","adj.all:noisy^uproarious"],["hubbub","uproar","brouhaha","katzenjammer","noise"]],
"mutter":[["noun.event","verb.communication:mutter1","noun.person:mutterer","verb.communication:mutter1","adj.all:soft4^murmurous","verb.communication:murmur","noun.person:murmurer","verb.communication:murmur","verb.communication:murmur","verb.communication:mussitate"],["mutter","muttering","murmur","murmuring","murmuration","mussitation","sound"]],
"paradiddle":[["noun.event","verb.perception:roll"],["paradiddle","roll3","drum roll","sound"]],
"pat":[["noun.event","verb.contact:pat","verb.motion:tap","verb.perception:tap1","verb.contact:tap"],["pat","rap","tap","sound"]],
"pitter-patter":[["noun.event","verb.perception:pitter-patter"],["pitter-patter","pat"]],
"plump":[["noun.event","verb.motion:plump1","verb.cognition"],["plump","noise","plump12","go12","choose","frames:8"]],
"quaver":[["noun.event","verb.communication:quaver1","verb.communication","noun.event:quaver"],["quaver","sound","quaver1","waver","sound"]],
"rat-a-tat-tat":[["noun.event"],["rat-a-tat-tat","rat-a-tat","rat-tat","tapping"]],
"rhonchus":[["noun.event"],["rhonchus","noise"]],
"rub-a-dub":[["noun.event"],["rub-a-dub","rataplan","drumbeat","sound"]],
"screech":[["noun.event","adj.all:high3^screechy","verb.perception:screech","verb.perception:screech","verb.communication:shriek","verb.perception:scream","verb.perception:scream"],["screech","screeching","shriek","shrieking","scream","screaming","noise"]],
"scrunch":[["noun.event","verb.perception:scrunch"],["scrunch","noise"]],
"shrilling":[["noun.event","verb.communication:shrill"],["shrilling","noise"]],
"squawk":[["noun.event","adj.all:cacophonous^squawky","verb.communication:squawk1","verb.communication","noun.event:squawk","noun.person:squawker","noun.communication:screech","noun.person:screecher"],["squawk","noise","squawk1","screak","skreak","skreigh","screech1","yell1"]],
"squeak":[["noun.event","adj.all:high3^squeaky","verb.perception:squeak"],["squeak","noise"]],
"squeal":[["noun.event","verb.communication:squeal1","verb.communication","noun.event:squeal","noun.animal:squealer"],["squeal","howl","squeal1","oink","utter2"]],
"stridulation":[["noun.event","verb.perception:stridulate"],["stridulation","noise"]],
"susurration":[["noun.event","verb.communication:susurrate","verb.communication:susurrate"],["susurration","susurrus","sound"]],
"swish":[["noun.event","adj.all:noisy^swishy","verb.perception:swish"],["swish","sound"]],
"swoosh":[["noun.event"],["swoosh","whoosh","noise"]],
"tapping":[["noun.event","verb.perception:tap1"],["tapping","sound"]],
"throbbing":[["noun.event"],["throbbing1","sound"]],
"thrum":[["noun.event","verb.perception:thrum2"],["thrum","sound"]],
"thunderclap":[["noun.event"],["thunderclap","thunder1"]],
"thunk":[["noun.event"],["thunk","sound"]],
"ticktock":[["noun.event","verb.perception:ticktock"],["ticktock","tocktact","tictac","tick"]],
"toot":[["noun.event","verb.perception:toot"],["toot","sound"]],
"vibrato":[["noun.event","noun.communication:music"],["vibrato","sound"]],
"water hammer":[["noun.event"],["water hammer","bang"]],
"whir":[["noun.event","verb.perception:whir","verb.perception:whirr","verb.perception:whir","verb.perception:birr"],["whir","whirr","whirring","birr","sound"]],
"whiz":[["noun.event","verb.perception:whiz"],["whiz","sound"]],
"yip":[["noun.event","verb.communication:yelp","verb.communication:yelp"],["yip","yelp","yelping","cry"]],
"zing":[["noun.event"],["zing","sound"]],
"news event":[["noun.event"],["news event","happening"]],
"diastole":[["noun.event","adj.pert:diastolic"],["diastole","pulse"]],
"systole":[["noun.event"],["systole","pulse"]],
"extrasystole":[["noun.event"],["extrasystole","systole"]],
"high tide":[["noun.event"],["high tide","low tide","high water","highwater","tide"]],
"low tide":[["noun.event"],["low tide","high tide","low water","tide"]],
"ebbtide":[["noun.event"],["ebbtide","flood tide","tide"]],
"direct tide":[["noun.event"],["direct tide","high tide"]],
"flood tide":[["noun.event"],["flood tide","ebbtide","flood","rising tide","tide"]],
"neap tide":[["noun.event"],["neap tide","springtide","neap","high tide"]],
"springtide":[["noun.event","noun.event"],["springtide","neap tide","high tide","springtide1","flush"]],
"leeward tide":[["noun.event"],["leeward tide","lee tide","tide"]],
"slack water":[["noun.event"],["slack water","slack tide","tide"]],
"tidal bore":[["noun.event"],["tidal bore","bore","eagre","aegir","eager","tidal flow"]],
"tidal flow":[["noun.event"],["tidal flow","tidal current","current","tide"]],
"riptide":[["noun.event"],["riptide","rip current","current","tide"]],
"undertide":[["noun.event"],["undertide","undercurrent","current","tide"]],
"lahar":[["noun.event"],["lahar","avalanche"]],
"landslide":[["noun.event","noun.event"],["landslide","landslip","slide","landslide1","victory"]],
"mudslide":[["noun.event"],["mudslide","landslide"]],
"plinian eruption":[["noun.event"],["Plinian eruption","volcanic eruption"]],
"rockslide":[["noun.event"],["rockslide","landslide"]],
"backflow":[["noun.event"],["backflow","backflowing","flow"]],
"airflow":[["noun.event"],["airflow","air flow","flow of air","flow"]],
"current":[["noun.event","verb.motion:stream","noun.phenomenon"],["current","stream","flow","current1","electric current","electrical phenomenon"]],
"freshet":[["noun.event"],["freshet","spate","flow"]],
"dripping":[["noun.event"],["dripping","drippage","flow"]],
"torrent":[["noun.event","adj.pert:torrential"],["torrent","violent stream","current"]],
"airburst":[["noun.event"],["airburst","explosion"]],
"bomb blast":[["noun.event"],["bomb blast","blast"]],
"nuclear explosion":[["noun.event"],["nuclear explosion","atomic explosion","bomb blast"]],
"backblast":[["noun.event"],["backblast","back-blast","backfire1"]],
"big bang":[["noun.event","noun.cognition:cosmology"],["big bang","explosion"]],
"ricochet":[["noun.event","verb.motion:ricochet","verb.motion:carom"],["ricochet","carom","rebound"]],
"concussion":[["noun.event","verb.motion:concuss"],["concussion","injury"]],
"pounding":[["noun.event"],["pounding","buffeting","blow"]],
"simple harmonic motion":[["noun.event"],["simple harmonic motion","harmonic motion"]],
"heat flash":[["noun.event"],["heat flash","flash"]],
"heat lightning":[["noun.event"],["heat lightning","lightning"]],
"sheet lighting":[["noun.event"],["sheet lighting","lightning"]],
"runup":[["noun.event"],["runup","run-up","increase"]],
"inferior conjunction":[["noun.event","noun.cognition:astronomy"],["inferior conjunction","conjunction"]],
"superior conjunction":[["noun.event","noun.cognition:astronomy"],["superior conjunction","conjunction"]],
"isomerization":[["noun.event","verb.change:isomerize1","verb.change:isomerize","verb.change:isomerise1","verb.change:isomerise"],["isomerization","isomerisation","conversion"]],
"conjuncture":[["noun.event"],["conjuncture","juncture"]],
"fall of man":[["noun.event","noun.communication:Old Testament"],["Fall of Man","landmark"]],
"road to damascus":[["noun.event"],["road to Damascus","landmark"]],
"reality check":[["noun.event"],["reality check","juncture"]],
"compaction":[["noun.event","verb.contact:compact9","verb.change:concrete"],["compaction","compression2","concretion","densification","concentration"]],
"rarefaction":[["noun.event","verb.change:rarefy3","verb.change:rarefy"],["rarefaction","concentration"]],
"detriment":[["noun.event","adj.all:harmful^detrimental","verb.change:hurt4"],["detriment","hurt1","damage"]],
"brake failure":[["noun.event"],["brake failure","equipment failure"]],
"engine failure":[["noun.event"],["engine failure","equipment failure"]],
"power outage":[["noun.event"],["power outage","power failure","equipment failure"]],
"dwindling":[["noun.event","verb.change:dwindle"],["dwindling","dwindling away","decrease"]],
"waning":[["noun.event","verb.change:wane2","verb.change:wane1","verb.change:wane"],["waning","waxing","decrease"]],
"fading away":[["noun.event"],["fading away","dwindling"]],
"cultural revolution":[["noun.event","noun.location:China"],["Cultural Revolution","Great Proletarian Cultural Revolution","revolution1"]],
"green revolution":[["noun.event"],["green revolution","revolution1"]],
"sex change":[["noun.event"],["sex change","change"]],
"mutagenesis":[["noun.event"],["mutagenesis","cause","mutation"]],
"insertional mutagenesis":[["noun.event","noun.cognition:genetics"],["insertional mutagenesis","mutagenesis"]],
"point mutation":[["noun.event","noun.cognition:genetics"],["point mutation","gene mutation","mutation"]],
"abiotrophy":[["noun.event"],["abiotrophy","degeneration"]],
"cataplasia":[["noun.event","adj.pert:cataplastic","noun.cognition:biology"],["cataplasia","degeneration"]],
"magnetic storm":[["noun.event"],["magnetic storm","perturbation"]],
"aftershock":[["noun.event"],["aftershock","tremor"]],
"foreshock":[["noun.event"],["foreshock","tremor"]],
"seaquake":[["noun.event"],["seaquake","submarine earthquake","earthquake"]],
"background noise":[["noun.event"],["background noise","ground noise","background"]],
"surface noise":[["noun.event"],["surface noise","background noise"]],
"background radiation":[["noun.event"],["background radiation","background"]],
"crosstalk":[["noun.event"],["crosstalk","XT","noise1"]],
"fadeout":[["noun.event"],["fadeout1","noise1"]],
"white noise":[["noun.event"],["white noise","noise1"]],
"radio noise":[["noun.event"],["radio noise","static"]],
"seepage":[["noun.event","verb.motion:seep","adj.all:leaky^oozy","verb.body:ooze","verb.motion:ooze","verb.motion:ooze","verb.body:ooze"],["seepage","ooze","oozing","flow"]],
"exudation":[["noun.event","verb.body:exude","verb.body:transude"],["exudation","transudation","seepage"]],
"intravenous drip":[["noun.event"],["intravenous drip","drip"]],
"whirlpool":[["noun.event","verb.motion:whirlpool"],["whirlpool","vortex","maelstrom","current"]],
"charybdis":[["noun.event","noun.group:Greek mythology"],["Charybdis","whirlpool"]],
"dismemberment":[["noun.event","verb.contact:dismember","noun.act:torture"],["dismemberment","taking apart","mutilation"]],
"mutilation":[["noun.event","verb.change:mutilate","verb.body:mutilate"],["mutilation","injury"]],
"fertilization":[["noun.event","verb.body:fertilize","verb.body:fecundate","verb.body:impregnate1","verb.body:impregnate"],["fertilization","fertilisation","fecundation","impregnation","creation"]],
"top dressing":[["noun.event"],["top dressing","dressing"]],
"dissilience":[["noun.event","adj.all:nascent^dissilient","noun.cognition:botany"],["dissilience","emergence"]],
"outbreak":[["noun.event","verb.change:erupt2","verb.change:irrupt3"],["outbreak","eruption3","irruption","happening"]],
"epidemic":[["noun.event","adj.all:epidemic"],["epidemic","outbreak"]],
"pandemic":[["noun.event","adj.all:epidemic^pandemic"],["pandemic","epidemic"]],
"recrudescence":[["noun.event","adj.all:revived^recrudescent","verb.change:recrudesce1"],["recrudescence","outbreak"]],
"volcanic eruption":[["noun.event","verb.change:erupt"],["volcanic eruption","eruption","discharge"]],
"pollination":[["noun.event","verb.body:pollinate","verb.body:pollenate"],["pollination","pollenation","fertilization"]],
"allogamy":[["noun.event","adj.pert:allogamous"],["allogamy","autogamy","cross-fertilization"]],
"self-fertilization":[["noun.event"],["self-fertilization","cross-fertilization","self-fertilisation","fertilization"]],
"superfecundation":[["noun.event"],["superfecundation","fertilization"]],
"superfetation":[["noun.event","verb.body:superfetate"],["superfetation","fertilization"]],
"autogamy":[["noun.event","adj.all:autogamic","adj.all:autogamous"],["autogamy","allogamy","self-fertilization"]],
"self-pollination":[["noun.event"],["self-pollination","cross-pollination","pollination"]],
"cleistogamy":[["noun.event"],["cleistogamy","self-pollination"]],
"adaptive radiation":[["noun.event"],["adaptive radiation","radiation"]],
"debris surge":[["noun.event"],["debris surge","debris storm","rush"]],
"onrush":[["noun.event"],["onrush","rush"]],
"dextrorotation":[["noun.event"],["dextrorotation","levorotation","clockwise rotation","rotation"]],
"levorotation":[["noun.event"],["levorotation","dextrorotation","counterclockwise rotation","rotation"]],
"axial rotation":[["noun.event","verb.motion:roll11","verb.body:roll6","verb.change:roll10","verb.contact:roll","verb.motion:roll1","verb.motion:roll"],["axial rotation","axial motion","roll2","rotation"]],
"orbital rotation":[["noun.event"],["orbital rotation","orbital motion","rotation"]],
"backspin":[["noun.event"],["backspin","spin"]],
"topspin":[["noun.event"],["topspin","spin"]],
"business cycle":[["noun.event"],["business cycle","trade cycle","variation1"]],
"daily variation":[["noun.event"],["daily variation","variation1"]],
"diurnal variation":[["noun.event"],["diurnal variation","variation1"]],
"luxation":[["noun.event","verb.change:luxate"],["luxation","displacement"]],
"subluxation":[["noun.event","verb.body:subluxate"],["subluxation","luxation"]],
"angelus bell":[["noun.event"],["angelus bell","angelus","bell"]],
"volution":[["noun.event"],["volution","turning"]],
"bash":[["noun.event"],["bash1","do","brawl","party"]],
"birthday party":[["noun.event"],["birthday party","party"]],
"bunfight":[["noun.event","noun.location:Britain","noun.communication:slang"],["bunfight","bun-fight","party"]],
"ceilidh":[["noun.event","noun.location:Scotland","noun.location:Ireland"],["ceilidh","party"]],
"cocktail party":[["noun.event"],["cocktail party","party"]],
"masked ball":[["noun.event","noun.group:masquerade"],["masked ball","masquerade ball","fancy-dress ball","ball"]],
"barn dance":[["noun.event"],["barn dance","dance"]],
"fete":[["noun.event","verb.social:fete","verb.consumption:feast1","verb.consumption:feast"],["fete","feast1","fiesta","party"]],
"luau":[["noun.event","noun.location:Hawaii"],["luau","fete"]],
"house party":[["noun.event"],["house party","party"]],
"jolly":[["noun.event","adj.all:joyous^jolly","verb.communication:jolly","noun.location:Britain"],["jolly","party"]],
"tea party":[["noun.event"],["tea party","party"]],
"whist drive":[["noun.event","noun.location:Britain"],["whist drive","party"]],
"funeral":[["noun.event","adj.all:joyless^funereal","adj.pert:funerary"],["funeral","obsequy","ceremony"]],
"burial":[["noun.event","verb.social:bury","verb.social:entomb","verb.social:inhume","verb.social:inter"],["burial","entombment","inhumation","interment","sepulture","funeral"]],
"sky burial":[["noun.event"],["sky burial","funeral"]],
"rededication":[["noun.event","verb.communication:rededicate"],["rededication","dedication"]],
"commemoration":[["noun.event","verb.cognition:commemorate2","verb.cognition:commemorate","verb.communication:memorialize","verb.communication:memorialise"],["commemoration","memorialization","memorialisation","ceremony"]],
"coronation":[["noun.event","verb.social:coronate","verb.social:enthrone1","verb.social:enthrone","verb.social:enthrone","verb.social:enthrone","verb.social:invest2","verb.social:invest"],["coronation","enthronement","enthronization","enthronisation","investiture1","initiation"]],
"fire walking":[["noun.event"],["fire walking","ceremony"]],
"commencement":[["noun.event","verb.possession:graduate1","verb.possession:graduate"],["commencement2","commencement exercise","commencement ceremony","graduation1","graduation exercise","exercise1"]],
"maundy":[["noun.event","noun.location:Great Britain1"],["Maundy","ceremony"]],
"potlatch":[["noun.event"],["potlatch","ceremony","fete"]],
"photo opportunity":[["noun.event"],["photo opportunity","photo op","affair"]],
"sleepover":[["noun.event","verb.stative:sleep over"],["sleepover","affair"]],
"athletic contest":[["noun.event"],["athletic contest","athletic competition","athletics","contest"]],
"bout":[["noun.event","noun.time"],["bout","contest","bout1","time period"]],
"decathlon":[["noun.event"],["decathlon","athletic contest"]],
"olympic games":[["noun.event"],["Olympic Games","Olympics","Olympiad","athletic contest"]],
"special olympics":[["noun.event"],["Special Olympics","athletic contest"]],
"winter olympic games":[["noun.event"],["Winter Olympic Games","Winter Olympics","Olympic Games"]],
"pentathlon":[["noun.event"],["pentathlon","athletic contest"]],
"automobile race":[["noun.event"],["automobile race","auto race","car race","race"]],
"grand prix":[["noun.event"],["Grand Prix","automobile race"]],
"bicycle race":[["noun.event"],["bicycle race","bike race","race"]],
"tour de france":[["noun.event"],["Tour de France","bicycle race"]],
"criterium":[["noun.event"],["criterium","crit","bicycle race"]],
"boat race":[["noun.event"],["boat race","race"]],
"chariot race":[["noun.event"],["chariot race","race"]],
"dog racing":[["noun.event"],["dog racing","race"]],
"sailing-race":[["noun.event"],["sailing-race","yacht race","boat race"]],
"footrace":[["noun.event","verb.competition:run1","verb.motion:run5","verb.motion:run10","verb.motion:run"],["footrace","foot race","run2","race"]],
"funrun":[["noun.event"],["funrun","fun run","footrace"]],
"freestyle":[["noun.event"],["freestyle","race"]],
"cross country":[["noun.event"],["cross country","race"]],
"iditarod":[["noun.event"],["Iditarod","Iditarod Trail Dog Sled Race","cross country"]],
"three-day event":[["noun.event","noun.act:equestrian sport"],["three-day event"]],
"horse race":[["noun.event"],["horse race","race"]],
"claiming race":[["noun.event"],["claiming race","horse race"]],
"selling race":[["noun.event"],["selling race","horse race"]],
"harness race":[["noun.event"],["harness race","harness racing","horse race"]],
"kentucky derby":[["noun.event"],["Kentucky Derby","thoroughbred race"]],
"preakness":[["noun.event"],["Preakness","thoroughbred race"]],
"belmont stakes":[["noun.event"],["Belmont Stakes","thoroughbred race"]],
"stake race":[["noun.event"],["stake race","horse race"]],
"steeplechase":[["noun.event","noun.event"],["steeplechase1","horse race","steeplechase2","footrace"]],
"grand national":[["noun.event"],["Grand National","steeplechase1"]],
"obstacle race":[["noun.event"],["obstacle race","footrace"]],
"thoroughbred race":[["noun.event"],["thoroughbred race","horse race"]],
"potato race":[["noun.event"],["potato race","race"]],
"sack race":[["noun.event"],["sack race","race"]],
"scratch race":[["noun.event"],["scratch race","race"]],
"ski race":[["noun.event"],["ski race","skiing race","race"]],
"repechage":[["noun.event"],["repechage","race"]],
"torch race":[["noun.event","noun.location:Greece","noun.time:antiquity"],["torch race","relay race"]],
"world cup":[["noun.event"],["World Cup","tournament"]],
"tournament":[["noun.event","verb.competition:tourney","noun.event"],["tournament","tourney","contest","tournament1","contest"]],
"elimination tournament":[["noun.event"],["elimination tournament","tournament"]],
"playoff":[["noun.event","verb.competition:play off"],["playoff","contest"]],
"home stand":[["noun.event"],["home stand","series"]],
"world series":[["noun.event"],["World Series","series","playoff"]],
"boxing match":[["noun.event"],["boxing match","match"]],
"chess match":[["noun.event"],["chess match","match"]],
"cockfight":[["noun.event"],["cockfight","match"]],
"cricket match":[["noun.event"],["cricket match","match"]],
"diving":[["noun.event"],["diving","diving event","match","swimming meet"]],
"field event":[["noun.event"],["field event","match","track meet"]],
"final":[["noun.event","adj.all:closing^final"],["final","match","elimination tournament"]],
"cup final":[["noun.event","noun.act:soccer"],["cup final","final"]],
"quarterfinal":[["noun.event"],["quarterfinal","match","elimination tournament"]],
"semifinal":[["noun.event","noun.person:semifinalist"],["semifinal","semi","match","elimination tournament"]],
"gymkhana":[["noun.event"],["gymkhana","meet"]],
"race meeting":[["noun.event","noun.location:Britain"],["race meeting","meet"]],
"regatta":[["noun.event"],["regatta","meet"]],
"swimming meet":[["noun.event"],["swimming meet","swim meet","meet"]],
"track meet":[["noun.event"],["track meet","meet"]],
"track event":[["noun.event"],["track event","footrace","track meet"]],
"hurdles":[["noun.event","verb.motion:hurdle"],["hurdles","hurdling","hurdle race","track event"]],
"mile":[["noun.event","noun.quantity:miler","noun.person:miler","noun.quantity","noun.quantity:miler","noun.person:miler","noun.quantity","noun.quantity:miler","noun.person:miler","noun.quantity","noun.quantity:miler","noun.person:miler","noun.quantity"],["mile","track event","mile1","statute mile","stat mi","land mile","international mile","mi","linear unit","league","mile2","mil5","Swedish mile","linear unit","mile3","Roman mile","linear unit","mile7","large indefinite quantity"]],
"long jump":[["noun.event"],["long jump","broad jump","field event"]],
"pole vault":[["noun.event"],["pole vault","pole vaulting","pole jump","pole jumping","field event"]],
"shot put":[["noun.event"],["shot put","field event"]],
"hammer throw":[["noun.event"],["hammer throw","field event"]],
"swimming event":[["noun.event"],["swimming event","match","swimming meet"]],
"tennis match":[["noun.event"],["tennis match","match"]],
"test match":[["noun.event"],["test match","match game","matched game","match"]],
"wrestling match":[["noun.event"],["wrestling match","match"]],
"takedown":[["noun.event","noun.act:wrestling"],["takedown1","fall2","wrestling match"]],
"sparring match":[["noun.event"],["sparring match","boxing match"]],
"triple jump":[["noun.event"],["triple jump","hop-step-and-jump","athletic contest"]],
"arms race":[["noun.event"],["arms race","race1"]],
"political campaign":[["noun.event","verb.competition:campaign1","verb.competition:run6"],["political campaign","campaign","run3","race1"]],
"governor's race":[["noun.event"],["governor's race","campaign for governor","political campaign"]],
"senate campaign":[["noun.event"],["senate campaign","senate race","political campaign"]],
"victory":[["noun.event","adj.all:undefeated^victorious","adj.all:successful^victorious","verb.competition:triumph"],["victory","defeat","triumph","ending","success"]],
"last laugh":[["noun.event"],["last laugh","victory"]],
"pyrrhic victory":[["noun.event"],["Pyrrhic victory","victory"]],
"grand slam":[["noun.event"],["grand slam","slam"]],
"little slam":[["noun.event"],["little slam","small slam","slam"]],
"runaway":[["noun.event","verb.competition:romp"],["runaway","blowout1","romp","laugher","shoo-in","walkaway","victory"]],
"service break":[["noun.event","noun.act:tennis"],["service break","victory"]],
"defeat":[["noun.event","noun.person:defeatist","verb.social:defeat"],["defeat","victory","licking1","ending","failure"]],
"whammy":[["noun.event"],["whammy","reverse1"]],
"shutout":[["noun.event","verb.competition:skunk"],["shutout","skunk","defeat"]],
"thrashing":[["noun.event","verb.contact:thrash2","verb.competition:wallop","verb.contact:drub","verb.competition:trounce","verb.competition:whip"],["thrashing","walloping","debacle","drubbing","slaughter","trouncing","whipping","defeat"]],
"spelling bee":[["noun.event"],["spelling bee","spelldown","spelling contest","contest"]],
"loss of consciousness":[["noun.event"],["loss of consciousness","change"]],
"head crash":[["noun.event","noun.cognition:computer science"],["head crash","crash3"]],
"supervention":[["noun.event","verb.change:supervene"],["supervention","happening"]]
}