var mysql_wn_data_noun_process = {
"intrusion":[["noun.process"],["intrusion","geological process"]],
"irruption":[["noun.process"],["irruption","population growth"]],
"effacement":[["noun.process","noun.state:parturiency"],["effacement","organic process"]],
"loss":[["noun.process","adj.all:lossy","noun.possession"],["loss","decline2","loss1","transferred property"]],
"succession":[["noun.process","noun.cognition:ecology"],["succession","ecological succession","natural process"]],
"sequestration":[["noun.process","verb.change:sequester6"],["sequestration","chemical process"]],
"conversion":[["noun.process","noun.cognition:psychiatry","noun.act","verb.change:convert2"],["conversion","defense mechanism","conversion3","exchange"]],
"mechanism":[["noun.process"],["mechanism","chemical mechanism","chemical process"]],
"rectification":[["noun.process","verb.change:rectify5","noun.cognition:chemistry"],["rectification","refining"]],
"corruption":[["noun.process"],["corruption","decay2"]],
"filtration":[["noun.process","verb.contact:filter1","verb.contact:filter"],["filtration","natural process"]],
"percolation":[["noun.process","verb.motion:percolate","verb.contact:percolate3","verb.contact:percolate2","verb.contact:percolate","verb.motion:infiltrate3","verb.motion:infiltrate1"],["percolation","infiltration","filtration"]],
"reduction":[["noun.process","verb.change:reduce3"],["reduction","reducing","chemical reaction"]],
"adaptation":[["noun.process","verb.change:adapt2","verb.change:adapt2","verb.change:adjust1"],["adaptation","adaption","adjustment","organic process"]],
"domestication":[["noun.process"],["domestication","adaptation"]],
"variation":[["noun.process","noun.Tops:process","noun.event","verb.stative:vary1","verb.motion:fluctuate"],["variation","variation1","fluctuation","change"]],
"aeration":[["noun.process","verb.perception:aerate"],["aeration","natural process"]],
"fossilization":[["noun.process","verb.change:fossilize","verb.change:fossilise"],["fossilization","fossilisation","natural process"]],
"deposition":[["noun.process"],["deposition","deposit","accretion"]],
"displacement":[["noun.process","noun.cognition:psychiatry"],["displacement","defense mechanism"]],
"dissolution":[["noun.process","verb.change:dissolve8","verb.change:disintegrate"],["dissolution","disintegration1","natural process"]],
"vaporization":[["noun.process","verb.change:vaporize1","verb.change:vaporize","verb.change:vaporise1","verb.change:vaporise","verb.change:evaporate2","verb.change:evaporate1","verb.change:evaporate","verb.change:vaporize1","verb.change:vaporize","verb.change:vaporise1","verb.change:vaporise","verb.change:evaporate2","verb.change:evaporate1"],["vaporization","vaporisation","vapor","vapour","evaporation","phase change"]],
"elimination":[["noun.process","verb.body:eliminate","verb.body:evacuate","verb.body:excrete","verb.body:excrete","verb.body:void"],["elimination","evacuation","excretion","excreting","voiding","discharge"]],
"gassing":[["noun.process"],["gassing","chemical process"]],
"extinction":[["noun.process","noun.state"],["extinction","natural process","extinction2","inaction"]],
"neutralization":[["noun.process","verb.change:neutralize","verb.change:neutralise","noun.act","verb.social:neutralize","verb.competition:neutralize","verb.competition:neutralise","noun.act","noun.communication:euphemism"],["neutralization","neutralisation","neutralization reaction","neutralisation reaction","chemical reaction","neutralization1","neutralisation1","nullification","neutralization2","neutralisation2","destruction"]],
"regression":[["noun.process","noun.cognition:psychiatry"],["regression","defense mechanism"]],
"activation":[["noun.process","verb.change:activate3","verb.change:activate2","verb.change:activate1","verb.creation:activate"],["activation","inactivation","stimulation"]],
"boiling":[["noun.process"],["boiling","heating","vaporization"]],
"electrolysis":[["noun.process","adj.pert:electrolytic1","noun.cognition:chemistry"],["electrolysis","decomposition1"]],
"defoliation":[["noun.process","verb.change:defoliate"],["defoliation","organic process"]],
"slippage":[["noun.process","noun.process","verb.change:slip"],["slippage","decrease","slippage1","decline2"]],
"consumption":[["noun.process","verb.consumption:use","noun.cognition:economics","noun.act","verb.consumption:consume","verb.consumption:ingest","noun.process:bodily process"],["consumption","economic consumption","usance","use","use of goods and services","demand","consumption1","ingestion","intake","uptake"]],
"expression":[["noun.process","verb.perception:express9","noun.cognition:genetics","noun.communication","verb.communication:manifest","noun.communication","verb.communication:express"],["expression","organic process","expression2","manifestation1","reflection1","reflexion1","demonstration","expression4","verbal expression","verbalism","communication1"]],
"deflation":[["noun.process","adj.all:deflationary","verb.change:deflate11","verb.change:deflate10","noun.process","noun.cognition:geology"],["deflation","inflation","disinflation","economic process","deflation1","erosion"]],
"inflation":[["noun.process","adj.all:inflationary","verb.change:inflate11","verb.change:inflate10"],["inflation","deflation","disinflation","rising prices","economic process"]],
"buildup":[["noun.process"],["buildup","accretion"]],
"focalization":[["noun.process","verb.stative:focalize","verb.stative:focalise"],["focalization","focalisation","pathogenesis"]],
"ignition":[["noun.process","verb.weather:ignite"],["ignition","fire"]],
"fusion":[["noun.process","noun.process"],["fusion","nuclear fusion","nuclear fusion reaction","nuclear reaction","fusion1","linguistic process"]],
"fractionation":[["noun.process","verb.contact:fractionate1","verb.contact:fractionate"],["fractionation","fractional process","industrial process"]],
"derivation":[["noun.process","verb.change:derive1","noun.cognition:descriptive linguistics","noun.act","noun.act"],["derivation","linguistic process","derivation1","drawing off","derivation2","drawing off"]],
"abscission":[["noun.process"],["abscission","shedding"]],
"extraction":[["noun.process","verb.contact:extract7","verb.change:extract"],["extraction","natural process"]],
"ablation":[["noun.process","verb.change:ablate"],["ablation","erosion"]],
"metamorphosis":[["noun.process","adj.all:metamorphic","adj.all:metabolic","adj.all:metabolous"],["metamorphosis","metabolism2","organic process"]],
"involution":[["noun.process"],["involution","organic process"]],
"widening":[["noun.process","verb.change:widen"],["widening","narrowing","broadening","increase"]],
"narrowing":[["noun.process"],["narrowing","widening","decrease"]],
"specialization":[["noun.process","verb.change:specialize7","verb.change:specialise7","verb.change:differentiate1","noun.cognition:biology","noun.act","verb.change:specialize1","verb.change:specialise1"],["specialization","specialisation","differentiation","adaptation","specialization1","specialisation1","change of state"]],
"photography":[["noun.process","adj.pert:photographic","noun.artifact:photograph","noun.Tops:process"],["photography"]],
"scanning":[["noun.process","verb.motion:scan"],["scanning","photography"]],
"implantation":[["noun.process","verb.contact:implant","noun.cognition:embryology"],["implantation","nidation","organic process"]],
"refrigeration":[["noun.process","verb.change:refrigerate1","verb.change:refrigerate"],["refrigeration","infrigidation","cooling","preservation"]],
"chlorination":[["noun.process","verb.change:chlorinate"],["chlorination","chemical process"]],
"foliation":[["noun.process","noun.cognition:geology"],["foliation","stratification"]],
"galvanization":[["noun.process","verb.body:galvanize2","verb.body:galvanise2","noun.act","verb.emotion:galvanize","verb.emotion:galvanise"],["galvanization","galvanisation","stimulation","galvanization1","galvanisation1","stimulation"]],
"doubling":[["noun.process","verb.change:double"],["doubling","multiplication"]],
"storage":[["noun.process","noun.cognition:computer science"],["storage","computer operation"]],
"insufflation":[["noun.process","verb.body:insufflate1","noun.cognition:medicine"],["insufflation","blowing"]],
"reproduction":[["noun.process","verb.body:reproduce","noun.cognition:biology","noun.act","verb.creation:reproduce"],["reproduction","organic process","reproduction1","replication","copying"]],
"multiplication":[["noun.process","verb.change:multiply"],["multiplication","increase"]],
"summation":[["noun.process","adj.all:additive^summational","noun.cognition:physiology"],["summation","organic process"]],
"relaxation":[["noun.process","noun.cognition:physics","noun.process","verb.change:relax1","verb.body:relax","noun.cognition:physiology"],["relaxation","relaxation behavior","exponential decay","relaxation1","increase"]],
"radiography":[["noun.process","adj.pert:radiographic","noun.person:radiographer"],["radiography","skiagraphy","photography"]],
"cultivation":[["noun.process","verb.creation:cultivate","noun.act","noun.act"],["cultivation","growth","cultivation2","production2","cultivation1","socialization"]],
"sericulture":[["noun.process","adj.pert:sericultural","noun.person:sericulturist"],["sericulture","natural process"]],
"formation":[["noun.process","noun.act","verb.stative:form2"],["formation","natural process","formation2","creating by mental acts"]],
"tanning":[["noun.process","verb.body:tan"],["tanning","bodily process"]],
"iteration":[["noun.process","verb.communication:iterate","noun.Tops:process","noun.cognition:computer science","noun.process","verb.communication:iterate","noun.Tops:process","noun.cognition:computer science"],["iteration","looping","iteration1","loop"]],
"stiffening":[["noun.process","verb.change:stiffen1","verb.change:rigidify","verb.change:rigidify"],["stiffening","rigidifying","rigidification","natural process"]],
"regeneration":[["noun.process","verb.change:regenerate2","verb.body:regenerate1","noun.cognition:biology"],["regeneration","organic process"]],
"superposition":[["noun.process","noun.cognition:geology","noun.act","verb.contact:superpose","noun.cognition:geometry"],["superposition","deposition","superposition1","placement"]],
"vegetation":[["noun.process","verb.change:vegetate1","verb.change:vegetate"],["vegetation","growth"]],
"inhibition":[["noun.process","noun.cognition:physiology"],["inhibition","organic process"]],
"suppression":[["noun.process"],["suppression","growth"]],
"execution":[["noun.process","noun.Tops:process","noun.cognition:computer science","noun.communication","verb.social:execute3","noun.act:subscription1","noun.group:law"],["execution","instruction execution","data processing","execution1","execution of instrument"]],
"rationalization":[["noun.process","noun.cognition:psychiatry"],["rationalization","rationalisation","defense mechanism"]],
"segregation":[["noun.process","noun.cognition:genetics"],["segregation","organic process","meiosis"]],
"idealization":[["noun.process","verb.cognition:idealise","noun.cognition:psychiatry"],["idealization","idealisation","defense mechanism"]],
"decentralization":[["noun.process","verb.change:decentralize"],["decentralization","decentalisation","social process"]],
"replication":[["noun.process","verb.creation:replicate1","noun.cognition:genetics"],["replication","organic process"]],
"radiation":[["noun.process","adj.all:radioactive"],["radiation","radioactivity","emission"]],
"emission":[["noun.process"],["emission","release"]],
"stimulation":[["noun.process","noun.cognition:physiology"],["stimulation","natural process"]],
"anamorphosis":[["noun.process"],["anamorphosis","anamorphism1","evolution"]],
"backup":[["noun.process","verb.contact:back up"],["backup","accretion"]],
"establishment":[["noun.process","noun.cognition:ecology","noun.group"],["establishment","ecesis","natural process","establishment1","organization"]],
"hatch":[["noun.process","verb.body:hatch","verb.body:hatch1","verb.body:hatch1","verb.body","noun.process:hatch","noun.process:hatching","noun.location:hatchery","verb.change:be born","verb.contact","noun.attribute:hatch","noun.attribute:hachure","noun.attribute:hatching","verb.creation","noun.attribute:hatch","noun.act:handicraft"],["hatch","hatching","parturition","hatch1","hatch4","line2","hatch3","inlay"]],
"incrustation":[["noun.process","verb.change:incrust","verb.change:encrust"],["incrustation","encrustation","formation"]],
"reticulation":[["noun.process","verb.contact:reticulate","noun.act:photography"],["reticulation","formation"]],
"transcription":[["noun.process","verb.change:transcribe","noun.cognition:genetics"],["transcription","organic process"]],
"fissiparity":[["noun.process"],["fissiparity","asexual reproduction"]],
"sort":[["noun.process","verb.cognition:sort","verb.social:sort","verb.cognition:sort"],["sort","sorting","operation"]],
"ossification":[["noun.process","noun.process","verb.change:ossify2","noun.process","verb.change:ossify1","verb.change:ossify"],["ossification","organic process","ossification1","human process","ossification2","calcification"]],
"heredity":[["noun.process","adj.all:inheritable^hereditary1"],["heredity","organic process"]],
"origin":[["noun.process"],["origin","source"]],
"pigmentation":[["noun.process","verb.change:pigment1"],["pigmentation","deposition"]],
"secretion":[["noun.process","verb.body:secrete"],["secretion","secernment","organic process"]],
"perspiration":[["noun.process","verb.body:perspire","verb.body:sweat","adj.pert:diaphoretic","verb.body:sudate","adj.pert:hidrotic"],["perspiration","sweating","diaphoresis","sudation","hidrosis","bodily process"]],
"photomechanics":[["noun.process","adj.pert:photomechanical"],["photomechanics","photoplate making","photography"]],
"digestion":[["noun.process","verb.consumption:digest","noun.process","verb.change:digest4"],["digestion","organic process","digestion1","chemical process"]],
"retrieval":[["noun.process","noun.cognition:computer science"],["retrieval","computer operation"]],
"synthesis":[["noun.process","adj.all:synthetical3","verb.cognition:synthesise"],["synthesis","chemical process"]],
"linguistic process":[["noun.process","noun.cognition:linguistics"],["linguistic process","human process"]],
"hypostasis":[["noun.process","noun.process"],["hypostasis","bodily process","hypostasis1","epistasis","organic process"]],
"blastogenesis":[["noun.process","adj.pert:blastogenetic"],["blastogenesis","asexual reproduction"]],
"nutrition":[["noun.process","adj.pert:nutritionary","adj.all:wholesome^nutritious","adj.pert:nutritional","noun.person:nutritionist","verb.consumption:nutrify","noun.cognition:physiology"],["nutrition","organic process"]],
"condensation":[["noun.process","verb.change:condense3","verb.change:condense1"],["condensation","natural process"]],
"feedback":[["noun.process","verb.possession:feed back"],["feedback","natural process"]],
"vicious circle":[["noun.process"],["vicious circle","vicious cycle","positive feedback"]],
"ejaculation":[["noun.process","verb.body:ejaculate"],["ejaculation","discharge"]],
"denial":[["noun.process","noun.cognition:psychiatry"],["denial","defense mechanism"]],
"meltdown":[["noun.process"],["meltdown","nuclear meltdown","overheating"]],
"materialization":[["noun.process","verb.change:materialize","verb.change:materialise"],["materialization","materialisation","natural process"]],
"germination":[["noun.process","verb.change:germinate1","verb.change:germinate","verb.change:sprout","verb.body:sprout1"],["germination","sprouting","growth"]],
"diffusion":[["noun.process","noun.cognition:physics"],["diffusion","natural process"]],
"oscillation":[["noun.process","verb.stative:oscillate"],["oscillation","natural process"]],
"glycogenesis":[["noun.process"],["glycogenesis","organic process"]],
"saltation":[["noun.process","verb.motion:saltate1","noun.cognition:geology"],["saltation","natural process"]],
"degeneration":[["noun.process","verb.body:degenerate","noun.Tops:process"],["degeneration","devolution","evolution1"]],
"thaw":[["noun.process","verb.change:thaw","verb.change:melt","verb.change:melt1","verb.change:thaw","verb.change:melt1","verb.change:melt"],["thaw","melt","thawing","melting","heating","phase change"]],
"civilization":[["noun.process","verb.change:civilise1"],["civilization","civilisation","social process"]],
"flowage":[["noun.process"],["flowage","flow"]],
"petrifaction":[["noun.process","verb.change:petrify","verb.change:petrify"],["petrifaction","petrification","fossilization"]],
"cohesion":[["noun.process","noun.cognition:botany"],["cohesion","growth"]],
"life cycle":[["noun.process"],["life cycle","growth"]],
"fructification":[["noun.process","verb.change:fructify","verb.body:fructify"],["fructification","maturation"]],
"placentation":[["noun.process"],["placentation","bodily process"]],
"mildew":[["noun.process","verb.change:mildew","verb.change:mold"],["mildew","mold","mould","spoilage"]],
"compensation":[["noun.process","verb.stative:compensate3","noun.cognition:psychiatry"],["compensation","defense mechanism"]],
"overcompensation":[["noun.process","verb.stative:overcompensate","noun.cognition:psychiatry"],["overcompensation","compensation"]],
"wastage":[["noun.process","verb.change:waste2","verb.change:waste1","verb.body:waste"],["wastage","decrease"]],
"ablactation":[["noun.process"],["ablactation","bodily process"]],
"absorption":[["noun.process","verb.contact:absorb","verb.contact:absorb1","noun.cognition:chemistry","noun.process","verb.weather:absorb","noun.cognition:physics"],["absorption","soaking up","sorption","absorption2","natural process","extinction"]],
"acclimatization":[["noun.process","verb.change:acclimatize","verb.change:acclimatise","verb.change:acclimate"],["acclimatization","acclimatisation","acclimation","adaptation"]],
"acetylation":[["noun.process","verb.change:acetylate","verb.change:acetylate1"],["acetylation","acylation"]],
"acheson process":[["noun.process"],["Acheson process","industrial process"]],
"acid-base equilibrium":[["noun.process","noun.cognition:physiology"],["acid-base equilibrium","acid-base balance","chemical equilibrium"]],
"acidification":[["noun.process","verb.change:acidify"],["acidification","natural process"]],
"active birth":[["noun.process"],["active birth","childbirth"]],
"active transport":[["noun.process","noun.artifact:drug"],["active transport","transport"]],
"acylation":[["noun.process"],["acylation","chemical process"]],
"addition reaction":[["noun.process"],["addition reaction","chemical reaction"]],
"adiabatic process":[["noun.process","noun.cognition:thermodynamics"],["adiabatic process","natural process"]],
"administrative data processing":[["noun.process"],["administrative data processing","business data processing","data processing"]],
"adsorption":[["noun.process","verb.contact:adsorb"],["adsorption","surface assimilation","sorption"]],
"advection":[["noun.process","verb.motion:advect","noun.cognition:meteorology"],["advection","temperature change"]],
"agenesis":[["noun.process"],["agenesis","agenesia","nondevelopment"]],
"agglutination":[["noun.process","verb.contact:agglutinate1","noun.process","verb.contact:agglutinate","noun.process"],["agglutination","linguistic process","agglutination1","organic process","agglutination2","agglutinating activity","chemical process"]],
"aging":[["noun.process","adj.all:old2^senescent"],["aging","ageing","senescence","organic process"]],
"aldol reaction":[["noun.process"],["aldol reaction","chemical reaction"]],
"alluvion":[["noun.process"],["alluvion","geological process"]],
"alpha decay":[["noun.process"],["alpha decay","decay3"]],
"alternative birth":[["noun.process"],["alternative birth","alternative birthing","childbirth"]],
"amelogenesis":[["noun.process"],["amelogenesis","growth"]],
"americanization":[["noun.process","verb.change:americanize1","verb.change:americanize","verb.change:americanise1","verb.change:americanise"],["Americanization","Americanisation","assimilation2"]],
"amitosis":[["noun.process","adj.pert:amitotic"],["amitosis","cell division"]],
"ammonification":[["noun.process","verb.change:ammonify"],["ammonification","permeation"]],
"amylolysis":[["noun.process","adj.pert:amylolytic"],["amylolysis","chemical process"]],
"anabolism":[["noun.process","adj.pert:anabolic","adj.all:anabolic"],["anabolism","catabolism","constructive metabolism","assimilation1","metabolism"]],
"anaglyphy":[["noun.process","adj.pert:anaglyptic","adj.pert:anaglyphical"],["anaglyphy","photography"]],
"anamorphism":[["noun.process"],["anamorphism","katamorphism","metamorphism"]],
"anaphase":[["noun.process","adj.pert:anaphasic"],["anaphase","phase of cell division","meiosis"]],
"anastalsis":[["noun.process"],["anastalsis","peristalsis","bodily process"]],
"androgenesis":[["noun.process","adj.pert:androgenetic","adj.pert:androgenous","adj.pert:androgenic"],["androgenesis","androgeny","parthenogenesis"]],
"angiogenesis":[["noun.process"],["angiogenesis","growth"]],
"anglicization":[["noun.process","verb.change:anglicize","verb.change:anglicise"],["Anglicization","Anglicisation","assimilation2"]],
"anisogamy":[["noun.process","adj.pert:anisogamous","noun.cognition:biology"],["anisogamy","sexual reproduction"]],
"anovulation":[["noun.process"],["anovulation","ovulation","organic process"]],
"anthropogenesis":[["noun.process","adj.pert:anthropogenetic","adj.pert:anthropogenetic"],["anthropogenesis","anthropogeny","evolution"]],
"antiredeposition":[["noun.process"],["antiredeposition","natural process"]],
"antisepsis":[["noun.process","adj.all:antiseptic^aseptic"],["antisepsis","asepsis","organic process"]],
"aphaeresis":[["noun.process","adj.pert:aphaeretic","adj.pert:apheretic","noun.cognition:linguistics"],["aphaeresis","apheresis","omission"]],
"aphesis":[["noun.process","adj.pert:aphetic"],["aphesis","omission"]],
"apogamy":[["noun.process","adj.pert:apogamic","adj.pert:apogamous","noun.cognition:botany"],["apogamy","apomixis"]],
"apomixis":[["noun.process","adj.all:asexual^apomictic","adj.pert:apomictic","adj.pert:apomictical"],["apomixis","asexual reproduction"]],
"asexual reproduction":[["noun.process","adj.all:asexual^agamogenetic"],["asexual reproduction","agamogenesis","reproduction"]],
"assibilation":[["noun.process","verb.change:assibilate"],["assibilation","evolution1"]],
"asynchronous operation":[["noun.process"],["asynchronous operation","synchronous operation","operation"]],
"autocatalysis":[["noun.process","adj.pert:autocatalytic"],["autocatalysis","catalysis"]],
"autolysis":[["noun.process","adj.pert:autolytic"],["autolysis","self-digestion","lysis"]],
"automatic data processing":[["noun.process"],["automatic data processing","ADP","data processing"]],
"autoradiography":[["noun.process"],["autoradiography","radiography"]],
"autotype":[["noun.process","adj.pert:autotypic"],["autotype","autotypy","photography"]],
"autoregulation":[["noun.process","noun.cognition:physiology"],["autoregulation","organic process"]],
"auxesis":[["noun.process","adj.pert:auxetic"],["auxesis","growth"]],
"auxiliary operation":[["noun.process"],["auxiliary operation","off-line operation","operation"]],
"background processing":[["noun.process"],["background processing","backgrounding","priority processing"]],
"bacteriolysis":[["noun.process","adj.pert:bacteriolytic"],["bacteriolysis","lysis"]],
"bacteriostasis":[["noun.process","adj.pert:bacteriostatic"],["bacteriostasis","organic process"]],
"basal metabolic rate":[["noun.process","noun.time:metabolic rate"],["basal metabolic rate","BMR"]],
"basal metabolism":[["noun.process"],["basal metabolism","metabolism"]],
"batch processing":[["noun.process"],["batch processing","execution"]],
"beach erosion":[["noun.process"],["beach erosion","erosion"]],
"bed-wetting":[["noun.process"],["bed-wetting","enuresis"]],
"bessemer process":[["noun.process"],["Bessemer process","industrial process","steel production"]],
"beta decay":[["noun.process"],["beta decay","decay3"]],
"biochemical mechanism":[["noun.process"],["biochemical mechanism","mechanism"]],
"biosynthesis":[["noun.process","adj.pert:biosynthetic","adj.pert:biogenous"],["biosynthesis","biogenesis","synthesis"]],
"blood coagulation":[["noun.process"],["blood coagulation","blood clotting","curdling"]],
"blooming":[["noun.process","verb.change:bloom"],["blooming","bloom","organic process"]],
"blossoming":[["noun.process","verb.change:flower","adj.all:mature1^efflorescent","verb.change:effloresce"],["blossoming","flowering","florescence","inflorescence","anthesis","efflorescence","maturation"]],
"blowing":[["noun.process","verb.change:blow8"],["blowing","processing"]],
"bodily process":[["noun.process","adj.all:active2"],["bodily process","body process","bodily function","activity","organic process"]],
"boolean operation":[["noun.process"],["boolean operation","binary operation","binary arithmetic operation","operation"]],
"bottom fermentation":[["noun.process"],["bottom fermentation","zymosis1"]],
"bowel movement":[["noun.process","noun.communication:euphemism"],["bowel movement","movement","bm","defecation"]],
"bradley method of childbirth":[["noun.process"],["Bradley method of childbirth","Bradley method","natural childbirth"]],
"brooding":[["noun.process","verb.body:incubate"],["brooding","incubation","parturition"]],
"budding":[["noun.process"],["budding","asexual reproduction"]],
"calcination":[["noun.process","verb.change:calcine"],["calcination","oxidation"]],
"calving":[["noun.process"],["calving","parturition"]],
"carbonation":[["noun.process","verb.change:carbonate"],["carbonation","permeation"]],
"carbon cycle":[["noun.process","noun.process"],["carbon cycle","thermonuclear reaction","carbon cycle1","organic process"]],
"carbonization":[["noun.process","verb.change:carbonize","verb.change:carbonise"],["carbonization","carbonisation","destructive distillation"]],
"carriage return":[["noun.process"],["carriage return","printing operation"]],
"catabiosis":[["noun.process"],["catabiosis","aging"]],
"catabolism":[["noun.process","adj.pert:catabolic","adj.all:catabolic","adj.pert:katabolic","adj.all:katabolic","verb.change:catabolize"],["catabolism","anabolism","katabolism","dissimilation","destructive metabolism","organic process","metabolism"]],
"catalysis":[["noun.process","adj.pert:catalytic"],["catalysis","contact action","chemical process"]],
"cell division":[["noun.process"],["cell division","cellular division","organic process"]],
"cenogenesis":[["noun.process","adj.pert:cenogenetic"],["cenogenesis","palingenesis","kenogenesis","caenogenesis","cainogenesis","kainogenesis","development1"]],
"centrifugation":[["noun.process","verb.motion:centrifuge"],["centrifugation","natural process"]],
"chain reaction":[["noun.process","noun.process"],["chain reaction1","chemical reaction","chain reaction2","nuclear reaction"]],
"chelation":[["noun.process","verb.stative:chelate","noun.process","verb.stative:chelate","noun.Tops:process","noun.cognition:medicine"],["chelation1","chemical process","chelation2"]],
"chemical equilibrium":[["noun.process","verb.stative:equilibrate","verb.change:equilibrate"],["chemical equilibrium","equilibrium","chemical reaction"]],
"chemical process":[["noun.process","noun.cognition:chemistry"],["chemical process","chemical change","chemical action","natural process"]],
"chemical reaction":[["noun.process","verb.change:react","noun.cognition:chemistry"],["chemical reaction","reaction","chemical process"]],
"chemisorption":[["noun.process","verb.contact:chemisorb","verb.contact:chemisorb"],["chemisorption","chemosorption","adsorption"]],
"chemosynthesis":[["noun.process"],["chemosynthesis","synthesis"]],
"childbirth":[["noun.process","adj.pert:childbearing"],["childbirth","childbearing","accouchement","vaginal birth","parturition"]],
"chromatography":[["noun.process","adj.pert:chromatographical"],["chromatography","natural process"]],
"climate change":[["noun.process"],["climate change","global climate change","temperature change"]],
"clouding":[["noun.process","verb.weather:cloud"],["clouding","clouding up","vaporization"]],
"cold fusion":[["noun.process"],["cold fusion","fusion"]],
"column chromatography":[["noun.process"],["column chromatography","chromatography"]],
"deflagration":[["noun.process","verb.change:deflagrate"],["deflagration","combustion"]],
"computer operation":[["noun.process"],["computer operation","machine operation","operation"]],
"concretion":[["noun.process"],["concretion","natural process"]],
"concurrent operation":[["noun.process"],["concurrent operation","operation"]],
"congealment":[["noun.process","verb.change:congeal"],["congealment","congelation","hardening"]],
"conspicuous consumption":[["noun.process"],["conspicuous consumption","consumption"]],
"control operation":[["noun.process"],["control operation","control function","operation"]],
"convalescence":[["noun.process","adj.all:ill1^convalescent","verb.body:convalesce","verb.body:recuperate1","verb.body:recuperate","verb.body:recover"],["convalescence","recuperation","recovery","healing"]],
"convection":[["noun.process","noun.process","verb.motion:convect","noun.cognition:meteorology"],["convection1","temperature change","convection2","natural process"]],
"cooling":[["noun.process","verb.change:cool1","verb.change:cool","verb.change:chill1","verb.change:chill"],["cooling","chilling","temperature reduction","temperature change"]],
"cost-pull inflation":[["noun.process"],["cost-pull inflation","inflation"]],
"cracking":[["noun.process","verb.change:crack8","verb.change:crack7"],["cracking","chemical process"]],
"crossing over":[["noun.process"],["crossing over","crossover","organic process","diplotene"]],
"curdling":[["noun.process","verb.change:curdle2","verb.change:curdle1","verb.change:curdle","verb.change:clot4","verb.change:clot1","verb.change:clot","verb.change:coagulate1","verb.change:coagulate"],["curdling","clotting","coagulation","natural process"]],
"cyanide process":[["noun.process"],["cyanide process","industrial process"]],
"cytogenesis":[["noun.process","adj.pert:cytogenetic"],["cytogenesis","cytogeny","development1"]],
"cytolysis":[["noun.process","adj.pert:cytolytic"],["cytolysis","lysis"]],
"data mining":[["noun.process"],["data mining","data processing"]],
"data processing":[["noun.process","noun.cognition:computer science"],["data processing","processing"]],
"dealignment":[["noun.process","noun.Tops:process"],["dealignment"]],
"deamination":[["noun.process","verb.change:deaminate","verb.change:deaminize"],["deamination","deaminization","chemical process"]],
"decalcification":[["noun.process","verb.change:decalcify1"],["decalcification","chemical process"]],
"decarboxylation":[["noun.process","verb.change:decarboxylate1","verb.change:decarboxylate"],["decarboxylation","chemical process"]],
"decoction":[["noun.process","verb.change:decoct","noun.cognition:pharmacology"],["decoction","extraction"]],
"decoction process":[["noun.process","noun.act:brewing"],["decoction process","decoction mashing","boiling"]],
"dedifferentiation":[["noun.process","verb.change:dedifferentiate"],["dedifferentiation","adaptation"]],
"deepening":[["noun.process","verb.change:deepen3"],["deepening","evolution1"]],
"defecation":[["noun.process","verb.body:defecate","verb.body:shit"],["defecation","laxation","shitting","elimination"]],
"defense mechanism":[["noun.process","noun.cognition:process1","noun.cognition:psychiatry"],["defense mechanism","defense reaction","defence mechanism","defence reaction","defense","defence","psychoanalytic process"]],
"degaussing":[["noun.process","verb.change:degauss"],["degaussing","demagnetization"]],
"de-iodination":[["noun.process","verb.change:de-iodinate"],["de-iodination","chemical process"]],
"demagnetization":[["noun.process","verb.change:demagnetize","verb.change:demagnetise"],["demagnetization","demagnetisation","natural process"]],
"demand-pull inflation":[["noun.process"],["demand-pull inflation","inflation"]],
"denazification":[["noun.process","verb.change:denazify"],["denazification","de-Nazification","social process"]],
"deossification":[["noun.process"],["deossification","organic process"]],
"eponymy":[["noun.process"],["eponymy","derivation"]],
"desalination":[["noun.process","verb.change:desalinate","verb.change:desalinize","verb.change:desalinise"],["desalination","desalinization","desalinisation","chemical process"]],
"desertification":[["noun.process"],["desertification","geological process"]],
"desensitization":[["noun.process","verb.perception:desensitize","verb.change:desensitize","verb.perception:desensitise","verb.change:desensitise"],["desensitization","desensitisation","decrease"]],
"desorption":[["noun.process","verb.change:desorb1","verb.change:desorb"],["desorption","natural process"]],
"destalinization":[["noun.process","verb.change:destalinize","verb.change:destalinise"],["destalinization","de-Stalinization","destalinisation","de-Stalinisation","social process"]],
"destructive distillation":[["noun.process"],["destructive distillation","fractionation"]],
"detumescence":[["noun.process"],["detumescence","decline2"]],
"diakinesis":[["noun.process","noun.time:phase"],["diakinesis","prophase2"]],
"diastrophism":[["noun.process"],["diastrophism","geological process"]],
"digital photography":[["noun.process"],["digital photography","photography"]],
"dilapidation":[["noun.process","verb.creation:dilapidate","verb.change:ruin"],["dilapidation","ruin","decay2"]],
"diplotene":[["noun.process","noun.time:phase"],["diplotene","prophase2"]],
"disinflation":[["noun.process"],["disinflation","inflation","deflation","economic process"]],
"dissimilation":[["noun.process","verb.change:dissimilate2","verb.change:dissimilate"],["dissimilation1","linguistic process"]],
"dissolving":[["noun.process","verb.change:dissolve1","verb.change:dissolve","verb.change:dissolve1","verb.change:dissolve"],["dissolving","dissolution1","liquefaction"]],
"distillation":[["noun.process","verb.change:distill3","verb.change:distill2","verb.change:distill1","verb.change:distill3","verb.change:distill1"],["distillation","distillment","natural process"]],
"distributed data processing":[["noun.process"],["distributed data processing","remote-access data processing","teleprocessing","data processing"]],
"dithering":[["noun.process"],["dithering","video digitizing"]],
"double decomposition":[["noun.process"],["double decomposition","double decomposition reaction","metathesis","chemical reaction"]],
"double replacement reaction":[["noun.process"],["double replacement reaction","double decomposition"]],
"dry plate":[["noun.process"],["dry plate","dry plate process","photography"]],
"melioration":[["noun.process","verb.change:meliorate"],["melioration","drift2"]],
"dyadic operation":[["noun.process"],["dyadic operation","operation"]],
"eburnation":[["noun.process"],["eburnation","organic process"]],
"economic growth":[["noun.process"],["economic growth","economic process"]],
"economic process":[["noun.process","noun.Tops:process"],["economic process"]],
"effervescence":[["noun.process","adj.all:effervescent","verb.change:effervesce"],["effervescence","natural process"]],
"electrodeposition":[["noun.process"],["electrodeposition","deposition"]],
"electronic data processing":[["noun.process"],["electronic data processing","EDP","automatic data processing"]],
"electrophoresis":[["noun.process","adj.pert:electrophoretic","adj.pert:cataphoretic"],["electrophoresis","cataphoresis","dielectrolysis","ionophoresis","natural process"]],
"electrostatic precipitation":[["noun.process"],["electrostatic precipitation","industrial process"]],
"elimination reaction":[["noun.process"],["elimination reaction","chemical reaction"]],
"elision":[["noun.process","verb.cognition:elide"],["elision","omission"]],
"ellipsis":[["noun.process"],["ellipsis","eclipsis","omission"]],
"elution":[["noun.process","verb.contact:elute"],["elution","extraction"]],
"emergent evolution":[["noun.process"],["emergent evolution","evolution"]],
"endoergic reaction":[["noun.process"],["endoergic reaction","nuclear reaction"]],
"endothermic reaction":[["noun.process"],["endothermic reaction","chemical reaction"]],
"enuresis":[["noun.process"],["enuresis","urinary incontinence","incontinence"]],
"epigenesis":[["noun.process"],["epigenesis","metamorphism"]],
"epilation":[["noun.process"],["epilation","loss"]],
"epitaxy":[["noun.process"],["epitaxy","growing1"]],
"erythropoiesis":[["noun.process","adj.pert:erythropoietic"],["erythropoiesis","organic process"]],
"europeanization":[["noun.process","verb.change:europeanize1","verb.change:europeanise1"],["Europeanization","Europeanisation","assimilation2"]],
"eutrophication":[["noun.process"],["eutrophication","organic process"]],
"evolution":[["noun.process","adj.pert:evolutionary","verb.change:evolve3","verb.change:evolve","adj.pert:phylogenetic","noun.cognition:biology"],["evolution","organic evolution","phylogeny","phylogenesis","organic process"]],
"exoergic reaction":[["noun.process"],["exoergic reaction","nuclear reaction"]],
"exothermic reaction":[["noun.process"],["exothermic reaction","chemical reaction"]],
"expectoration":[["noun.process","verb.body:expectorate"],["expectoration","bodily process"]],
"exponential decay":[["noun.process"],["exponential decay","exponential return","decay1"]],
"fat metabolism":[["noun.process"],["fat metabolism","metabolism"]],
"feminization":[["noun.process","verb.change:feminize1","verb.change:feminise1"],["feminization","feminisation","pathologic process"]],
"festering":[["noun.process","verb.body:fester","verb.body:suppurate1","verb.body:suppurate","verb.body:mature4","verb.body:maturate","noun.cognition:medicine"],["festering","suppuration","maturation2","bodily process"]],
"fibrinolysis":[["noun.process"],["fibrinolysis","dissolution"]],
"field emission":[["noun.process"],["field emission","emission"]],
"fission":[["noun.process","noun.process"],["fission","nuclear fission","nuclear reaction","fission1","asexual reproduction"]],
"fixed-cycle operation":[["noun.process"],["fixed-cycle operation","operation"]],
"floating-point operation":[["noun.process"],["floating-point operation","flop","computer operation"]],
"flocculation":[["noun.process","verb.stative:flocculate"],["flocculation","natural process"]],
"foreground processing":[["noun.process"],["foreground processing","foregrounding","priority processing"]],
"fractional distillation":[["noun.process"],["fractional distillation","fractionation"]],
"freeze-drying":[["noun.process","verb.change:lyophilize","verb.change:lyophilise"],["freeze-drying","lyophilization","lyophilisation","freeze1","dehydration"]],
"galactosis":[["noun.process"],["galactosis","secretion"]],
"gametogenesis":[["noun.process"],["gametogenesis","growth"]],
"gasification":[["noun.process","verb.change:gasify"],["gasification","chemical process"]],
"gastric digestion":[["noun.process"],["gastric digestion","digestion"]],
"gastrulation":[["noun.process"],["gastrulation","organic process","growth"]],
"geological process":[["noun.process","noun.cognition:geology"],["geological process","geologic process","natural process"]],
"riss glaciation":[["noun.process"],["Riss glaciation","glaciation"]],
"saale glaciation":[["noun.process"],["Saale glaciation","glaciation"]],
"wolstonian glaciation":[["noun.process"],["Wolstonian glaciation","glaciation"]],
"globalization":[["noun.process","verb.change:globalize","verb.change:globalise"],["globalization","globalisation","economic process"]],
"global warming":[["noun.process"],["global warming","heating"]],
"glycolysis":[["noun.process"],["glycolysis","metabolism"]],
"growing":[["noun.process","noun.act:production","noun.cognition:electronics"],["growing1"]],
"gynogenesis":[["noun.process"],["gynogenesis","parthenogenesis"]],
"haber process":[["noun.process"],["Haber process","Haber-Bosch process","industrial process"]],
"healing":[["noun.process","verb.change:heal","verb.body:heal"],["healing","bodily process"]],
"heat dissipation":[["noun.process"],["heat dissipation","cooling"]],
"heating":[["noun.process","verb.change:heat","verb.change:warm"],["heating","warming","temperature change"]],
"hemagglutination":[["noun.process","verb.contact:hemagglutinate","verb.contact:haemagglutinate"],["hemagglutination","haemagglutination","agglutination1"]],
"hematochezia":[["noun.process"],["hematochezia","haematochezia","defecation"]],
"hematopoiesis":[["noun.process","adj.pert:hematopoietic","adj.pert:haematopoietic","adj.pert:hemopoietic","adj.pert:haemopoietic"],["hematopoiesis","haematopoiesis","hemopoiesis","haemopoiesis","hemogenesis","haemogenesis","hematogenesis","haematogenesis","sanguification","organic process"]],
"hemimetamorphosis":[["noun.process","adj.all:metamorphic^hemimetamorphous","adj.all:metamorphic^hemimetabolic","adj.all:metamorphic^hemimetabolous","adj.all:metamorphic^hemimetabolic"],["hemimetamorphosis","hemimetabolism","hemimetaboly","metamorphosis"]],
"heterometabolism":[["noun.process","adj.all:metamorphic^heterometabolic","adj.all:metamorphic^heterometabolic"],["heterometabolism","heterometaboly","metamorphosis"]],
"hemolysis":[["noun.process","adj.pert:hemolytic","adj.pert:haemolytic"],["hemolysis","haemolysis","hematolysis","haematolysis","lysis"]],
"heterospory":[["noun.process","adj.pert:heterosporous"],["heterospory","sporulation"]],
"holometabolism":[["noun.process","adj.all:metamorphic^holometabolic","adj.all:metamorphic^holometabolous","adj.all:metamorphic^holometabolous","noun.animal:insect"],["holometabolism","holometaboly","metamorphosis"]],
"homospory":[["noun.process","adj.pert:homosporous"],["homospory","sporulation"]],
"human process":[["noun.process","noun.Tops:process"],["human process"]],
"humification":[["noun.process","verb.change:humify"],["humification","organic process"]],
"hydration":[["noun.process","verb.change:hydrate2","verb.change:hydrate"],["hydration","association"]],
"hydrocracking":[["noun.process"],["hydrocracking","cracking"]],
"hydrogenation":[["noun.process","verb.change:hydrogenate"],["hydrogenation","chemical process"]],
"hydrolysis":[["noun.process","verb.change:hydrolize1","verb.change:hydrolise1"],["hydrolysis","chemical reaction"]],
"hyperhidrosis":[["noun.process"],["hyperhidrosis","hyperidrosis","polyhidrosis","perspiration"]],
"hypersecretion":[["noun.process"],["hypersecretion","secretion"]],
"imbibition":[["noun.process","verb.contact:imbibe","noun.cognition:chemistry"],["imbibition","absorption"]],
"immunoelectrophoresis":[["noun.process"],["immunoelectrophoresis","electrophoresis"]],
"inactivation":[["noun.process","verb.change:inactivate"],["inactivation","activation","natural process"]],
"incontinence":[["noun.process","adj.all:incontinent","adj.all:incontinent"],["incontinence","incontinency","elimination"]],
"induction heating":[["noun.process"],["induction heating","heating"]],
"industrial process":[["noun.process","noun.Tops:process"],["industrial process"]],
"indweller":[["noun.process","verb.stative:indwell"],["indweller","activation"]],
"inflationary spiral":[["noun.process"],["inflationary spiral","deflationary spiral","spiral"]],
"deflationary spiral":[["noun.process"],["deflationary spiral","inflationary spiral","spiral"]],
"inflow":[["noun.process"],["inflow","outflow","influx","efflux","flow"]],
"infructescence":[["noun.process"],["infructescence","maturation"]],
"inpouring":[["noun.process"],["inpouring","inpour","inrush","inflow"]],
"inspissation":[["noun.process","verb.change:inspissate3"],["inspissation","dehydration"]],
"integrated data processing":[["noun.process"],["integrated data processing","IDP","automatic data processing"]],
"intellectualization":[["noun.process","noun.cognition:psychiatry"],["intellectualization","intellectualisation","defense mechanism"]],
"internal combustion":[["noun.process"],["internal combustion","combustion"]],
"intussusception":[["noun.process","noun.cognition:biology"],["intussusception","growth"]],
"iodination":[["noun.process","verb.change:iodize","verb.change:iodise"],["iodination","chemical process"]],
"ion exchange":[["noun.process"],["ion exchange","natural process"]],
"irreversible process":[["noun.process","noun.Tops:process"],["irreversible process","reversible process"]],
"isoagglutination":[["noun.process"],["isoagglutination","agglutination1"]],
"isogamy":[["noun.process","noun.cognition:biology"],["isogamy","sexual reproduction"]],
"juvenescence":[["noun.process"],["juvenescence","growth"]],
"cytokinesis":[["noun.process"],["cytokinesis","organic process","mitosis","meiosis"]],
"karyokinesis":[["noun.process","adj.pert:karyokinetic"],["karyokinesis","organic process","mitosis","meiosis"]],
"karyolysis":[["noun.process"],["karyolysis","lysis"]],
"katamorphism":[["noun.process"],["katamorphism","anamorphism","metamorphism"]],
"keratinization":[["noun.process","verb.change:keratinize","verb.change:keratinise"],["keratinization","keratinisation","organic process"]],
"krebs cycle":[["noun.process"],["Krebs cycle","Krebs citric acid cycle","citric acid cycle","tricarboxylic acid cycle","organic process","metabolism"]],
"lacrimation":[["noun.process","verb.body:tear","verb.change:water4"],["lacrimation","lachrymation","tearing","watering","bodily process"]],
"lamaze method of childbirth":[["noun.process"],["Lamaze method of childbirth","Lamaze method","natural childbirth"]],
"laying":[["noun.process"],["laying","egg laying","parturition"]],
"leboyer method of childbirth":[["noun.process"],["Leboyer method of childbirth","Leboyer method","natural childbirth"]],
"leeway":[["noun.process","noun.artifact:ship","noun.artifact:plane1"],["leeway","drift1"]],
"leptotene":[["noun.process","noun.time:phase"],["leptotene","prophase2"]],
"lexicalization":[["noun.process","verb.communication:lexicalize"],["lexicalization","lexicalisation","linguistic process"]],
"libration":[["noun.process","verb.motion:librate","noun.phenomenon:variation","noun.cognition:astronomy"],["libration","oscillation"]],
"light reaction":[["noun.process"],["light reaction","photochemical reaction","photosynthesis"]],
"line feed":[["noun.process"],["line feed","printing operation"]],
"liquefaction":[["noun.process","verb.weather:liquefy","verb.change:liquefy1","verb.change:liquefy"],["liquefaction","phase change"]],
"list processing":[["noun.process"],["list processing","data processing"]],
"lithuresis":[["noun.process"],["lithuresis","micturition"]],
"logic operation":[["noun.process","noun.cognition:logic"],["logic operation","logical operation","operation"]],
"lymphopoiesis":[["noun.process"],["lymphopoiesis","organic process"]],
"lysis":[["noun.process","noun.cognition:biochemistry","noun.process"],["lysis","dissolution","lysis1","recuperation"]],
"lysogenization":[["noun.process","verb.change:lysogenize"],["lysogenization","lysogenisation","organic process"]],
"maceration":[["noun.process","verb.change:macerate1"],["maceration","softening"]],
"macroevolution":[["noun.process"],["macroevolution","evolution"]],
"majority operation":[["noun.process"],["majority operation","threshold operation"]],
"malabsorption":[["noun.process"],["malabsorption","assimilation1"]],
"marginalization":[["noun.process","verb.social:marginalize","verb.social:marginalise"],["marginalization","marginalisation","social process"]],
"market forces":[["noun.process"],["market forces","economic process"]],
"markov chain":[["noun.process"],["Markov chain","Markoff chain","Markov process"]],
"markov process":[["noun.process"],["Markov process","Markoff process","stochastic process"]],
"masculinization":[["noun.process","verb.change:masculinize","verb.change:virilize"],["masculinization","masculinisation","virilization","virilisation","growth"]],
"maturation":[["noun.process","adj.pert:maturational","verb.change:mature","verb.change:maturate","verb.change:ripen1","verb.change:ripen","verb.communication:mature","verb.change:mature4","verb.change:mature"],["maturation1","ripening","maturement","organic process"]],
"meiosis":[["noun.process","adj.pert:meiotic","noun.cognition:genetics"],["meiosis","miosis","reduction division","cell division"]],
"mellowing":[["noun.process","verb.change:mellow3","verb.change:mellow1","verb.change:mellow"],["mellowing","ripening1"]],
"menorrhagia":[["noun.process","noun.state:symptom"],["menorrhagia","hypermenorrhea","menstruation"]],
"menstruation":[["noun.process","verb.body:menstruate","adj.pert:catamenial","verb.body:flow"],["menstruation","menses","menstruum","catamenia","period","flow1","discharge"]],
"metabolism":[["noun.process","adj.pert:metabolic","verb.consumption:metabolize","noun.Tops:organism"],["metabolism","metabolic process","organic process"]],
"metamorphism":[["noun.process"],["metamorphism","geological process"]],
"metaphase":[["noun.process","noun.process"],["metaphase1","phase of cell division","mitosis","metaphase2","phase of cell division","meiosis"]],
"metastasis":[["noun.process","verb.body:metastasize","adj.pert:metastatic"],["metastasis1","pathologic process"]],
"metathesis":[["noun.process"],["metathesis1","linguistic process"]],
"microevolution":[["noun.process"],["microevolution","evolution"]],
"microphoning":[["noun.process"],["microphoning","transduction"]],
"micturition":[["noun.process","verb.body:micturate","verb.body:urinate"],["micturition","urination","elimination"]],
"mineral extraction":[["noun.process","verb.change:beneficiate"],["mineral extraction","mineral processing","mineral dressing","ore processing","ore dressing","beneficiation","extraction"]],
"mitosis":[["noun.process"],["mitosis","cell division"]],
"molt":[["noun.process","verb.body:molt","verb.body:molt","verb.body:moult","verb.body:moult"],["molt","molting","moult","moulting","ecdysis","shedding"]],
"monadic operation":[["noun.process"],["monadic operation","unary operation","operation"]],
"monogenesis":[["noun.process","verb.creation:sporulate"],["monogenesis","sporulation","asexual reproduction"]],
"morphallaxis":[["noun.process"],["morphallaxis","regeneration"]],
"morphogenesis":[["noun.process","noun.Tops:organism"],["morphogenesis","growth"]],
"multiplex operation":[["noun.process"],["multiplex operation","operation"]],
"multiprocessing":[["noun.process"],["multiprocessing","parallel processing","data processing"]],
"multiprogramming":[["noun.process"],["multiprogramming","concurrent execution","execution"]],
"myelinization":[["noun.process"],["myelinization","myelinisation","growth"]],
"natural childbirth":[["noun.process"],["natural childbirth","childbirth"]],
"natural process":[["noun.process","adj.all:active10","adj.all:active4","noun.Tops:process"],["natural process","natural action","action","activity1"]],
"nazification":[["noun.process"],["Nazification","social process"]],
"necrolysis":[["noun.process"],["necrolysis","lysis"]],
"negative feedback":[["noun.process"],["negative feedback","feedback"]],
"neoplasia":[["noun.process"],["neoplasia","pathologic process"]],
"neurogenesis":[["noun.process"],["neurogenesis","growth"]],
"new line":[["noun.process"],["new line","printing operation"]],
"nitrification":[["noun.process","verb.change:nitrify2","verb.change:nitrify","noun.Tops:plant","noun.process","verb.change:nitrify1"],["nitrification","oxidation","nitrification1","chemical process"]],
"nitrogen cycle":[["noun.process"],["nitrogen cycle","organic process"]],
"nitrogen fixation":[["noun.process"],["nitrogen fixation","organic process"]],
"nocturia":[["noun.process"],["nocturia","nycturia","micturition"]],
"nocturnal emission":[["noun.process","noun.cognition:wet dream"],["nocturnal emission","ejaculation"]],
"nondevelopment":[["noun.process"],["nondevelopment","development1","organic process"]],
"nondisjunction":[["noun.process"],["nondisjunction","meiosis"]],
"nuclear reaction":[["noun.process","noun.cognition:physics"],["nuclear reaction","natural process"]],
"nucleosynthesis":[["noun.process","noun.cognition:astronomy"],["nucleosynthesis","synthesis"]],
"obsolescence":[["noun.process","adj.all:noncurrent^obsolescent","verb.change:obsolesce"],["obsolescence","degeneration"]],
"oligomenorrhea":[["noun.process"],["oligomenorrhea","menstruation"]],
"oogenesis":[["noun.process"],["oogenesis","gametogenesis"]],
"opacification":[["noun.process","verb.change:opacify"],["opacification","natural process"]],
"open-hearth process":[["noun.process"],["open-hearth process","steel production"]],
"opsonization":[["noun.process","verb.change:opsonize","verb.change:opsonize"],["opsonization","opsonisation","bodily process"]],
"organic process":[["noun.process","noun.Tops:process"],["organic process","biological process"]],
"organification":[["noun.process"],["organification","organic process"]],
"orogeny":[["noun.process"],["orogeny","geological process"]],
"osmosis":[["noun.process","adj.pert:osmotic","noun.act:dialysis","noun.cognition:biology","noun.cognition:chemistry"],["osmosis","diffusion"]],
"reverse osmosis":[["noun.process","noun.cognition:chemistry"],["reverse osmosis","osmosis"]],
"osteolysis":[["noun.process"],["osteolysis","lysis"]],
"outflow":[["noun.process","adj.all:outgoing^effluent"],["outflow","inflow","effluence","efflux","influx","flow"]],
"overactivity":[["noun.process","adj.all:active1^overactive"],["overactivity","bodily process"]],
"overflow incontinence":[["noun.process"],["overflow incontinence","enuresis"]],
"overheating":[["noun.process","verb.change:overheat1","verb.change:overheat"],["overheating","heating"]],
"ovulation":[["noun.process","verb.body:ovulate"],["ovulation","anovulation","organic process"]],
"oxidation":[["noun.process","verb.change:oxidate1","verb.change:oxidate","verb.change:oxidize1","verb.change:oxidize","verb.change:oxidise1","verb.change:oxidise"],["oxidation","oxidization","oxidisation","chemical reaction"]],
"oxidation-reduction":[["noun.process"],["oxidation-reduction","oxidoreduction","redox","chemical reaction"]],
"oxidative phosphorylation":[["noun.process"],["oxidative phosphorylation","organic process","Krebs cycle"]],
"oxygenation":[["noun.process","verb.change:oxygenate"],["oxygenation","natural process"]],
"pachytene":[["noun.process","noun.time:phase"],["pachytene","prophase2"]],
"pair production":[["noun.process"],["pair production","pair creation","pair formation","natural process"]],
"palingenesis":[["noun.process","adj.pert:palingenetic","verb.creation:recapitulate1"],["palingenesis","cenogenesis","recapitulation","development1"]],
"paper chromatography":[["noun.process"],["paper chromatography","chromatography"]],
"paper electrophoresis":[["noun.process"],["paper electrophoresis","carrier electrophoresis","electrophoresis"]],
"parallel operation":[["noun.process"],["parallel operation","serial operation","simultaneous operation","operation"]],
"parthenocarpy":[["noun.process","noun.cognition:botany"],["parthenocarpy","apomixis"]],
"parthenogenesis":[["noun.process","adj.all:asexual^parthenogenetic","noun.process"],["parthenogenesis","parthenogeny","apomixis","parthenogenesis1","parthenogeny1","virgin birth","asexual reproduction"]],
"parturition":[["noun.process","verb.body:birth"],["parturition","birth","giving birth","birthing","organic process","reproduction"]],
"passive transport":[["noun.process"],["passive transport","transport"]],
"pathogenesis":[["noun.process"],["pathogenesis","pathologic process"]],
"pathologic process":[["noun.process"],["pathologic process","pathological process","organic process"]],
"peace process":[["noun.process"],["peace process","social process"]],
"peeing":[["noun.process","verb.body:pee","verb.body:pee","verb.body:piss","verb.body:piss","noun.communication:obscenity"],["peeing","pee","pissing","piss","micturition"]],
"peptization":[["noun.process","verb.change:peptize","verb.change:peptise"],["peptization","peptisation","chemical process"]],
"perennation":[["noun.process","verb.stative:perennate","noun.Tops:plant"],["perennation","organic process"]],
"peristalsis":[["noun.process"],["peristalsis","anastalsis","vermiculation","bodily process"]],
"permeation":[["noun.process","verb.contact:permeate2","verb.contact:permeate1","verb.contact:permeate","verb.contact:pervade","verb.change:suffuse","verb.change:suffuse1"],["permeation","pervasion","suffusion","diffusion"]],
"phagocytosis":[["noun.process"],["phagocytosis","bodily process"]],
"phase change":[["noun.process"],["phase change","phase transition","state change","physical change","natural process"]],
"phase of cell division":[["noun.process","noun.time:phase"],["phase of cell division"]],
"photochemical reaction":[["noun.process"],["photochemical reaction","chemical reaction"]],
"photoelectric emission":[["noun.process"],["photoelectric emission","emission"]],
"photosynthesis":[["noun.process","adj.pert:photosynthetic","noun.Tops:plant"],["photosynthesis","chemical process"]],
"pinocytosis":[["noun.process"],["pinocytosis","bodily process"]],
"pitting":[["noun.process","verb.contact:pit","verb.contact:indent"],["pitting","roughness","indentation","corrosion"]],
"planation":[["noun.process","verb.contact:plane3"],["planation","erosion"]],
"plastination":[["noun.process","verb.possession:plastinate"],["plastination","preservation"]],
"polymerization":[["noun.process","verb.change:polymerize2","verb.change:polymerize","verb.change:polymerise2","verb.change:polymerise"],["polymerization","polymerisation","chemical process"]],
"population growth":[["noun.process"],["population growth","increase"]],
"positive feedback":[["noun.process","verb.change:regenerate6"],["positive feedback","regeneration1","feedback"]],
"potentiation":[["noun.process","verb.change:potentiate","noun.cognition:medicine"],["potentiation","synergy"]],
"powder photography":[["noun.process"],["powder photography","powder method","powder technique","photography"]],
"precession of the equinoxes":[["noun.process"],["precession of the equinoxes","natural process"]],
"prechlorination":[["noun.process"],["prechlorination","chlorination"]],
"precocious dentition":[["noun.process"],["precocious dentition","teething"]],
"premature ejaculation":[["noun.process"],["premature ejaculation","ejaculation"]],
"printing operation":[["noun.process"],["printing operation","operation"]],
"priority processing":[["noun.process"],["priority processing","data processing"]],
"processing":[["noun.process","verb.social:process1","verb.change:process","noun.Tops:process"],["processing"]],
"professionalization":[["noun.process","verb.change:professionalize1","verb.change:professionalize"],["professionalization","professionalisation","social process"]],
"proliferation":[["noun.process","verb.change:proliferate1","verb.change:proliferate","noun.process","noun.act:nonproliferation","noun.act:non-proliferation","verb.change:proliferate1","verb.change:proliferate"],["proliferation","growth","proliferation1","increase"]],
"prophase":[["noun.process","noun.process"],["prophase1","phase of cell division","mitosis","prophase2","phase of cell division","meiosis"]],
"proteolysis":[["noun.process","adj.pert:proteolytic"],["proteolysis","chemical process"]],
"psilosis":[["noun.process"],["psilosis","epilation","bodily process"]],
"psychoanalytic process":[["noun.process"],["psychoanalytic process","human process"]],
"psychogenesis":[["noun.process","noun.process"],["psychogenesis","growth","psychogenesis1","growth"]],
"psychomotor development":[["noun.process"],["psychomotor development","growth"]],
"psychosexual development":[["noun.process","noun.act:psychoanalysis"],["psychosexual development","growth"]],
"ptyalism":[["noun.process","verb.body:ptyalize"],["ptyalism","salivation"]],
"pullulation":[["noun.process","verb.change:pullulate1","noun.process","verb.change:pullulate"],["pullulation","increase","pullulation1","gemmation","asexual reproduction"]],
"pyrochemical process":[["noun.process","adj.pert:pyrochemical"],["pyrochemical process","pyrochemistry","chemical process"]],
"quadrupling":[["noun.process","verb.change:quadruple"],["quadrupling","multiplication"]],
"quellung":[["noun.process"],["quellung","quellung reaction","organic process"]],
"quintupling":[["noun.process","verb.change:quintuple"],["quintupling","multiplication"]],
"radiant heating":[["noun.process"],["radiant heating","heating"]],
"radiolysis":[["noun.process"],["radiolysis","lysis"]],
"rain-wash":[["noun.process"],["rain-wash","washout"]],
"random walk":[["noun.process"],["random walk","stochastic process"]],
"reaction formation":[["noun.process","noun.cognition:psychiatry"],["reaction formation","defense mechanism"]],
"read method of childbirth":[["noun.process"],["Read method of childbirth","Read method","natural childbirth"]],
"real-time processing":[["noun.process"],["real-time processing","real-time operation","data processing"]],
"redeposition":[["noun.process","verb.possession:redeposit","verb.contact:redeposit"],["redeposition","deposition"]],
"reducing":[["noun.process","verb.body:reduce"],["reducing1","loss"]],
"refilling":[["noun.process","verb.change:refill","verb.change:replenish"],["refilling","replenishment","replacement","renewal","filling"]],
"refining":[["noun.process","verb.change:refine","verb.change:refine2","verb.change:refine","verb.change:purify"],["refining","refinement","purification","processing"]],
"reflation":[["noun.process","verb.change:reflate5","verb.change:reflate4"],["reflation","inflation"]],
"resorption":[["noun.process","verb.contact:resorb","verb.contact:reabsorb"],["resorption","reabsorption","organic process"]],
"stovepiping":[["noun.process"],["stovepiping","retrieval"]],
"reuptake":[["noun.process"],["reuptake","re-uptake","uptake"]],
"reversible process":[["noun.process","noun.Tops:process"],["reversible process","irreversible process"]],
"ripening":[["noun.process"],["ripening1","aging1","ageing1","organic process"]],
"rooting":[["noun.process","verb.change:root1","verb.change:root"],["rooting","growth"]],
"salivation":[["noun.process","verb.body:salivate"],["salivation","secretion"]],
"saponification":[["noun.process","verb.change:saponify1","verb.change:saponify"],["saponification","chemical reaction"]],
"schizogony":[["noun.process"],["schizogony","fission1"]],
"secondary emission":[["noun.process"],["secondary emission","emission"]],
"serial operation":[["noun.process"],["serial operation","parallel operation","sequential operation","consecutive operation","operation"]],
"serial processing":[["noun.process"],["serial processing","data processing"]],
"sexual reproduction":[["noun.process"],["sexual reproduction","amphimixis","reproduction"]],
"shaping":[["noun.process","verb.cognition:shape","verb.stative:define3","noun.Tops:process"],["shaping","defining"]],
"shedding":[["noun.process","verb.body:shed","verb.body:slough"],["shedding","sloughing","organic process"]],
"shit":[["noun.process","verb.body:shit","verb.communication:shit9"],["shit","dump","defecation"]],
"sinking spell":[["noun.process"],["sinking spell","decline2"]],
"social process":[["noun.process"],["social process","human process"]],
"softening":[["noun.process","verb.change:soften1","verb.change:soften"],["softening","natural process"]],
"soil erosion":[["noun.process"],["soil erosion","erosion"]],
"solvation":[["noun.process","verb.change:solvate1","verb.change:solvate"],["solvation","association"]],
"solvay process":[["noun.process"],["Solvay process","industrial process"]],
"sorption":[["noun.process","verb.contact:sorb"],["sorption","natural process"]],
"souring":[["noun.process","verb.change:sour1"],["souring","spoilage"]],
"spallation":[["noun.process","noun.cognition:physics"],["spallation","nuclear reaction"]],
"speciation":[["noun.process","verb.change:speciate"],["speciation","evolution"]],
"spermatogenesis":[["noun.process"],["spermatogenesis","gametogenesis"]],
"spontaneous combustion":[["noun.process"],["spontaneous combustion","ignition"]],
"stagflation":[["noun.process","adj.pert:stagflationary"],["stagflation","inflation"]],
"stalinization":[["noun.process","verb.change:stalinize","verb.change:stalinise"],["Stalinization","Stalinisation","social process"]],
"stationary stochastic process":[["noun.process"],["stationary stochastic process","stochastic process"]],
"steel production":[["noun.process","noun.act:production"],["steel production"]],
"stochastic process":[["noun.process","noun.cognition:model"],["stochastic process"]],
"stress incontinence":[["noun.process"],["stress incontinence","enuresis"]],
"subduction":[["noun.process"],["subduction","geological process"]],
"synapsis":[["noun.process"],["synapsis","organic process","leptotene"]],
"synchronous operation":[["noun.process"],["synchronous operation","asynchronous operation","operation"]],
"syneresis":[["noun.process","noun.process"],["syneresis","synaeresis","chemical process","syneresis1","synaeresis1","linguistic process"]],
"synergy":[["noun.process","adj.all:cooperative^synergetic","adj.all:cooperative^synergistic","adj.all:synergistic","noun.artifact:synergist"],["synergy","synergism","natural process"]],
"synizesis":[["noun.process"],["synizesis","synezesis","organic process","prophase2"]],
"teething":[["noun.process","verb.body:teethe"],["teething","dentition","odontiasis","growth"]],
"telophase":[["noun.process","noun.process"],["telophase1","phase of cell division","mitosis","telophase2","phase of cell division","meiosis"]],
"temperature change":[["noun.process"],["temperature change","natural process"]],
"teratogenesis":[["noun.process"],["teratogenesis","growth"]],
"thermionic emission":[["noun.process"],["thermionic emission","thermal emission","emission"]],
"thermocoagulation":[["noun.process"],["thermocoagulation","curdling"]],
"thermonuclear reaction":[["noun.process"],["thermonuclear reaction","fusion"]],
"threshold operation":[["noun.process"],["threshold operation","operation"]],
"thrombolysis":[["noun.process"],["thrombolysis","lysis"]],
"top fermentation":[["noun.process"],["top fermentation","zymosis1"]],
"transamination":[["noun.process","verb.change:transaminate","noun.process"],["transamination","chemical process","transamination1","chemical process"]],
"transduction":[["noun.process","verb.change:transduce","noun.process","noun.cognition:genetics"],["transduction","natural process","transduction1","organic process"]],
"protein folding":[["noun.process"],["protein folding","folding","organic process"]],
"translocation":[["noun.process","verb.possession:translocate1","noun.cognition:genetics","noun.process"],["translocation","organic process","translocation1","organic process"]],
"transpiration":[["noun.process","verb.change:transpire2","noun.process","verb.motion:transpire","noun.process","verb.body:transpire"],["transpiration","organic process","transpiration1","natural process","transpiration2","bodily process"]],
"tripling":[["noun.process","verb.change:triple"],["tripling","multiplication"]],
"tumefaction":[["noun.process","verb.change:tumefy1","verb.change:tumefy"],["tumefaction","organic process"]],
"ulceration":[["noun.process","verb.change:ulcerate"],["ulceration","organic process"]],
"ultracentrifugation":[["noun.process","verb.motion:ultracentrifuge"],["ultracentrifugation","centrifugation"]],
"unfolding":[["noun.process","verb.change:unfold"],["unfolding","flowering1","evolution1"]],
"uptake":[["noun.process"],["uptake","human process"]],
"urge incontinence":[["noun.process"],["urge incontinence","enuresis"]],
"urochesia":[["noun.process"],["urochesia","urochezia","defecation"]],
"vascularization":[["noun.process","verb.change:vascularize1","verb.change:vascularize"],["vascularization","vascularisation","organic process"]],
"vesiculation":[["noun.process","verb.change:vesiculate1","verb.change:vesiculate","verb.change:vesicate"],["vesiculation","vesication","blistering","organic process"]],
"video digitizing":[["noun.process"],["video digitizing","photography"]],
"vinification":[["noun.process","verb.change:vinify"],["vinification","zymosis1"]],
"vulcanization":[["noun.process","verb.change:vulcanize1","verb.change:vulcanize","verb.change:vulcanise1","verb.change:vulcanise"],["vulcanization","vulcanisation","processing"]],
"westernization":[["noun.process"],["Westernization","Westernisation","assimilation2"]],
"word processing":[["noun.process","noun.communication:printing"],["word processing","data processing"]],
"zygotene":[["noun.process","noun.time:phase"],["zygotene","prophase2"]],
"zymosis":[["noun.process","adj.pert:zymotic","noun.cognition:medicine","noun.process","adj.pert:zymotic1","adj.pert:zymolytic","verb.change:ferment1","verb.change:ferment","verb.change:ferment1","verb.change:ferment1","verb.change:ferment"],["zymosis","infection","zymosis1","zymolysis","fermentation","fermenting","ferment","chemical process"]]
}