var mysql_wn_data_verb_emotion = {
"stew":[["verb.emotion","noun.feeling:grudge"],["stew","grudge1","resent","frames:2"]],
"puff":[["verb.emotion","verb.consumption","noun.act:puff","noun.act:puffing2"],["puff","elate","frames:11","puff1","whiff2","smoke"]],
"rack":[["verb.emotion","verb.social","noun.artifact:rack1","noun.artifact","verb.body:rack","verb.emotion:rack1","verb.motion"],["rack","strain","rack1","work1","rack2","wheel2","instrument of torture","rack3","fly","frames:2"]],
"cling":[["verb.emotion","verb.contact"],["cling","cling2","hang7","grasp","frames:8","11"]],
"break":[["verb.emotion","verb.stative","verb.stative","noun.event:break","verb.change:change2","verb.contact","verb.social","verb.communication:make14","verb.stative"],["break","burst","erupt","express emotion","break14","emerge","break5","break13","break9","break9","ruin","frames:11","break15","end"]],
"distress":[["verb.emotion","noun.feeling:distress2","noun.feeling","verb.emotion:distress","verb.perception:hurt","verb.body:hurt1","verb.emotion:suffer","noun.state"],["distress","upset","frames:9","distress2","hurt2","suffering2","pain","distress1","adversity"]],
"impress":[["verb.emotion","adj.all:impressive","verb.change"],["impress","strike","frames:9","impress8","yarn-dye","dye"]],
"capture":[["verb.emotion","noun.state:trance","noun.person:catch","noun.person:captive2","noun.state:captivation","noun.feeling:captivation","noun.attribute:beguilement","noun.person:beguiler","noun.person:charmer1","noun.attribute:charm","noun.person:charmer","noun.feeling:fascination","noun.attribute:bewitchery","noun.feeling:entrancement","noun.feeling:enchantment","noun.act","verb.possession","noun.process:capture","verb.change:change1"],["capture","enamour","trance","catch5","becharm","enamor","captivate","beguile","charm","fascinate1","bewitch","entrance","enchant1","attract","frames:10","capture2","chess move","capture1"]],
"crush":[["verb.emotion","verb.change"],["crush","smash","humiliate","frames:9","crush8","break","frames:1"]],
"sting":[["verb.emotion","noun.state:sting2","noun.communication:stinger","noun.state:stinging"],["sting","hurt","frames:9"]],
"tease":[["verb.emotion","noun.act:tease","noun.person:tease","noun.person:teaser","noun.person:badgerer","noun.person:pesterer","verb.communication","noun.person:tease1","noun.person:teaser","verb.emotion","noun.person:tease1","verb.contact","*verb.change:change surface","verb.contact"],["tease","badger","pester","bug","beleaguer","torment1","tease9","make fun","frames:9","tease1","arouse1","*disappoint","*manipulate","tease2","brush1","tease3","shred"]],
"pride":[["verb.emotion","noun.feeling:pride1","adj.all:felicitous^congratulatory","noun.communication:congratulation1","noun.feeling","verb.emotion:pride"],["pride","plume","congratulate","feel","pride1","satisfaction"]],
"envy":[["verb.emotion","noun.feeling:envy","noun.act:envy","verb.emotion","noun.feeling:envy"],["envy","frames:9begrudge1","desire","envy1","frames:14admire"]],
"lock":[["verb.emotion","noun.artifact","noun.artifact","verb.creation:lock4","verb.motion:lock4","noun.artifact","verb.motion","noun.artifact:lock2","noun.artifact:lockage","noun.act:lockage"],["lock","overwhelm","lock1","ignition lock","restraint","ignition switch","lock2","lock chamber","enclosure","canal","lock3","mechanism","firearm","lock4","pass","frames:2"]],
"bridle":[["verb.emotion"],["bridle","anger1"]],
"shock":[["verb.emotion","noun.feeling:shock1","noun.event:shock1","noun.communication:shocker","verb.emotion","noun.feeling:shock1","noun.person:shocker","adj.all:unwholesome^offensive","adj.all:offensive4","adj.all:offensive1","noun.act:scandalization","noun.event:scandal","noun.communication:scandal","noun.act:scandalisation","noun.event:scandal","noun.communication:scandal","noun.event:outrage","noun.act:outrage","noun.feeling:outrage"],["shock","horrify1","frames:9","shock2","offend2","scandalize","scandalise","appal","appall","outrage1","disgust","frames:10"]],
"reverence":[["verb.emotion","noun.cognition:reverence","noun.feeling:reverence","noun.feeling:fear2","adj.all:pious^reverent","adj.all:reverent","noun.feeling:reverence","noun.feeling:veneration","noun.person:venerator","verb.cognition:respect"],["reverence","fear1","revere","venerate","frames:8"]],
"bore":[["verb.emotion","noun.person:bore"],["bore","interest","tire1","frames:9"]],
"brace":[["verb.emotion","noun.attribute:poise","verb.change:prepare","verb.contact","noun.artifact:brace4","noun.act:stabilization1","verb.change:strengthen1","noun.artifact","noun.artifact","verb.contact:brace","verb.contact:brace1","noun.artifact","verb.contact:suspend","noun.communication:plural","noun.artifact"],["brace","poise","brace1","steady","stabilize2","stabilise2","frames:8","11","brace3","braces2","orthodontic braces","dental appliance","brace4","support","strengthener","brace5","suspender","gallus","man's clothing","brace6","rope"]],
"cotton":[["verb.emotion","noun.substance","adj.all:soft1^cottony","noun.artifact:padding","noun.artifact:cotton"],["cotton","like5","cotton1","cotton fiber","cotton wool1","plant fiber"]],
"grizzle":[["verb.emotion","noun.state:stew","verb.stative:sulk"],["grizzle","brood","stew1","frames:2"]],
"jar":[["verb.emotion","verb.contact","noun.quantity:jar","noun.artifact:jar","verb.motion"],["jar","affect","frames:9","jar10","place","jar1","shake up","bump around","move1","frames:9"]],
"pique":[["verb.emotion","noun.feeling:pique","adj.all:offensive2","noun.feeling:offence"],["pique","offend1","resent",">anger","frames:9"]],
"steel":[["verb.emotion","noun.attribute:nerve"],["steel","nerve","brace"]],
"ambition":[["verb.emotion","noun.feeling:ambition","noun.attribute:ambition"],["ambition","desire"]],
"hope":[["verb.emotion","noun.attribute:hope","noun.person:hope","noun.cognition:hope","noun.feeling:hope","noun.feeling:hope1","noun.person:hoper","noun.person"],["hope","despair","desire","frames:2","22","Hope1","Bob Hope","Leslie Townes Hope","comedian"]],
"desire":[["verb.emotion","noun.feeling:desire","noun.state:desire","noun.attribute:desire","noun.person:wanter","noun.feeling:want","verb.emotion","noun.state:desire","noun.attribute:desire","verb.communication:request1"],["desire","want","frames:24frames:8","26","desire1"]],
"chill":[["verb.emotion","noun.feeling:chill","noun.state","verb.body:shiver"],["chill","dispirit","frames:9","10","chill1","shivering","symptom"]],
"interest":[["verb.emotion","noun.attribute:interest2","noun.cognition:interest","noun.possession","noun.group:law"],["interest","bore","arouse","frames:9","interest3","stake2","share"]],
"hamstring":[["verb.emotion"],["hamstring","frustrate","frames:8"]],
"fancy":[["verb.emotion","noun.feeling:fancy","noun.person:fancier"],["fancy","go for","take to","like5","*desire","frames:8"]],
"pain":[["verb.emotion","noun.cognition:pain1","noun.feeling:pain","noun.state:pain","noun.state:anguish","noun.feeling:anguish2","noun.feeling:hurt1"],["pain","anguish","hurt1","suffer",">upset1"]],
"wish":[["verb.emotion","noun.feeling:wish","noun.communication:wish","noun.feeling:wishing","verb.emotion","noun.feeling:wish","noun.communication:wish","verb.emotion","noun.feeling:wish"],["wish","desire","frames:8","wish1","begrudge","wish well","frames:9desire","wish2","care","like1","desire"]],
"content":[["verb.emotion","noun.state:content"],["content","discontent","satisfy","frames:9"]],
"love":[["verb.emotion","adj.all:loveable","adj.all:lovable","noun.person:love","noun.cognition:love","noun.feeling:love","noun.person:lover1","noun.person:lover","verb.emotion","adj.all:loveable","adj.all:lovable","noun.person:love","noun.cognition:love","noun.feeling:love","noun.person:lover","verb.emotion","noun.cognition:love","noun.feeling:love","noun.person:lover1","noun.person:lover","noun.feeling:enjoyment","noun.act:enjoyment","noun.person:enjoyer"],["love","hate","frames:8","love1","love","love2","enjoy1","like5","frames:8"]],
"romance":[["verb.emotion","noun.communication:romance2","noun.state:romance"],["romance","love1","frames:8"]],
"dissolve":[["verb.emotion","verb.change","verb.change","verb.change","noun.process:dissolution","noun.act:dissolution1","noun.act:dissolution","verb.change","noun.phenomenon:thaw","noun.process:thaw","noun.process:thawing","adj.all:soluble1^meltable","noun.process:melt","noun.person:melter","noun.process:melting","verb.change","noun.process:dissolution1","noun.substance:dissolvent","noun.substance:dissolver","noun.process:dissolving","noun.substance:resolvent","verb.change","noun.communication:dissolve","noun.event:fadeout","verb.change","verb.emotion"],["dissolve","break down","dissolve9","dismiss9","change1","dissolve2","break up1","end1","dissolve8","break up9","dissolve9","$terminate1","frames:8","dissolve7","thaw","unfreeze","unthaw","dethaw","melt","liquefy","frames:1","8","dissolve1","resolve7","break up3","dissolve",">change integrity","frames:8","dissolve3","fade out","fade away","change state","dissolve11","dissolve3","$change1","frames:8","dissolve4","dissolve","$upset1"]],
"lament":[["verb.emotion","noun.communication:lament","noun.communication:lament1","noun.communication:lament2","noun.communication:lamentation","noun.act:lamentation","noun.person:lamenter","noun.communication:keen"],["lament","keen","grieve","*express emotion"]],
"fuss":[["verb.emotion","noun.state:fuss","noun.state:fret"],["fuss","niggle","fret3","worry","frames:2"]],
"sizzle":[["verb.emotion"],["sizzle","seethe"]],
"zap":[["verb.emotion"],["zap","affect","frames:9"]],
"affect":[["verb.emotion","adj.all:emotional^affective","noun.feeling:affect","adj.all:impressible","adj.all:effective^impressive","adj.all:impressive","verb.perception:strike"],["affect","impress1","move","strike","$feel"]],
"dislike":[["verb.emotion","noun.feeling:dislike","verb.cognition:disapprove"],["dislike","like5","*frames:8","9"]],
"shame":[["verb.emotion","noun.feeling:shame","verb.social","noun.state:shame","noun.feeling:shame"],["shame","elicit","frames:9","shame1","compel"]],
"awe":[["verb.emotion","noun.feeling:awe2"],["awe","frighten"]],
"anger":[["verb.emotion","noun.state:anger","noun.feeling:anger","noun.act:anger","verb.emotion","noun.state:anger","noun.feeling:anger","noun.act:anger"],["anger","anger1",">arouse","frames:10","anger1","see red","feel"]],
"fear":[["verb.emotion","noun.feeling:fear","noun.feeling:dread","verb.emotion","verb.communication:regret2","verb.emotion","noun.feeling:fear1","verb.emotion","noun.feeling:fear1"],["fear","dread","frames:8","9","fear2","fear13","fear3","worry","frames:26"]],
"panic":[["verb.emotion","noun.feeling:panic","verb.emotion","noun.feeling:panic","noun.state:panic1"],["panic","fear","frames:2","panic1","panic",">terrify","frames:9"]],
"worry":[["verb.emotion","noun.attribute:worriment","noun.person:worrier","noun.feeling:worry","noun.cognition:worry","verb.emotion","noun.cognition:worry","noun.act:worrying","noun.cognition:vexation","verb.emotion","noun.feeling:worry","noun.cognition:worry","noun.feeling:care1","noun.feeling:care","verb.cognition:mind2"],["worry","worry1","$frames:2","22","worry1","reassure","vex2","worry",">perturb","frames:9","worry12","care12"]],
"despair":[["verb.emotion","noun.feeling:despair","noun.state:despair","noun.state:desperation1","noun.person:desperate"],["despair","hope","frames:2"]],
"hate":[["verb.emotion","noun.person:hater","noun.feeling:hate","noun.feeling:detestation"],["hate","love","detest","dislike","frames:8"]],
"grudge":[["verb.emotion"],["grudge","resent"]],
"peeve":[["verb.emotion"],["peeve","annoy","frames:9"]],
"gall":[["verb.emotion","noun.feeling:gall"],["gall","irk","anger","frames:10"]],
"dither":[["verb.emotion","noun.state:dither","noun.state:flap","noun.state:pother","verb.emotion"],["dither","flap","pother","fuss","frames:2","dither1","fret","frames:2"]],
"ferment":[["verb.emotion","noun.state:fermentation","verb.emotion","noun.state:fermentation"],["ferment","inflame","frames:9","10","8","ferment1","seethe","frames:1"]],
"break down":[["verb.emotion","noun.state:breakdown1","verb.body:behave","verb.contact","verb.motion:break down"],["break down","lose it","snap","break down1",">break1","frames:8"]],
"inflame":[["verb.emotion","adj.all:provocative^inflammatory","noun.act:inflammation","noun.act:inflaming","noun.attribute:heat2","verb.body","adj.all:unhealthy^inflammatory","noun.state:inflammation","verb.change:worsen1"],["inflame","stir up","wake","ignite","heat","fire up","arouse","frames:8","inflame1","frames:11"]],
"hurt":[["verb.emotion","adj.all:offensive2","noun.act:offence2","noun.attribute:spite","noun.feeling:spite"],["hurt","wound","injure","bruise","offend","spite","arouse","frames:10"]],
"suffer":[["verb.emotion","noun.person:sufferer1","noun.state:suffering1","noun.feeling:suffering2","frames:8verb.cognition:suffer","verb.perception","verb.body","verb.stative:be3","verb.perception","verb.stative"],["suffer","$feel","frames:2","suffer1","enjoy","endure","experience1","suffer3","frames:2","suffer2","meet","experience1","suffer4","tend1"]],
"salivate":[["verb.emotion"],["salivate","drool","covet"]],
"knock out":[["verb.emotion","verb.change","verb.change"],["knock out","overwhelm","frames:10","knock out2","empty1","knock out1","eliminate1","frames:8"]],
"disturb":[["verb.emotion","noun.state:disturbance2","noun.act:upset1","noun.state:upset","noun.feeling:trouble3","noun.event:trouble"],["disturb","upset","trouble1","affect"]],
"afflict":[["verb.emotion","adj.all:unpleasant^afflictive","noun.state:affliction2","noun.event:affliction"],["afflict","upset1"]],
"benight":[["verb.emotion"],["benight","overwhelm"]],
"appreciate":[["verb.emotion","adj.all:grateful^appreciative","verb.communication:acknowledge1"],["appreciate"]],
"seethe":[["verb.emotion","verb.stative:be3","verb.change"],["seethe","boil","frames:2","seethe3","foam5"]],
"smolder":[["verb.emotion"],["smolder","smoulder","feel"]],
"dehumanize":[["verb.emotion","noun.act:dehumanization","noun.act:dehumanisation"],["dehumanize","humanize","dehumanise","degrade"]],
"electrify":[["verb.emotion","noun.feeling:electricity","noun.act:electrification","verb.change","noun.phenomenon:electricity1","noun.phenomenon:electricity","noun.act:electrification1","noun.cognition:physics"],["electrify","charge5","frames:9","electrify1","fill1","frames:8"]],
"nag":[["verb.emotion"],["nag","worry1"]],
"confuse":[["verb.emotion","noun.feeling:confusion","noun.feeling:disconcertment","noun.feeling:disconcertion","verb.cognition:confuse3"],["confuse","flurry","disconcert2","put off2","$embarrass","frames:9"]],
"discountenance":[["verb.emotion"],["discountenance","shame","frames:9"]],
"draw out":[["verb.emotion"],["draw out","encourage","frames:9"]],
"overwhelm":[["verb.emotion"],["overwhelm","overpower","sweep over","whelm","overcome","overtake","arouse"]],
"encourage":[["verb.emotion","noun.feeling:encouragement"],["encourage","discourage","hope",">inspire","frames:9"]],
"besiege":[["verb.emotion"],["besiege","distress"]],
"tempt":[["verb.emotion","adj.all:susceptible^temptable","noun.cognition:temptation","noun.person:tempter","noun.attribute:invitation"],["tempt","invite","stimulate"]],
"stultify":[["verb.emotion","noun.communication:stultification","verb.cognition:demonstrate","noun.group:law"],["stultify"]],
"crack up":[["verb.emotion","noun.state:crack-up","noun.state:collapse1","verb.body:suffer1"],["crack up","crack","crock up","break up4","collapse"]],
"enthuse":[["verb.emotion"],["enthuse","excite2","frames:9"]],
"reassure":[["verb.emotion","noun.act:reassurance"],["reassure","worry1","assure","calm","frames:9"]],
"beckon":[["verb.emotion","verb.communication"],["beckon","attract","beckon1","summon5","frames:2"]],
"disarm":[["verb.emotion","verb.communication:win over","verb.competition","noun.act:disarmament","noun.person:disarmer","noun.act:disarming","verb.possession:deprive1"],["disarm","frames:9","disarm1","unarm"]],
"harass":[["verb.emotion","noun.person:harasser1","noun.act:harassment","noun.event:hassle","noun.person:harrier","noun.cognition:plague","noun.act:molestation","adj.all:provocative","noun.act:provocation","noun.person:provoker"],["harass","hassle","harry","chivy","chivvy","chevy","chevvy","beset","plague","molest","provoke1","annoy","frames:10"]],
"repel":[["verb.emotion","adj.all:ugly^repulsive","adj.all:offensive1^repulsive","adj.all:unpleasant^repellant","adj.all:offensive1^repellant","adj.all:offensive1^repellent","noun.substance:repellent","noun.substance:repellant"],["repel","attract","repulse","displease","frames:9"]],
"eat":[["verb.emotion"],["eat","eat on","worry1"]],
"wean":[["verb.emotion"],["wean","estrange"]],
"devour":[["verb.emotion","verb.consumption","noun.person:devourer"],["devour","enjoy","devour1","demolish","down1","consume3","go through","eat up"]],
"engrave":[["verb.emotion"],["engrave","impress1"]],
"attract":[["verb.emotion","adj.all:attractive1","noun.communication:attraction","noun.cognition:attraction","noun.attribute:attraction","noun.cognition:attractor","noun.attribute:appeal"],["attract","repel","appeal","frames:4please","*frames:10"]],
"ruffle":[["verb.emotion","verb.contact","verb.emotion"],["ruffle","vex","frames:8","ruffle2","ruffle up","rumple","mess up1","disarrange","frames:8","ruffle1","fluster","frames:8","9","10"]],
"smite":[["verb.emotion"],["smite","affect","frames:9"]],
"enshrine":[["verb.emotion"],["enshrine","saint","venerate"]],
"lacerate":[["verb.emotion","noun.act:laceration"],["lacerate","hurt","frames:10"]],
"inspire":[["verb.emotion","noun.act:invigoration","noun.state:exaltation"],["inspire","animate","invigorate","enliven","exalt","stimulate","frames:9"]],
"pacify":[["verb.emotion","noun.act:pacification","noun.state:peace1","noun.feeling:peace","noun.artifact:pacifier","adj.all:conciliative","noun.state:conciliation","noun.act:conciliation","noun.person:conciliator","adj.all:placable^appeasable","noun.state:mollification","noun.act:mollification","adj.all:conciliatory^placative","adj.all:conciliatory^placatory","noun.act:placation"],["pacify","lenify","conciliate","assuage","appease","mollify","placate","gentle","gruntle","calm","frames:10","9"]],
"infatuate":[["verb.emotion","noun.feeling:infatuation2","noun.feeling:infatuation","noun.cognition:infatuation"],["infatuate","arouse","frames:10"]],
"bubble over":[["verb.emotion"],["bubble over","overflow","spill over","seethe"]],
"hype up":[["verb.emotion"],["hype up","psych up","agitate","frames:9"]],
"calm":[["verb.emotion","noun.attribute:quiet","noun.artifact:tranquilizer","noun.time:lull","noun.attribute:still"],["calm","agitate","calm down","quiet","tranquilize","tranquillize","tranquillise","quieten","lull","still","comfort1","frames:9"]],
"strike dumb":[["verb.emotion"],["strike dumb","affect"]],
"hit home":[["verb.emotion"],["hit home","strike home","strike a chord","frames:4strike a note","affect"]],
"wow":[["verb.emotion"],["wow","impress","frames:9"]],
"sweep away":[["verb.emotion"],["sweep away","sweep off","affect","frames:9"]],
"emote":[["verb.emotion","adj.all:emotional^emotive","noun.feeling:emotion","verb.creation:act"],["emote"]],
"resent":[["verb.emotion","noun.feeling:resentment"],["resent","dislike","frames:8"]],
"embitter":[["verb.emotion","noun.state:embitterment","noun.attribute:acerbity"],["embitter","envenom","acerbate","resent"]],
"eat into":[["verb.emotion"],["eat into","fret2","rankle","grate","annoy"]],
"abhor":[["verb.emotion","adj.all:offensive1^abhorrent","noun.feeling:abhorrence","noun.person:loather","noun.feeling:loathing","adj.all:hateful^abominable","noun.person:abomination","noun.feeling:abomination","noun.act:abomination","noun.person:abominator","noun.feeling:execration","noun.cognition:execration"],["abhor","loathe","abominate","execrate","hate","frames:8"]],
"contemn":[["verb.emotion","noun.feeling:despising","noun.feeling:despisal","noun.communication:scorn","noun.feeling:scorn","noun.person:scorner","noun.feeling:disdain"],["contemn","despise","scorn","disdain","hate","frames:8"]],
"care for":[["verb.emotion","noun.possession:treasure1","verb.emotion"],["care for8","cherish","hold dear","treasure","love","frames:8","care for1","like5","frames:8"]],
"yearn":[["verb.emotion"],["yearn10","care for8"]],
"cool off":[["verb.emotion"],["cool off1","feel"]],
"adore":[["verb.emotion","adj.all:lovable^adorable","noun.person:adorer"],["adore","love","frames:8","9","32"]],
"idolize":[["verb.emotion","noun.act:idolization1","noun.act:idolization","noun.person:idolizer1","noun.person:idol","noun.cognition:idol","noun.artifact:idol","noun.act:idolisation1","noun.act:idolisation","noun.person:idol","noun.cognition:idol","noun.artifact:idol","noun.feeling:worship1","noun.person:worshiper1","noun.person:worshipper1","adj.all:pious^reverent","adj.all:reverent","noun.cognition:reverence"],["idolize","idolise","worship","hero-worship","revere1","adore","frames:8"]],
"frighten":[["verb.emotion","noun.act:frightening","noun.feeling:fright","noun.feeling:scare","noun.artifact:scarer","noun.feeling:affright"],["frighten","frighten off","^frighten away","^fright","scare","affright","fear",">excite","frames:9"]],
"overawe":[["verb.emotion","noun.person:coward"],["overawe","cow","awe","frames:9"]],
"terrify":[["verb.emotion","noun.feeling:terror","noun.act:terrorization","noun.feeling:terror","noun.act:terrorisation","noun.feeling:terror"],["terrify","terrorize","terrorise","frighten","frames:9"]],
"intimidate":[["verb.emotion","noun.feeling:intimidation","noun.communication:intimidation","noun.act:intimidation1","verb.emotion","noun.communication:intimidation","noun.act:intimidation1","verb.communication:warn"],["intimidate","frighten","intimidate1","discourage","*frames:9"]],
"apprehend":[["verb.emotion","adj.all:uneasy^apprehensive","adj.all:afraid^apprehensive","noun.feeling:apprehension","noun.cognition:apprehension1","noun.person:apprehender1"],["apprehend","quail at","fear","*anticipate"]],
"dismay":[["verb.emotion","noun.feeling:dismay","noun.person:alarmist","noun.feeling:alarm","noun.feeling:horror1"],["dismay","alarm","appal1","appall10","horrify1","frighten","frames:9"]],
"faze":[["verb.emotion"],["faze","unnerve","enervate","unsettle","upset1","frames:10"]],
"unman":[["verb.emotion"],["unman","unnerve","frames:9"]],
"freak out":[["verb.emotion"],["freak out","freak","gross out","panic"]],
"daunt":[["verb.emotion","noun.feeling:pall","noun.state:scare"],["daunt","dash","scare off","pall","frighten off","scare away","frighten away","scare4","intimidate1"]],
"combust":[["verb.emotion"],["combust1","combust",">anger","frames:9","10"]],
"miff":[["verb.emotion","noun.state:miff"],["miff","anger","frames:9"]],
"infuriate":[["verb.emotion","noun.state:fury","noun.feeling:fury","noun.feeling:infuriation","noun.feeling:exasperation","noun.act:exasperation"],["infuriate","exasperate1","incense1","anger","frames:10"]],
"raise the roof":[["verb.emotion"],["raise the roof","anger1"]],
"madden":[["verb.emotion","verb.emotion","verb.emotion","noun.state:craze"],["madden","anger","frames:10","madden1","torment1","frames:10","madden2","craze"]],
"annoy":[["verb.emotion","noun.person:annoyer","noun.act:annoyance","noun.state:botheration","noun.cognition:botheration","noun.cognition:bother","noun.state:irritation","noun.feeling:irritation1","noun.act:irritation1","noun.act:irritation","noun.cognition:irritant","noun.state:vexation","noun.act:vexation","noun.person:vexer","noun.act:devilment","noun.act:deviltry1","noun.act:devilry1"],["annoy","rag1","get to","bother","get at","irritate","rile","nark","nettle","gravel","vex","chafe","devil","displease","frames:9"]],
"fluster":[["verb.emotion","noun.attribute:fluster","verb.emotion","noun.attribute:fluster","verb.social:behave1"],["fluster","fluster1",">confuse","frames:10","fluster1"]],
"consternate":[["verb.emotion"],["consternate","frighten","frames:9"]],
"bewilder":[["verb.emotion","noun.cognition:bemusement","noun.feeling:discombobulation"],["bewilder","bemuse","discombobulate","throw","upset1","frames:10"]],
"distract":[["verb.emotion","noun.act:distraction2"],["distract","deflect6","confuse","frames:9"]],
"embarrass":[["verb.emotion","noun.event:embarrassment","noun.feeling:abashment"],["embarrass","abash","upset1","frames:9"]],
"break someone's heart":[["verb.emotion"],["break someone's heart","pain","frames:10"]],
"agonize":[["verb.emotion","noun.state:agony","noun.state:agony","noun.feeling:agony","verb.emotion","noun.state:agony","noun.feeling:agony"],["agonize","agonise","suffer","frames:2","agonize1","agonise1","agonize",">anguish"]],
"flip one's lid":[["verb.emotion","noun.communication:blowup"],["flip one's lid","blow up","throw a fit","hit the roof","hit the ceiling","have kittens","have a fit","combust","blow one's stack","fly off the handle","flip one's wig","lose one's temper","blow a fuse","go ballistic","rage","frames:2"]],
"enrage":[["verb.emotion","noun.feeling:enragement"],["enrage","rage",">anger","frames:10"]],
"foam at the mouth":[["verb.emotion"],["foam at the mouth","froth at the mouth","rage"]],
"repent":[["verb.emotion","adj.all:repentant","noun.feeling:repentance","noun.feeling:regret","noun.feeling:rue","verb.emotion","adj.all:repentant","noun.act:atonement"],["repent","regret","frames:26","33rue","feel","repent1","atone"]],
"mourn":[["verb.emotion","noun.person:mourner","noun.state:mourning","verb.emotion","noun.person:mourner","verb.social:observe2"],["mourn","grieve","frames:2","mourn1"]],
"grieve":[["verb.emotion","noun.person:griever","noun.state:sorrow","noun.cognition:sorrow","noun.feeling:sorrow1","noun.feeling:sorrow","noun.person:sorrower","verb.emotion"],["grieve","sorrow","suffer","frames:2","grieve1","aggrieve","grieve",">afflict"]],
"tribulate":[["verb.emotion","noun.event:tribulation"],["tribulate","afflict"]],
"disappoint":[["verb.emotion","noun.feeling:disappointment","noun.act:disappointment","noun.feeling:letdown","verb.social:frustrate"],["disappoint","let down","frames:9"]],
"fall short":[["verb.emotion"],["fall short12","come short12","disappoint","frames:1","2","4"]],
"humiliate":[["verb.emotion","noun.state:humiliation","noun.feeling:humiliation","noun.event:humiliation","noun.act:humiliation","noun.feeling:mortification","noun.event:mortification","noun.feeling:chagrin","noun.act:abasement"],["humiliate","mortify1","chagrin1","humble","abase","hurt","frames:9"]],
"take down":[["verb.emotion","noun.communication:takedown","noun.state:degradation","noun.act:degradation","noun.communication:put-down"],["take down","degrade","disgrace","demean","put down","humiliate","frames:9"]],
"efface":[["verb.emotion","noun.act:effacement"],["efface","humble1"]],
"humanize":[["verb.emotion","noun.act:humanization","noun.act:humanisation","verb.change:change1"],["humanize","dehumanize","humanise"]],
"humble":[["verb.emotion","verb.change:change1"],["humble1","frames:9"]],
"mortify":[["verb.emotion","noun.act:mortification","verb.consumption:abstain","*verb.social:contain","verb.emotion","noun.act:mortification","verb.social:discipline1"],["mortify2","subdue","crucify3","frames:9","mortify4","mortify2"]],
"express emotion":[["verb.emotion"],["express emotion","express feelings"]],
"torment":[["verb.emotion","noun.feeling:torment1","noun.feeling:torment2","noun.person:tormenter","noun.person:tormentor","noun.feeling:torture1","noun.feeling:torture2","noun.person:torturer","noun.state:excruciation","noun.artifact:rack2","verb.emotion","noun.act:torment","noun.feeling:torment3","noun.person:tormenter","noun.person:tormentor","noun.act:bedevilment","noun.act:crucifixion1","noun.feeling:frustration1"],["torment","torture","excruciate","rack1","anguish","frames:10","torment1","rag","bedevil","crucify","dun","frustrate","harass","frames:10"]],
"ingratiate":[["verb.emotion","adj.all:flattering^ingratiatory"],["ingratiate","manipulate","frames:9"]],
"cozy up":[["verb.emotion"],["cozy up9","cotton up9","shine up9","play up9","sidle up9","suck up9","ingratiate"]],
"warm to":[["verb.emotion","verb.cognition:consider1"],["warm to"]],
"take heart":[["verb.emotion"],["take heart","buck up","hearten","frames:2"]],
"endear":[["verb.emotion","noun.act:endearment"],["endear","please"]],
"shout down":[["verb.emotion","verb.change:silence"],["shout down"]],
"despond":[["verb.emotion","adj.all:hopeless^despondent","noun.feeling:despondency","noun.feeling:despondence"],["despond","despair"]],
"elate":[["verb.emotion","noun.state:elation","noun.feeling:elation","noun.feeling:intoxication"],["elate","depress","lift up","uplift","pick up","intoxicate","rejoice",">stimulate","frames:9"]],
"exhilarate":[["verb.emotion","noun.feeling:exhilaration","noun.act:thrill","noun.feeling:thrill2","noun.feeling:thrill","noun.state:exaltation","noun.state:beatification","noun.act:beatification1"],["exhilarate","tickle pink","inebriate","thrill1","exalt1","beatify3","elate","frames:9"]],
"gladden":[["verb.emotion","verb.emotion","noun.cognition:joy","noun.feeling:joy"],["gladden","sadden","rejoice","gladden1","sadden1","joy1","gladden",">frames:9"]],
"sadden":[["verb.emotion"],["sadden","gladden","feel","frames:2"]],
"overjoy":[["verb.emotion"],["overjoy","gladden1","frames:9"]],
"exult":[["verb.emotion","adj.all:elated^exultant","noun.feeling:exultation","noun.state:walking on air"],["exult","walk on air","be on cloud nine","jump for joy","rejoice"]],
"rejoice":[["verb.emotion","noun.feeling:rejoicing","noun.feeling:joy"],["rejoice","joy","feel","frames:2"]],
"weigh down":[["verb.emotion"],["weigh down","lighten1","weigh on","sadden1"]],
"abreact":[["verb.emotion","noun.act:abreaction","noun.act:psychoanalysis"],["abreact","relieve"]],
"please":[["verb.emotion","adj.all:pleasant","noun.feeling:pleasure","noun.cognition:pleasure","noun.act:pleasure2","noun.person:pleaser","noun.act:pleasing","noun.cognition:delight","noun.feeling:delight","verb.emotion","adj.all:nice^pleasant","verb.emotion","noun.act:pleasure2"],["please","displease","delight","like5",">like4",">satisfy","frames:9","please3","please","$satisfy","frames:9","please1","wish2","frames:1"]],
"titillate":[["verb.emotion","noun.act:titillation1"],["titillate","please","*excite","frames:9"]],
"dissatisfy":[["verb.emotion","adj.all:unsatisfactory^dissatisfactory","noun.feeling:dissatisfaction"],["dissatisfy","satisfy","disappoint","*displease","frames:9"]],
"discontent":[["verb.emotion","noun.feeling:discontentment","noun.feeling:discontent"],["discontent","content","dissatisfy","frames:9"]],
"displease":[["verb.emotion","noun.feeling:displeasure"],["displease","please","dislike",">frames:9"]],
"enchant":[["verb.emotion","noun.state:enchantment","noun.cognition:enchantment","noun.state:transport","noun.feeling:enthrallment","noun.feeling:ravishment"],["enchant","disenchant","enrapture","transport","enthrall","ravish","enthral","delight2","please","frames:9"]],
"disenchant":[["verb.emotion","noun.cognition:disenchantment","noun.cognition:disillusionment","noun.cognition:disillusion"],["disenchant","enchant","disillusion","disappoint","frames:9"]],
"discourage":[["verb.emotion","noun.feeling:discouragement2"],["discourage","encourage","frames:9"]],
"dishearten":[["verb.emotion","noun.feeling:disheartenment","noun.communication:disheartenment"],["dishearten","hearten","put off","discourage","frames:9"]],
"throw cold water on":[["verb.emotion"],["throw cold water on","pour cold water on","discourage","frames:8"]],
"pother":[["verb.emotion","noun.state:pother"],["pother1","agitate","frames:10"]],
"feast one's eyes":[["verb.emotion"],["feast one's eyes","enjoy"]],
"exacerbate":[["verb.emotion","noun.act:exacerbation","noun.feeling:exasperation","noun.act:exasperation","noun.act:aggravation","noun.feeling:aggravation","noun.person:aggravator"],["exacerbate","exasperate","aggravate","anger","frames:9"]],
"fascinate":[["verb.emotion","noun.state:fascination","noun.attribute:fascination","noun.attribute:grip","noun.person:spellbinder"],["fascinate","transfix","grip","spellbind","interest","frames:9"]],
"feel for":[["verb.emotion","noun.attribute:pity","noun.feeling:pity","noun.feeling:compassion","noun.attribute:compassion"],["feel for","pity","compassionate","condole with","sympathize with","grieve"]],
"commiserate":[["verb.emotion","adj.all:sympathetic^commiserative","noun.feeling:commiseration","noun.communication:commiseration","noun.person:sympathizer1","noun.feeling:sympathy","noun.person:sympathiser1","noun.feeling:sympathy"],["commiserate","sympathize","sympathise","sympathize with","frames:2"]],
"condole":[["verb.emotion","noun.communication:condolence"],["condole","sympathize","frames:2"]],
"care a hang":[["verb.emotion"],["care a hang","give a hoot","give a hang","give a damn","frames:2"]],
"alienate":[["verb.emotion"],["alienate1","affect"]],
"drift apart":[["verb.emotion"],["drift apart","drift away3","estrange"]],
"begrudge":[["verb.emotion"],["begrudge","wish1","frames:14resent1"]],
"feel like":[["verb.emotion"],["feel like","want","frames:8"]],
"covet":[["verb.emotion"],["covet","envy"]],
"drool over":[["verb.emotion"],["drool over","slobber over","idolize","frames:8"]],
"look down on":[["verb.emotion"],["look down on","contemn","frames:9"]],
"lust after":[["verb.emotion"],["lust after","lech after","desire"]],
"hanker":[["verb.emotion","noun.feeling:hankering","noun.person:longer","noun.feeling:longing","noun.person:yearner","noun.feeling:yearning"],["hanker","long2","yearn","desire"]],
"take pride":[["verb.emotion"],["take pride9","pride oneself9","feel"]],
"fall apart":[["verb.emotion"],["fall apart","go to pieces","lose it"]],
"fly high":[["verb.emotion"],["fly high","feel"]],
"bring down":[["verb.emotion"],["bring down","enthuse","frames:9"]],
"disgruntle":[["verb.emotion","noun.feeling:disgruntlement"],["disgruntle","dissatisfy","frames:9"]],
"spook":[["verb.emotion","noun.cognition:spook"],["spook","frighten","frames:9"]],
"obsess":[["verb.emotion","adj.all:neurotic^obsessive","noun.cognition:obsession"],["obsess3","worry"]]
}