var mysql_wn_data_noun_time = {
"meal":[["noun.time"],["meal","occasion"]],
"game":[["noun.time","noun.cognition:division","noun.act:tennis","noun.act","noun.act","noun.event:contest","noun.act","noun.act","noun.communication:colloquialism"],["game","set","game1","diversion","game3","game","game4","play","game2","biz","occupation"]],
"assumption":[["noun.time","noun.act","verb.cognition:assume","noun.Tops:act"],["Assumption","Assumption of Mary","August 15\"","holy day of obligation","August","assumption1"]],
"occupation":[["noun.time","verb.stative:occupy1","verb.possession:occupy8","noun.act","verb.stative:occupy4","verb.social:occupy","verb.cognition:occupy","noun.act","verb.competition:occupy","noun.group:military"],["occupation","time period","occupation4","activity","occupation2","military control","social control"]],
"depression":[["noun.time","noun.state","verb.change:slump"],["Depression","Great Depression","historic period","depression2","slump","economic crisis","economic condition","crisis"]],
"trick":[["noun.time"],["trick","shift"]],
"flux":[["noun.time","noun.state","noun.Tops:state"],["flux","rate","flux1","state of flux"]],
"prohibition":[["noun.time","noun.person:prohibitionist","noun.communication","noun.person:prohibitionist","noun.group:law","noun.communication"],["prohibition","prohibition era","time period","prohibition2","law","prohibition1","refusal1"]],
"termination":[["noun.time","verb.stative:expire"],["termination","expiration","expiry","end"]],
"beginning":[["noun.time","verb.social:start","verb.creation:start1","verb.creation:start","verb.stative:start","verb.change:start1","verb.change:start","verb.social:kick off"],["beginning","middle","end","commencement","first","outset","get-go","start","kickoff","starting time","showtime","offset","point in time"]],
"restoration":[["noun.time","noun.act","verb.social:restore","noun.location:England","noun.artifact"],["Restoration","historic period","Restoration2","group action","restoration1","model"]],
"reconstruction":[["noun.time"],["Reconstruction","Reconstruction Period","historic period"]],
"march":[["noun.time","verb.motion","noun.group:march","noun.act:march","noun.act:marching","verb.motion","noun.group:march","noun.act:march","verb.motion","noun.group:march","noun.act:march"],["March","Mar","Gregorian calendar month","Gregorian calendar","march1","process","walk","frames:2","march4","march",">walk1","march10","walk5"]],
"speed":[["noun.time","adj.all:fast1^speedy","verb.motion:speed1","verb.motion:speed","verb.change:speed2","verb.motion:speed3","verb.change:speed","verb.motion","noun.act:speed","noun.time:speed","noun.attribute:speed","noun.person:speeder","noun.act:speeding"],["speed","velocity","rate","speed1","travel","frames:4"]],
"acceleration":[["noun.time","noun.cognition:physics"],["acceleration","deceleration","rate"]],
"deceleration":[["noun.time","noun.cognition:physics"],["deceleration","acceleration","rate"]],
"sheepshearing":[["noun.time","noun.act"],["sheepshearing","season2","sheepshearing2","festival"]],
"extension":[["noun.time"],["extension","delay"]],
"circumcision":[["noun.time","noun.group:Roman Catholic","noun.group:Anglican Church","noun.act","verb.contact:circumcise"],["Circumcision","Feast of the Circumcision","January 1\"2","feast day","circumcision1","rite1"]],
"transfiguration":[["noun.time","verb.change:transfigure2","noun.cognition:Christianity","noun.act","verb.change:transfigure"],["Transfiguration","Transfiguration Day","August 6\"","Christian holy day","transfiguration2","metamorphosis2","alteration"]],
"kip":[["noun.time","verb.body:kip","noun.location:Britain"],["kip","sleep"]],
"feria":[["noun.time","adj.pert:ferial"],["feria","weekday"]],
"festival":[["noun.time"],["festival","time period"]],
"mardi gras":[["noun.time"],["Mardi Gras","Shrove Tuesday","Fat Tuesday","pancake day","Christian holy day","Shrovetide"]],
"caliphate":[["noun.time"],["Caliphate","era"]],
"presidency":[["noun.time","noun.person:president4","noun.act:president4","noun.person:president3","noun.person:president2","noun.person:president1","noun.person:president","verb.social:administer"],["presidency","presidential term","administration","tenure"]],
"regency":[["noun.time","noun.location:England","noun.time"],["Regency","rule","regency1","rule"]],
"vice-presidency":[["noun.time"],["vice-presidency","vice-presidential term","tenure"]],
"hospitalization":[["noun.time","verb.possession:hospitalize"],["hospitalization","time period"]],
"incubation":[["noun.time","verb.change:incubate2","noun.state:infection","noun.cognition:pathology"],["incubation","phase"]],
"limitation":[["noun.time","verb.change:limit1","verb.change:limit","noun.group:law"],["limitation","time limit"]],
"breath":[["noun.time","verb.communication:breathe"],["breath","breather","breathing place","breathing space","breathing spell","breathing time","respite"]],
"generation":[["noun.time","noun.time","adj.pert:generational","verb.creation:generate"],["generation","time period","generation1","phase"]],
"lustrum":[["noun.time"],["lustrum","time period"]],
"none":[["noun.time"],["none","hour1"]],
"pause":[["noun.time","verb.communication:pause1","verb.stative:pause","verb.social:break1","verb.change:suspend","verb.communication","noun.time:pause","noun.act:pause","noun.act:intermission","noun.act:break5"],["pause","intermission","break","interruption","suspension","time interval","pause1","intermit","break4","interrupt"]],
"respite":[["noun.time","verb.communication:rest1","verb.communication:rest"],["respite","rest","relief","rest period","pause"]],
"leisure":[["noun.time","adj.all:unhurried^leisurely"],["leisure","leisure time","time off"]],
"new deal":[["noun.time"],["New Deal","historic period"]],
"turnaround":[["noun.time"],["turnaround","turnaround time","work time"]],
"enlistment":[["noun.time","verb.competition:enlist1","verb.competition:enlist"],["enlistment","hitch","term of enlistment","tour of duty","duty tour","tour1","time period"]],
"attendance":[["noun.time","adj.all:present2^attendant"],["attendance","frequency"]],
"absence":[["noun.time","noun.state"],["absence","time interval","absence1","absence seizure","seizure","petit mal1"]],
"ramadan":[["noun.time"],["Ramadan","Islamic calendar month","Muhammadan calendar"]],
"probation":[["noun.time","adj.all:conditional^probationary","verb.stative:probate","noun.time","adj.all:conditional^probationary"],["probation","trial period","probation1","trial period"]],
"anachronism":[["noun.time","adj.all:asynchronous^anachronistic","adj.all:asynchronous^anachronic","verb.change:mistime","verb.cognition:misdate"],["anachronism","mistiming","misdating","timekeeping"]],
"antiquity":[["noun.time","adj.all:old1^antique1"],["antiquity","historic period","history"]],
"checkout":[["noun.time","verb.communication:check out"],["checkout","checkout time","departure time"]],
"deathbed":[["noun.time"],["deathbed","time of life"]],
"fag end":[["noun.time"],["fag end","tail","tail end","end"]],
"future":[["noun.time","adj.all:prospective^future","adj.all:future","noun.Tops:time"],["future","past","hereafter","futurity","time to come"]],
"grave":[["noun.time"],["grave","death"]],
"point":[["noun.time","noun.Tops:measure","noun.quantity","verb.competition","noun.artifact:point2","noun.communication:pointer","noun.artifact:pointer1","noun.artifact:pointer","verb.stative:be3","noun.relation","verb.change","verb.contact","noun.communication:point","noun.shape:point2","verb.contact","noun.communication:point","noun.shape:point2","verb.contact","noun.communication:point","noun.shape:point2"],["point","point in time","point1","unit of measurement","score","point2","frames:4","point4","relevance","point9","repoint","repair","point11","mark9","point12","mark9","point13","mark9"]],
"study hall":[["noun.time"],["study hall","time period","school day1"]],
"window":[["noun.time","noun.artifact","noun.artifact","noun.artifact","noun.cognition:computer science","noun.artifact"],["window","time period","window1","opening","car","bus","window2","panel","window envelope","window3","display1","computer screen","window5","opening"]],
"baroque":[["noun.time"],["Baroque","Baroque era","Baroque period","historic period"]],
"isometry":[["noun.time","noun.process:growth","noun.attribute","adj.all:equal^isometric"],["isometry","growth rate","isometry2","elevation"]],
"age":[["noun.time","verb.change:age","verb.change","verb.change","noun.time:age1"],["age","eld1","time of life","life","age1","develop","frames:1","age2","rejuvenate","age",">change1"]],
"youth":[["noun.time","noun.time"],["youth","time of life","youth1","early days","time period"]],
"value":[["noun.time","noun.communication:music","verb.cognition","noun.possession:value","noun.person:valuer"],["value","time value","note value","duration2","value3","determine1"]],
"duration":[["noun.time","adj.all:soft3^continuant","noun.Tops:time","noun.time","verb.change:continue10"],["duration","continuance","duration2","continuance2","time period"]],
"spacing":[["noun.time"],["spacing","rate"]],
"span":[["noun.time","noun.quantity"],["span","duration2","span1","linear unit"]],
"majority":[["noun.time","adj.all:major3"],["majority","minority","legal age","age","adulthood"]],
"minority":[["noun.time","adj.all:minor3","noun.state:legal status"],["minority","majority","nonage","age"]],
"hour":[["noun.time","adj.all:periodic^hourly","adj.pert:horary","noun.time","adj.pert:horary","noun.time"],["hour","hr","60\" minutes","time unit","day","hour1","time of day","clock time","hour2","time period"]],
"ab":[["noun.time"],["Ab","Av","Jewish calendar month","Jewish calendar"]],
"pus":[["noun.time"],["Pus","Pansa","Hindu calendar month","Hindu calendar"]],
"half-moon":[["noun.time"],["half-moon","phase of the moon","month"]],
"retardation":[["noun.time","verb.stative:retard"],["retardation","delay"]],
"blackout":[["noun.time","verb.change:black out"],["blackout","pause"]],
"threshold":[["noun.time"],["threshold","beginning"]],
"gestation":[["noun.time","adj.pert:gestational","verb.body:gestate"],["gestation","gestation period","biological time"]],
"moment":[["noun.time","adj.all:fast1^instantaneous","noun.time","adj.all:short2^momentary","adj.all:short2^momentaneous","noun.location:Britain"],["moment","minute2","second2","instant","point in time","moment1","mo","minute1","second1","bit","time"]],
"history":[["noun.time","adj.all:past^historic","noun.cognition","adj.all:past^historic","noun.Tops:cognition","noun.time"],["history","past","history1","history2","continuum"]],
"past":[["noun.time","noun.Tops:time","noun.time"],["past","future","past times","yesteryear","past1","time period","life1"]],
"octave":[["noun.time"],["octave","religious festival"]],
"chapter":[["noun.time","noun.group"],["chapter","phase","chapter1","assembly"]],
"minute":[["noun.time"],["minute","min","time unit","hour"]],
"curfew":[["noun.time"],["curfew","deadline"]],
"alpha and omega":[["noun.time"],["alpha and omega","eternity"]],
"annunciation":[["noun.time"],["Annunciation","Lady Day","Annunciation Day","March 25\"","quarter day","March"]],
"immaculate conception":[["noun.time"],["Immaculate Conception","December 8\"","holy day of obligation"]],
"incarnation":[["noun.time"],["incarnation","time"]],
"air alert":[["noun.time"],["air alert","time period"]],
"allegro":[["noun.time","adj.all:fast2^allegro"],["allegro","tempo1"]],
"allegretto":[["noun.time","adj.all:fast2^allegretto"],["allegretto","tempo1"]],
"andante":[["noun.time","adj.all:slow2^andante"],["andante","tempo1"]],
"caesura":[["noun.time","adj.pert:caesural"],["caesura","pause"]],
"ascension":[["noun.time","noun.cognition:Christianity"],["Ascension","Ascension Day","Ascension of the Lord","holy day of obligation"]],
"birth":[["noun.time","verb.body:birth"],["birth","death","beginning","life"]],
"epiphany":[["noun.time"],["Epiphany","Epiphany of Our Lord","Twelfth day","Three Kings' Day","January 6\"","Christian holy day","January"]],
"sunset":[["noun.time"],["sunset","sunrise","sundown","hour1","evening"]],
"tide":[["noun.time","verb.motion","noun.event:tide1","noun.event:surge1","noun.event:surge","verb.motion","noun.event:tide","verb.motion","noun.event:tide","verb.stative:tide over"],["tide","lunar time period","time period","tide1","ebb","surge3","flow","tide2","drift2","tide3","^tide2",">float2"]],
"dead":[["noun.time"],["dead","time"]],
"day shift":[["noun.time"],["day shift","shift"]],
"evening shift":[["noun.time"],["evening shift","swing shift","shift"]],
"night shift":[["noun.time"],["night shift","graveyard shift","shift"]],
"apogee":[["noun.time","verb.social:culminate","verb.change:culminate3","verb.change:culminate"],["apogee","culmination","phase"]],
"vernal equinox":[["noun.time"],["vernal equinox","autumnal equinox","March equinox","spring equinox","equinox","spring","March"]],
"autumnal equinox":[["noun.time"],["autumnal equinox","vernal equinox","September equinox","fall equinox","equinox","fall","September"]],
"saint joseph":[["noun.time"],["Saint Joseph","St Joseph","March 19\"","Christian holy day","March"]],
"corpus christi":[["noun.time"],["Corpus Christi","Christian holy day"]],
"deep":[["noun.time","adj.all:intense^deep1"],["deep","middle"]],
"offing":[["noun.time"],["offing","future"]],
"eon":[["noun.time","adj.all:permanent^eonian","noun.time","adj.pert:eonian","adj.pert:aeonian"],["eon","aeon","long time","eon1","aeon1","geological time"]],
"mississippian":[["noun.time"],["Mississippian","Missippian period","Lower Carboniferous","Lower Carboniferous period","period3","Carboniferous period"]],
"pennsylvanian":[["noun.time"],["Pennsylvanian","Pennsylvanian period","Upper Carboniferous","Upper Carboniferous period","period3","Carboniferous period"]],
"novitiate":[["noun.time","noun.cognition:religion"],["novitiate","noviciate","time period"]],
"day":[["noun.time","adj.all:periodic^daily","noun.time","noun.time","noun.time","noun.time","noun.time","noun.time"],["day","twenty-four hours","twenty-four hour period","24-hour interval","solar day","mean solar day","time unit","day3","time","day4","work time","day1","calendar day","day2","night","daytime","daylight","time period","day","day7","time period","day5","era"]],
"hertz":[["noun.time","noun.person","adj.pert:hertzian"],["hertz","Hz","cycle per second","cycles/second","cps","cycle2","rate","kilohertz","Hertz1","Heinrich Hertz","Heinrich Rudolph Hertz","physicist"]],
"sunday":[["noun.time"],["Sunday","Lord's Day","Dominicus","Sun","rest day","weekend"]],
"monsoon":[["noun.time","noun.phenomenon"],["monsoon","rainy season","monsoon1","wind","rain"]],
"twilight":[["noun.time","adj.all:dark1^dusky","adj.all:dark1^crepuscular","adj.all:dark1^crepuscular","noun.state"],["twilight","dusk","gloaming","gloam","nightfall","evenfall","fall1","crepuscule","crepuscle","hour1","evening","twilight1","decline"]],
"flower":[["noun.time","verb.change:blossom","adj.all:rich^flush"],["flower","prime2","peak","heyday","bloom1","blossom","efflorescence","flush","time period"]],
"double time":[["noun.time"],["double time","pace"]],
"lactation":[["noun.time","verb.consumption:lactate"],["lactation","time period"]],
"frequency":[["noun.time","adj.all:common1^frequent","adj.all:frequent"],["frequency","frequence","oftenness","rate"]],
"teens":[["noun.time"],["teens","time of life","adulthood"]],
"time constant":[["noun.time","noun.cognition:electronics"],["time constant","time interval"]],
"eternity":[["noun.time","adj.all:infinite","noun.Tops:time","noun.time","adj.all:long2^eternal"],["eternity","infinity","eternity1","time interval"]],
"bachelorhood":[["noun.time","noun.person:bachelor"],["bachelorhood","time of life"]],
"widowhood":[["noun.time","noun.person:widow"],["widowhood","time of life"]],
"night":[["noun.time","adj.all:periodic^nightly","noun.time","noun.time","noun.time","noun.time","noun.time"],["night","day2","nighttime","dark","time period","day","night2","time unit","night3","time period","night4","time period","night1","time period","night5","twilight"]],
"moratorium":[["noun.time"],["moratorium","delay"]],
"embolism":[["noun.time"],["embolism","intercalation","time interval","calendar"]],
"hard time":[["noun.time"],["hard time","prison term"]],
"adulthood":[["noun.time","noun.person:adult","noun.animal:adult","adj.all:mature1"],["adulthood","maturity","time of life"]],
"adolescence":[["noun.time","adj.all:young^adolescent","adj.all:immature1^adolescent","verb.change:adolesce"],["adolescence","youth","time of life"]],
"childhood":[["noun.time","noun.person:child"],["childhood","time of life"]],
"infancy":[["noun.time","noun.person:infant","noun.person:baby","noun.animal:baby"],["infancy","babyhood","early childhood","time of life"]],
"drought":[["noun.time"],["drought","drouth","time period"]],
"time period":[["noun.time","noun.quantity:fundamental quantity"],["time period","period of time","period"]],
"trial period":[["noun.time"],["trial period","test period","time period"]],
"time frame":[["noun.time"],["time frame","time period"]],
"geological time":[["noun.time","noun.Tops:time"],["geological time","geologic time"]],
"biological time":[["noun.time","noun.Tops:time"],["biological time"]],
"cosmic time":[["noun.time","noun.Tops:time"],["cosmic time"]],
"civil time":[["noun.time","noun.Tops:time"],["civil time","standard time","local time"]],
"daylight-saving time":[["noun.time","noun.Tops:time"],["daylight-saving time","daylight-savings time","daylight saving","daylight savings"]],
"hours":[["noun.time"],["hours","work time"]],
"downtime":[["noun.time"],["downtime","uptime","time period"]],
"uptime":[["noun.time","noun.artifact:factory"],["uptime","downtime","time period"]],
"24/7\"":[["noun.time"],["24/7\"","uptime"]],
"work time":[["noun.time"],["work time","time off","time period"]],
"time off":[["noun.time"],["time off","work time","time period"]],
"face time":[["noun.time"],["face time","work time"]],
"compensatory time":[["noun.time"],["compensatory time","time off"]],
"travel time":[["noun.time"],["travel time","time period"]],
"now":[["noun.time"],["now","present"]],
"here and now":[["noun.time"],["here and now","present moment","moment2","present"]],
"times":[["noun.time"],["times1","time period"]],
"modern times":[["noun.time"],["modern times","present times","modern world","contemporary world","times1"]],
"roman times":[["noun.time"],["Roman times","times1"]],
"yore":[["noun.time"],["yore","past"]],
"bygone":[["noun.time","adj.all:past^bygone"],["bygone","water under the bridge","past"]],
"old":[["noun.time"],["old","past"]],
"kingdom come":[["noun.time","noun.time"],["kingdom come","future","kingdom come1","afterlife"]],
"musical time":[["noun.time","noun.Tops:time","noun.communication:music"],["musical time"]],
"elizabethan age":[["noun.time"],["Elizabethan age","historic period"]],
"victorian age":[["noun.time"],["Victorian age","historic period"]],
"hard times":[["noun.time"],["hard times","time"]],
"continuum":[["noun.time","adj.all:continuous2","adj.all:continuous1","noun.Tops:time"],["continuum"]],
"phanerozoic":[["noun.time"],["Phanerozoic","Phanerozoic eon","Phanerozoic aeon","eon1"]],
"cenozoic":[["noun.time"],["Cenozoic","Cenozoic era","Age of Mammals","era1","Phanerozoic"]],
"quaternary":[["noun.time"],["Quaternary","Quaternary period","Age of Man","period3","Cenozoic era"]],
"holocene":[["noun.time"],["Holocene","Holocene epoch","Recent","Recent epoch","epoch1","Quaternary period"]],
"pleistocene":[["noun.time"],["Pleistocene","Pleistocene epoch","Glacial epoch","epoch1","Quaternary period"]],
"tertiary":[["noun.time"],["Tertiary","Tertiary period","period3","Cenozoic era"]],
"pliocene":[["noun.time"],["Pliocene","Pliocene epoch","epoch1","Tertiary period"]],
"miocene":[["noun.time"],["Miocene","Miocene epoch","epoch1","Tertiary period"]],
"oligocene":[["noun.time"],["Oligocene","Oligocene epoch","epoch1","Tertiary period"]],
"eocene":[["noun.time"],["Eocene","Eocene epoch","epoch1","Tertiary period"]],
"paleocene":[["noun.time"],["Paleocene","Paleocene epoch","epoch1","Tertiary period"]],
"mesozoic":[["noun.time"],["Mesozoic","Mesozoic era","Age of Reptiles","era1"]],
"cretaceous":[["noun.time","adj.pert:cretaceous"],["Cretaceous","Cretaceous period","period3","Mesozoic era"]],
"jurassic":[["noun.time"],["Jurassic","Jurassic period","period3","Mesozoic era"]],
"triassic":[["noun.time"],["Triassic","Triassic period","period3","Mesozoic era"]],
"paleozoic":[["noun.time"],["Paleozoic","Paleozoic era","era1"]],
"permian":[["noun.time"],["Permian","Permian period","period3","Paleozoic era"]],
"carboniferous":[["noun.time","adj.pert:carboniferous2"],["Carboniferous","Carboniferous period","period3","Paleozoic era"]],
"devonian":[["noun.time"],["Devonian","Devonian period","Age of Fishes","period3","Paleozoic era"]],
"silurian":[["noun.time"],["Silurian","Silurian period","period3","Paleozoic era"]],
"ordovician":[["noun.time"],["Ordovician","Ordovician period","period3","Paleozoic era"]],
"cambrian":[["noun.time"],["Cambrian","Cambrian period","period3","Paleozoic era"]],
"precambrian":[["noun.time"],["Precambrian","Precambrian eon","Precambrian aeon","Precambrian period","eon1"]],
"proterozoic":[["noun.time","adj.all:early^proterozoic"],["Proterozoic","Proterozoic eon","Proterozoic aeon","eon1","Precambrian"]],
"archean":[["noun.time","adj.all:early^archean","adj.all:early^archeozoic","adj.all:early^archaeozoic"],["Archean","Archean eon","Archean aeon","Archeozoic","Archaeozoic","Archeozoic eon","Archaeozoic aeon","eon1","Precambrian period"]],
"hadean":[["noun.time"],["Hadean","Hadean time","Hadean eon","Hadean aeon","Priscoan","Priscoan eon","Priscoan aeon","eon1"]],
"clock time":[["noun.time","verb.change:time1","noun.cognition:meter reading"],["clock time","time3"]],
"greenwich mean time":[["noun.time","noun.Tops:time"],["Greenwich Mean Time","Greenwich Time","GMT","universal time","UT","UT1\""]],
"coordinated universal time":[["noun.time"],["coordinated universal time","UTC","Greenwich Mean Time"]],
"earth-received time":[["noun.time"],["Earth-received time","ERT","coordinated universal time"]],
"one-way light time":[["noun.time"],["one-way light time","OWLT","elapsed time"]],
"round-trip light time":[["noun.time"],["round-trip light time","RTLT","elapsed time"]],
"elapsed time":[["noun.time"],["elapsed time","time period"]],
"transmission time":[["noun.time"],["transmission time","TRM","coordinated universal time"]],
"spacecraft event time":[["noun.time"],["spacecraft event time","SCET","coordinated universal time"]],
"spacecraft clock time":[["noun.time"],["spacecraft clock time","SCLK","clock time"]],
"atlantic time":[["noun.time"],["Atlantic Time","Atlantic Standard Time","civil time"]],
"eastern time":[["noun.time"],["Eastern Time","Eastern Standard Time","EST","civil time"]],
"central time":[["noun.time"],["Central Time","Central Standard Time","CST","civil time"]],
"mountain time":[["noun.time"],["Mountain Time","Mountain Standard Time","MST","civil time"]],
"pacific time":[["noun.time"],["Pacific Time","Pacific Standard Time","PST","civil time"]],
"alaska standard time":[["noun.time"],["Alaska Standard Time","Yukon Time","civil time"]],
"hawaii time":[["noun.time"],["Hawaii Time","Hawaii Standard Time","civil time"]],
"bering time":[["noun.time"],["Bering Time","Bering Standard Time","civil time"]],
"clocking":[["noun.time","verb.change:clock"],["clocking","duration2"]],
"longueur":[["noun.time","noun.communication:literature","noun.act:art"],["longueur","duration2"]],
"residence time":[["noun.time"],["residence time","duration2"]],
"time scale":[["noun.time"],["time scale","duration2"]],
"extended time scale":[["noun.time","noun.cognition:simulation"],["extended time scale","slow time scale","time scale"]],
"fast time scale":[["noun.time","noun.cognition:simulation"],["fast time scale","time scale"]],
"time being":[["noun.time"],["time being","nonce","present"]],
"biological clock":[["noun.time","noun.object:mechanism"],["biological clock"]],
"circadian rhythm":[["noun.time"],["circadian rhythm","biological time"]],
"fourth dimension":[["noun.time","noun.attribute:dimension"],["fourth dimension","time4"]],
"workweek":[["noun.time"],["workweek","week1","work time","calendar week"]],
"week":[["noun.time","adj.all:periodic^hebdomadary"],["week","hebdomad","time period"]],
"midweek":[["noun.time"],["midweek","time period","week2"]],
"workday":[["noun.time","noun.time"],["workday","working day","day4","workday1","rest day","working day1","work day1","weekday"]],
"rest day":[["noun.time"],["rest day","workday1","day of rest","day of the week"]],
"overtime":[["noun.time","noun.act:athletic game"],["overtime","regulation time","extra time","time period"]],
"spare time":[["noun.time"],["spare time","free time","time off"]],
"day off":[["noun.time"],["day off","time off"]],
"half-term":[["noun.time","noun.location:Britain"],["half-term","vacation"]],
"vac":[["noun.time","noun.location:Britain"],["vac","vacay","vacation"]],
"half-holiday":[["noun.time"],["half-holiday","holiday1"]],
"playtime":[["noun.time"],["playtime","playday","leisure"]],
"field day":[["noun.time","noun.time","noun.group:military"],["field day","day1","field day2","day1"]],
"paid vacation":[["noun.time"],["paid vacation","vacation"]],
"compassionate leave":[["noun.time","noun.group:military"],["compassionate leave","leave"]],
"sabbatical":[["noun.time"],["sabbatical","sabbatical leave","leave"]],
"sabbatical year":[["noun.time"],["sabbatical year","sabbatical"]],
"shore leave":[["noun.time"],["shore leave","liberty","leave"]],
"sick leave":[["noun.time"],["sick leave","leave"]],
"terminal leave":[["noun.time"],["terminal leave","leave"]],
"days":[["noun.time"],["days","years2","life2"]],
"millennium":[["noun.time","adj.pert:millennial","adj.pert:millenary","adj.pert:millennian","noun.time","adj.pert:millennial","adj.pert:millenary","noun.time","adj.pert:millenary1","noun.cognition:doctrine","noun.communication:New Testament"],["millennium","millenary","time period","millennium2","millenary2","anniversary","millennium1"]],
"bimillennium":[["noun.time","adj.pert:bimillenial","noun.time"],["bimillennium","bimillenary","time period","bimillennium1","bimillenary1","anniversary"]],
"shelf life":[["noun.time"],["shelf life","time period"]],
"life expectancy":[["noun.time","noun.cognition:anticipation1"],["life expectancy"]],
"puerperium":[["noun.time","adj.pert:puerperal"],["puerperium","time period"]],
"incipiency":[["noun.time","adj.all:early2^incipient","adj.all:early2^incipient"],["incipiency","incipience","beginning"]],
"afterlife":[["noun.time"],["afterlife","hereafter1","life"]],
"time of life":[["noun.time"],["time of life","time period","life"]],
"neonatal period":[["noun.time"],["neonatal period","time of life"]],
"anal stage":[["noun.time","noun.act:psychoanalysis"],["anal stage","anal phase","phase","childhood"]],
"genital stage":[["noun.time","noun.act:psychoanalysis"],["genital stage","genital phase","phase","adolescence"]],
"latency stage":[["noun.time","noun.act:psychoanalysis"],["latency stage","latency phase","latency period","phase","childhood"]],
"oral stage":[["noun.time","noun.act:psychoanalysis"],["oral stage","oral phase","phase","infancy"]],
"phallic stage":[["noun.time","noun.act:psychoanalysis"],["phallic stage","phallic phase","phase","childhood"]],
"girlhood":[["noun.time","noun.person:girl2","noun.person:girl","noun.person:maiden","noun.person:maid"],["girlhood","maidenhood","maidhood","childhood"]],
"boyhood":[["noun.time","noun.person:boy"],["boyhood","childhood"]],
"schooldays":[["noun.time"],["schooldays","schooltime2","time of life"]],
"prepuberty":[["noun.time","adj.all:immature1^prepubertal"],["prepuberty","time of life","childhood"]],
"puberty":[["noun.time","adj.pert:pubertal","adj.all:immature1^pubescent"],["puberty","pubescence","time of life","adolescence"]],
"twenties":[["noun.time","noun.time"],["twenties","mid-twenties","time of life","adulthood","twenties1","1920\"s","decade"]],
"1900\"s":[["noun.time"],["1900\"s","decade"]],
"1530\"s":[["noun.time"],["1530\"s","decade"]],
"1820\"s":[["noun.time"],["1820\"s","decade"]],
"thirties":[["noun.time","noun.time"],["thirties","mid-thirties","thirty-something","time of life","adulthood","thirties1","1930\"s","decade"]],
"1830\"s":[["noun.time"],["1830\"s","decade"]],
"forties":[["noun.time","noun.time"],["forties","mid-forties","time of life","adulthood","forties1","1940\"s","decade"]],
"1840\"s":[["noun.time"],["1840\"s","decade"]],
"fifties":[["noun.time","noun.time"],["fifties","mid-fifties","time of life","adulthood","fifties1","1950\"s","decade"]],
"1850\"s":[["noun.time"],["1850\"s","decade"]],
"1750\"s":[["noun.time"],["1750\"s","decade"]],
"sixties":[["noun.time","noun.time"],["sixties","mid-sixties","time of life","old age","sixties1","1960\"s","decade"]],
"1860\"s":[["noun.time"],["1860\"s","decade"]],
"1760\"s":[["noun.time"],["1760\"s","decade"]],
"golden years":[["noun.time"],["golden years","time of life"]],
"seventies":[["noun.time","noun.time"],["seventies","mid-seventies","time of life","old age","seventies1","1970\"s","decade"]],
"1870\"s":[["noun.time"],["1870\"s","decade"]],
"1770\"s":[["noun.time"],["1770\"s","decade"]],
"eighties":[["noun.time","noun.time","noun.time"],["eighties","mid-eighties","time of life","old age","eighties1","1980\"s","decade","eighties2","1880\"s","decade"]],
"1780\"s":[["noun.time"],["1780\"s","decade"]],
"nineties":[["noun.time","noun.time","noun.time"],["nineties","mid-nineties","time of life","old age","nineties1","1990\"s","decade","nineties2","1890\"s","decade"]],
"1790\"s":[["noun.time"],["1790\"s","decade"]],
"age of consent":[["noun.time"],["age of consent","age"]],
"drinking age":[["noun.time"],["drinking age","age","adulthood"]],
"voting age":[["noun.time"],["voting age","age","adulthood"]],
"middle age":[["noun.time"],["middle age","time of life","adulthood"]],
"old age":[["noun.time","verb.change:age2","verb.change:age","noun.person:geezer"],["old age","years","age1","eld","geezerhood","time of life"]],
"dotage":[["noun.time","adj.all:old2^senile"],["dotage","second childhood","senility","old age"]],
"menopause":[["noun.time","adj.pert:menopausal"],["menopause","climacteric1","change of life","biological time","middle age"]],
"climacteric":[["noun.time"],["climacteric2","biological time","middle age"]],
"time unit":[["noun.time","noun.Tops:measure"],["time unit","unit of time"]],
"tomorrow":[["noun.time"],["tomorrow","future"]],
"today":[["noun.time"],["today","present"]],
"yesterday":[["noun.time"],["yesterday","past"]],
"morrow":[["noun.time"],["morrow","day"]],
"mean time":[["noun.time","noun.cognition:astronomy"],["mean time","mean solar time","time unit"]],
"terrestrial time":[["noun.time","noun.cognition:astronomy"],["terrestrial time","TT","terrestrial dynamical time","TDT","ephemeris time","time unit"]],
"calendar day":[["noun.time"],["calendar day","civil day","time period","week"]],
"admission day":[["noun.time"],["Admission Day","day1"]],
"arbor day":[["noun.time"],["Arbor Day","day1"]],
"cinco de mayo":[["noun.time"],["Cinco de Mayo","day1"]],
"commencement day":[["noun.time"],["commencement day","degree day","day1"]],
"november \"":[["noun.time","noun.location:Britain"],["November 5\"","day1","November"]],
"guy fawkes day":[["noun.time","noun.location:Britain"],["Guy Fawkes Day","November 5\""]],
"bonfire night":[["noun.time"],["Bonfire Night","Guy Fawkes Night","November 5\""]],
"inauguration day":[["noun.time"],["Inauguration Day","January 20\"","day1","January"]],
"leap day":[["noun.time"],["leap day","bissextile day","February 29\"","day1","February"]],
"future date":[["noun.time"],["future date","date5"]],
"rain date":[["noun.time"],["rain date","date5"]],
"sell-by date":[["noun.time","noun.location:Britain"],["sell-by date","date5"]],
"quarter day":[["noun.time","noun.location:Britain"],["quarter day","Christian holy day"]],
"fast day":[["noun.time"],["fast day","religious holiday"]],
"major fast day":[["noun.time"],["major fast day","fast day"]],
"minor fast day":[["noun.time"],["minor fast day","fast day"]],
"feast day":[["noun.time"],["feast day","fete day","holiday1","religious festival"]],
"succoth":[["noun.time","noun.cognition:Judaism"],["Succoth","Sukkoth","Succos","Feast of Booths","Feast of Tabernacles","Tabernacles","religious festival","Jewish holy day","Tishri"]],
"religious festival":[["noun.time"],["religious festival","church festival","festival"]],
"d-day":[["noun.time"],["D-day","6\" June 1944\"","date"]],
"v-day":[["noun.time"],["V-day","Victory Day","day1"]],
"v-e day":[["noun.time"],["V-E Day","8\" May 1945\"","V-day"]],
"v-j day":[["noun.time"],["V-J Day","15\" August 1945\"","V-day"]],
"day of the week":[["noun.time"],["day of the week","calendar day","week"]],
"weekday":[["noun.time"],["weekday","day of the week"]],
"monday":[["noun.time"],["Monday","Mon","weekday"]],
"tuesday":[["noun.time"],["Tuesday","Tues","weekday"]],
"wednesday":[["noun.time"],["Wednesday","Midweek1","Wed","weekday"]],
"thursday":[["noun.time"],["Thursday","Th","weekday"]],
"friday":[["noun.time"],["Friday","Fri","weekday"]],
"saturday":[["noun.time"],["Saturday","Sabbatum","Sat","weekday","weekend"]],
"sabbath":[["noun.time","adj.pert:sabbatical1","adj.pert:sabbatarian"],["Sabbath","rest day"]],
"morning":[["noun.time"],["morning","morn","morning time","forenoon","time period","day2"]],
"noon":[["noun.time"],["noon","twelve noon","high noon","midday","noonday","noontide","hour1","day"]],
"mealtime":[["noun.time"],["mealtime","hour1"]],
"breakfast time":[["noun.time"],["breakfast time","mealtime"]],
"lunchtime":[["noun.time"],["lunchtime","lunch period","mealtime"]],
"dinnertime":[["noun.time"],["dinnertime","suppertime","mealtime"]],
"afternoon":[["noun.time"],["afternoon","daytime"]],
"midafternoon":[["noun.time"],["midafternoon","daytime","afternoon"]],
"evening":[["noun.time","noun.time","noun.time","noun.communication:figure of speech"],["evening","eve","even","eventide","daytime","evening2","time period","night","evening1","time period"]],
"guest night":[["noun.time","noun.location:Britain"],["guest night","evening"]],
"prime time":[["noun.time"],["prime time","time3"]],
"weeknight":[["noun.time"],["weeknight","night"]],
"late-night hour":[["noun.time"],["late-night hour","hour1","night"]],
"midnight":[["noun.time"],["midnight","hour1","night"]],
"small hours":[["noun.time"],["small hours","hour1","night"]],
"bedtime":[["noun.time"],["bedtime","hour1"]],
"lights-out":[["noun.time"],["lights-out","bedtime","night"]],
"closing time":[["noun.time"],["closing time","hour1"]],
"early-morning hour":[["noun.time"],["early-morning hour","hour1","morning"]],
"week from monday":[["noun.time","noun.communication:colloquialism"],["week from Monday","week"]],
"fortnight":[["noun.time","adj.all:periodic^fortnightly"],["fortnight","two weeks","time period"]],
"rag day":[["noun.time","noun.location:Britain"],["rag day","day1","rag"]],
"red-letter day":[["noun.time"],["red-letter day","day1"]],
"judgment day":[["noun.time","noun.communication:New Testament"],["Judgment Day","Judgement Day","Day of Judgment","Day of Judgement","Doomsday","Last Judgment","Last Judgement","Last Day","eschaton","day of reckoning","doomsday","crack of doom","end of the world","day3"]],
"off-day":[["noun.time"],["off-day","day3"]],
"access time":[["noun.time","noun.cognition:computer science"],["access time","time interval"]],
"payday":[["noun.time"],["payday","day1"]],
"polling day":[["noun.time"],["polling day","election day","day1"]],
"church year":[["noun.time"],["church year","Christian year","year1"]],
"timekeeping":[["noun.time","noun.act:activity"],["timekeeping"]],
"roman calendar":[["noun.time"],["Roman calendar","lunar calendar"]],
"ides":[["noun.time"],["ides","day1"]],
"market day":[["noun.time"],["market day","day1"]],
"gregorian calendar":[["noun.time"],["Gregorian calendar","New Style calendar","solar calendar"]],
"julian calendar":[["noun.time"],["Julian calendar","Old Style calendar","solar calendar"]],
"revolutionary calendar":[["noun.time"],["Revolutionary calendar","solar calendar"]],
"revolutionary calendar month":[["noun.time"],["Revolutionary calendar month","calendar month","Revolutionary calendar"]],
"vendemiaire":[["noun.time"],["Vendemiaire","Revolutionary calendar month","Revolutionary calendar"]],
"brumaire":[["noun.time"],["Brumaire","Revolutionary calendar month","Revolutionary calendar"]],
"frimaire":[["noun.time"],["Frimaire","Revolutionary calendar month","Revolutionary calendar"]],
"nivose":[["noun.time"],["Nivose","Revolutionary calendar month","Revolutionary calendar"]],
"pluviose":[["noun.time"],["Pluviose","Revolutionary calendar month","Revolutionary calendar"]],
"ventose":[["noun.time"],["Ventose","Revolutionary calendar month","Revolutionary calendar"]],
"germinal":[["noun.time"],["Germinal","Revolutionary calendar month","Revolutionary calendar"]],
"floreal":[["noun.time"],["Floreal","Revolutionary calendar month","Revolutionary calendar"]],
"prairial":[["noun.time"],["Prairial","Revolutionary calendar month","Revolutionary calendar"]],
"messidor":[["noun.time"],["Messidor","Revolutionary calendar month","Revolutionary calendar"]],
"thermidor":[["noun.time"],["Thermidor","Revolutionary calendar month","Revolutionary calendar"]],
"fructidor":[["noun.time"],["Fructidor","Revolutionary calendar month","Revolutionary calendar"]],
"jewish calendar":[["noun.time","noun.cognition:Judaism"],["Jewish calendar","Hebrew calendar","lunisolar calendar"]],
"lunar calendar":[["noun.time"],["lunar calendar","calendar"]],
"lunisolar calendar":[["noun.time"],["lunisolar calendar","calendar"]],
"solar calendar":[["noun.time"],["solar calendar","calendar"]],
"islamic calendar":[["noun.time"],["Islamic calendar","Muhammadan calendar","Mohammedan calendar","Moslem calendar","Muslim calendar","lunar calendar"]],
"hindu calendar":[["noun.time"],["Hindu calendar","lunisolar calendar"]],
"deadline":[["noun.time"],["deadline","point in time"]],
"arrival time":[["noun.time"],["arrival time","time of arrival","point"]],
"departure time":[["noun.time"],["departure time","time of departure","point"]],
"holy week":[["noun.time"],["Holy Week","Passion Week","week","church calendar"]],
"holy year":[["noun.time","noun.group:Roman Catholic"],["Holy Year","year1"]],
"church calendar":[["noun.time"],["church calendar","ecclesiastical calendar","Gregorian calendar"]],
"walpurgis night":[["noun.time"],["Walpurgis Night","day1"]],
"new year's eve":[["noun.time"],["New Year's Eve","December 31\"","day1","December"]],
"new year's day":[["noun.time"],["New Year's Day","New Year's","January 1\"","legal holiday","January"]],
"new year":[["noun.time"],["New Year","year1"]],
"martin luther king jr's birthday":[["noun.time"],["Martin Luther King Jr's Birthday","Martin Luther King Day","legal holiday","January"]],
"robert e lee's birthday":[["noun.time"],["Robert E Lee's Birthday","Robert E Lee Day","Lee's Birthday","January 19\"","day1"]],
"hogmanay":[["noun.time"],["Hogmanay","New Year's Eve"]],
"rosh hashanah":[["noun.time","noun.cognition:Judaism"],["Rosh Hashanah","Rosh Hashana","Rosh Hashonah","Rosh Hashona","Jewish New Year","high holy day","feast day"]],
"rosh hodesh":[["noun.time","noun.cognition:Judaism"],["Rosh Hodesh","Rosh Chodesh","Jewish holy day"]],
"tet":[["noun.time"],["Tet","day1","January"]],
"holiday":[["noun.time"],["holiday1","day1"]],
"religious holiday":[["noun.time"],["religious holiday","holy day1","holiday1","church year"]],
"high holy day":[["noun.time"],["High Holy Day","High Holiday","Jewish holy day"]],
"christian holy day":[["noun.time"],["Christian holy day","religious holiday"]],
"jewish holy day":[["noun.time"],["Jewish holy day","religious holiday"]],
"holy day of obligation":[["noun.time"],["holy day of obligation","Christian holy day"]],
"movable feast":[["noun.time"],["movable feast","moveable feast","feast day"]],
"yom kippur":[["noun.time","noun.cognition:Judaism"],["Yom Kippur","Day of Atonement","high holy day","major fast day"]],
"saint agnes's eve":[["noun.time"],["Saint Agnes's Eve","January 20\"1","Christian holy day","January"]],
"martinmas":[["noun.time"],["Martinmas","St Martin's Day","11 November","quarter day","November"]],
"indian summer":[["noun.time"],["Indian summer","Saint Martin's summer","time period","autumn"]],
"michaelmas":[["noun.time"],["Michaelmas","Michaelmas Day","September 29\"","quarter day","September"]],
"michaelmastide":[["noun.time"],["Michaelmastide","season1"]],
"candlemas":[["noun.time"],["Candlemas","Candlemas Day","Feb 2\"","quarter day","February"]],
"groundhog day":[["noun.time","noun.location:US"],["Groundhog Day","February 2\"","day1","February"]],
"lincoln's birthday":[["noun.time","noun.location:US"],["Lincoln's Birthday","February 12\"","day1","February"]],
"valentine day":[["noun.time"],["Valentine Day","Valentine's Day","Saint Valentine's Day","St Valentine's Day","February 14\"","day1","February"]],
"washington's birthday":[["noun.time","noun.location:US"],["Washington's Birthday","February 22\"","day1","February"]],
"presidents' day":[["noun.time","noun.location:US"],["Presidents' Day","legal holiday","February"]],
"texas independence day":[["noun.time"],["Texas Independence Day","March 2\"","day1","March"]],
"st patrick's day":[["noun.time"],["St Patrick's Day","Saint Patrick's Day","March 17\"","day1"]],
"easter":[["noun.time"],["Easter","movable feast"]],
"easter sunday":[["noun.time"],["Easter Sunday","Easter Day","Christian holy day"]],
"april fools'":[["noun.time"],["April Fools'","April Fools' day","All Fools' day","day1","April"]],
"pan american day":[["noun.time"],["Pan American Day","April 14\"","day1","April"]],
"patriot's day":[["noun.time"],["Patriot's Day","day1","April"]],
"may day":[["noun.time"],["May Day","First of May","May 1\"","day1","May"]],
"mother's day":[["noun.time"],["Mother's Day","day1","May"]],
"armed forces day":[["noun.time"],["Armed Forces Day","day1","May"]],
"memorial day":[["noun.time"],["Memorial Day","Decoration Day","legal holiday","May"]],
"jefferson davis' birthday":[["noun.time"],["Jefferson Davis' Birthday","Davis' Birthday","June 3\"","day1","June"]],
"flag day":[["noun.time"],["Flag Day","June 14\"","day1","June"]],
"father's day":[["noun.time"],["Father's Day","day1","June"]],
"independence day":[["noun.time"],["Independence Day","Fourth of July","July 4\"","legal holiday","July"]],
"lammas":[["noun.time"],["Lammas","Lammas Day","August 1\"","quarter day"]],
"lammastide":[["noun.time","noun.location:Scotland"],["Lammastide","season1"]],
"labor day":[["noun.time"],["Labor Day","legal holiday","September"]],
"citizenship day":[["noun.time"],["Citizenship Day","September 17\"","day1","September"]],
"american indian day":[["noun.time"],["American Indian Day","day1","September"]],
"columbus day":[["noun.time"],["Columbus Day","Discovery Day","October 12\"","legal holiday","October"]],
"united nations day":[["noun.time"],["United Nations Day","October 24\"","day1","October"]],
"halloween":[["noun.time"],["Halloween","Hallowe'en","Allhallows Eve","day1"]],
"pasch":[["noun.time","noun.time"],["Pasch","Pascha","Easter","Pasch1","Pascha1","Passover"]],
"eastertide":[["noun.time"],["Eastertide","season1"]],
"palm sunday":[["noun.time"],["Palm Sunday","Christian holy day"]],
"passion sunday":[["noun.time"],["Passion Sunday","Christian holy day"]],
"good friday":[["noun.time"],["Good Friday","Christian holy day","Lent"]],
"low sunday":[["noun.time"],["Low Sunday","Christian holy day"]],
"holy saturday":[["noun.time"],["Holy Saturday","Christian holy day"]],
"holy innocents' day":[["noun.time"],["Holy Innocents' Day","Innocents' Day","Christian holy day"]],
"septuagesima":[["noun.time"],["Septuagesima","Septuagesima Sunday","Christian holy day"]],
"quinquagesima":[["noun.time"],["Quinquagesima","Quinquagesima Sunday","Christian holy day"]],
"quadragesima":[["noun.time"],["Quadragesima","Quadrigesima Sunday","Christian holy day"]],
"trinity sunday":[["noun.time"],["Trinity Sunday","Christian holy day"]],
"rogation day":[["noun.time"],["Rogation Day","Christian holy day"]],
"solemnity of mary":[["noun.time","noun.group:Roman Catholic"],["Solemnity of Mary","January 1\"1","holy day of obligation","January"]],
"maundy thursday":[["noun.time"],["Maundy Thursday","Holy Thursday","Christian holy day"]],
"saints peter and paul":[["noun.time"],["Saints Peter and Paul","June 29\"","Christian holy day","June"]],
"dormition":[["noun.time"],["Dormition","Feast of Dormition","religious holiday","August"]],
"twelfthtide":[["noun.time"],["Twelfthtide","season1"]],
"twelfth night":[["noun.time"],["Twelfth night","Christian holy day","January"]],
"all saints' day":[["noun.time"],["All Saints' Day","Allhallows","November 1\"","Hallowmas","Hallowmass","holy day of obligation","November"]],
"allhallowtide":[["noun.time"],["Allhallowtide","season1"]],
"all souls' day":[["noun.time"],["All Souls' Day","November 2\"","Christian holy day","November"]],
"ash wednesday":[["noun.time"],["Ash Wednesday","Christian holy day","Lent"]],
"ember day":[["noun.time"],["Ember Day","Christian holy day"]],
"passover":[["noun.time","noun.cognition:Judaism"],["Passover","Pesach","Pesah","Feast of the Unleavened Bread","moveable feast"]],
"christmas":[["noun.time","noun.time"],["Christmas","Christmas Day","Xmas","Dec 25\"","legal holiday","holy day of obligation","quarter day","feast day","December","Christmas1","Christmastide","Christmastime","Yule","Yuletide","Noel","season1","December","January"]],
"christmas eve":[["noun.time"],["Christmas Eve","Dec 24\"","holiday1"]],
"boxing day":[["noun.time","noun.location:Britain"],["Boxing Day","legal holiday","Christmastide"]],
"purim":[["noun.time","noun.cognition:Judaism"],["Purim","Jewish holy day","Adar"]],
"shavous":[["noun.time","adj.pert:pentecostal","noun.cognition:Judaism"],["Shavous","Shabuoth","Shavuoth","Shavuot","Pentecost2","Feast of Weeks","Jewish holy day"]],
"shimchath torah":[["noun.time","noun.cognition:Judaism"],["Shimchath Torah","Simchat Torah","Simhath Torah","Simhat Torah","Simchas Torah","Rejoicing over the Law","Rejoicing of the Law","Rejoicing in the Law","Jewish holy day"]],
"tishah b'av":[["noun.time","noun.cognition:Judaism"],["Tishah b'Av","Tishah b'Ab","Tisha b'Av","Tisha b'Ab","Ninth of Av","Ninth of Ab","Fast of Av","Fast of Ab","Jewish holy day","major fast day"]],
"fast of gedaliah":[["noun.time","noun.cognition:Judaism"],["Fast of Gedaliah","minor fast day"]],
"fast of tevet":[["noun.time","noun.cognition:Judaism"],["Fast of Tevet","minor fast day"]],
"fast of esther":[["noun.time","noun.cognition:Judaism"],["Fast of Esther","minor fast day"]],
"fast of the firstborn":[["noun.time","noun.cognition:Judaism"],["Fast of the Firstborn","minor fast day"]],
"fast of tammuz":[["noun.time","noun.cognition:Judaism"],["Fast of Tammuz","minor fast day"]],
"hanukkah":[["noun.time","noun.cognition:Judaism"],["Hanukkah","Hanukah","Hannukah","Chanukah","Chanukkah","Channukah","Channukkah","Festival of Lights","Feast of Lights","Feast of Dedication","Feast of the Dedication","Jewish holy day","Kislev","Tebet"]],
"lag b'omer":[["noun.time","noun.cognition:Judaism"],["Lag b'Omer","Jewish holy day","Iyar"]],
"legal holiday":[["noun.time"],["legal holiday","national holiday","public holiday","holiday1"]],
"bank holiday":[["noun.time"],["bank holiday","legal holiday"]],
"commonwealth day":[["noun.time"],["Commonwealth Day","Empire day","May 24\"","legal holiday","May"]],
"dominion day":[["noun.time","noun.location:Canada"],["Dominion Day","July 1\"","legal holiday","July"]],
"bastille day":[["noun.time"],["Bastille Day","14 July","legal holiday","July"]],
"remembrance day":[["noun.time","noun.location:Great Britain1","noun.location:Canada"],["Remembrance Day","Remembrance Sunday","Poppy Day","holiday1"]],
"veterans day":[["noun.time"],["Veterans Day","Veterans' Day","Armistice Day","November 11\"","legal holiday","November"]],
"thanksgiving":[["noun.time"],["Thanksgiving","Thanksgiving Day","legal holiday","feast day","November"]],
"victoria day":[["noun.time"],["Victoria Day","legal holiday"]],
"year":[["noun.time","noun.time","adj.all:periodic^yearly","noun.time"],["year","time period","year1","twelvemonth","yr","time period","decade","year2","time period"]],
"anomalistic year":[["noun.time"],["anomalistic year","year"]],
"year-end":[["noun.time"],["year-end","end"]],
"common year":[["noun.time"],["common year","365\" days","year1"]],
"leap year":[["noun.time"],["leap year","intercalary year","366 days","bissextile year","year1"]],
"off year":[["noun.time","noun.time"],["off year","year1","off year1","year1"]],
"calendar year":[["noun.time"],["calendar year","civil year","year1"]],
"solar year":[["noun.time"],["solar year","tropical year","astronomical year","equinoctial year","year"]],
"lunar year":[["noun.time"],["lunar year","year"]],
"fiscal year":[["noun.time"],["fiscal year","financial year","year1"]],
"school year":[["noun.time"],["school year","academic year","year2"]],
"annum":[["noun.time","noun.communication:Latin"],["annum","year1"]],
"semester":[["noun.time","adj.all:periodic^semestrial","adj.all:periodic^semestral","noun.time","adj.all:periodic^semestral"],["semester2","time period","semester1","school term","school year"]],
"bimester":[["noun.time","adj.all:long2^bimestrial","adj.all:periodic^bimestrial"],["bimester","time period"]],
"olympiad":[["noun.time"],["Olympiad","time period"]],
"decade":[["noun.time"],["decade","decennary","decennium","time period","century"]],
"century":[["noun.time"],["century","time period","millennium"]],
"quadrennium":[["noun.time"],["quadrennium","time period"]],
"quinquennium":[["noun.time"],["quinquennium","time period"]],
"quattrocento":[["noun.time"],["quattrocento","century","Renaissance"]],
"twentieth century":[["noun.time"],["twentieth century","century"]],
"half-century":[["noun.time"],["half-century","time period","century"]],
"quarter-century":[["noun.time"],["quarter-century","time period","century"]],
"month":[["noun.time","adj.all:periodic^monthly"],["month","time unit","year"]],
"phase of the moon":[["noun.time","noun.attribute:phase"],["phase of the moon","time period"]],
"new moon":[["noun.time"],["new moon","new phase of the moon","phase of the moon","month"]],
"first quarter":[["noun.time"],["first quarter","half-moon"]],
"last quarter":[["noun.time"],["last quarter","half-moon"]],
"full moon":[["noun.time"],["full moon","full-of-the-moon","full phase of the moon","full","phase of the moon","month"]],
"harvest moon":[["noun.time"],["harvest moon","full moon"]],
"lunar month":[["noun.time"],["lunar month","moon","lunation","synodic month","month","lunar year"]],
"anomalistic month":[["noun.time"],["anomalistic month","month"]],
"sidereal time":[["noun.time"],["sidereal time","cosmic time"]],
"sidereal day":[["noun.time"],["sidereal day","day6","time unit","sidereal time"]],
"lunar day":[["noun.time"],["lunar day","day7"]],
"sidereal year":[["noun.time"],["sidereal year","year","sidereal time"]],
"sidereal hour":[["noun.time"],["sidereal hour","hour","sidereal time"]],
"sidereal month":[["noun.time"],["sidereal month","month","sidereal time"]],
"solar month":[["noun.time"],["solar month","month"]],
"calendar month":[["noun.time","adj.all:periodic^monthly"],["calendar month","month1","time period"]],
"gregorian calendar month":[["noun.time"],["Gregorian calendar month","calendar month","Gregorian calendar"]],
"january":[["noun.time"],["January","Jan","Gregorian calendar month","Gregorian calendar"]],
"mid-january":[["noun.time"],["mid-January","time period","January"]],
"february":[["noun.time"],["February","Feb","Gregorian calendar month","Gregorian calendar"]],
"mid-february":[["noun.time"],["mid-February","time period","February"]],
"mid-march":[["noun.time"],["mid-March","time period","March"]],
"april":[["noun.time"],["April","Apr","Gregorian calendar month","Gregorian calendar"]],
"mid-april":[["noun.time"],["mid-April","time period","April"]],
"may":[["noun.time"],["May","Gregorian calendar month","Gregorian calendar"]],
"mid-may":[["noun.time"],["mid-May","time period","May"]],
"june":[["noun.time"],["June","Gregorian calendar month","Gregorian calendar"]],
"mid-june":[["noun.time"],["mid-June","time period","June"]],
"july":[["noun.time"],["July","Gregorian calendar month","Gregorian calendar"]],
"mid-july":[["noun.time"],["mid-July","time period","July"]],
"august":[["noun.time"],["August","Aug","Gregorian calendar month","Gregorian calendar"]],
"mid-august":[["noun.time"],["mid-August","time period","August"]],
"september":[["noun.time"],["September","Sep","Sept","Gregorian calendar month","Gregorian calendar"]],
"mid-september":[["noun.time"],["mid-September","time period","September"]],
"october":[["noun.time"],["October","Oct","Gregorian calendar month","Gregorian calendar"]],
"mid-october":[["noun.time"],["mid-October","time period","October"]],
"november":[["noun.time"],["November","Nov","Gregorian calendar month","Gregorian calendar"]],
"mid-november":[["noun.time"],["mid-November","time period","November"]],
"december":[["noun.time"],["December","Dec","Gregorian calendar month","Gregorian calendar"]],
"mid-december":[["noun.time"],["mid-December","time period","December"]],
"jewish calendar month":[["noun.time"],["Jewish calendar month","calendar month","Jewish calendar"]],
"tishri":[["noun.time"],["Tishri","Jewish calendar month","Jewish calendar"]],
"heshvan":[["noun.time"],["Heshvan","Jewish calendar month","Jewish calendar"]],
"kislev":[["noun.time"],["Kislev","Chislev","Jewish calendar month","Jewish calendar"]],
"tebet":[["noun.time"],["Tebet","Tevet","Jewish calendar month","Jewish calendar"]],
"shebat":[["noun.time"],["Shebat","Shevat","Jewish calendar month","Jewish calendar"]],
"adar":[["noun.time"],["Adar","Jewish calendar month","Jewish calendar"]],
"veadar":[["noun.time"],["Veadar","Adar Sheni","Jewish calendar month","Jewish calendar"]],
"nisan":[["noun.time"],["Nisan","Nissan","Jewish calendar month","Jewish calendar"]],
"iyar":[["noun.time"],["Iyar","Iyyar","Jewish calendar month","Jewish calendar"]],
"sivan":[["noun.time"],["Sivan","Siwan","Jewish calendar month","Jewish calendar"]],
"tammuz":[["noun.time"],["Tammuz","Thammuz","Jewish calendar month","Jewish calendar"]],
"elul":[["noun.time"],["Elul","Ellul","Jewish calendar month","Jewish calendar"]],
"islamic calendar month":[["noun.time"],["Islamic calendar month","calendar month","Islamic calendar"]],
"muharram":[["noun.time"],["Muharram","Moharram","Muharrum","Islamic calendar month","Muhammadan calendar"]],
"safar":[["noun.time"],["Safar","Saphar","Islamic calendar month","Muhammadan calendar"]],
"rabi i":[["noun.time"],["Rabi I","Islamic calendar month","Muhammadan calendar"]],
"rabi ii":[["noun.time"],["Rabi II","Islamic calendar month","Muhammadan calendar"]],
"jumada i":[["noun.time"],["Jumada I","Jomada I","Islamic calendar month","Muhammadan calendar"]],
"jumada ii":[["noun.time"],["Jumada II","Jomada II","Islamic calendar month","Muhammadan calendar"]],
"rajab":[["noun.time"],["Rajab","Islamic calendar month","Muhammadan calendar"]],
"sha'ban":[["noun.time"],["Sha'ban","Shaaban","Islamic calendar month","Muhammadan calendar"]],
"id al-fitr":[["noun.time"],["Id al-Fitr","feast day"]],
"shawwal":[["noun.time"],["Shawwal","Islamic calendar month","Muhammadan calendar"]],
"dhu'l-qa'dah":[["noun.time"],["Dhu'l-Qa'dah","Dhu al-Qadah","Islamic calendar month","Muhammadan calendar"]],
"dhu'l-hijja":[["noun.time"],["Dhu'l-Hijja","Dhu'l-Hijjah","Dhu al-Hijja","Dhu al-Hijjah","Islamic calendar month","Muhammadan calendar"]],
"id al-adha":[["noun.time"],["Id al-Adha","Feast of Sacrifice","feast day"]],
"hindu calendar month":[["noun.time"],["Hindu calendar month","calendar month","Hindu calendar"]],
"chait":[["noun.time"],["Chait","Caitra","Hindu calendar month","Hindu calendar"]],
"ramanavami":[["noun.time"],["Ramanavami","holiday1","Chait"]],
"baisakh":[["noun.time"],["Baisakh","Vaisakha","Hindu calendar month","Hindu calendar"]],
"jeth":[["noun.time"],["Jeth","Jyaistha","Hindu calendar month","Hindu calendar"]],
"asarh":[["noun.time"],["Asarh","Asadha","Hindu calendar month","Hindu calendar"]],
"sawan":[["noun.time"],["Sawan","Sravana","Hindu calendar month","Hindu calendar"]],
"bhadon":[["noun.time"],["Bhadon","Bhadrapada","Hindu calendar month","Hindu calendar"]],
"asin":[["noun.time"],["Asin","Asvina","Hindu calendar month","Hindu calendar"]],
"kartik":[["noun.time"],["Kartik","Karttika","Hindu calendar month","Hindu calendar"]],
"aghan":[["noun.time"],["Aghan","Margasivsa","Hindu calendar month","Hindu calendar"]],
"magh":[["noun.time"],["Magh","Magha","Hindu calendar month","Hindu calendar"]],
"mesasamkranti":[["noun.time"],["Mesasamkranti","holiday1","Magh"]],
"phagun":[["noun.time"],["Phagun","Phalguna","Hindu calendar month","Hindu calendar"]],
"saint's day":[["noun.time"],["saint's day","day1","church year"]],
"name day":[["noun.time"],["name day","saint's day"]],
"solstice":[["noun.time"],["solstice","cosmic time"]],
"summer solstice":[["noun.time"],["summer solstice","winter solstice","June 21\"","midsummer","solstice","June","summer"]],
"midsummer day":[["noun.time"],["Midsummer Day","Midsummer's Day","St John's Day","June 24\"","quarter day","June"]],
"midsummer eve":[["noun.time"],["Midsummer Eve","Midsummer Night","St John's Eve","St John's Night","June 23\"","day1","June"]],
"school day":[["noun.time"],["school day","day1"]],
"speech day":[["noun.time","noun.location:Britain"],["speech day","day1"]],
"washday":[["noun.time"],["washday","washing day","day1"]],
"wedding day":[["noun.time"],["wedding day","day1"]],
"wedding night":[["noun.time"],["wedding night","night","wedding day"]],
"winter solstice":[["noun.time"],["winter solstice","summer solstice","solstice","winter"]],
"equinox":[["noun.time","adj.pert:equinoctial"],["equinox","cosmic time"]],
"noruz":[["noun.time","noun.communication:Persian"],["Noruz","Nowruz","Nowrooz","vernal equinox"]],
"time limit":[["noun.time"],["time limit","time period"]],
"prison term":[["noun.time","verb.communication:sentence"],["prison term","sentence","time1","term"]],
"life sentence":[["noun.time","noun.person:lifer"],["life sentence","life3","prison term"]],
"school term":[["noun.time"],["school term","academic term","academic session","session","term","school year"]],
"summer school":[["noun.time"],["summer school","school term"]],
"midterm":[["noun.time","noun.time"],["midterm","point in time","term","midterm1","point in time","gestation"]],
"trimester":[["noun.time"],["trimester","time period","gestation"]],
"first trimester":[["noun.time"],["first trimester","trimester"]],
"second trimester":[["noun.time"],["second trimester","trimester"]],
"third trimester":[["noun.time"],["third trimester","trimester"]],
"refractory period":[["noun.time","noun.cognition:neurology1"],["refractory period","biological time"]],
"half-hour":[["noun.time"],["half-hour","30\" minutes","time unit","hour"]],
"quarter-hour":[["noun.time"],["quarter-hour","15\" minutes","time unit","hour"]],
"happy hour":[["noun.time"],["happy hour","hour1"]],
"rush hour":[["noun.time"],["rush hour","hour1"]],
"zero hour":[["noun.time"],["zero hour","hour1"]],
"canonical hour":[["noun.time","noun.group:Roman Catholic"],["canonical hour","hour1"]],
"matins":[["noun.time"],["matins","morning prayer","canonical hour"]],
"terce":[["noun.time"],["terce","tierce","canonical hour"]],
"sext":[["noun.time"],["sext","canonical hour"]],
"nones":[["noun.time"],["nones","canonical hour"]],
"vespers":[["noun.time"],["vespers","evensong","canonical hour"]],
"compline":[["noun.time"],["compline","complin","canonical hour"]],
"man hour":[["noun.time"],["man hour","person hour","hour","workday"]],
"silly season":[["noun.time"],["silly season","time period"]],
"golden age":[["noun.time","noun.group:classical mythology","noun.time","noun.time"],["Golden Age","time period","golden age1","age2","golden age2","flower"]],
"silver age":[["noun.time","noun.group:classical mythology"],["silver age","time period"]],
"bronze age":[["noun.time","noun.group:classical mythology","noun.time","noun.cognition:archeology"],["bronze age","time period","Bronze Age1","time period","prehistory"]],
"iron age":[["noun.time","noun.group:classical mythology","noun.time","noun.cognition:archeology"],["iron age","time period","Iron Age1","time period","prehistory"]],
"stone age":[["noun.time","noun.cognition:archeology"],["Stone Age","time period","prehistory"]],
"eolithic age":[["noun.time"],["Eolithic Age","Eolithic","time period","Stone Age"]],
"paleolithic age":[["noun.time"],["Paleolithic Age","Paleolithic","Palaeolithic","time period","Stone Age"]],
"lower paleolithic":[["noun.time"],["Lower Paleolithic","time period","Paleolithic Age"]],
"middle paleolithic":[["noun.time"],["Middle Paleolithic","time period","Paleolithic Age"]],
"upper paleolithic":[["noun.time"],["Upper Paleolithic","time period","Paleolithic Age"]],
"mesolithic age":[["noun.time"],["Mesolithic Age","Mesolithic","Epipaleolithic","time period","Stone Age"]],
"neolithic age":[["noun.time"],["Neolithic Age","Neolithic","New Stone Age","time period","Stone Age"]],
"great year":[["noun.time"],["great year","Platonic year","time period"]],
"regulation time":[["noun.time","noun.act:athletic game","noun.act:sport"],["regulation time","overtime","time period"]],
"extra innings":[["noun.time"],["extra innings","overtime"]],
"overtime period":[["noun.time"],["overtime period","overtime"]],
"tiebreaker":[["noun.time"],["tiebreaker","overtime"]],
"sudden death":[["noun.time","noun.act:sport"],["sudden death","overtime"]],
"leap second":[["noun.time"],["leap second","second"]],
"attosecond":[["noun.time"],["attosecond","time unit","femtosecond"]],
"femtosecond":[["noun.time"],["femtosecond","time unit","picosecond"]],
"picosecond":[["noun.time"],["picosecond","time unit","nanosecond"]],
"nanosecond":[["noun.time"],["nanosecond","time unit","microsecond"]],
"microsecond":[["noun.time"],["microsecond","time unit","millisecond"]],
"millisecond":[["noun.time"],["millisecond","msec","time unit","second"]],
"dog days":[["noun.time","adj.pert:canicular2","adj.pert:canicular"],["dog days","canicule","canicular days","time period","summer"]],
"midwinter":[["noun.time"],["midwinter","time period","winter"]],
"growing season":[["noun.time"],["growing season","season2"]],
"seedtime":[["noun.time","noun.time"],["seedtime","season2","seedtime1","phase"]],
"holiday season":[["noun.time"],["holiday season","season2"]],
"high season":[["noun.time"],["high season","off-season","peak season","season2"]],
"off-season":[["noun.time"],["off-season","high season","season2"]],
"rainy season":[["noun.time"],["rainy season","dry season","season"]],
"dry season":[["noun.time"],["dry season","rainy season","season"]],
"preseason":[["noun.time"],["preseason","season2"]],
"spring training":[["noun.time"],["spring training","preseason"]],
"baseball season":[["noun.time"],["baseball season","season2"]],
"triple-crown season":[["noun.time"],["triple-crown season","baseball season"]],
"basketball season":[["noun.time"],["basketball season","season2"]],
"exhibition season":[["noun.time"],["exhibition season","season2"]],
"fishing season":[["noun.time"],["fishing season","season2"]],
"football season":[["noun.time"],["football season","season2"]],
"hockey season":[["noun.time"],["hockey season","season2"]],
"hunting season":[["noun.time"],["hunting season","season2"]],
"social season":[["noun.time"],["social season","season2"]],
"theatrical season":[["noun.time"],["theatrical season","season2"]],
"advent sunday":[["noun.time"],["Advent Sunday","Christian holy day","Advent1"]],
"shrovetide":[["noun.time"],["Shrovetide","season1","church calendar"]],
"lent":[["noun.time"],["Lent","Lententide","season1","church calendar"]],
"pentecost":[["noun.time","adj.pert:pentecostal"],["Pentecost1","Whitsunday","quarter day","Whitsun"]],
"whitmonday":[["noun.time"],["Whitmonday","Whitsun Monday","Monday","Whitsun"]],
"whit-tuesday":[["noun.time"],["Whit-Tuesday","Whitsun Tuesday","Tuesday","Whitsun"]],
"whitsun":[["noun.time"],["Whitsun","Whitsuntide","Whitweek","season2","church calendar"]],
"long time":[["noun.time"],["long time","age3","years1","time period"]],
"month of sundays":[["noun.time","noun.communication:colloquialism"],["month of Sundays","long time"]],
"long run":[["noun.time"],["long run","long haul","time period"]],
"blue moon":[["noun.time","noun.communication:colloquialism"],["blue moon","long time"]],
"year dot":[["noun.time","noun.location:Britain"],["year dot","long time"]],
"eleventh hour":[["noun.time"],["eleventh hour","last minute","moment"]],
"moment of truth":[["noun.time","noun.time","noun.act:bullfighting"],["moment of truth","moment","moment of truth1","moment"]],
"high time":[["noun.time"],["high time","time6"]],
"psychological moment":[["noun.time"],["psychological moment","moment"]],
"wee":[["noun.time","noun.location:Scotland"],["wee","time"]],
"while":[["noun.time"],["while","piece","spell1","patch","time"]],
"cold spell":[["noun.time"],["cold spell","cold snap","while"]],
"hot spell":[["noun.time"],["hot spell","while"]],
"blink of an eye":[["noun.time","verb.perception:flash2"],["blink of an eye","flash","heartbeat","instant1","jiffy","split second","trice","twinkling","wink","New York minute","moment1"]],
"ephemera":[["noun.time","adj.all:impermanent^ephemeral"],["ephemera","time"]],
"era":[["noun.time","adj.all:significant^epochal"],["era","epoch","time period"]],
"epoch":[["noun.time","noun.time","noun.cognition:astronomy"],["epoch1","geological time","period3","epoch2","date of reference","date3"]],
"christian era":[["noun.time"],["Christian era","Common era","era"]],
"year of grace":[["noun.time"],["year of grace","year1"]],
"y\"k":[["noun.time"],["Y2\"K","year1"]],
"anniversary":[["noun.time"],["anniversary","day of remembrance","day1"]],
"birthday":[["noun.time","noun.time"],["birthday","anniversary","birthday1","natal day","date"]],
"jubilee":[["noun.time","verb.social:jubilate"],["jubilee","anniversary"]],
"diamond jubilee":[["noun.time"],["diamond jubilee","jubilee"]],
"silver jubilee":[["noun.time"],["silver jubilee","jubilee"]],
"wedding anniversary":[["noun.time"],["wedding anniversary","anniversary"]],
"silver wedding anniversary":[["noun.time"],["silver wedding anniversary","wedding anniversary"]],
"golden wedding anniversary":[["noun.time"],["golden wedding anniversary","wedding anniversary"]],
"diamond wedding anniversary":[["noun.time"],["diamond wedding anniversary","diamond wedding","wedding anniversary"]],
"semicentennial":[["noun.time"],["semicentennial","semicentenary","anniversary"]],
"centennial":[["noun.time","adj.pert:centennial","adj.pert:centenary"],["centennial","centenary","anniversary"]],
"sesquicentennial":[["noun.time"],["sesquicentennial","anniversary"]],
"bicentennial":[["noun.time","adj.pert:bicentennial","adj.pert:bicentenary"],["bicentennial","bicentenary","anniversary"]],
"tercentennial":[["noun.time"],["tercentennial","tercentenary","triennial","anniversary"]],
"quatercentennial":[["noun.time"],["quatercentennial","quatercentenary","anniversary"]],
"quincentennial":[["noun.time"],["quincentennial","quincentenary","anniversary"]],
"time immemorial":[["noun.time"],["time immemorial","time out of mind","past"]],
"auld langsyne":[["noun.time"],["auld langsyne","langsyne","old times","good old days","past"]],
"by-and-by":[["noun.time"],["by-and-by","future"]],
"historic period":[["noun.time"],["historic period","age2","era","history"]],
"prehistory":[["noun.time","adj.all:past^prehistoric","adj.pert:prehistoric"],["prehistory","prehistoric culture","time period"]],
"modern era":[["noun.time"],["modern era","era"]],
"information age":[["noun.time"],["information age","modern era"]],
"ice age":[["noun.time"],["ice age","glacial period","glacial epoch1","period3","prehistory"]],
"jazz age":[["noun.time"],["Jazz Age","historic period"]],
"chukker":[["noun.time","noun.cognition:division","noun.act:polo"],["chukker","chukka","playing period"]],
"inning":[["noun.time","noun.cognition:division","noun.act:baseball"],["inning","frame","playing period"]],
"playing period":[["noun.time","verb.competition:play2","verb.competition:play","noun.Tops:measure","noun.act:athletic game","noun.act:game"],["playing period","period of play","play"]],
"first period":[["noun.time","noun.cognition:division"],["first period","playing period"]],
"second period":[["noun.time","noun.cognition:division"],["second period","playing period"]],
"final period":[["noun.time","noun.cognition:division"],["final period","playing period"]],
"half":[["noun.time","noun.cognition:division","noun.act:football","noun.act:basketball"],["half","playing period"]],
"first half":[["noun.time"],["first half","half"]],
"second half":[["noun.time"],["second half","last half","half"]],
"over":[["noun.time","noun.cognition:division","noun.act:cricket"],["over","playing period"]],
"maiden over":[["noun.time","noun.act:cricket"],["maiden over","maiden","over"]],
"middle ages":[["noun.time"],["Middle Ages","Dark Ages","historic period","history"]],
"renaissance":[["noun.time"],["Renaissance","Renascence","historic period","history"]],
"italian renaissance":[["noun.time"],["Italian Renaissance","historic period","Renaissance"]],
"industrial revolution":[["noun.time"],["Industrial Revolution","technological revolution","historic period"]],
"reign of terror":[["noun.time","noun.time","noun.act:terrorism"],["Reign of Terror","historic period","reign of terror1","reign1"]],
"turn of the century":[["noun.time"],["turn of the century","historic period"]],
"harlem renaissance":[["noun.time"],["Harlem Renaissance","historic period"]],
"print run":[["noun.time"],["print run","press run","run"]],
"run-time":[["noun.time","noun.cognition:computer science","noun.time"],["run-time","run","run-time1","point"]],
"split run":[["noun.time"],["split run","print run"]],
"space age":[["noun.time"],["space age","time"]],
"tonight":[["noun.time"],["tonight","present"]],
"manana":[["noun.time"],["manana","future"]],
"common time":[["noun.time"],["common time","four-four time","quadruple time","common measure","musical time"]],
"duple time":[["noun.time"],["duple time","musical time"]],
"triple time":[["noun.time"],["triple time","musical time"]],
"tempo":[["noun.time","verb.cognition:pace"],["tempo","pace1","rate"]],
"in time":[["noun.time"],["in time","musical time"]],
"accelerando":[["noun.time","adj.all:increasing2^accelerando"],["accelerando","tempo1"]],
"allegro con spirito":[["noun.time"],["allegro con spirito","allegro"]],
"meno mosso":[["noun.time"],["meno mosso","tempo1"]],
"rubato":[["noun.time"],["rubato","tempo1"]],
"terminus a quo":[["noun.time"],["terminus a quo","starting point","beginning"]],
"stopping point":[["noun.time","verb.change:finish3","verb.stative:finish","verb.change:finish2","verb.stative:close","verb.social:close1","verb.social:close"],["stopping point","finale","finis","finish","last","conclusion","close","end"]],
"cease":[["noun.time","verb.stative:cease"],["cease","end"]],
"fin de siecle":[["noun.time","noun.communication:French"],["fin de siecle","end"]],
"last gasp":[["noun.time"],["last gasp","end"]],
"terminus ad quem":[["noun.time","verb.communication:limit"],["terminus ad quem","terminal point","limit","end"]],
"seek time":[["noun.time","noun.cognition:computer science"],["seek time","time interval","access time"]],
"track-to-track seek time":[["noun.time","noun.cognition:computer science"],["track-to-track seek time","seek time"]],
"time interval":[["noun.time","noun.Tops:measure"],["time interval","interval"]],
"time slot":[["noun.time","verb.cognition:slot"],["time slot","slot","time interval"]],
"lunitidal interval":[["noun.time"],["lunitidal interval","time interval"]],
"dead air":[["noun.time"],["dead air","pause"]],
"halftime":[["noun.time"],["halftime","pause"]],
"entr'acte":[["noun.time"],["entr'acte","interlude"]],
"interim":[["noun.time"],["interim","meantime","meanwhile","lag","time interval"]],
"latent period":[["noun.time"],["latent period","time interval"]],
"reaction time":[["noun.time"],["reaction time","response time","latency","latent period1","time interval"]],
"interregnum":[["noun.time"],["interregnum","interim"]],
"beauty sleep":[["noun.time"],["beauty sleep","sleep"]],
"time-out":[["noun.time","noun.act:athletic game"],["time-out","pause"]],
"letup":[["noun.time","verb.change:let up","verb.change:let up1","verb.emotion:lull","verb.change:lull","verb.emotion:lull1"],["letup","lull","pause"]],
"half life":[["noun.time"],["half life","half-life","time period"]],
"relaxation time":[["noun.time"],["relaxation time","time constant"]],
"centripetal acceleration":[["noun.time"],["centripetal acceleration","acceleration"]],
"attrition rate":[["noun.time"],["attrition rate","rate of attrition","rate"]],
"birthrate":[["noun.time"],["birthrate","birth rate","fertility","fertility rate","natality","rate"]],
"bits per second":[["noun.time","noun.cognition:computer science"],["bits per second","bps","rate"]],
"crime rate":[["noun.time"],["crime rate","rate"]],
"data rate":[["noun.time"],["data rate","rate"]],
"deathrate":[["noun.time"],["deathrate","death rate","mortality","mortality rate","fatality rate","rate"]],
"dose rate":[["noun.time"],["dose rate","rate"]],
"erythrocyte sedimentation rate":[["noun.time"],["erythrocyte sedimentation rate","ESR","sedimentation rate","sed rate","rate"]],
"cardiac output":[["noun.time"],["cardiac output","flow"]],
"gigahertz":[["noun.time"],["gigahertz","GHz","gigacycle per second","gigacycle","Gc","rate"]],
"growth rate":[["noun.time"],["growth rate","rate of growth","rate"]],
"inflation rate":[["noun.time"],["inflation rate","rate of inflation","rate"]],
"kilohertz":[["noun.time"],["kilohertz","kHz","kilocycle per second","kilocycle","kc","rate","megahertz"]],
"kilometers per hour":[["noun.time","noun.location:Canada","noun.location:Britain"],["kilometers per hour","kilometres per hour","kph","km/h","rate"]],
"megahertz":[["noun.time"],["megahertz","MHz","megacycle per second","megacycle","Mc","rate"]],
"terahertz":[["noun.time"],["terahertz","THz","rate"]],
"metabolic rate":[["noun.time"],["metabolic rate","rate"]],
"miles per hour":[["noun.time","noun.cognition:meter reading"],["miles per hour","mph"]],
"femoral pulse":[["noun.time"],["femoral pulse","pulse"]],
"radial pulse":[["noun.time"],["radial pulse","pulse"]],
"rate of return":[["noun.time"],["rate of return","rate"]],
"return on invested capital":[["noun.time","noun.act:corporate finance"],["return on invested capital","return on investment","ROI","rate of return"]],
"respiratory rate":[["noun.time","noun.state:vital sign"],["respiratory rate","rate of respiration","rate"]],
"revolutions per minute":[["noun.time","verb.change:rev"],["revolutions per minute","rpm","rev","rate"]],
"sampling rate":[["noun.time","noun.communication:telecommunication"],["sampling rate","rate"]],
"nyquist rate":[["noun.time","noun.communication:telecommunication"],["Nyquist rate","sampling rate"]],
"solar constant":[["noun.time"],["solar constant","rate"]],
"quick time":[["noun.time"],["quick time","pace"]],
"airspeed":[["noun.time"],["airspeed","speed"]],
"escape velocity":[["noun.time"],["escape velocity","speed"]],
"groundspeed":[["noun.time"],["groundspeed","speed"]],
"hypervelocity":[["noun.time"],["hypervelocity","speed"]],
"muzzle velocity":[["noun.time"],["muzzle velocity","speed"]],
"peculiar velocity":[["noun.time"],["peculiar velocity","speed"]],
"radial velocity":[["noun.time"],["radial velocity","speed"]],
"speed of light":[["noun.time","noun.quantity:constant"],["speed of light","light speed","c","speed"]],
"steerageway":[["noun.time","noun.act:navigation1"],["steerageway","speed"]],
"terminal velocity":[["noun.time"],["terminal velocity","speed"]],
"count per minute":[["noun.time"],["count per minute","counts/minute","frequency"]],
"sampling frequency":[["noun.time","noun.communication:telecommunication"],["sampling frequency","frequency"]],
"nyquist frequency":[["noun.time","noun.communication:telecommunication"],["Nyquist frequency","sampling frequency"]],
"infant deathrate":[["noun.time"],["infant deathrate","infant mortality","infant mortality rate","deathrate"]],
"neonatal mortality":[["noun.time"],["neonatal mortality","neonatal mortality rate","deathrate"]],
"words per minute":[["noun.time"],["words per minute","wpm","rate"]],
"beats per minute":[["noun.time","M.M.","noun.act:music","noun.communication:music"],["beats per minute","bpm","metronome marking","tempo"]],
"channel capacity":[["noun.time"],["channel capacity","data rate"]],
"neutron flux":[["noun.time"],["neutron flux","flux"]],
"radiant flux":[["noun.time"],["radiant flux","flux"]],
"luminous flux":[["noun.time"],["luminous flux","radiant flux"]],
"menstrual cycle":[["noun.time","noun.event:cycle1"],["menstrual cycle"]],
"fertile period":[["noun.time"],["fertile period","fertile phase","phase","menstrual cycle"]],
"menstrual phase":[["noun.time"],["menstrual phase","phase","menstrual cycle"]],
"musth":[["noun.time"],["musth","phase"]],
"secretory phase":[["noun.time"],["secretory phase","luteal phase","phase","menstrual cycle"]],
"lead time":[["noun.time"],["lead time","time interval"]],
"orbit period":[["noun.time"],["orbit period","period2"]],
"multistage":[["noun.time"],["multistage","time period"]],
"episcopate":[["noun.time"],["episcopate","tenure"]],
"dogwatch":[["noun.time"],["dogwatch","watch"]],
"split shift":[["noun.time"],["split shift","shift"]],
"peacetime":[["noun.time"],["peacetime","time period"]],
"wartime":[["noun.time"],["wartime","time period"]],
"graveyard watch":[["noun.time"],["graveyard watch","middle watch","midwatch","night watch","watch"]],
"indiction":[["noun.time"],["indiction","time period"]],
"incubation period":[["noun.time"],["incubation period","time period"]],
"rainy day":[["noun.time","noun.communication:figure of speech"],["rainy day","time period"]],
"running time":[["noun.time"],["running time","time period"]],
"show time":[["noun.time"],["show time1","point"]],
"safe period":[["noun.time"],["safe period","phase","menstrual cycle"]],
"then":[["noun.time"],["then","point in time"]],
"shiva":[["noun.time","noun.cognition:Judaism"],["shiva","shivah","shibah","week"]],
"clotting time":[["noun.time"],["clotting time","time period"]],
"rotational latency":[["noun.time","noun.cognition:computer science"],["rotational latency","latency1","time interval","access time"]],
"processing time":[["noun.time"],["processing time","time interval"]],
"command processing overhead time":[["noun.time","noun.cognition:computer science"],["command processing overhead time","command processing overhead","command overhead","overhead","processing time","access time"]],
"great schism":[["noun.time","noun.event:schism","noun.group:Roman Catholic Church"],["Great Schism","time period"]],
"question time":[["noun.time","noun.location:Great Britain1"],["question time","time period"]],
"real time":[["noun.time","noun.cognition:computer science","noun.time"],["real time","time period","real time1","time period"]],
"usance":[["noun.time","noun.act:commerce"],["usance","time period"]],
"9/11":[["noun.time","noun.act:terrorist attack","noun.act:terrorism"],["9/11","9-11","September 11","Sept. 11","Sep 11","September"]]
}