var mysql_wn_data_noun_shape = {
"heart":[["noun.shape","noun.attribute","noun.attribute","adj.all:bold^nervy","verb.emotion:nerve","adj.all:spirited^spunky","adj.all:brave^spunky"],["heart","plane figure","heart4","spirit3","temperament","heart1","mettle2","nerve","spunk","courage"]],
"curve":[["noun.shape","verb.motion:curve"],["curve","straight line","curved shape","line"]],
"intersection":[["noun.shape","noun.group:set2"],["intersection"]],
"articulation":[["noun.shape","verb.possession:articulate","verb.contact:joint","verb.possession:joint","verb.stative:joint","verb.stative:join1","noun.communication","verb.communication:articulate2","verb.communication:articulate1","verb.communication:articulate","verb.communication:voice"],["articulation","join","joint","juncture","junction","connection","articulation1","voice1","expression4"]],
"bifurcation":[["noun.shape","verb.change:bifurcate","noun.shape","verb.stative:bifurcate","verb.change:bifurcate"],["bifurcation","furcation","bifurcation1","branch","bifurcation"]],
"corrugation":[["noun.shape","verb.contact:corrugate"],["corrugation","ridge"]],
"indentation":[["noun.shape"],["indentation","indenture","concave shape"]],
"roulette":[["noun.shape"],["roulette","line roulette","curved shape"]],
"figure eight":[["noun.shape","noun.location:Britain"],["figure eight","figure 8\"","figure of eight","plane figure"]],
"incision":[["noun.shape","adj.all:sharp^incisive","verb.contact:incise","verb.contact:scratch","verb.contact:prick","verb.contact:slit","verb.contact:slit1","verb.contact:dent"],["incision","scratch","prick","slit","dent","depression"]],
"perversion":[["noun.shape","noun.act"],["perversion","curve","perversion1","sexual perversion","sexual activity"]],
"constriction":[["noun.shape","verb.change:constrict","verb.change:bottleneck","noun.attribute:narrowing"],["constriction","bottleneck","chokepoint"]],
"vector":[["noun.shape"],["vector","straight line"]],
"helix":[["noun.shape","verb.stative:spiral"],["helix","spiral1","curve"]],
"tail":[["noun.shape","verb.contact","noun.artifact","noun.possession:coin2","noun.communication:plural"],["tail","tail end","projection","tail1","top","tail2","head4","reverse2"]],
"bolus":[["noun.shape"],["bolus","ball"]],
"bulb":[["noun.shape","adj.all:round^bulblike"],["bulb","round shape"]],
"circlet":[["noun.shape"],["circlet","circle"]],
"cupid's bow":[["noun.shape"],["Cupid's bow","curve"]],
"cylinder":[["noun.shape","adj.all:rounded^cylindric"],["cylinder","round shape"]],
"disk":[["noun.shape"],["disk","disc","saucer","round shape"]],
"dogleg":[["noun.shape"],["dogleg","angle"]],
"dome":[["noun.shape","noun.artifact"],["dome","concave shape","dome1","domed stadium","covered stadium","stadium"]],
"envelope":[["noun.shape","noun.artifact","noun.artifact"],["envelope","curve","envelope1","container","envelope2","gasbag","bag","balloon"]],
"keel":[["noun.shape"],["keel","projection"]],
"pentagon":[["noun.shape"],["pentagon","polygon"]],
"perpendicular":[["noun.shape","adj.all:perpendicular"],["perpendicular","straight line"]],
"prism":[["noun.shape","adj.pert:prismatic"],["prism","polyhedron"]],
"projection":[["noun.shape","noun.cognition"],["projection","convex shape","projection1","prediction"]],
"scoop":[["noun.shape","verb.contact:scoop1","verb.contact","noun.shape:scoop","noun.artifact:scoop1","noun.artifact:scoop","noun.quantity:scoop","verb.change:remove"],["scoop","pocket1","concave shape","scoop1","scoop out2","lift out2","scoop up","take up","frames:8"]],
"sector":[["noun.shape","adj.pert:sectorial"],["sector","plane figure"]],
"torus":[["noun.shape","adj.pert:toroidal"],["torus","toroid","round shape"]],
"triangle":[["noun.shape","adj.all:multilateral^triangular","adj.all:angular^triangular","verb.social:triangulate","verb.cognition:triangulate","noun.shape","noun.Tops:shape"],["triangle","trigon","trilateral","polygon","triangle1"]],
"warp":[["noun.shape","verb.change:warp","verb.change:buckle"],["warp","buckle","distorted shape"]],
"shapelessness":[["noun.shape","adj.all:unformed^shapeless"],["shapelessness","amorphous shape"]],
"eccentricity":[["noun.shape","adj.all:eccentric","noun.relation:ratio1","noun.cognition:geometry","noun.attribute","adj.all:eccentric"],["eccentricity","eccentricity1","concentricity","circularity"]],
"symmetry":[["noun.shape","adj.all:symmetric","verb.change:symmetrize","verb.change:symmetrise","verb.change:proportion1"],["symmetry","proportion","disproportion","balance"]],
"taper":[["noun.shape","verb.change:taper","verb.change","noun.act:tapering"],["taper","convex shape","taper2","decrease"]],
"diameter":[["noun.shape","adj.pert:diametral","adj.pert:diametric","adj.pert:diametrical"],["diameter","straight line"]],
"radius":[["noun.shape","adj.pert:radial"],["radius","straight line"]],
"margin":[["noun.shape","adj.all:peripheral^marginal","verb.stative:border","noun.possession"],["margin","border","perimeter","boundary","margin1","security deposit","deposit"]],
"altitude":[["noun.shape","adj.pert:altitudinal","noun.attribute:distance1"],["altitude"]],
"groove":[["noun.shape","verb.contact:groove","verb.contact:groove2","verb.contact","noun.shape:groove","noun.artifact:groover","noun.act:grooving"],["groove","channel","depression","groove2","incise"]],
"pore":[["noun.shape","adj.all:leaky^porous","adj.all:poriferous"],["pore","hole"]],
"trapezoid":[["noun.shape","adj.pert:trapezoidal","noun.location:US"],["trapezoid","quadrilateral"]],
"cavity":[["noun.shape"],["cavity","enclosed space","space"]],
"hemisphere":[["noun.shape","adj.pert:hemispherical"],["hemisphere","subfigure"]],
"hip":[["noun.shape","noun.artifact:hip roof","noun.cognition:architecture","noun.body"],["hip","exterior angle","hip2","hip joint","coxa","articulatio coxae","ball-and-socket joint","thigh","pelvis"]],
"rhomboid":[["noun.shape","adj.pert:rhomboid","adj.pert:rhomboidal"],["rhomboid","parallelogram"]],
"kink":[["noun.shape","verb.change:kink","verb.contact:kink","verb.contact:twist1","noun.cognition","adj.all:unconventional1^kinky"],["kink","twist","twirl","fold","kink1","idea"]],
"thalweg":[["noun.shape"],["thalweg","boundary"]],
"delta":[["noun.shape"],["delta","equilateral triangle"]],
"conglomeration":[["noun.shape","verb.change:conglobate"],["conglomeration","conglobation","sphere"]],
"whirl":[["noun.shape","verb.motion:whirl4","verb.motion:whirl2","verb.motion:swirl","verb.motion:swirl1","verb.motion","noun.event:whirl","verb.motion","noun.shape:whirl","noun.act:whirl2","noun.act:spin","noun.artifact:spinner1","noun.act:twirl","noun.person:twirler1"],["whirl","swirl","vortex","convolution","round shape","whirl3","tumble7","whirl around","move","frames:1","whirl2","birl","spin2","twirl1","rotate"]],
"diagonal":[["noun.shape","adj.all:inclined1^diagonal"],["diagonal","bias","straight line"]],
"boundary":[["noun.shape","verb.stative:bound","verb.contact:edge","verb.stative:bound","verb.change:bound"],["boundary","edge","bound","line"]],
"brink":[["noun.shape","verb.stative:verge1"],["brink","threshold","verge","boundary"]],
"equator":[["noun.shape","adj.pert:equatorial2","verb.change:equate"],["equator","circle"]],
"hour angle":[["noun.shape","noun.cognition:astronomy"],["hour angle","HA","angular distance"]],
"asterism":[["noun.shape","noun.cognition:mineralogy"],["asterism","star"]],
"nub":[["noun.shape","adj.all:rough^nubby","adj.all:rough^nubbly"],["nub","nubble","bulge"]],
"mogul":[["noun.shape"],["mogul","bulge"]],
"washout":[["noun.shape"],["washout","groove"]],
"tangent":[["noun.shape","adj.pert:tangential","noun.state:tangency"],["tangent","straight line"]],
"secant":[["noun.shape"],["secant","straight line"]],
"cartesian plane":[["noun.shape"],["Cartesian plane","plane"]],
"complex plane":[["noun.shape"],["complex plane","Cartesian plane"]],
"facet plane":[["noun.shape"],["facet plane","plane"]],
"midplane":[["noun.shape"],["midplane","midline","plane"]],
"orbital plane":[["noun.shape","noun.cognition:astronomy"],["orbital plane","plane"]],
"picture plane":[["noun.shape","noun.attribute:perspective"],["picture plane","plane"]],
"tangent plane":[["noun.shape"],["tangent plane","plane"]],
"natural shape":[["noun.shape","noun.Tops:shape"],["natural shape"]],
"leaf shape":[["noun.shape","noun.plant:leaf"],["leaf shape","leaf form","natural shape"]],
"equilateral":[["noun.shape"],["equilateral","figure"]],
"plane figure":[["noun.shape"],["plane figure","two-dimensional figure","figure"]],
"solid figure":[["noun.shape"],["solid figure","three-dimensional figure","figure"]],
"subfigure":[["noun.shape"],["subfigure","figure"]],
"convex shape":[["noun.shape","adj.all:convex"],["convex shape","convexity","solid"]],
"entasis":[["noun.shape","noun.artifact:column"],["entasis","convex shape"]],
"angular shape":[["noun.shape","adj.all:angular","noun.Tops:shape"],["angular shape","angularity"]],
"concave shape":[["noun.shape","adj.all:concave","verb.contact:incurvate","verb.motion:incurvate"],["concave shape","concavity","incurvation","incurvature","solid"]],
"round shape":[["noun.shape","noun.Tops:shape"],["round shape"]],
"polygon":[["noun.shape"],["polygon","polygonal shape","plane figure"]],
"isogon":[["noun.shape","adj.all:angular^isogonic"],["isogon","polygon"]],
"convex polygon":[["noun.shape"],["convex polygon","concave polygon","polygon"]],
"concave polygon":[["noun.shape"],["concave polygon","convex polygon","polygon"]],
"reentrant polygon":[["noun.shape"],["reentrant polygon","reentering polygon","concave polygon"]],
"regular polygon":[["noun.shape"],["regular polygon","isogon"]],
"distorted shape":[["noun.shape","noun.person:distortionist","verb.contact:distort1","verb.contact:distort","noun.Tops:shape"],["distorted shape","distortion"]],
"amorphous shape":[["noun.shape","noun.Tops:shape"],["amorphous shape"]],
"closed curve":[["noun.shape"],["closed curve","curve"]],
"simple closed curve":[["noun.shape"],["simple closed curve","Jordan curve","closed curve"]],
"s-shape":[["noun.shape"],["S-shape","curve"]],
"catenary":[["noun.shape"],["catenary","curve"]],
"extrados":[["noun.shape"],["extrados","curve"]],
"gooseneck":[["noun.shape"],["gooseneck","curved shape"]],
"intrados":[["noun.shape"],["intrados","curve"]],
"uncus":[["noun.shape","noun.cognition:biology"],["uncus","hook"]],
"straight line":[["noun.shape"],["straight line","curve","line"]],
"geodesic":[["noun.shape","adj.pert:geodesic","noun.cognition:math"],["geodesic","geodesic line","line"]],
"asymptote":[["noun.shape","adj.pert:asymptotic"],["asymptote","straight line"]],
"perimeter":[["noun.shape"],["perimeter1","line"]],
"centerline":[["noun.shape"],["centerline","center line","line"]],
"conic section":[["noun.shape","adj.pert:conic","noun.cognition:geometry"],["conic section","conic","plane figure"]],
"oblong":[["noun.shape","adj.all:long1^oblong"],["oblong","plane figure"]],
"semicircle":[["noun.shape","adj.all:curved^semicircular"],["semicircle","hemicycle","plane figure"]],
"arc":[["noun.shape","verb.motion:arc"],["arc","curve","circle","sector"]],
"double helix":[["noun.shape"],["double helix","helix"]],
"element of a cone":[["noun.shape"],["element of a cone","element"]],
"element of a cylinder":[["noun.shape"],["element of a cylinder","element"]],
"helix angle":[["noun.shape"],["helix angle","angle"]],
"ellipse":[["noun.shape","adj.all:rounded^elliptic","adj.all:rounded^elliptical","adj.all:rounded^oval"],["ellipse","oval","conic section"]],
"quadrate":[["noun.shape","noun.shape"],["quadrate1","square","quadrate2","cube"]],
"quadrilateral":[["noun.shape","adj.pert:quadrangular","adj.pert:tetragonal"],["quadrilateral","quadrangle","tetragon","polygon"]],
"acute triangle":[["noun.shape"],["acute triangle","acute-angled triangle","triangle"]],
"equilateral triangle":[["noun.shape"],["equilateral triangle","equiangular triangle","triangle","regular polygon"]],
"isosceles triangle":[["noun.shape"],["isosceles triangle","triangle"]],
"oblique triangle":[["noun.shape"],["oblique triangle","right triangle","triangle"]],
"obtuse triangle":[["noun.shape"],["obtuse triangle","obtuse-angled triangle","triangle"]],
"right triangle":[["noun.shape"],["right triangle","oblique triangle","right-angled triangle","triangle"]],
"scalene triangle":[["noun.shape"],["scalene triangle","triangle"]],
"hexagram":[["noun.shape"],["hexagram","star"]],
"parallelogram":[["noun.shape"],["parallelogram","trapezium","quadrilateral"]],
"pentacle":[["noun.shape"],["pentacle","pentagram","pentangle","star"]],
"hexagon":[["noun.shape","adj.pert:hexagonal"],["hexagon","polygon"]],
"regular hexagon":[["noun.shape"],["regular hexagon","hexagon"]],
"heptagon":[["noun.shape"],["heptagon","polygon"]],
"octagon":[["noun.shape"],["octagon","polygon"]],
"nonagon":[["noun.shape"],["nonagon","polygon"]],
"decagon":[["noun.shape"],["decagon","polygon"]],
"undecagon":[["noun.shape"],["undecagon","polygon"]],
"dodecagon":[["noun.shape"],["dodecagon","polygon"]],
"rhombus":[["noun.shape","adj.pert:rhombic"],["rhombus","rhomb","diamond","parallelogram"]],
"rectangle":[["noun.shape","adj.all:angular^rectangular"],["rectangle","parallelogram"]],
"spherical polygon":[["noun.shape"],["spherical polygon","polygon"]],
"spherical triangle":[["noun.shape"],["spherical triangle","spherical polygon"]],
"polyhedron":[["noun.shape","adj.pert:polyhedral"],["polyhedron","solid"]],
"convex polyhedron":[["noun.shape"],["convex polyhedron","polyhedron"]],
"concave polyhedron":[["noun.shape"],["concave polyhedron","polyhedron"]],
"parallelepiped":[["noun.shape"],["parallelepiped","parallelopiped","parallelepipedon","parallelopipedon","prism"]],
"cuboid":[["noun.shape"],["cuboid","parallelepiped"]],
"quadrangular prism":[["noun.shape"],["quadrangular prism","prism"]],
"triangular prism":[["noun.shape"],["triangular prism","prism"]],
"sinuosity":[["noun.shape","adj.all:curved^sinuous","adj.all:curved^sinuous"],["sinuosity","sinuousness","curved shape"]],
"tortuosity":[["noun.shape","adj.all:crooked1^tortuous","adj.all:crooked1^tortuous","noun.person:contortionist","verb.contact:contort"],["tortuosity","tortuousness","torsion","contortion","crookedness","distorted shape"]],
"parabola":[["noun.shape","adj.all:rounded^parabolic","adj.all:rounded^parabolical"],["parabola","conic section"]],
"hyperbola":[["noun.shape","adj.pert:hyperbolic"],["hyperbola","conic section"]],
"furcation":[["noun.shape","verb.change:furcate","verb.change:fork"],["furcation","forking","angular shape"]],
"complementary angles":[["noun.shape"],["complementary angles","angle"]],
"angular distance":[["noun.shape"],["angular distance","angle"]],
"true anomaly":[["noun.shape"],["true anomaly","angular distance"]],
"plane angle":[["noun.shape"],["plane angle","angle"]],
"spherical angle":[["noun.shape"],["spherical angle","angle"]],
"solid angle":[["noun.shape"],["solid angle","angle"]],
"reentrant angle":[["noun.shape"],["reentrant angle","reentering angle","interior angle"]],
"salient angle":[["noun.shape"],["salient angle","reentrant angle","angle"]],
"interior angle":[["noun.shape"],["interior angle","internal angle","angle"]],
"exterior angle":[["noun.shape"],["exterior angle","external angle","angle"]],
"angle of incidence":[["noun.shape"],["angle of incidence","incidence angle","angle"]],
"angle of attack":[["noun.shape"],["angle of attack","angle of incidence"]],
"critical angle":[["noun.shape"],["critical angle","angle of incidence"]],
"angle of reflection":[["noun.shape"],["angle of reflection","angle"]],
"angle of refraction":[["noun.shape"],["angle of refraction","angle"]],
"angle of extinction":[["noun.shape"],["angle of extinction","extinction angle","angle"]],
"acute angle":[["noun.shape"],["acute angle","oblique angle"]],
"obtuse angle":[["noun.shape"],["obtuse angle","oblique angle"]],
"right angle":[["noun.shape"],["right angle","oblique angle","angle"]],
"oblique angle":[["noun.shape"],["oblique angle","right angle","angle"]],
"reflex angle":[["noun.shape"],["reflex angle","angle"]],
"perigon":[["noun.shape"],["perigon","round angle","angle"]],
"cutting angle":[["noun.shape"],["cutting angle","angle"]],
"magnetic declination":[["noun.shape","verb.stative:vary1"],["magnetic declination","magnetic variation","variation","angle"]],
"azimuth":[["noun.shape","adj.pert:azimuthal"],["azimuth","AZ","angle"]],
"caput":[["noun.shape"],["caput","bulge"]],
"crescent":[["noun.shape","adj.all:rounded^crescent"],["crescent","curved shape"]],
"hyperboloid":[["noun.shape","adj.all:rounded^hyperboloidal"],["hyperboloid","quadric"]],
"paraboloid":[["noun.shape","adj.all:rounded^paraboloidal"],["paraboloid","plane figure"]],
"ellipsoid":[["noun.shape","adj.all:rounded^ellipsoid","adj.all:rounded^ellipsoidal"],["ellipsoid","plane figure"]],
"hypotenuse":[["noun.shape"],["hypotenuse","flank","right triangle"]],
"conformation":[["noun.shape"],["conformation","balance"]],
"disproportion":[["noun.shape","noun.attribute:disparity"],["disproportion","proportion"]],
"spheroid":[["noun.shape","adj.all:rounded^spheroidal"],["spheroid","ellipsoid of revolution","round shape"]],
"spherule":[["noun.shape"],["spherule","ball"]],
"toroid":[["noun.shape","adj.pert:toroidal"],["toroid1","solid"]],
"columella":[["noun.shape"],["columella","column2"]],
"pellet":[["noun.shape"],["pellet","ball"]],
"dewdrop":[["noun.shape"],["dewdrop","drop"]],
"teardrop":[["noun.shape"],["teardrop","drop"]],
"quadric":[["noun.shape"],["quadric","quadric surface","curved shape"]],
"lemniscate":[["noun.shape","noun.cognition:geometry"],["lemniscate","curved shape"]],
"periphery":[["noun.shape","adj.all:peripheral","adj.all:peripheral^fringy"],["periphery","fringe","outer boundary","boundary"]],
"upper bound":[["noun.shape","noun.cognition:math"],["upper bound","boundary"]],
"lower bound":[["noun.shape","noun.cognition:math"],["lower bound","boundary"]],
"incisure":[["noun.shape","verb.contact:incise","noun.cognition:anatomy"],["incisure","incisura","notch"]],
"crow's foot":[["noun.shape"],["crow's foot","crow's feet","laugh line","wrinkle"]],
"dermatoglyphic":[["noun.shape"],["dermatoglyphic","wrinkle"]],
"frown line":[["noun.shape"],["frown line","wrinkle"]],
"line of life":[["noun.shape"],["line of life","life line","lifeline","wrinkle"]],
"line of heart":[["noun.shape"],["line of heart","heart line","love line","mensal line","wrinkle"]],
"line of fate":[["noun.shape"],["line of fate","line of destiny","line of Saturn","wrinkle"]],
"crevice":[["noun.shape","verb.change:fissure"],["crevice","cranny1","crack","fissure","chap","depression"]],
"cleft":[["noun.shape","verb.contact:cleave","verb.contact:cleave1"],["cleft","indentation"]],
"stria":[["noun.shape","verb.change:striate","verb.change:striate"],["stria","striation","groove"]],
"cycloid":[["noun.shape","adj.all:rounded^cycloidal"],["cycloid","roulette"]],
"curtate cycloid":[["noun.shape"],["curtate cycloid","cycloid"]],
"prolate cycloid":[["noun.shape"],["prolate cycloid","cycloid"]],
"sine curve":[["noun.shape","adj.all:curved^sinusoidal"],["sine curve","sinusoid","wave"]],
"epicycle":[["noun.shape","adj.pert:epicyclic","adj.pert:epicyclical"],["epicycle","circle"]],
"epicycloid":[["noun.shape"],["epicycloid","roulette"]],
"cardioid":[["noun.shape"],["cardioid","epicycloid"]],
"hypocycloid":[["noun.shape"],["hypocycloid","roulette"]],
"blob":[["noun.shape","verb.contact:blob"],["blob","amorphous shape"]],
"void":[["noun.shape","adj.all:empty^void","verb.change:void4","adj.all:empty^vacant1","verb.change","noun.shape:void"],["void","vacancy","emptiness","vacuum","space","void4","empty1"]],
"cladogram":[["noun.shape"],["cladogram","tree"]],
"stemma":[["noun.shape"],["stemma","tree"]],
"facet":[["noun.shape"],["facet","subfigure"]],
"brachium":[["noun.shape","noun.cognition:biology"],["brachium","branch"]],
"ovoid":[["noun.shape","adj.all:rounded^ovoid"],["ovoid","solid"]],
"tetrahedron":[["noun.shape"],["tetrahedron","polyhedron"]],
"pentahedron":[["noun.shape"],["pentahedron","polyhedron"]],
"hexahedron":[["noun.shape"],["hexahedron","polyhedron"]],
"rhombohedron":[["noun.shape","adj.all:symmetrical^rhombohedral"],["rhombohedron","parallelepiped","hexahedron"]],
"octahedron":[["noun.shape"],["octahedron","polyhedron"]],
"decahedron":[["noun.shape"],["decahedron","polyhedron"]],
"dodecahedron":[["noun.shape"],["dodecahedron","polyhedron"]],
"icosahedron":[["noun.shape","adj.pert:icosahedral"],["icosahedron","polyhedron"]],
"regular polyhedron":[["noun.shape"],["regular polyhedron","regular convex solid","regular convex polyhedron","Platonic body","Platonic solid","ideal solid","polyhedron"]],
"polyhedral angle":[["noun.shape"],["polyhedral angle","angle"]],
"face angle":[["noun.shape"],["face angle","angle"]],
"regular tetrahedron":[["noun.shape"],["regular tetrahedron","regular polyhedron"]],
"tesseract":[["noun.shape"],["tesseract","cube"]],
"regular dodecahedron":[["noun.shape"],["regular dodecahedron","regular polyhedron"]],
"regular octahedron":[["noun.shape"],["regular octahedron","regular polyhedron"]],
"regular icosahedron":[["noun.shape"],["regular icosahedron","regular polyhedron"]],
"frustum":[["noun.shape"],["frustum","solid"]],
"truncated pyramid":[["noun.shape"],["truncated pyramid","frustum"]],
"truncated cone":[["noun.shape"],["truncated cone","frustum"]],
"prismatoid":[["noun.shape"],["prismatoid","polyhedron"]],
"prismoid":[["noun.shape"],["prismoid","prismatoid"]],
"tilt angle":[["noun.shape"],["tilt angle","angle"]],
"trapezohedron":[["noun.shape"],["trapezohedron","polyhedron"]],
"vertical angle":[["noun.shape"],["vertical angle","angle"]],
"verticil":[["noun.shape"],["verticil","coil"]],
"view angle":[["noun.shape"],["view angle","angle of view","angle"]],
"wave angle":[["noun.shape"],["wave angle","angle"]]
}