var mysql_wn_data_vframesentence = [
[1,'The children % to the playground'],
[10,'The cars % down the avenue'],
[100,'These glasses % easily'],
[101,'These fabrics % easily'],
[102,'They % their earnings this year'],
[103,'Their earnings % this year'],
[104,'The water % '],
[105,'They % the water '],
[106,'The animals %'],
[107,'They % a long time'],
[108,'The car % the tree '],
[109,'John will % angry'],
[11,'They % the car down the avenue'],
[110,'They % in the city'],
[111,'They won\'t % the story '],
[112,'They % that there was a traffic accident '],
[113,'They % whether there was a traffic accident'],
[114,'They % her vice president'],
[115,'Did he % his major works over a short period of time?'],
[116,'The chefs % the vegetables'],
[117,'They % the cape '],
[118,'The food does % good '],
[119,'The music does % good '],
[12,'They % the glass tubes'],
[120,'The cool air does % good'],
[121,'This food does % well '],
[122,'It was %ing all day long '],
[123,'They % him to write the letter'],
[124,'They % him into writing the letter'],
[125,'They % him from writing the letter'],
[126,'The bad news will % him'],
[127,'The good news will % her'],
[128,'The chef wants to % the eggs '],
[129,'Sam wants to % with Sue '],
[13,'The glass tubes %'],
[130,'The fighter managed to % his opponent'],
[131,'These cars won\'t % '],
[132,'The branches % from the trees'],
[133,'The stock market is going to % '],
[134,'The moon will soon % '],
[135,'The business is going to % '],
[136,'The airplane is sure to % '],
[137,'They % to move '],
[138,'They % moving '],
[139,'Sam and Sue % the movie '],
[14,'Sam and Sue %'],
[140,'They want to % the prisoners '],
[141,'They want to % the doors'],
[142,'The doors % '],
[143,'Did he % his foot? '],
[144,'Did his feet %?'],
[145,'They will % the duet'],
[146,'They % their hair '],
[147,'They % the trees'],
[148,'They % him of all his money'],
[149,'Lights % on the horizon'],
[15,'Sam cannot % Sue '],
[150,'The horizon is %ing with lights'],
[151,'The crowds % in the streets'],
[152,'The streets % with crowds'],
[153,'Cars % in the streets '],
[154,'The streets % with cars '],
[155,'You can hear animals % in the meadows'],
[156,'The meadows % with animals '],
[157,'The birds % in the woods '],
[158,'The woods % with many kinds of birds '],
[159,'The performance is likely to % Sue'],
[16,'The ropes %'],
[160,'Sam and Sue % over the results of the experiment'],
[161,'In the summer they like to go out and %'],
[162,'The children % in the rocking chair'],
[163,'There % some children in the rocking chair'],
[164,'Some big birds % in the tree'],
[165,'There % some big birds in the tree'],
[166,'The men % the area for animals '],
[167,'The men % for animals in the area'],
[168,'The customs agents % the bags for drugs '],
[169,'They % him as chairman '],
[17,'The strong winds % the rope'],
[170,'They % him \"Bobby\"'],
[18,'They % the sheets'],
[19,'The sheets didn\'t %'],
[2,'The banks % the check'],
[20,'The horses % across the field'],
[21,'They % the bags on the table'],
[22,'The men % the horses across the field'],
[23,'Our properties % at this point'],
[24,'His fields % mine at this point'],
[25,'They % the hill'],
[26,'They % up the hill'],
[27,'They % the river'],
[28,'They % down the river '],
[29,'They % the countryside'],
[3,'The checks % '],
[30,'They % in the countryside'],
[31,'These men % across the river'],
[32,'These men % the river'],
[33,'They % the food to the people'],
[34,'They % the people the food'],
[35,'They % more bread'],
[36,'They % the object in the water'],
[37,'The men % the bookshelves'],
[38,'They % the money in the closet'],
[39,'The lights % from the ceiling'],
[4,'The children % the ball'],
[40,'They % the lights from the ceiling'],
[41,'They % their rifles on the cabinet'],
[42,'The chairs % in the corner'],
[43,'The men % the chairs'],
[44,'The women % water into the bowl'],
[45,'Water and oil % into the bowl'],
[46,'They % the wire around the stick'],
[47,'The wires % around the stick'],
[48,'They % the bread with melted butter'],
[49,'They % the cart with boxes '],
[5,'The balls % '],
[50,'They % the books into the box'],
[51,'They % sugar over the cake'],
[52,'They % the cake with sugar'],
[53,'They % the fruit with a chemical'],
[54,'They % a chemical into the fruit'],
[55,'They % the field with rye'],
[56,'They % rye in the field'],
[57,'They % notices on the doors'],
[58,'They % the doors with notices'],
[59,'They % money on their grandchild'],
[6,'The girls % the wooden sticks'],
[60,'They % their grandchild with money'],
[61,'They % coins on the image '],
[62,'They % the image with coins '],
[63,'They % butter on the bread'],
[64,'They % the lake with fish'],
[65,'The children % the paper with grease '],
[66,'The children % grease onto the paper'],
[67,'They % papers over the floor'],
[68,'They % the floor with papers'],
[69,'They % the money '],
[7,'The wooden sticks % '],
[70,'They % the newspapers'],
[71,'They % the goods'],
[72,'The men % the boat '],
[73,'They % the animals'],
[74,'The books % the box '],
[75,'They % the halls with holly'],
[76,'Holly flowers % the halls'],
[77,'The wind storms % the area with dust and dirt'],
[78,'Dust and dirt % the area'],
[79,'The swollen rivers % the area with water'],
[8,'The coins % '],
[80,'The waters % the area'],
[81,'They % the cloth with water and alcohol'],
[82,'Water and alcohol % the cloth'],
[83,'They % the snow from the path'],
[84,'They % the path of the snow'],
[85,'They % the water from the sink'],
[86,'They % the sink of water'],
[87,'They % the parcel to their parents'],
[88,'They % them the parcel'],
[89,'They % cars to the tourists'],
[9,'They % the coin '],
[90,'They % the tourists their cars'],
[91,'They % the money to them '],
[92,'They % them the money'],
[93,'They % them the information'],
[94,'They % the information to them'],
[95,'The parents % a French poem to the children'],
[96,'The parents % the children a French poem '],
[97,'They % '],
[98,'They % themselves'],
[99,'These balls % easily'],
]