var mysql_wn_data_verb_stative = {
"board":[["verb.stative","noun.food:board","noun.artifact:board1","noun.person:boarder1","noun.artifact:room","noun.person:roomer","noun.artifact","verb.consumption","noun.food:board","noun.artifact:board1","noun.person:boarder1","noun.person:boarder","*verb.stative:live6"],["board","room","inhabit","board5","gameboard","surface","board1","board","$consume"]],
"jumble":[["verb.stative","noun.cognition:jumble","noun.state:jumble"],["jumble","mingle","be3","frames:1"]],
"conserve":[["verb.stative","noun.cognition:conservation","verb.possession","noun.event:conservation","noun.act:conservation","adj.all:protective^preservative","noun.act:preservation","noun.act:maintenance"],["conserve","keep","frames:8","conserve2","preserve","maintain","keep up","keep1"]],
"breast":[["verb.stative","noun.body:breast1","noun.body","verb.stative:breast"],["breast","meet2","frames:11","9","10","breast1","chest1","external body part","chest"]],
"cut":[["verb.stative","noun.act:skip","noun.person:skipper2","verb.creation","verb.creation","$verb.communication:record1","verb.motion","noun.act:cutting3","$verb.change:switch2","verb.change","noun.act","verb.contact:cut5","noun.act","verb.contact:undercut","verb.creation","$verb.communication:record1","verb.contact","verb.motion","verb.motion","noun.act:boxing","verb.social","verb.contact","noun.act:sport","verb.contact","noun.act:cutting2","noun.act:cutting1","verb.creation","noun.act:cutting5","noun.act:cutting","verb.perception"],["cut","skip","miss1","cut6","burn5","create3","cut5","cut4","cut1","cut to","^cut","frames:22","cut2","cut back","^cut back1","^cut out","^prune","rationalize","rationalise","eliminate1","cut9","cutting9","division","card game","cut8","undercut","stroke","tennis","badminton","squash","cut4","cut6","cut14","penetrate","cut12","pass through","frames:8","cut15","move","cut13","free2","cut7","hit","cut10","cut11","create","frames:8","cut3","look1"]],
"flank":[["verb.stative","noun.shape:flank","noun.person:flanker1","noun.person:flanker"],["flank","lie","frames:11","10"]],
"cheese":[["verb.stative"],["cheese","stop"]],
"spread":[["verb.stative","noun.act:spread","noun.attribute:spread","noun.event:spread","noun.event:spreading","noun.attribute","verb.contact","noun.act:spread","noun.attribute:spread","noun.event:spread","verb.motion:move","verb.contact","noun.food:spread","noun.artifact:spreader","verb.contact","noun.food:spread","noun.artifact:spreader"],["spread","overspread","cover1","spread1","girth","spread7","propagate6","spread13","spread12","cover"]],
"play":[["verb.stative","verb.creation","verb.change:run7","$verb.social:run","noun.act","verb.social:play12","verb.creation","noun.act:playing1","verb.perception:sound1","noun.communication:music","noun.act:music","verb.social","noun.act:play","noun.act:play6","noun.act:playing","verb.creation","noun.communication:play1","noun.communication:play3","noun.cognition:performing arts","verb.social","noun.act:play8","noun.state:play","verb.consumption","noun.act:play4","verb.competition","noun.act:play4","$verb.contact:hit3","verb.creation","verb.creation:play5","$verb.perception:sound3","verb.social"],["play","play5","run1","$frames:8","play8","use","play1","play3","play","$act7","play4","frames:1","play12","play2","$act","frames:8","play13","exploit","play9","play2","play11","frames:1","play2","act","frames:2","5"]],
"entail":[["verb.stative","noun.relation:implication1","noun.cognition:implication1","noun.cognition:implication","verb.stative","noun.cognition:entailment","adj.all:connotative^implicative","noun.cognition:implication1"],["entail","implicate","lead12","entail1","imply","mean","necessitate1"]],
"straddle":[["verb.stative","noun.cognition:straddle","noun.act","verb.stative:straddle1"],["straddle","straddle2","gymnastic exercise"]],
"drive":[["verb.stative","noun.artifact:drive1","noun.artifact:drive","noun.act:drive","noun.act:ride","verb.contact","noun.artifact:drift","noun.act:mining","noun.act","verb.contact:drive2","verb.contact:drive1","verb.contact:drive7","verb.contact","noun.act:drive3","noun.person:driver1","noun.artifact:driver","noun.act:driving3","noun.act:golf","verb.social","noun.state:drive","verb.motion","noun.artifact:drive1","noun.artifact:drive","noun.act:drive","noun.person:driver","noun.act:driving","verb.stative:drive","$verb.contact:operate","noun.act:driving","verb.contact","noun.act:drive5","noun.act:drive3","noun.person:driver2","noun.act:driving","verb.motion","noun.artifact:drive1","noun.act:drive","noun.artifact:drive","noun.act:driving","verb.motion","verb.motion","noun.artifact:drive1","noun.artifact:drive","noun.act:drive","verb.social","noun.artifact:drive1","noun.act:drive","noun.artifact:drive","noun.person:driver","verb.motion:drive1"],["drive","ride3","drive6","excavate1","drive5","return4","tennis","squash","drive3","drive2","$hit3","drive2","force","frames:9","drive1","drive7","propel","frames:8","drive11","take11","drive","$drive2","$drive1","$traverse","drive10","push","drive9","drive1","move3","drive13","$work","frames:2"]],
"roll":[["verb.stative","noun.shape:roll","noun.act","verb.contact","verb.change","verb.change","verb.motion","noun.event:roller","noun.event:undulation1","noun.event:undulation","noun.event:flap1","noun.event:flapping","noun.act:wave2","verb.motion","noun.event:roll2","verb.motion","verb.motion","noun.person:wanderer","noun.act:wandering","noun.animal:stray","noun.person:strayer","noun.person:tramp2","noun.person:roamer","noun.act:ramble","noun.person:rambler","noun.act:roving","noun.person:drifter","noun.act:drifting","noun.person:vagabond1","noun.object:vagabond","noun.act:vagabondage"],["roll","undulate","frames:1","roll4","gait1","roll1","operate3","roll6","change shape","frames:1","4","roll7","roll up2","roll up","$roll up1","$change","roll10","undulate","flap1","wave","move","frames:1","roll11","revolve2","roll","$move1","roll12","sway","roll9","wander","swan","stray1","tramp2","roam","cast1","ramble1","rove","range","drift1","vagabond","travel","frames:22","4","2"]],
"press":[["verb.stative","noun.state:pressure","noun.act","verb.competition:press","verb.creation","noun.act:press","noun.artifact:press","noun.artifact","verb.contact","noun.act:press","noun.phenomenon:push","noun.act:push","verb.motion:push"],["press","be3","press2","military press","weightlifting","press1","create","frames:8","press3","clamp","press6","push6"]],
"draw":[["verb.stative","verb.motion:draw","verb.motion","noun.artifact:drawer","$verb.contact:pull10","$verb.change:pull11","$verb.change:remove","verb.stative","verb.change","verb.change","verb.change","verb.change","verb.social","noun.quantity:quarter1","verb.contact:kill","verb.motion","verb.body:draw","$verb.change:remove"],["draw","$be3","draw1","pull3","pull out3","get out2","take out10","draw","frames:8","draw2","require","draw4","shape","frames:8","draw15","steep","frames:1","draw8","draw15","$draw4","$thin1","frames:8","draw14","change1","frames:20","21","draw13","quarter","draw and quarter","draw7","frames:8"]],
"enfilade":[["verb.stative"],["enfilade","rake10"]],
"crash":[["verb.stative","verb.motion","noun.event","verb.change:crash10","noun.cognition:computer science","verb.change","noun.event:crash3","verb.change","noun.event:crash2","verb.contact","verb.motion","noun.event:crash1","verb.motion"],["crash","occupy","crash2","fall","frames:1","2","4","crash3","mishap","crash10","go down14","fail","crash11","change","crash7","dash2","hurl","frames:8","21","crash1","move","crash4","pass","frames:1","2"]],
"probate":[["verb.stative","noun.time:probation","noun.act:probation"],["probate","defer"]],
"measure":[["verb.stative","noun.artifact:measure","noun.act:measure"],["measure","measure up","^be3"]],
"embrace":[["verb.stative","noun.state:encompassment","adj.all:inclusive^comprehensive","adj.all:comprehensive","noun.relation:comprehension","verb.communication:cover1"],["embrace","encompass","comprehend","cover2","$include"]],
"run":[["verb.stative","noun.attribute:extent","verb.stative","verb.stative","verb.stative","verb.change","verb.motion","verb.motion","noun.act:run","verb.stative","verb.stative","verb.motion:pass4","verb.contact:run1","verb.motion","noun.act:run","noun.event:run2","verb.motion","noun.state:run"],["run","run along","^go","pass8","lead","extend3","extend to","^run7","$be5","run4","go2","be3","run5","run for","last","run2","incur","run7","process","frames:8","run3","sail","frames:2","run13","run11","$move3","frames:2","run6","occur3","run8","lead2","run10","move1","frames:8","run11","run13","$move3","frames:4"]],
"kill":[["verb.stative","noun.act:kill","verb.contact","noun.act:kill","verb.change","noun.act:kill1","$verb.contact:turn off","verb.change","$verb.body:exhaust","verb.contact","noun.act:sport","verb.contact","noun.act:sport"],["kill","be3","kill2","kill1","$frames:8","kill3","kill2","kill4","kill3","kill5","hit3","kill6","kill5","$hit3"]],
"wash":[["verb.stative","adj.all:washable","noun.act:wash1","verb.contact","adj.all:washable","noun.artifact:wash","noun.person:washer","noun.artifact:washer","noun.act:rinse","$verb.change:wash5","verb.change","verb.motion:wash1","verb.change","verb.contact","noun.artifact:wash2","verb.stative"],["wash","be3","frames:1","wash2","rinse2","wash","$wash1","$process","wash9","$erode","wash5","wash out4","wash off","wash away","remove","wash10","cover","wash12","stand2"]],
"prowl":[["verb.stative","noun.act:prowl"],["prowl","lurch","loiter","frames:2"]],
"crawl":[["verb.stative"],["crawl","swarm"]],
"lap":[["verb.stative","noun.artifact:lap"],["lap","lie"]],
"beat":[["verb.stative","verb.motion","noun.act:beat","noun.act:navigation","verb.contact","verb.contact","noun.communication:beat","verb.social","verb.creation","noun.communication:beat","noun.communication:music","verb.motion","noun.event:flap1","noun.event:flapping","verb.motion","noun.attribute:beat","noun.event:flap1","noun.event:flapping"],["beat","be3","beat1","sail","frames:2","1","4","beat12","beat","beat10","strike","beat3","bunk","cheat","beat5","play1","beat2","flap2","move","beat4","flap3","beat2","$move1"]],
"rise":[["verb.stative","noun.attribute:rise1","verb.perception:appear","noun.attribute","verb.motion:boost","verb.motion:hike1","verb.motion","verb.change:grow","verb.change","noun.event:jump","verb.motion","noun.event:rise2","adj.all:ascending^ascendent","noun.event:ascension1","noun.cognition:astronomy"],["rise","lift1","rear","frames:1","rise3","boost","hike1","cost increase","increase","rise2","prove1","rise9","jump1","climb up2","change","frames:1","rise8","set","come up","uprise2","ascend3","rise"]],
"flow":[["verb.stative","noun.time:flow","noun.event:flow","noun.process:flow","noun.act:flow","verb.motion","noun.state:flow","noun.act:flow","noun.event:fluxion","verb.motion","noun.process:flow","noun.act:flow","noun.time:flow","noun.event:flow"],["flow","be","flow1","flux","move","frames:1","flow2","flow",">frames:8"]],
"transplant":[["verb.stative","noun.act:transplant1","verb.motion:transplant"],["transplant","$be3"]],
"reach":[["verb.stative","noun.location:reach","noun.event:touch","verb.motion","noun.act:attainment1","verb.motion","noun.act:reaching","verb.social:achieve"],["reach","reach out","^reach into","^extend to","touch1","be5","frames:11","reach1","make","attain1","hit","arrive at","gain","travel","reach6","make2","get to2","progress to"]],
"spiral":[["verb.stative","noun.shape:spiral1","noun.shape:spiral","noun.artifact","adj.all:coiled^volute"],["spiral","wind","frames:1","spiral1","volute1","ornament"]],
"squat":[["verb.stative","noun.person:squatter1","verb.stative"],["squat","occupy","frames:2","squat1","be3","frames:1"]],
"wind":[["verb.stative","noun.attribute:curve","noun.artifact:curve","noun.phenomenon","verb.contact","noun.artifact:winder","noun.person:winder","verb.change:wrap up","noun.artifact:roller1","noun.event:roll2","verb.change:roll up","verb.motion:move1"],["wind","twist","curve","be3","frames:1","wind1","influence","wind6","unwind6","wrap2","^roll","^twine3"]],
"stretch":[["verb.stative","noun.object:stretch","verb.body","noun.act:stretch","noun.act:stretching","noun.act:extension1","noun.body:extensor","verb.change","noun.act:stretch2"],["stretch","stretch along","be5","stretch1","frames:2extend","tense","stretch5","extend1","frames:8"]],
"blend":[["verb.stative"],["blend","go11","blend in","harmonize","frames:1"]],
"sport":[["verb.stative","noun.artifact:feature","noun.communication:feature1","noun.person","noun.Tops:person","noun.person"],["sport","feature1","boast","have","sport2","sport3","summercater","vacationer"]],
"hang":[["verb.stative","verb.contact","verb.contact","verb.contact","noun.act:hanging1","verb.social","verb.contact","noun.attribute:hang","verb.stative"],["hang","be3","hang4","fasten1","hang5","hang4","hang6","hang3","obstruct","frames:8","hang2","fall","flow4","hang1","frames:1","2","4"]],
"frame":[["verb.stative","noun.person:framer1","noun.artifact:framing","noun.artifact","noun.artifact"],["frame","enclose","frame2","framework","frame3","photograph"]],
"bridge":[["verb.stative","noun.relation:bridge","verb.contact:connect","noun.artifact","noun.artifact","noun.artifact","noun.artifact","noun.artifact"],["bridge","bridge over1","^bridge over","bridge1","bridge deck","upper deck","bridge2","nosepiece","link","spectacles","bridge3","bridgework","denture","bridge4","support","stringed instrument","bridge5","bridge circuit","circuit"]],
"figure":[["verb.stative","verb.cognition","noun.communication:colloquialism"],["figure","enter","be3","frames:4","figure2","comprehend","frames:8"]],
"serve":[["verb.stative","verb.stative","$verb.creation:effect","verb.social","verb.competition:serve","verb.stative","noun.state:servant","verb.communication:foster","verb.stative","noun.attribute:function","verb.social:serve"],["serve","do2","spend","frames:22","serve1","serve2","frames:28","serve13","$work","serve2","serve well","frames:10","11","serve3","function12","$do1","frames:1","11","2"]],
"trade":[["verb.stative","noun.act:trade2","noun.act:trade5","noun.act:commerce","noun.act","verb.possession:trade11","verb.stative:trade","verb.possession:trade","verb.possession:trade1","verb.possession","noun.act:trade2","noun.act:trade5","noun.person:trader","noun.person:merchandiser","noun.act:merchandising","noun.artifact:merchandise","*noun.act:commerce","verb.possession","noun.act:trade3","noun.act:swap","noun.act:swop","noun.event:switch","noun.act:switching"],["trade","sell","frames:1","trade5","commerce","trade1","merchandise","buy","*sell","trade2","swap","swop","switch","exchange","frames:2","8"]],
"count":[["verb.stative","noun.cognition:matter","noun.attribute:matter","verb.cognition","noun.state:dependency","adj.all:dependent^reliant","noun.state:reliance","noun.cognition:reliance","verb.stative","noun.group:number","verb.cognition:classify","verb.stative"],["count","matter","matter to","^weigh3","be3","frames:1","count2","bet","depend","swear10","rely11","bank2","look2","calculate5","reckon5","trust","frames:8","count1","number1","frames:21","count4","be3"]],
"scan":[["verb.stative","noun.communication:poetry2","verb.perception","noun.artifact:scan","noun.act:scan"],["scan","conform6","scan1","examine","frames:8"]],
"contrast":[["verb.stative","adj.all:different^contrastive","adj.all:antonymous^contrastive","noun.relation:contrast","noun.cognition:contrast1","noun.act:contrast"],["contrast","counterpoint","differ","frames:1"]],
"back":[["verb.stative","noun.artifact:back","verb.motion","noun.location","adj.all:back^rear","verb.change"],["back","front","lie","back1","advance1","back",">frames:21","back2","front2","rear1","position","back3","veer3","shift"]],
"end":[["verb.stative","noun.communication:end","noun.location:end1","noun.location:end2","noun.state:end","noun.cognition:end","noun.event:end","noun.time:end","noun.location:end","noun.event:finish2","noun.time:finish","noun.act:finish","adj.all:closing^terminative","noun.location:terminus","verb.stative","noun.communication:end","noun.state:end","noun.cognition:end","noun.time:end","noun.event:end","noun.time:ending","noun.event:ending","adj.all:closing^terminative","noun.cognition:terminus","noun.location","verb.creation","noun.communication:end","noun.state:end","noun.event:end","noun.time:end","noun.event:ending"],["end","begin","stop13","finish","terminate","cease13","frames:1","end1","terminate5","be3","end3","topographic point","end13","destroy","frames:8"]],
"fall":[["verb.stative","verb.possession:fall5","$verb.change:die","verb.possession","verb.possession","verb.social","noun.act:fall3","verb.possession","verb.change","verb.change","verb.motion","noun.act:fall1","verb.motion","noun.object:fall","verb.possession","noun.act:fall2","verb.competition:yield"],["fall","frames:1","2","fall8","light12","devolve13","frames:24","fall13","return13","pass13","devolve13","change hands","fall15","fall1","fall12","fall3","fall9","be born","fall10","issue","fall14","change posture","fall11","slope","frames:1","fall5"]],
"test":[["verb.stative","noun.act:test","noun.act:testing3","noun.act","verb.cognition:test6","verb.competition:test","verb.communication:test","verb.social:try1","noun.act","verb.cognition:test6","verb.competition:test","verb.communication:test","verb.cognition","noun.communication:test","noun.act:test3","noun.act:test2","noun.person:testee","verb.competition:test","$verb.communication:test","verb.communication","noun.act:test","noun.act:testing3"],["test","be3","test3","trial3","attempt","test2","mental test","mental testing","psychometric test","mental measurement","test6","$take9","test8","determine1"]],
"wear":[["verb.stative","adj.all:wearable","verb.body","verb.stative:have","verb.body","adj.all:wearable","noun.artifact:wear","noun.act:wear","noun.act:wearing","verb.stative:have","verb.stative"],["wear","hold out1","endure1","last","frames:6","wear2","frames:8","wear4","bear2","wear1","have","frames:11"]],
"feel":[["verb.stative","noun.state:feel","verb.perception:feel","$verb.perception:appear","verb.perception","noun.state:feeling","verb.contact","noun.act:feel","noun.communication:slang","verb.perception","noun.attribute:feel","verb.contact:feel","$verb.contact:feel1","$verb.contact:feel11","*verb.contact:search","verb.perception","noun.state:feel"],["feel","frames:6","feel1","experience1","frames:8","feel11","touch","feel10","$touch","frames:8","feel9","seem"]],
"gape":[["verb.stative"],["gape","yawn","yaw","be3"]],
"conflict":[["verb.stative","noun.state:conflict","noun.feeling:conflict","noun.attribute:conflict","verb.social","noun.state:conflict","noun.act:infringement1","noun.act:infringement","noun.act:contravention"],["conflict","contrast","frames:1","conflict11","run afoul11","infringe","contravene","violate"]],
"stand":[["verb.stative","noun.cognition:stand","verb.competition:stand","$verb.competition:resist","verb.stative","noun.location:stand","verb.stative","noun.cognition:stand","^verb.competition:stand firm","verb.contact","noun.act:animal husbandry","verb.stative","verb.change:continue10","verb.stative","noun.event:stand","verb.change:remain","verb.stative","noun.cognition:stand"],["stand","yield","remain firm","frames:2","stand1","measure","stand4","stand for","^stand out2","^stand out","^stand by","^stand by1","^be3","frames:6","stand10","serve1","stand2","stand6","stand3","be3","frames:4"]],
"cover":[["verb.stative","noun.act","verb.body","noun.act:covering","verb.perception","noun.act:covering2","noun.act:cover-up","verb.competition","verb.competition","noun.act:cards","verb.stative","noun.process:compensation","noun.process:overcompensation","verb.communication:cover","verb.social","verb.social"],["cover","satisfy","frames:8","cover2","concealment","cover15","wrap up","dress1","cover12","cover up","hide","cover13","cover","$protect","cover7","play3","cover14","compensate3","overcompensate","$compensate","cover10","substitute9","cover8","endow","frames:20"]],
"rut":[["verb.stative","noun.state:rut"],["rut","be3"]],
"worship":[["verb.stative","noun.act:worship","noun.person:worshiper","noun.person:worshipper","verb.emotion","noun.person:worshiper","noun.person:worshipper","noun.cognition:religion"],["worship","attend","frames:1","worship1","reverence"]],
"sojourn":[["verb.stative","noun.person:sojourner","noun.act:sojourn"],["sojourn","spend"]],
"wait":[["verb.stative","noun.act:wait","noun.person:waiter1","noun.act:waiting","verb.stative","noun.time:wait","noun.person:waiter1","verb.social:act"],["wait","frames:2","wait1","hold off","hold back","frames:2","8"]],
"delay":[["verb.stative","noun.time:delay"],["delay","wait1"]],
"retail":[["verb.stative","noun.act:retail","noun.act:retailing","verb.possession:retail","noun.act:commerce"],["retail","$sell"]],
"sell":[["verb.stative","noun.act:sell","noun.act:selling","verb.possession:sell","$verb.possession:sell1","verb.possession","verb.stative","noun.act:sell","verb.stative"],["sell","$be3","frames:1","sell2","surrender","frames:8","15","sell13","be3","sell14","be3"]],
"line":[["verb.stative","noun.group:line1","noun.group","noun.artifact","noun.group:common carrier","noun.artifact","verb.contact","noun.shape:line1","noun.communication:line1","noun.location:lineation","noun.act:lineation","noun.communication"],["line","run along","lie","line3","formation","line5","transportation system","line8","product line","line of products","line of merchandise","business line","line of business","merchandise","line2","mark1","line6","persuasion"]],
"answer":[["verb.stative","verb.cognition","adj.all:soluble2^answerable","verb.stative","verb.cognition","noun.act:answer","verb.cognition","noun.act:answer","verb.communication","noun.communication:answer3"],["answer","match","frames:11","answer3","resolve4","solve","frames:8","answer1","be3","answer5","react","frames:1","answer2","respond","answer6","refute"]],
"vacation":[["verb.stative","noun.time:vacation","noun.person:vacationist","noun.person:vacationer","noun.act:vacationing","noun.time:holiday"],["vacation","holiday","spend","frames:2"]],
"quarter":[["verb.stative","noun.artifact:quarters","noun.artifact:quartering","noun.artifact:billet","noun.artifact:cantonment","noun.group:military","verb.contact","noun.quantity:quarter1","noun.act:quartering","noun.quantity","noun.location:Britain","noun.time","adj.pert:quarterly","noun.time"],["quarter","billet","canton","lodge","frames:2","quarter1","section","frames:8","quarter4","British capacity unit","hundredweight1","quarter2","time period","quarter3","time unit","hour"]],
"reprieve":[["verb.stative","noun.act:reprieve","noun.communication:reprieve","noun.act:respite1"],["reprieve","respite1","postpone"]],
"last":[["verb.stative","noun.quantity","noun.location:Britain","noun.quantity"],["last","endure6","measure","last1","capacity unit","last2","weight unit"]],
"head":[["verb.stative","noun.location:head2","noun.communication:header","noun.location:head","noun.communication:heading","noun.person","noun.communication:colloquialism","noun.person","verb.stative","verb.change:form5","verb.stative","noun.location:head2","noun.group:head","noun.person:head","verb.motion:head2","verb.stative"],["head","lie","frames:11","head2","drug user","head3","individual","head4","head1","head up","$be3","frames:8","head5","originate"]],
"scale":[["verb.stative","noun.artifact:scale2","noun.act:scalage","noun.act:scaling1","noun.artifact","verb.change:scale","verb.stative:scale","verb.motion","noun.relation","verb.change:scale1","verb.creation:scale","noun.communication:standard"],["scale","measure","scale2","weighing machine","measuring instrument","scale1","surmount","reach1","frames:8","scale3","scale of measurement","graduated table","ordered series"]],
"rail":[["verb.stative","noun.artifact:rail","noun.artifact:rail2","noun.artifact:railing","verb.contact","noun.artifact:rail1","verb.motion","noun.artifact:rail1","noun.artifact:rail3","verb.motion","noun.artifact:rail2","noun.artifact:railing"],["rail","rail in","enclose","frames:8","rail3","lay","rail4","transport","frames:20","rail1","rail off","separate1","frames:8"]],
"beard":[["verb.stative","noun.body:beard","noun.animal:beard1"],["beard","rim"]],
"ape":[["verb.stative","noun.person:ape1","noun.person:aper","noun.act:apery"],["ape","imitate","frames:9"]],
"balance":[["verb.stative","noun.state:balance","noun.state:equilibrium","noun.shape:equilibrium","noun.process:equilibrium","noun.cognition:equilibrium","noun.state:equilibrium","noun.shape:equilibrium","verb.contact:balance","$verb.change:match1","verb.stative","noun.state:balance","noun.animal:balancer","noun.person:balancer"],["balance","unbalance","equilibrate","equilibrize","equilibrise","$balance1","frames:8","balance1","be3","frames:2"]],
"barrack":[["verb.stative","noun.artifact:barrack"],["barrack","lodge","frames:9"]],
"bead":[["verb.stative","noun.shape:bead","verb.change:form5"],["bead","frames:1"]],
"blanket":[["verb.stative","noun.object:blanket","verb.contact:cover1","noun.artifact"],["blanket","blanket1","layer","breeder reactor"]],
"body":[["verb.stative","noun.body:body2","noun.person:personification","noun.communication:personification","noun.body:person","noun.attribute","noun.group"],["body","personify1","embody","frames:8","body1","mass","body2","system"]],
"brim":[["verb.stative","noun.artifact","verb.change:brim"],["brim","have","brim1","rim","lip","edge","vessel1"]],
"camp":[["verb.stative","noun.artifact:camp1","noun.artifact:camp","noun.person:camper","noun.act:camping","noun.act:encampment","noun.location:bivouac","noun.artifact:bivouac","noun.act:tenting","noun.artifact:tent","noun.artifact","verb.stative:camp","noun.artifact","noun.artifact","noun.location:site","noun.artifact"],["camp","encamp","camp out","bivouac","tent","dwell","frames:2","camp1","lodging","camp2","penal institution","camp3","summer camp","camp4","refugee camp","shelter2"]],
"cantilever":[["verb.stative","noun.artifact:cantilever"],["cantilever","project"]],
"cap":[["verb.stative","noun.location:crest1","noun.location:crest","noun.artifact","noun.artifact"],["cap","crest","lie","cap2","top1","cap3","protective covering"]],
"chamber":[["verb.stative","noun.artifact:chamber2","noun.artifact:chamber","verb.social:house","noun.artifact","verb.stative:chamber"],["chamber","frames:8","chamber2","room"]],
"cloister":[["verb.stative","noun.artifact:cloister1","verb.contact:surround"],["cloister","frames:8"]],
"counterweight":[["verb.stative","noun.artifact:counterweight","noun.artifact:counterpoise"],["counterweight","counterpoise","counterpose","counterbalance","frames:11"]],
"cross":[["verb.stative","noun.attribute:span","noun.attribute:sweep","verb.motion","verb.creation","noun.attribute:cross","verb.motion","verb.contact:fold"],["cross","traverse","span","sweep3","extend1","cross1","intersect","cross9","write1","cross4","uncross"]],
"crown":[["verb.stative","noun.communication","verb.social:crown","verb.social:coronate","noun.artifact","noun.artifact","noun.location:top","noun.artifact","noun.cognition:dentistry"],["crown","head","Crown1","symbol","crown2","wreath","crown3","crest1","road","crown4","crownwork","jacket2","jacket crown","cap4","dental appliance"]],
"deck":[["verb.stative","noun.artifact:adornment","adj.all:nonfunctional^decorative","noun.artifact:decoration","noun.act:decoration","noun.attribute:grace1","noun.act:beautification","noun.attribute:beauty","noun.artifact","noun.communication:slang","noun.artifact"],["deck","adorn","decorate","grace","embellish","beautify","be3","deck1","packet","deck2","porch"]],
"dovetail":[["verb.stative","noun.artifact:dovetail",">verb.change:fit1"],["dovetail","fit2"]],
"foil":[["verb.stative","noun.cognition:foil","noun.artifact","verb.contact:foil","verb.creation:foliate","verb.contact:foliate","noun.artifact"],["foil","contrast","frames:8","foil1","sheet metal","foil2","transparency1","picture"]],
"form":[["verb.stative","noun.communication:form2","noun.attribute:constitution","noun.artifact:constituent","noun.attribute","verb.stative","noun.act:formation2","verb.change"],["form","constitute3","make5","be2","form3","manner2","form2","take form","take shape","spring","become","frames:1","2","4","form5","change"]],
"freewheel":[["verb.stative","noun.person:freewheeler"],["freewheel","drift","live1"]],
"front":[["verb.stative","noun.location:front2","noun.location:front","noun.relation:frontage","noun.location","adj.all:anterior^frontal1","verb.stative:front"],["front","back","look","face","face2","$lie","front2","back2","position"]],
"harbor":[["verb.stative","noun.artifact:harbor","noun.location:harborage","noun.artifact:harbour","noun.location:harbourage"],["harbor","harbour","shelter","frames:8"]],
"hoodoo":[["verb.stative","noun.person:hoodoo","noun.artifact:hoodoo","noun.artifact:hoodoo2"],["hoodoo","be3","frames:2"]],
"joint":[["verb.stative","noun.artifact:joint1","noun.shape:joint","verb.contact","noun.artifact"],["joint","fit2","joint1","separate1","joint2","spot"]],
"keep":[["verb.stative","verb.social:keep in","^verb.social:keep out","^verb.consumption:keep off","^verb.communication:keep off","^verb.change:keep down","^verb.change:keep apart","^verb.competition:keep up","adj.all:reparable^maintainable","noun.person:maintainer","verb.competition:hold back","^verb.competition:hold out","^verb.change:hold up","verb.possession","verb.stative","verb.stative","verb.creation:raise3","verb.possession","verb.stative","noun.location:preserve","noun.act:preservation","noun.person:preserver1","verb.competition:protect","verb.stative","verb.change:stay"],["keep","^keep up","^maintain","hold","^hold over","^hold out","^frames:5","20","keep10","maintain10","have","keep1","lodge","frames:8","keep12","keep13","keep12","$store2","keep2","preserve1","keep3","stay fresh"]],
"litter":[["verb.stative","noun.substance:litter","noun.person:litterer"],["litter","be3"]],
"loom":[["verb.stative","noun.shape:tower","noun.attribute:predomination","noun.person:hulk","verb.stative","verb.perception:appear"],["loom","tower","predominate1","hulk","rise","frames:1","loom2","frames:1"]],
"map":[["verb.stative","noun.act:mapping","verb.creation","verb.creation"],["map","locate","map1","map","$depict","map3","map out3","plan"]],
"match":[["verb.stative","noun.artifact:match1","adj.all:similar^correspondent","noun.attribute:correspondence2","adj.all:consistent^agreeable","noun.attribute:agreement","verb.change","noun.cognition:match","noun.event:fitting","noun.artifact","verb.contact","noun.group:match","noun.person:match1","noun.artifact:mate","noun.quantity:couple","noun.artifact:coupling1","noun.group:pair","noun.group:pair1","verb.contact","noun.person:matcher1","noun.group:match","noun.person:match1"],["match","fit4","correspond","check8","jibe","gibe","tally","agree","disagree","agree1","$equal","frames:1","match1","fit","adjust","frames:8","match2","lighter","match8","mate2","couple2","pair1","twin","join1","frames:8","match10","match8","$join1"]],
"nest":[["verb.stative","noun.animal:nester","noun.object:nest","verb.contact","noun.animal:nester","noun.object:nest"],["nest","inhabit","nest1","gather","frames:2"]],
"overhang":[["verb.stative","noun.artifact:overhang","verb.contact:hang3","verb.stative","noun.artifact:overhang"],["overhang","beetle","overhang1","project","frames:1"]],
"photograph":[["verb.stative","noun.artifact:photograph"],["photograph","frames:1"]],
"pig":[["verb.stative","noun.animal:pig","noun.person:pig"],["pig","pig it","live6","frames:2"]],
"pinnacle":[["verb.stative","noun.artifact:pinnacle"],["pinnacle","surmount"]],
"ramp":[["verb.stative","adj.all:uncontrolled^rampant","noun.act:rampage","noun.state:rage","noun.feeling:rage","noun.state:storm","verb.body:act","noun.artifact","verb.possession:ramp","verb.motion"],["ramp","rage1","storm","ramp1","stairway","ramp2","climb","frames:1"]],
"range":[["verb.stative","noun.attribute:range","verb.stative","noun.group:range","noun.location:range1","noun.attribute:range","noun.location","adj.all:mobile^rangy","adj.all:large^rangy","verb.consumption:range","verb.contact:range2","verb.stative","noun.location:range1","noun.cognition:range"],["range","straddle2","be2","range1","run7","run8","$be3","range2","tract","range3"]],
"ride":[["verb.stative","noun.act:ride","verb.motion","verb.stative","verb.motion","noun.act:ride","verb.motion","noun.act:ride","noun.person:rider","noun.act:riding","noun.act:riding","verb.stative","verb.motion:float4"],["ride","continue1","ride3","climb","frames:1","ride2","lie","ride7","travel2","frames:8","ride1","sit3","travel","frames:2","ride4"]],
"ridge":[["verb.stative","noun.object:ridge1","noun.object:ridge","verb.contact","noun.shape:ridge","noun.object"],["ridge","extend1","ridge1","throw","ridge2","geological formation"]],
"rim":[["verb.stative"],["rim","run along"]],
"seat":[["verb.stative","noun.artifact:seat1","noun.location:seat1","noun.artifact:seating","verb.possession","noun.location:seat1","noun.artifact:seat1","noun.act:cabinetry","verb.contact","noun.artifact"],["seat","accommodate3","seat1","supply","seat2","sit",">put","frames:9","seat3","part"]],
"separate":[["verb.stative","noun.location:divide","noun.artifact:divider","verb.social","noun.person:separatist","noun.act:separation2","noun.act:split","noun.event:break3","noun.act:breakup","verb.motion","adj.all:disjunctive^separative1","adj.all:divisible","noun.act:division2"],["separate","divide","separate2","part","split up1","split","break13","break up","separate1","divide","frames:8","9","10"]],
"shelter":[["verb.stative","noun.possession:shelter","noun.state:shelter","noun.artifact:shelter1","noun.artifact:shelter","verb.possession:provide","noun.artifact","verb.stative:shelter","noun.artifact"],["shelter","frames:9","8","10","shelter1","protective covering","shelter2","housing"]],
"shore":[["verb.stative","noun.object:shore"],["shore","bound"]],
"skirt":[["verb.stative","noun.artifact"],["skirt","border","skirt1","cloth covering","garment"]],
"spear":[["verb.stative","noun.artifact:spear","noun.artifact","verb.contact:spear"],["spear","spear up","project","frames:1","spear1","gig3","fizgig1","fishgig","lance1","implement","fishing gear"]],
"square":[["verb.stative","verb.stative","verb.change:adjust1"],["square","agree","square1","frames:8"]],
"stem":[["verb.stative","noun.communication:stem1","verb.stative","noun.act:stem"],["stem","originate in","stem3","orient1"]],
"yield":[["verb.stative","verb.possession"],["yield","stand","relent","soften","frames:1","yield2","give5","afford","supply"]],
"distance":[["verb.stative","noun.feeling:distance","noun.time","adj.all:distant1","adj.all:far^distant2"],["distance","keep","frames:8","distance1","point"]],
"supplement":[["verb.stative","noun.attribute:supplement","verb.possession:supplement"],["supplement","$constitute"]],
"root":[["verb.stative","noun.location:root","noun.location:rootage","verb.change","noun.process:rooting","verb.contact","noun.plant:root"],["root","become","frames:1","root1","root","$grow1","root4","plant"]],
"place":[["verb.stative","noun.attribute:placement","noun.act:localization","noun.location:locale","noun.act:localisation","verb.competition","noun.communication:place2","noun.location","verb.possession:place","verb.social","noun.state:place2","noun.state:place1","noun.cognition:place","verb.cognition","noun.communication:place2","verb.cognition"],["place","localize1","localise1","situate","place2","race","place4","property","geographical area","place1","assign","place3","come in","come out","rank13","frames:6","place13","put13","set13","estimate"]],
"open":[["verb.stative","noun.object:opening","noun.body:opening","noun.artifact:opening1","verb.social","noun.event:opener","noun.event:opening1","noun.act:opening3","verb.creation:open up","^verb.creation:start1","verb.contact","noun.act:opening2","verb.change:change state","verb.perception"],["open","open1","close1","frames:8","open6","close6","open up6","open10","close10","display"]],
"object":[["verb.stative","noun.act:objection1"],["object","be3","frames:4"]],
"average":[["verb.stative","noun.cognition:average"],["average","average out","number"]],
"correlate":[["verb.stative","adj.all:related2^correlative","noun.relation:correlation","noun.cognition:correlation1","noun.cognition:correlation","noun.cognition:correlate"],["correlate","correspond"]],
"intrigue":[["verb.stative","noun.state:fascination","noun.attribute:fascination"],["intrigue","fascinate","interest","frames:10"]],
"pattern":[["verb.stative","noun.location:pattern","noun.act:pattern","noun.cognition:pattern"],["pattern","match","frames:1"]],
"promise":[["verb.stative","noun.cognition:promise","verb.communication","adj.pert:promissory","noun.communication:promise","noun.cognition:promise","noun.person:promisee","noun.person:promisor"],["promise","be3","frames:11","promise1","declare","frames:14"]],
"scruple":[["verb.stative","noun.cognition:scruple","noun.feeling:scruple"],["scruple","hesitate1"]],
"slant":[["verb.stative","noun.attribute:slant"],["slant","lie"]],
"present":[["verb.stative","verb.communication","noun.communication:presentation2","verb.possession","noun.possession:present","noun.act:presentation1","noun.person:presenter2"],["present","pose","constitute","present4","introduce","present1","submit","give","frames:15","17"]],
"miss":[["verb.stative","noun.state:lack","verb.stative","verb.social:fail2","verb.stative"],["miss","have","lack","frames:11","miss1","attend","miss2","frames:1"]],
"act":[["verb.stative","adj.all:actable","noun.communication:act2","noun.act:acting","verb.creation:act3","verb.creation","adj.all:actable","noun.person:actor","noun.communication:act2","noun.act:acting","noun.communication:play3","noun.communication:play1","noun.person:player","noun.act:playing2","noun.act:roleplaying","noun.person:playactor","noun.act:playacting","noun.communication:theater","verb.social","noun.state:action"],["act","$be3","act3","play10","roleplay","playact","play3","$play4","$perform1","act7"]],
"read":[["verb.stative","noun.communication:read","verb.cognition","verb.cognition","noun.person:reader3","noun.person:reader","noun.communication:reading2","verb.communication:speak","verb.communication","noun.cognition:reading2","noun.act:reading2","noun.act:registration1","verb.cognition","verb.creation","noun.cognition:performing arts"],["read","say","have","frames:11","read8","understand","frames:8","read1","frames:2","8","14","15","read2","register","show4","record3","indicate","read6","scan","interpret","frames:8","read5","audition"]],
"leave":[["verb.stative","adj.all:subsequent^resultant","noun.phenomenon:result","noun.event:resultant","$verb.creation:produce3","verb.stative","$verb.change:make","verb.stative","verb.possession:have1","verb.cognition","noun.act:leave","verb.stative","$verb.possession:give5"],["leave","result2","lead4","leave3","leave2","leave","frames:5","leave3","frames:11","leave5","leave2","$frames:8","9","leave1","allow for","allow","provide","frames:22allow7","frames:8"]],
"thrust":[["verb.stative","noun.phenomenon:thrust","verb.motion","noun.phenomenon:thrust","noun.act:shove","verb.stative","noun.phenomenon:thrust","$noun.cognition:geology"],["thrust","push up","project","frames:1","thrust2","stuff","shove1","squeeze","push","frames:20","thrust1","thrust"]],
"exhibit":[["verb.stative","noun.act:exhibition"],["exhibit","possess"]],
"dot":[["verb.stative","noun.shape:dot","noun.artifact:stud1","noun.cognition:constellation"],["dot","stud","constellate","cover1"]],
"do":[["verb.stative","verb.change:go1","verb.social","verb.social","noun.person:doer","verb.creation:carry out"],["do","fare","make out","come2","get along","frames:6","do3","manage2","frames:4","do4","perform","frames:8"]],
"prelude":[["verb.stative","noun.event:prelude"],["prelude","serve3"]],
"refrain":[["verb.stative","verb.social:act","noun.act:forbearance"],["refrain","forbear"]],
"rhyme":[["verb.stative","noun.communication:rhyme","noun.communication:rime"],["rhyme","rime","correspond"]],
"offer":[["verb.stative","noun.communication:offer1","noun.act:offering","verb.possession","noun.communication:offer","noun.communication:bid","noun.person:bidder","noun.communication:tender","*noun.act:auction","verb.perception","verb.possession","noun.communication:offer1","verb.possession","verb.possession","noun.communication:offer1","noun.communication:offering1","verb.communication:give1"],["offer","offer up","worship","offer1","bid","tender2","bargain","frames:2","8","offer6","produce","offer2","provide","frames:8","11","15","offer3","market","offer9","frames:14extend4","frames:8"]],
"result":[["verb.stative","adj.all:subsequent^resultant","noun.phenomenon:result","noun.event:result","noun.state:resultant"],["result","ensue","frames:34turn out"]],
"hum":[["verb.stative","noun.event:hum","noun.event:humming","noun.act:buzz","verb.communication","noun.event:hum","noun.event:humming","verb.perception:make noise"],["hum","buzz","seethe","be3","hum1"]],
"meet":[["verb.stative","adj.all:pervious^receptive","adj.all:receptive","verb.change:experience","verb.motion","verb.social:meet","verb.social","noun.event:meet","noun.person:meeter","noun.group:meeting1","noun.act:meeting","noun.group:get together","verb.social"],["meet","frames:4","22encounter2","receive","frames:8","meet6","frames:8","meet1","get together1","frames:2","meet3","frames:9"]],
"sulk":[["verb.stative","noun.feeling:sulk","noun.person:pouter","verb.emotion:resent"],["sulk","pout","brood"]],
"people":[["verb.stative","noun.group:people3","noun.group:people1","noun.group:people","noun.group"],["people","dwell","people2","family1"]],
"herd":[["verb.stative","noun.group:herd1","noun.group:herd","noun.person:herder","verb.motion","noun.group:herd2","noun.person:herder","noun.group:crowd","noun.state:crowding"],["herd","keep12","herd1","crowd1","move1","frames:8","9","20"]],
"company":[["verb.stative","noun.group:company6","noun.person:companion2","noun.person:companion1","noun.person:companion","noun.act:accompaniment","verb.social:associate2","noun.group","noun.group"],["company","companion","accompany1","keep company","frames:9","company2","troupe","organization","company3","army unit","battalion","battle group","military"]],
"crowd":[["verb.stative","noun.group:crowd","noun.state:crowding","noun.group","verb.competition:gang"],["crowd","occupy1","frames:8","crowd1","crew3","gang2","bunch1","gathering"]],
"aggregate":[["verb.stative","noun.artifact:aggregate"],["aggregate","amount"]],
"rank":[["verb.stative","verb.cognition","noun.state:rank","noun.person:ranker1","noun.person:ranker","noun.state:ranking","verb.stative:be3"],["rank","outrank","frames:9surpass","rank13","frames:8"]],
"carpet":[["verb.stative","noun.artifact:carpet","verb.contact:cover1","verb.contact","noun.artifact:carpet"],["carpet","carpet1","cover"]],
"neighbor":[["verb.stative","noun.object:neighbor","noun.object:neighbour","verb.contact:adjoin2","verb.stative","noun.person:neighbor","noun.person:neighbour"],["neighbor","neighbour","neighbor1","neighbour1","dwell"]],
"star":[["verb.stative","noun.person:star2","noun.person:star","noun.object","adj.all:starry"],["star","feature","star1","celestial body"]],
"twin":[["verb.stative","noun.artifact:twin"],["twin","duplicate","parallel1","match"]],
"bachelor":[["verb.stative","noun.person:bachelor"],["bachelor","bach","live6"]],
"beggar":[["verb.stative"],["beggar","defy1"]],
"co-star":[["verb.stative","noun.person:co-star"],["co-star","star"]],
"begin":[["verb.stative","noun.act:start","noun.time:start","noun.event:start","verb.change","noun.person:beginner1","noun.event:beginning","noun.act:start","noun.time:start","noun.event:start","noun.act:commencement","verb.stative:begin","verb.stative","noun.act:start","noun.event:start","verb.stative","$verb.change:begin1","verb.stative","noun.cognition:beginning"],["begin","end","start","frames:1","4","begin1","end1","lead off","start1","commence1",">frames:8","begin3","start3","begin","$begin2","$be3","begin4","begin","$be3","begin2"]],
"fry":[["verb.stative","verb.change:heat up1"],["fry"]],
"smother":[["verb.stative","verb.contact:cover1","verb.contact","noun.person:smotherer","noun.person:stifler","noun.act:stifling","verb.social:suppress","verb.contact","verb.contact","*verb.change:extinguish"],["smother","smother1","stifle","strangle1","muffle","repress","frames:8","9","10","smother2","surround1","cover","frames:10","smother3","put out","cover","frames:8"]],
"weather":[["verb.stative","noun.group:brave","verb.motion","noun.act:navigation"],["weather","endure4","brave","brave out","defy","frames:11","weather1","sail"]],
"cost":[["verb.stative","noun.attribute:cost","noun.possession:cost","verb.stative","noun.attribute:cost1"],["cost","frames:14be9","be3","cost1","demand"]],
"share":[["verb.stative","noun.relation:sharing","noun.possession","verb.possession","noun.relation:sharing1","verb.consumption:use1"],["share","overlap3","frames:8","9","11","share1","stock certificate","stock","share2","frames:2"]],
"parallel":[["verb.stative","noun.attribute:parallel"],["parallel","correspond"]],
"bulge":[["verb.stative","noun.shape:bulge","verb.change","noun.shape:bulge"],["bulge","bag","project","frames:1","bulge1","bulk","bulge",">swell1"]],
"rage":[["verb.stative","noun.state:rage1","noun.state"],["rage","be3","rage2","passion1","desire"]],
"clash":[["verb.stative","noun.state:clash","noun.communication:collision","noun.state"],["clash","jar","collide","conflict","frames:1","2","4","clash1","conflict"]],
"sleep":[["verb.stative","noun.time:sleep","noun.artifact:sleeper2","noun.artifact:sleeper","noun.state"],["sleep","accommodate3","sleep2","sopor","physical condition"]],
"chelate":[["verb.stative","noun.process:chelation2","noun.process:chelation1","noun.substance:chelate"],["chelate","form"]],
"carbonate":[["verb.stative","noun.substance:carbonic acid","noun.substance:carbon","noun.substance:carbonate","verb.change:change"],["carbonate"]],
"honeymoon":[["verb.stative","noun.time:honeymoon","noun.person:honeymooner","noun.time"],["honeymoon","vacation","frames:2","honeymoon1","time period"]],
"summer":[["verb.stative","noun.time:summer"],["summer","spend","frames:2"]],
"weekend":[["verb.stative","noun.time:weekend","noun.person:weekender","noun.artifact:weekender"],["weekend","spend"]],
"winter":[["verb.stative","noun.time:winter"],["winter","overwinter","spend","frames:2"]],
"breathe":[["verb.stative","verb.communication","verb.stative"],["breathe","exist1","frames:1","breathe3","convey","frames:8","11","breathe1","be3"]],
"make":[["verb.stative","verb.change","verb.stative","verb.social:make1","noun.cognition:arithmetic","verb.stative","verb.communication","verb.social:break9","verb.motion","verb.social:work5","verb.stative","noun.artifact:making","noun.act:making","verb.change:change","verb.stative","verb.stative","noun.artifact:making"],["make","become","frames:9","make2","make up","straighten","make12","$amount1","make15","constitute","make14","assure3","frames:8","9","10","make10","work","$pass","frames:22","make9","make11","make12","$amount3","make13","be3","frames:11"]],
"spread-eagle":[["verb.stative"],["spread-eagle","straddle2"]],
"vegetate":[["verb.stative","adj.pert:vegetative1","noun.act:vegetation","verb.change","noun.group:vegetation"],["vegetate","live6","vegetate2","grow1"]],
"have":[["verb.stative","noun.body:feature","noun.cognition:feature","verb.possession:have","$verb.possession:have4","verb.stative"],["have","lack","feature","have12"]],
"help":[["verb.stative","noun.attribute:help","noun.act:help","noun.act:facilitation","verb.change","noun.attribute:help","noun.act:help","verb.social","noun.person:helper1","noun.person:helper","noun.attribute:help","noun.act:help"],["help","frames:35facilitate","frames:35serve1","frames:2","34","help13","better1","help12","promote1","frames:8"]],
"continue":[["verb.stative","noun.person:upholder","noun.state:preservation","verb.stative:continue1","$verb.motion:continue","verb.stative","noun.attribute:continuation","noun.act:continuation","noun.act:continuance","verb.social:act","verb.stative","noun.attribute:continuation","noun.act:continuation","$verb.social:act","verb.stative","noun.act:continuation","verb.social:continue","$verb.social:act"],["continue","discontinue","uphold","carry on","bear on1","preserve","$keep","frames:8","continue1","discontinue1","frames:1","2go on","frames:1","2proceed","go along","keep7","continue11","continue1","frames:2","continue12","persist in","frames:8"]],
"individuate":[["verb.stative","noun.cognition:individuation","noun.attribute:individuation"],["individuate","characterize1","frames:10"]],
"suspend":[["verb.stative"],["suspend","defer"]],
"become":[["verb.stative","verb.stative","noun.event:turn1","verb.change:transform3","verb.stative","verb.change:embellish"],["become","become1","turn","frames:9","become3","suit1"]],
"reincarnate":[["verb.stative","noun.person:reincarnation","noun.event:transmigration","verb.change:be born","noun.cognition:religion"],["reincarnate","transmigrate"]],
"clean":[["verb.stative","noun.act:cleaning","verb.contact","verb.change:remove","verb.contact","verb.possession:deprive1"],["clean","be3","frames:1","clean4","strip4","frames:8","11","22","clean12"]],
"add":[["verb.stative","adj.all:additive","verb.change:add","verb.communication"],["add","$form","add1","append","supply","state","frames:8","11"]],
"include":[["verb.stative"],["include","exclude","have"]],
"qualify":[["verb.stative","noun.attribute:qualification","noun.state:quality","noun.attribute:quality2","noun.person:qualifier","noun.act:qualifying","verb.communication","noun.cognition:quality","noun.attribute:quality","noun.communication:characterization1","noun.cognition:character","noun.communication:characterisation1","noun.communication:characterisation","noun.communication:character1","noun.cognition:character","verb.cognition:think of"],["qualify","measure up","suffice","frames:1","qualify1","characterize","characterise","frames:8","9","10"]],
"lubricate":[["verb.stative","noun.state:lubrication","noun.substance:lubricant","noun.substance:lubricator"],["lubricate","be3"]],
"mummify":[["verb.stative","noun.state:mummification"],["mummify","preserve"]],
"work out":[["verb.stative","verb.cognition","$verb.stative:amount1"],["work out","turn out2","work out7","work out6"]],
"derive":[["verb.stative","adj.all:derived^derivative","noun.location:derivation","noun.attribute:derivation","noun.relation:descent","noun.group:descent","noun.person:descendent","noun.person:descendant","verb.change","adj.all:derived^derivative","noun.process:derivation","noun.location:derivation","noun.communication:derivation1","noun.communication:deriving","verb.stative:come15"],["derive","come15","descend","come9","$frames:22","derive1","$evolve"]],
"total":[["verb.stative","noun.artifact:total","noun.cognition:total","noun.communication:number1","noun.quantity:number","noun.attribute:number","noun.cognition:amount","noun.Tops:amount"],["total","number","add up3","come12","amount1","be3"]],
"predate":[["verb.stative","adj.all:preceding^precedent","noun.act:precession","noun.cognition:precedent","noun.attribute:precedency","noun.attribute:precedence","noun.attribute:antecedency","noun.event:antecedent","noun.attribute:antecedence"],["predate","postdate","precede","forego","forgo","antecede","antedate"]],
"postdate":[["verb.stative"],["postdate","predate","follow"]],
"take in":[["verb.stative","verb.social:house","verb.consumption","verb.contact","verb.possession:receive"],["take in","take in1","sop up","suck in","take up","ingest","take in2","take up1","frames:8","9","10"]],
"taper off":[["verb.stative"],["taper off","peter out","fizzle out","fizzle","discontinue1"]],
"prolong":[["verb.stative","noun.attribute:prolongation1","noun.act:prolongation","adj.pert:sustainable","noun.person:sustainer","noun.act:sustenance"],["prolong","sustain1","keep up","continue","frames:11"]],
"bake":[["verb.stative"],["bake","broil","be3","frames:1"]],
"bifurcate":[["verb.stative","noun.act:fork","noun.shape:bifurcation1","noun.act:bifurcation"],["bifurcate","diverge","frames:1"]],
"intervene":[["verb.stative"],["intervene","lie","frames:4"]],
"take up":[["verb.stative","verb.social","verb.motion:turn14"],["take up","occupy1","take up1","frames:8"]],
"go out":[["verb.stative","verb.change:change","noun.cognition:fashion","verb.motion","verb.motion"],["go out","come in","go out2","leave1","go out1","leave1","frames:1"]],
"come to life":[["verb.stative"],["come to life","resemble","frames:1"]],
"converge":[["verb.stative","adj.all:convergent","noun.act:convergency","noun.act:converging","noun.event:convergence","verb.contact:meet","verb.stative","noun.cognition:convergency","noun.cognition:convergence","noun.cognition:math"],["converge","diverge","meet2","$frames:1","converge1","diverge2","approach"]],
"translate":[["verb.stative","noun.communication:translation","verb.communication:translate","verb.communication","noun.process:translation","noun.cognition:genetics","verb.communication","verb.motion","noun.act:translation1","noun.cognition:physics","verb.stative"],["translate","$be3","frames:1","translate5","determine","frames:1","translate6","paraphrase","translate4","move1","frames:8","translate3","be7"]],
"synchronize":[["verb.stative","noun.relation:synchronization","noun.relation:synchrony","noun.relation:synchronizing","noun.relation:synchronisation","noun.relation:synchrony","verb.change:happen","verb.change","verb.change","$verb.contact:operate"],["synchronize","synchronise","contemporize","contemporise","synchronize3","synchronise3","align","synchronize1","synchronise1","synchronize3"]],
"equal":[["verb.stative","verb.stative","noun.person:equal","noun.person:match","verb.competition:compete"],["equal","differ","be7","frames:11","equal1","touch2","rival","match1","frames:11"]],
"homologize":[["verb.stative","noun.attribute:homology"],["homologize","correspond"]],
"retard":[["verb.stative","noun.time:retardation","noun.attribute:retardation","noun.act:retardation"],["retard","be3"]],
"populate":[["verb.stative","noun.group:population","noun.person:dweller","noun.artifact:dwelling","adj.all:liveable","adj.all:livable","noun.person:liver","verb.consumption:live in","^verb.consumption:live out","noun.act:inhabitation","noun.person:inhabitant","noun.act:inhabitancy"],["populate","dwell","live8","^inhabit","be5"]],
"align":[["verb.stative","noun.act:alignment","verb.change","noun.act:alignment","noun.act:coordination"],["align","match","align1","ordinate","coordinate1","adjust"]],
"harmonize":[["verb.stative","noun.state:harmony","noun.attribute:harmony1","adj.all:accordant","noun.attribute:accord","noun.state:concord","adj.all:consistent^agreeable"],["harmonize","harmonise","consort","accord","concord","fit in","agree1","match","frames:2","1"]],
"adhere":[["verb.stative","verb.stative","noun.act:adhesion","noun.person:adherent","verb.possession:follow"],["adhere","agree","adhere2","stick5"]],
"reverberate":[["verb.stative","noun.phenomenon:reverberation"],["reverberate","persist"]],
"rusticate":[["verb.stative","noun.person:rustic","noun.state:rustication","noun.act:rustication"],["rusticate","reside","frames:2"]],
"run out":[["verb.stative","noun.time:expiration"],["run out","expire","discontinue1"]],
"leave off":[["verb.stative"],["leave off","discontinue1"]],
"retain":[["verb.stative","adj.all:retentive","verb.social","noun.attribute:continuation","verb.stative:prolong"],["retain","hold13","frames:8","retain1","continue","keep2","keep on","frames:9"]],
"recognize":[["verb.stative","verb.social","verb.possession:appreciate"],["recognize","be3","recognize1","recognise1","frames:8"]],
"exclude":[["verb.stative"],["exclude","include","lack","frames:11"]],
"compare":[["verb.stative","noun.attribute:compare","verb.cognition","adj.pert:comparative","noun.attribute:compare","noun.attribute:comparison","noun.act:comparing","noun.person:equal","noun.act:equation","noun.act:equating","verb.perception:consider"],["compare","be3","compare1","liken","equate","frames:20"]],
"refer":[["verb.stative","noun.cognition:reference","adj.all:apropos^pertinent","noun.relation:pertinency","noun.relation:pertinence","verb.communication:touch9","verb.communication"],["refer","frames:4pertain1","frames:4relate","frames:4concern","come to3","bear on","touch","touch on","have to do with","$frames:10","refer4","call2","frames:8","9","10"]],
"collocate":[["verb.stative"],["collocate","occur3"]],
"prove":[["verb.stative","verb.cognition","noun.cognition:mathematics","verb.cognition","noun.group:law"],["prove","turn out","turn up3","be3","frames:6","7","28","prove2","prove","prove1","authenticate"]],
"accept":[["verb.stative","verb.cognition","verb.cognition","adj.all:receptive^acceptive","adj.all:acceptive","adj.all:receptive^acceptant","noun.state:acceptation","noun.act:acceptation","noun.state:acceptance","noun.act:acceptance","verb.possession","noun.state:acceptation"],["accept","take3","be3","accept8","respond","accept1","react","frames:8","accept7","receive"]],
"sit out":[["verb.stative","noun.act:sport"],["sit out","refrain"]],
"buy":[["verb.stative","noun.possession:buy","verb.possession"],["buy","be3","buy3","get"]],
"subsume":[["verb.stative","noun.cognition:subsumption"],["subsume","include"]],
"pay":[["verb.stative","verb.possession","noun.possession:payment","noun.act:payment","noun.person:payer","verb.possession","noun.possession:pay1","noun.person:payee","noun.person:payer","verb.competition:pay back","^verb.competition:pay off","noun.possession:compensation","noun.act:compensation","verb.possession","verb.competition:pay back"],["pay","be3","pay14","settle","pay2","^pay off4","make up","compensate2","settle","pay13","$requite"]],
"apply":[["verb.stative","adj.all:practical^applicative","adj.all:relevant^applicable","verb.communication","noun.act:application2","verb.social","noun.act:application1","verb.communication:devote"],["apply","hold4","go for","frames:11","10apply1","$relate","frames:1","apply1","refer","frames:15","apply9"]],
"oppose":[["verb.stative","noun.artifact:counterbalance"],["oppose","counterbalance","contrast","frames:11"]],
"prevail":[["verb.stative","noun.attribute:prevalence","adj.all:persistent","noun.person:diehard","$verb.change:continue10","verb.stative"],["prevail","persist","die hard","run3","endure8","run6","prevail1","hold2","obtain","exist"]],
"cancel":[["verb.stative","noun.possession:offset","verb.social","noun.act:cancellation","verb.communication:schedule"],["cancel","offset","set off","balance","cancel3","call off","scratch","scrub"]],
"disagree":[["verb.stative","adj.all:inharmonious^discordant","adj.all:discordant","noun.state:discord","noun.act:discordance"],["disagree","agree","disaccord","discord","be3"]],
"confront":[["verb.stative","noun.communication:confrontation","noun.act:confrontation","verb.communication","noun.act:confrontation1"],["confront","face","frames:8","confront3","face3","present6","frames:17face","$frames:9","10","8"]],
"admit":[["verb.stative","verb.social","adj.all:admissible^admittible","adj.all:admissible^admittable","noun.possession:admission","noun.act:admission","noun.act:intromission","verb.stative:admit3","$verb.communication:permit","verb.stative","adj.all:admissible^admittible","adj.all:admissible^admittable","noun.possession:admission","verb.stative","adj.all:receptive^admissive","adj.all:admissible^allowable"],["admit","admit1","reject","allow in","let in2","intromit","frames:9","20","admit3","serve","frames:11","admit6","allow7"]],
"contradict":[["verb.stative","adj.all:unsupportive^contradictory","adj.all:inconsistent^contradictory","adj.all:incompatible1^contradictory","adj.all:antonymous^contradictory","noun.communication:negation2"],["contradict","belie","negate","vary"]],
"typify":[["verb.stative","noun.cognition:typification","noun.person:type","noun.group:type1","noun.cognition:type","noun.communication:epitome","noun.cognition:epitome","noun.communication:epitome","noun.cognition:epitome","verb.communication:represent2"],["typify","epitomize","epitomise","frames:11"]],
"defy":[["verb.stative","adj.all:defiant","noun.person:withstander","verb.competition:resist","verb.stative"],["defy","withstand","hold8","hold up2","frames:11","defy1","lend oneself","resist1","refuse","elude"]],
"orient":[["verb.stative","noun.communication:pointer","noun.artifact:pointer"],["orient","point","lie"]],
"get into":[["verb.stative","verb.change:change state"],["get into","tangle with","frames:1"]],
"stand up":[["verb.stative"],["stand up","hold up1","hold water","last1"]],
"account for":[["verb.stative"],["account for","be3"]],
"specify":[["verb.stative","noun.communication:delineation1"],["specify","define","delineate","delimit","delimitate","be3"]],
"redefine":[["verb.stative","noun.communication:redefinition"],["redefine","define"]],
"run on":[["verb.stative","verb.communication:keep going"],["run on","keep going2","$continue1","frames:1"]],
"go around":[["verb.stative"],["go around","suffice"]],
"articulate":[["verb.stative"],["articulate","unite2"]],
"exemplify":[["verb.stative","noun.cognition:exemplification","noun.cognition:example2","noun.cognition:example"],["exemplify","represent1","be8","frames:11"]],
"line up":[["verb.stative","verb.contact:arrange","verb.motion","noun.group:lineup","noun.group:queue","verb.stative:wait","*verb.contact:stand"],["line up","frames:1","2","4","line up1","queue up","queue"]],
"sit":[["verb.stative","verb.motion","noun.communication:sitting","verb.stative"],["sit","sit around","be5","frames:1","sit1","convene","frames:1","sit5","be5"]],
"go down":[["verb.stative"],["go down","frames:22"]],
"emulate":[["verb.stative","noun.feeling:emulation","noun.act:emulation","noun.person:emulator","verb.creation:imitate","verb.stative","noun.cognition:emulation","noun.cognition:computer science"],["emulate","frames:8","emulate1","imitate"]],
"invade":[["verb.stative","noun.event:invasion","noun.state:infestation","noun.group:infestation"],["invade","overrun","infest2","inhabit2","frames:4"]],
"put out":[["verb.stative","verb.contact","noun.act:putout","noun.act:baseball"],["put out","be3","put out1","retire","play"]],
"partake":[["verb.stative"],["partake","share"]],
"live out":[["verb.stative"],["live out","live4"]],
"afford":[["verb.stative","adj.all:cheap^affordable","verb.possession","noun.cognition:open","noun.body:opening"],["afford","afford1","open4","give15"]],
"violate":[["verb.stative","adj.all:violable","adj.all:offending^violative","noun.act:violation4"],["violate","conform to","go against","break","frames:8"]],
"tessellate":[["verb.stative"],["tessellate","fit2"]],
"nestle":[["verb.stative"],["nestle","lie"]],
"entangle":[["verb.stative","noun.artifact:entanglement"],["entangle","mire","involve4","frames:10"]],
"shut off":[["verb.stative"],["shut off","close off","discontinue","frames:8","9"]],
"dangle":[["verb.stative","noun.artifact:swing","noun.act:swinging","verb.contact:hang3"],["dangle","swing","drop4","frames:1"]],
"incorporate":[["verb.stative","noun.act:incorporation"],["incorporate","contain","comprise","include","frames:11"]],
"stand back":[["verb.stative"],["stand back","keep one's eyes off","keep one's distance","keep one's hands off","stay away","be5","frames:2"]],
"situate":[["verb.stative","noun.location:situation","noun.person:locater","noun.act:location1","noun.Tops:location","noun.person:locator","verb.communication:determine"],["situate","locate"]],
"divaricate":[["verb.stative"],["divaricate","diverge"]],
"reticulate":[["verb.stative","noun.artifact:reticulation","noun.body:reticulum","verb.change:change"],["reticulate"]],
"enclose":[["verb.stative","noun.object:enclosure","noun.artifact:enclosure","noun.state:confinement"],["enclose","hold in","confine","hold13"]],
"underrun":[["verb.stative"],["underrun","run"]],
"compose":[["verb.stative","noun.cognition:component"],["compose","make up"]],
"originate":[["verb.stative","adj.all:original^originative","noun.event:origin","noun.event:origination","noun.act:origination","noun.event:growth1","verb.stative","noun.location:origin","noun.event:origin","noun.event:origination"],["originate","arise","rise1","develop","uprise2","spring up","grow","become","originate2","begin"]],
"incarnate":[["verb.stative","noun.person:incarnation","noun.act:embodiment"],["incarnate","body forth","embody1","substantiate","be3","frames:8"]],
"overbear":[["verb.stative"],["overbear","dominate1","frames:8"]],
"imitate":[["verb.stative"],["imitate","resemble","frames:9"]],
"take after":[["verb.stative"],["take after","resemble"]],
"unbalance":[["verb.stative"],["unbalance","balance","frames:8"]],
"dote":[["verb.stative","noun.person:dotard","verb.change:age"],["dote"]],
"hold over":[["verb.stative","noun.act:holdover","verb.stative","noun.person:holdover"],["hold over","keep","hold over1","stay2"]],
"satisfy":[["verb.stative","adj.all:good1^satisfactory","adj.all:satisfactory","noun.act:satisfaction","noun.object:satisfier","noun.act:fulfillment","noun.act:fulfilment","verb.consumption:meet"],["satisfy","fall short of","fulfill","fulfil","live up to","frames:11"]],
"gravitate":[["verb.stative","noun.cognition:gravitation","verb.stative","noun.cognition:gravitation"],["gravitate","be3","frames:4","gravitate1","tend1"]],
"falter":[["verb.stative","noun.person:waverer"],["falter","waver2","hesitate","frames:1"]],
"swim":[["verb.stative"],["swim","drown","be3"]],
"boggle":[["verb.stative"],["boggle","hesitate"]],
"hover":[["verb.stative","adj.all:irresolute^vacillant","noun.cognition:vacillation","noun.person:vacillator","noun.process:oscillation","verb.stative"],["hover","vibrate3","vacillate","oscillate","waver","hover1","linger1","hesitate"]],
"leap out":[["verb.stative","verb.perception:appear"],["leap out","jump out","jump","stand out2","stick out2","frames:1","4"]],
"transgress":[["verb.stative","noun.phenomenon:transgression"],["transgress","overspread"]],
"infest":[["verb.stative"],["infest","inhabit2"]],
"diverge":[["verb.stative","adj.all:divergent","noun.act:divergency","verb.stative","noun.cognition:divergency","noun.cognition:divergence","noun.cognition:math"],["diverge","converge","diverge2","converge","be3"]],
"overarch":[["verb.stative"],["overarch","dominate"]],
"bushwhack":[["verb.stative","noun.person:bushwhacker1"],["bushwhack","live6"]],
"deviate":[["verb.stative","adj.all:abnormal^deviant","noun.person:deviate","noun.event:deviation","noun.cognition:deviation","noun.attribute:deviation1","noun.act:deviation","noun.person:deviant","adj.all:different^variant","noun.phenomenon:variation","noun.person:variation","noun.act:variation","noun.event:variant","noun.act:variance","adj.all:different^divergent","noun.event:divergence","noun.event:departure1","verb.motion","noun.act:deviation1"],["deviate","conform6","vary","diverge1","depart","differ","frames:1","deviate1","divert1","frames:8"]],
"elude":[["verb.stative","adj.all:unidentifiable^elusive","adj.all:impalpable^elusive","verb.cognition:baffle"],["elude","escape"]],
"overshadow":[["verb.stative"],["overshadow","dominate3","eclipse","loom6"]],
"attend":[["verb.stative","noun.person:attendant1","noun.person:attender1","noun.person:attender","noun.act:attendance","noun.act:church","verb.social","noun.act:attention1","verb.stative"],["attend","miss1","go to","be5","attend12","take care11","look13","see14","care13","attend1","accompany"]],
"seem":[["verb.stative"],["seem","be3"]],
"distribute":[["verb.stative","verb.stative","$verb.motion:spread"],["distribute","be3","distribute2","distribute1"]],
"eke out":[["verb.stative","verb.possession","verb.possession"],["eke out","live6","eke out1","squeeze out1","make1","eke out2","fill out","supplement"]],
"compensate":[["verb.stative","noun.act:compensation","noun.possession:counterbalance","noun.artifact:counterbalance","adj.all:bettering^corrective","verb.possession","noun.possession:compensation","noun.act:compensation","noun.possession:reparation1","noun.act:reparation","noun.possession:indemnification","noun.act:indemnification","noun.possession:indemnity"],["compensate","counterbalance1","correct3","make up3","even out","even off","even up","balance","compensate1","recompense1","repair","indemnify","pay","frames:8"]],
"owe":[["verb.stative","verb.possession"],["owe","build on","frames:21","owe1","frames:8","14"]],
"misspend":[["verb.stative","verb.possession:spend"],["misspend"]],
"spend":[["verb.stative","verb.possession","noun.person:spender2","noun.act:spending","verb.consumption:use up"],["spend","pass","spend1","frames:8"]],
"acquire":[["verb.stative"],["acquire","locate","frames:8"]],
"lend":[["verb.stative","verb.possession","noun.artifact:addition","verb.change:change1"],["lend","be3","frames:20","lend1","impart1","bestow1","contribute1","add","bring2","frames:11","8","15"]],
"hold one's own":[["verb.stative"],["hold one's own"]],
"govern":[["verb.stative"],["govern","require"]],
"set back":[["verb.stative"],["set back","knock back","put back","cost"]],
"compel":[["verb.stative"],["compel","necessitate"]],
"localize":[["verb.stative","noun.process:focalization","noun.process:focalisation"],["localize","localise","focalize","focalise","lie"]],
"kick around":[["verb.stative"],["kick around","knock about","kick about","exist","frames:1"]],
"sit in":[["verb.stative"],["sit in","attend"]],
"exist":[["verb.stative","adj.all:existent4","adj.all:existent2","adj.all:existent","noun.state:existence","noun.state:being","verb.stative","noun.state:survival","noun.person:subsister","noun.state:subsistence1"],["exist","be","frames:1","2","exist1","survive","live1","subsist","live4","$frames:1","2","22"]],
"preexist":[["verb.stative","adj.all:antecedent^preexistent","adj.all:antecedent^pre-existent","noun.state:preexistence"],["preexist","exist"]],
"coexist":[["verb.stative","adj.all:synchronous^coexistent","verb.stative","adj.all:synchronous^coexistent","noun.state:coexistence"],["coexist","cohabit1","exist","frames:1","coexist1","coexist","frames:1"]],
"cut across":[["verb.stative"],["cut across","be3"]],
"eventuate":[["verb.stative","noun.phenomenon:event1"],["eventuate","come out"]],
"bunk off":[["verb.stative","noun.communication:slang"],["bunk off","play hooky","cut"]],
"live":[["verb.stative","noun.person:liver1","noun.cognition:living","verb.stative"],["live6","be","live7","live6"]],
"dissipate":[["verb.stative","noun.act:dissipation1"],["dissipate4","live6"]],
"unlive":[["verb.stative"],["unlive","live down","live6"]],
"buccaneer":[["verb.stative","noun.person:buccaneer"],["buccaneer","live6"]],
"indwell":[["verb.stative","noun.process:indweller"],["indwell","exist"]],
"survive":[["verb.stative","noun.state:survival","noun.state:endurance","verb.stative","noun.person:survivor3","noun.state:survival","verb.body:recuperate","*verb.competition:overcome3"],["survive1","last1","live4","live on","go14","endure","hold up","hold out","be1","*live","$frames:1","2","survive2","succumb","frames:8pull through","pull round","come through","make it"]],
"perennate":[["verb.stative","noun.plant:perennial","noun.process:perennation"],["perennate","survive1"]],
"last out":[["verb.stative","noun.animal:stayer"],["last out","stay3","ride out","outride"]],
"outstay":[["verb.stative"],["outstay1","stay3","frames:11"]],
"make sense":[["verb.stative"],["make sense","add up","be3","frames:1"]],
"outlive":[["verb.stative","noun.person:survivor2"],["outlive","outlast","survive3","be1","*frames:8","9","10"]],
"succumb":[["verb.stative","verb.change:die"],["succumb","survive2","yield5","frames:2"]],
"constitute":[["verb.stative","adj.all:essential^constituent","noun.attribute:makeup"],["constitute","represent","make up","comprise3","be2","frames:8"]],
"hang together":[["verb.stative","adj.all:dependent^interdependent","noun.relation:interdependency","noun.relation:interdependence","verb.contact:connect"],["hang together","interdepend"]],
"intercommunicate":[["verb.stative"],["intercommunicate","interconnect"]],
"complect":[["verb.stative","noun.group:complexion","noun.state:interconnection"],["complect","interconnect","interlink","connect2"]],
"tide over":[["verb.stative"],["tide over","bridge over1","keep going","suffice"]],
"resurge":[["verb.stative","adj.all:revived^resurgent","noun.act:resurgence"],["resurge","rise1"]],
"come forth":[["verb.stative","adj.all:nascent^emergent","noun.act:emersion1"],["come forth","emerge","arise"]],
"flocculate":[["verb.stative","adj.all:soft1^flocculent","noun.process:flocculation","verb.change:change","verb.stative","adj.all:soft1^flocculent","verb.change:change1"],["flocculate","flocculate1"]],
"nucleate":[["verb.stative","noun.body:nucleus"],["nucleate","become1"]],
"well up":[["verb.stative"],["well up","swell3","arise","frames:1"]],
"originate in":[["verb.stative"],["originate in","frames:11"]],
"necessitate":[["verb.stative","noun.state:necessity","noun.object:necessity","noun.object:need","noun.cognition:requirement1","noun.cognition:demand","noun.state:demand","verb.communication:take","verb.stative"],["necessitate","obviate","frames:34ask","postulate","need","require","frames:24","34take","involve7","call for","demand","necessitate1","lead12"]],
"cry out for":[["verb.stative"],["cry out for","cry for","need"]],
"obviate":[["verb.stative","noun.act:obviation"],["obviate","necessitate","rid of","eliminate1"]],
"preclude":[["verb.stative","adj.all:preventive^preclusive"],["preclude","rule out","close out","obviate"]],
"give off":[["verb.stative"],["give off","have","frames:11"]],
"phosphoresce":[["verb.stative","adj.all:light6^phosphorescent","noun.phenomenon:phosphorescence"],["phosphoresce","exhibit"]],
"possess":[["verb.stative","verb.stative"],["possess","have","frames:11","possess2","dominate1"]],
"consist":[["verb.stative","verb.stative","noun.attribute:consistency2","noun.attribute:consistence2","verb.stative"],["consist1","comprise1","be3","consist2","agree","consist4","be3"]],
"equate":[["verb.stative","noun.state:equation","noun.communication:equation","adj.all:similar^correspondent"],["equate","frames:11correspond4","equal"]],
"be due":[["verb.stative"],["be due","frames:4flow from","result"]],
"incriminate":[["verb.stative","adj.all:inculpatory^incriminatory","noun.communication:incrimination","noun.act:crime1","noun.act:crime","noun.relation:implication","noun.communication:implication","adj.all:inculpative","adj.all:inculpatory","noun.communication:inculpation","verb.communication:suggest1"],["incriminate","imply2","inculpate"]],
"bide":[["verb.stative","noun.act:abidance1","noun.act:stay","noun.communication:archaism"],["bide","abide1","stay1","remain3"]],
"overstay":[["verb.stative"],["overstay","outstay","stay1"]],
"remain":[["verb.stative","noun.relation:remainder","noun.artifact:remainder","noun.relation:remnant"],["remain5","be3"]],
"kick one's heels":[["verb.stative"],["kick one's heels","cool one's heels","wait","frames:1","4","2"]],
"stand by":[["verb.stative"],["stand by","refrain","frames:2"]],
"loiter":[["verb.stative","noun.person:loiterer","noun.person:lounger","noun.person:lingerer"],["loiter","lounge","footle","lollygag","loaf","lallygag","hang around","mess about","tarry","linger","lurk","mill about","mill around","be3","frames:2"]],
"bum":[["verb.stative","noun.person:loafer","verb.social:idle"],["bum","bum around","bum about","arse around","arse about","fuck off","loaf1","frig around","waste one's time","lounge around","loll","loll around","lounge about","frames:2"]],
"lie about":[["verb.stative","verb.social:idle"],["lie about","lie around","frames:2"]],
"lurk":[["verb.stative","noun.person:lurker","noun.person:skulker","verb.perception:hide"],["lurk1","skulk"]],
"dwell on":[["verb.stative"],["dwell on","linger over","hesitate"]],
"hesitate":[["verb.stative","adj.all:indecisive1^hesitant","noun.cognition:hesitation","noun.attribute:hesitation1","noun.person:hesitater","noun.attribute:hesitancy","noun.person:hesitator","noun.act:waver1","noun.person:waverer","noun.cognition:wavering","noun.person:waffler","verb.cognition:doubt1","verb.stative","noun.act:hesitation","noun.person:hesitater","noun.act:pause","noun.time:pause"],["hesitate","waver","waffle","*frames:2","28","hesitate1","pause","delay","frames:2"]],
"hold out":[["verb.stative","noun.person:holdout","noun.communication:holdout"],["hold out2","wait1","frames:2"]],
"procrastinate":[["verb.stative","noun.act:procrastination","noun.person:procrastinator","noun.act:stall","noun.act:shillyshally","noun.person:dillydallier","verb.stative","noun.attribute:procrastination"],["procrastinate","stall","drag one's feet","drag one's heels","shillyshally2","dilly-dally","dillydally","delay","procrastinate1","procrastinate","delay","frames:8"]],
"postpone":[["verb.stative","noun.act:postponement","noun.person:postponer","noun.act:prorogation","noun.person:shelver","noun.act:deferment","noun.act:deferral1","noun.communication:putoff","verb.social:cancel3","*verb.communication:reschedule"],["postpone","prorogue","hold over2","put over","table","shelve","set back1","defer","remit","put off","*delay","frames:8"]],
"predominate":[["verb.stative","adj.all:frequent^predominant","noun.state:predomination","noun.state:predominance","noun.time:reign1","noun.attribute:prevalence1"],["predominate","dominate","rule","reign","prevail2","frames:1","4","2"]],
"outnumber":[["verb.stative"],["outnumber","number","frames:8","9"]],
"preponderate":[["verb.stative","adj.all:dominant1^preponderant","noun.attribute:preponderance2","noun.attribute:preponderance1","noun.attribute:preponderance"],["preponderate","outweigh","overbalance","outbalance","predominate"]],
"weigh":[["verb.stative","noun.person:weigher","$verb.change:measure","verb.stative"],["weigh","librate","weigh1","frames:8","9","weigh1","measure","frames:11"]],
"deserve":[["verb.stative","adj.all:worthy^meritable","noun.attribute:merit2"],["deserve","merit4","be3","frames:8"]],
"have it coming":[["verb.stative"],["have it coming","deserve"]],
"perpetuate":[["verb.stative","noun.act:perpetuation"],["perpetuate","continue"]],
"eternize":[["verb.stative"],["eternize","perpetuate"]],
"occupy":[["verb.stative","noun.act:occupation1","noun.person:occupier","noun.person:occupant","noun.act:occupancy","adj.all:resident","noun.person:resident","noun.act:residency","noun.act:residence","verb.stative","noun.time:occupation"],["occupy","reside1","lodge in","dwell","frames:8","occupy1","fill","be5"]],
"stay at":[["verb.stative"],["stay at1","reside1"]],
"reside":[["verb.stative","adj.all:resident","noun.person:resident","noun.act:residency","noun.act:residence","noun.artifact:shack"],["reside","shack","domicile","domiciliate","dwell"]],
"overpopulate":[["verb.stative","noun.group:overpopulation"],["overpopulate","populate"]],
"cohabit":[["verb.stative","noun.act:cohabitation"],["cohabit","live together","shack up","dwell","frames:2"]],
"wrangle":[["verb.stative","noun.person:wrangler"],["wrangle","herd"]],
"sleep over":[["verb.stative"],["sleep over","stay over","lodge2","frames:2"]],
"lay over":[["verb.stative","noun.act:layover","noun.act:stopover","verb.motion:stop2"],["lay over","stop over","frames:1"]],
"dwell":[["verb.stative","noun.location:lie","verb.stative"],["dwell1","consist","lie1","lie in","exist","dwell3","inhabit3","exist"]],
"inhere":[["verb.stative","adj.all:intrinsic^inherent","adj.all:implicit^inherent","noun.state:inherence"],["inhere","belong6"]],
"pertain":[["verb.stative","adj.all:relevant^pertinent","adj.all:supportive^appurtenant","noun.artifact:appurtenance"],["pertain","appertain","belong6"]],
"inhabit":[["verb.stative","noun.act:inhabitation"],["inhabit2","be5"]],
"coincide":[["verb.stative","adj.all:synchronous^coincident","noun.event:co-occurrence"],["coincide","co-occur","cooccur","cooccur with","^coexist","frames:1"]],
"collocate with":[["verb.stative"],["collocate with","construe with","cooccur with","co-occur with","go with","accompany"]],
"aberrate":[["verb.stative","noun.state:aberration1","noun.phenomenon:aberration","noun.state:aberrance","noun.cognition:optics","verb.stative","noun.state:aberration1","noun.state:aberration","noun.person:aberrant","noun.state:aberrance"],["aberrate","deviate","aberrate1","deviate"]],
"co-vary":[["verb.stative","noun.cognition:covariance","noun.cognition:covariation","noun.cognition:statistics"],["co-vary","vary1"]],
"conform":[["verb.stative","noun.act:conformation1","noun.attribute:conformance"],["conform6","deviate","frames:1","4"]],
"corroborate":[["verb.stative","adj.all:supportive^corroborative","adj.all:supportive^corroboratory","noun.communication:corroboration","noun.act:support2"],["corroborate","underpin","bear out","support","agree","frames:8"]],
"repose on":[["verb.stative"],["repose on","rest on","build on","build upon","depend on"]],
"depend on":[["verb.stative"],["depend on","devolve on","depend upon","ride7","turn on","hinge on","hinge upon","frames:11"]],
"depend":[["verb.stative","adj.all:conditional^dependent","adj.all:conditional^dependant"],["depend","be3"]],
"hang by a thread":[["verb.stative"],["hang by a thread","hang by a hair","depend"]],
"underlie":[["verb.stative","verb.stative"],["underlie","be3","underlie1","lie"]],
"resemble":[["verb.stative","noun.attribute:resemblance"],["resemble","match","frames:11","9","8"]],
"look like":[["verb.stative"],["look like","resemble","frames:11","9","8"]],
"approximate":[["verb.stative","adj.all:inexact^approximative"],["approximate","come close","frames:4resemble"]],
"differ":[["verb.stative","adj.all:other^different1","adj.all:unusual^different","adj.all:other^different","adj.all:different","noun.attribute:difference"],["differ","equal","frames:1"]],
"come in":[["verb.stative","verb.change:change","noun.cognition:fashion"],["come in","go out"]],
"fit the bill":[["verb.stative","verb.consumption:meet"],["fit the bill","fill the bill","frames:1"]],
"behoove":[["verb.stative"],["behoove","behove","be3"]],
"fly in the face of":[["verb.stative"],["fly in the face of","fly in the teeth of","violate"]],
"conform to":[["verb.stative","verb.social:comply"],["conform to","violate","frames:4"]],
"exceed":[["verb.stative","adj.all:immoderate^excessive","noun.attribute:exceedance","adj.all:superior2^transcendent","noun.state:transcendency2","noun.state:transcendence2","noun.state:top","noun.person:topper2","noun.communication:topper","verb.stative","adj.all:superior2^transcendent","noun.state:transcendence2"],["exceed","transcend1","overstep","pass4","go past","top","surpass","frames:11","exceed1","transcend","surpass1"]],
"suffice":[["verb.stative","adj.all:sufficient","noun.state:sufficiency","noun.quantity:sufficiency","noun.attribute:sufficiency"],["suffice","frames:34do1","answer2","serve12","satisfy"]],
"go a long way":[["verb.stative"],["go a long way","suffice"]],
"act as":[["verb.stative"],["act as","serve3","frames:11","9"]],
"fall short of":[["verb.stative"],["fall short of","satisfy"]],
"excel":[["verb.stative","adj.all:superior2^excellent","noun.attribute:excellence"],["excel","stand out","surpass","frames:1"]],
"stink":[["verb.stative","noun.artifact:stinker"],["stink","be3","frames:1"]],
"shine at":[["verb.stative"],["shine at","excel at","excel","frames:8"]],
"follow suit":[["verb.stative"],["follow suit","imitate"]],
"focus on":[["verb.stative","noun.cognition:center1","noun.cognition:centering"],["focus on","center on","revolve around","revolve about","concentrate on","center","frames:4","22relate","frames:11"]],
"implicate":[["verb.stative","noun.relation:implication","noun.communication:implication"],["implicate1","involve1","frames:11","10","8"]],
"embroil":[["verb.stative","noun.state:embroilment"],["embroil","tangle","sweep","sweep up","drag","drag in","involve4","frames:9"]],
"disinvolve":[["verb.stative","noun.act:disentanglement1","verb.social:free2"],["disinvolve","disembroil","disentangle","frames:9"]],
"matter to":[["verb.stative","noun.attribute:interest2"],["matter to","interest","relate","frames:10"]],
"discontinue":[["verb.stative","noun.act:discontinuation","noun.act:discontinuance","noun.act:stop2","noun.act:stop","noun.event:stop","noun.act:stoppage","noun.event:cessation","noun.time:cease","verb.stative"],["discontinue","continue","stop","frames:28cease","frames:28give up","quit4","lay off","frames:11","8","discontinue1","continue1","end"]],
"call it quits":[["verb.stative"],["call it quits","call it a day","stop"]],
"housekeep":[["verb.stative","noun.person:housekeeper","noun.act:housekeeping"],["housekeep","keep"]],
"ramble on":[["verb.stative","noun.person:rambler1","verb.communication:go on"],["ramble on","ramble","jog","frames:1"]],
"imbricate":[["verb.stative","noun.artifact:imbrication","verb.stative","noun.artifact:imbrication","$verb.contact:place"],["imbricate","overlap1","imbricate1","imbricate"]],
"reach into":[["verb.stative"],["reach into","extend to"]],
"mediate":[["verb.stative"],["mediate","lie"]],
"subtend":[["verb.stative"],["subtend","delimit1","be3"]],
"surmount":[["verb.stative"],["surmount","head"]],
"radiolocate":[["verb.stative","noun.artifact:radiolocation"],["radiolocate","locate","frames:8","11","10"]],
"endanger":[["verb.stative","noun.state:jeopardy","noun.state:jeopardy","noun.state:menace","noun.state:peril1","noun.state:peril"],["endanger","jeopardize","jeopardise","menace","threaten","frames:28imperil","peril","be","frames:10"]],
"embody":[["verb.stative","noun.cognition:persona","noun.attribute:persona","verb.communication:represent2","verb.stative","noun.cognition:embodiment1","verb.communication:represent"],["embody","be8","personify","frames:11","embody2"]],
"characterize":[["verb.stative","noun.cognition:character","noun.cognition:character","verb.cognition:distinguish2"],["characterize1","characterise1","frames:10"]],
"befit":[["verb.stative"],["befit","suit","beseem","match","frames:10"]],
"contain":[["verb.stative","noun.artifact:hold2","verb.stative","noun.cognition:arithmetic"],["contain14","take15","hold14","hold5","$hold13","$be3","contain6","be3"]],
"truckle":[["verb.stative","noun.person:truckler"],["truckle","yield"]],
"border on":[["verb.stative","noun.attribute:approach1"],["border on","approach","approximate"]],
"outwear":[["verb.stative","verb.competition:surpass"],["outwear"]],
"drag on":[["verb.stative"],["drag on","drag out","last","frames:1"]],
"inhere in":[["verb.stative"],["inhere in","attach to","include"]],
"fall into":[["verb.stative"],["fall into","fall under","be2"]],
"shillyshally":[["verb.stative"],["shillyshally","vacillate"]],
"lend oneself":[["verb.stative","adj.all:practical^applicative","adj.all:relevant^applicable","adj.all:practical^applicatory","noun.act:application2"],["lend oneself","defy1","apply1"]],
"piddle":[["verb.stative","noun.act:trifling","verb.possession:spend"],["piddle","wanton","wanton away","piddle away","trifle"]],
"while away":[["verb.stative"],["while away","get through","spend"]],
"bound":[["verb.stative","noun.shape:boundary","noun.location:boundary","noun.shape:bound","noun.location:bound","noun.shape:border","noun.location:border1","noun.location:border"],["bound","border","border on","^enclose"]],
"embank":[["verb.stative","noun.artifact:embankment"],["embank","enclose"]],
"box in":[["verb.stative"],["box in","box up","confine","frames:8"]],
"stick out":[["verb.stative","adj.all:extensile^protrusible","adj.all:protrusive","noun.act:protrusion","noun.act:jutting","noun.act:projection2"],["stick out1","protrude","jut out","jut","project","frames:1"]],
"protuberate":[["verb.stative","adj.all:protrusive^protuberant","noun.state:protuberance","verb.stative","adj.all:protrusive^protuberant","noun.shape:protuberance"],["protuberate","bulge","protuberate1","protuberate"]],
"teem":[["verb.stative","noun.group:swarm","noun.group:swarm1"],["teem","teem in","^frames:1pullulate","swarm","hum"]],
"abound":[["verb.stative","adj.all:abundant","noun.attribute:abundance","verb.stative","noun.act:burst2"],["abound","abound in","^be3","frames:1","abound1","burst","bristle","have"]],
"abound in":[["verb.stative"],["abound in","teem in","pullulate with","occur3","frames:10"]],
"attach to":[["verb.stative","noun.event:accompaniment"],["attach to1","accompany","come with","go with1","frames:11"]],
"droop":[["verb.stative","noun.shape:droop"],["droop","loll1","drop4"]],
"take kindly to":[["verb.stative"],["take kindly to","lean1"]],
"belong to":[["verb.stative"],["belong to","belong6","frames:11","9"]],
"incur":[["verb.stative","noun.act:incursion2","noun.act:incurring","noun.act:incurrence","verb.perception:subject3"],["incur"]],
"look out on":[["verb.stative","noun.location:overlook"],["look out on","look out over","overlook1","look across","lie"]],
"center on":[["verb.stative"],["center on1","be5"]],
"do well":[["verb.stative","verb.social:act"],["do well","had best"]],
"go back":[["verb.stative","verb.creation:originate"],["go back","date back","date from","frames:11"]],
"stagnate":[["verb.stative","adj.all:standing2^stagnant","noun.state:stagnation1","noun.state:stagnancy1","verb.stative","adj.all:standing2^stagnant","noun.state:stagnation","noun.state:stagnation1","noun.state:stagnancy1","$verb.change:change","verb.stative","adj.all:undynamic^stagnant","noun.state:stagnation"],["stagnate","be3","stagnate2","stagnate","stagnate1","be3"]],
"come in handy":[["verb.stative"],["come in handy","be3"]],
"forbear":[["verb.stative"],["forbear1","hold back1","refrain"]],
"help oneself":[["verb.stative"],["help oneself","help8","refrain","frames:2"]],
"impend":[["verb.stative","noun.state:impendency","noun.state:impendence"],["impend","be3"]],
"come in for":[["verb.stative"],["come in for","be3","frames:11"]],
"persist":[["verb.stative","adj.all:persistent"],["persist1","remain1","stay4","frames:1"]],
"resplend":[["verb.stative","adj.all:beautiful^resplendent","noun.attribute:resplendency","noun.attribute:resplendence","verb.weather:shine1"],["resplend"]],
"go far":[["verb.stative"],["go far","go deep","extend3"]],
"iridesce":[["verb.stative","adj.all:colorful^iridescent","adj.all:bright^iridescent","noun.attribute:iridescence"],["iridesce","be3"]],
"tie in":[["verb.stative"],["tie in","relate1"]],
"go into":[["verb.stative"],["go into"]],
"let go":[["verb.stative"],["let go","be3"]],
"circumvolute":[["verb.stative"],["circumvolute","wind","frames:1"]],
"miscegenate":[["verb.stative","noun.act:miscegenation"],["miscegenate","cohabit"]],
"issue forth":[["verb.stative"],["issue forth","come13","frames:1"]],
"ornament":[["verb.stative","noun.state:ornamentation","verb.creation:ornament"],["ornament","$adorn"]],
"assonate":[["verb.stative","adj.all:same^assonant","adj.all:rhymed^assonant","noun.communication:assonance"],["assonate","rhyme"]],
"osculate":[["verb.stative","noun.state:osculation","noun.cognition:math","verb.stative"],["osculate","share","frames:1","osculate3","be3"]],
"summarize":[["verb.stative","noun.communication:summarization1","noun.communication:summarisation1","noun.communication:summation","verb.communication:summarize","$verb.communication:state"],["summarize","summarise","sum","sum up"]],
"cohere":[["verb.stative","adj.all:coherent","verb.stative","adj.all:united^cohesive","adj.all:coherent",">verb.change:change1"],["cohere","be3","cohere1","cohere"]],
"cash out":[["verb.stative"],["cash out","live6"]]
}