var mysql_wn_data_noun_motive = {
"compulsion":[["noun.motive","adj.all:neurotic^compulsive","noun.person:compulsive","adj.all:neurotic^obsessional","noun.motive","adj.all:neurotic^compulsive"],["compulsion","obsession","irrational motive","compulsion1","irresistible impulse","irrational impulse"]],
"conscience":[["noun.motive"],["conscience","scruples","moral sense","sense of right and wrong","ethical motive"]],
"hedonism":[["noun.motive","adj.all:indulgent^hedonistic","adj.all:indulgent^hedonic","noun.person:hedonist"],["hedonism","ethical motive"]],
"rational motive":[["noun.motive","noun.Tops:motive"],["rational motive"]],
"why":[["noun.motive"],["why","wherefore","reason"]],
"incentive":[["noun.motive","verb.communication:induce","verb.creation:motivate"],["incentive","disincentive","inducement","motivator","rational motive"]],
"moral force":[["noun.motive"],["moral force","dynamic","incentive"]],
"disincentive":[["noun.motive","adj.all:preventive^deterrent"],["disincentive","incentive","deterrence","rational motive"]],
"irrational motive":[["noun.motive","noun.Tops:motive"],["irrational motive"]],
"abience":[["noun.motive","adj.pert:abient","noun.cognition:psychology"],["abience","adience","urge"]],
"adience":[["noun.motive","adj.pert:adient","noun.cognition:psychology"],["adience","abience","urge"]],
"death instinct":[["noun.motive","noun.act:psychoanalysis"],["death instinct","death wish","Thanatos","urge"]],
"irrational impulse":[["noun.motive"],["irrational impulse","irrational motive"]],
"agromania":[["noun.motive"],["agromania","mania"]],
"dipsomania":[["noun.motive"],["dipsomania","alcoholism1","potomania","mania"]],
"egomania":[["noun.motive"],["egomania","mania"]],
"kleptomania":[["noun.motive"],["kleptomania","mania"]],
"logorrhea":[["noun.motive"],["logorrhea","logomania","mania"]],
"monomania":[["noun.motive","adj.all:neurotic^monomaniacal"],["monomania","possession","mania"]],
"necrophilia":[["noun.motive"],["necrophilia","necrophilism","necromania","mania"]],
"phaneromania":[["noun.motive"],["phaneromania","mania"]],
"pyromania":[["noun.motive"],["pyromania","mania"]],
"trichotillomania":[["noun.motive"],["trichotillomania","mania"]],
"wanderlust":[["noun.motive"],["wanderlust","itchy feet","impulse"]],
"onomatomania":[["noun.motive"],["onomatomania","compulsion"]],
"ethical motive":[["noun.motive","adj.all:right1^ethical","adj.all:ethical","noun.person:ethicist","noun.person:ethician","adj.all:moral^moralistic","noun.Tops:motive"],["ethical motive","ethics","morals","morality"]],
"wee small voice":[["noun.motive"],["wee small voice","small voice","voice of conscience","conscience"]],
"sense of shame":[["noun.motive"],["sense of shame","sense of duty","conscience"]],
"inner light":[["noun.motive"],["Inner Light","Light","Light Within","Christ Within","ethical motive"]],
"psychic energy":[["noun.motive","noun.Tops:motive"],["psychic energy","mental energy"]],
"incitement":[["noun.motive","verb.contact:incite","verb.creation:incite","verb.contact:incite","verb.communication:incite","verb.emotion:provoke","verb.creation:provoke","verb.communication:provoke"],["incitement","incitation","provocation","psychic energy"]],
"libidinal energy":[["noun.motive","noun.act:psychoanalysis"],["libidinal energy","psychic energy"]],
"cathexis":[["noun.motive","adj.pert:cathectic","noun.act:psychoanalysis"],["cathexis","charge","libidinal energy"]],
"acathexis":[["noun.motive","noun.act:psychoanalysis"],["acathexis","libidinal energy"]]
}